import {
  encodeGrantBytes,
  type OfflineGrantClaims,
  type OfflineGrantTrust,
  type SignedOfflineGrant,
} from "../src/offline-grant.ts";
import {
  projectionResource,
  projectionSchemaHash,
} from "../src/generated/product-category.ts";
import type { ProjectionScope } from "../src/contracts.ts";

/** Test-only ephemeral signing authority. Production keys are never generated by clients. */
export async function grantFixture() {
  const keys = await crypto.subtle.generateKey(
    { name: "ECDSA", namedCurve: "P-256" },
    true,
    ["sign", "verify"],
  );
  const publicKey = encodeGrantBytes(
    new Uint8Array(await crypto.subtle.exportKey("raw", keys.publicKey)),
  );
  const trust: OfflineGrantTrust = {
    deploymentId: "test-deployment",
    maximumLifetimeSeconds: 3600,
    keys: [{ keyId: "test-key", publicKey }],
  };
  const scope: ProjectionScope = {
    environmentId: "fixture-server",
    actorId: "actor-a",
    organizationId: "7",
    companyId: "9",
    authorizationVersion: "auth-1",
  };
  const claims: OfflineGrantClaims = {
    version: 1,
    resource: projectionResource,
    deploymentId: trust.deploymentId,
    audience: "https://erp.example",
    schemaHash: projectionSchemaHash,
    scope,
    issuedAt: 1_700_000_000,
    expiresAt: 1_700_003_600,
  };
  async function sign(
    value: OfflineGrantClaims = claims,
    keyId = "test-key",
  ): Promise<SignedOfflineGrant> {
    const payload = encodeGrantBytes(
      new TextEncoder().encode(JSON.stringify(value)),
    );
    const signature = await crypto.subtle.sign(
      { name: "ECDSA", hash: "SHA-256" },
      keys.privateKey,
      new TextEncoder().encode(
        `lumiere-offline-category-grant-v1.${keyId}.${payload}`,
      ),
    );
    return {
      version: 1,
      algorithm: "ES256",
      keyId,
      payload,
      signature: encodeGrantBytes(new Uint8Array(signature)),
    };
  }
  return { trust, claims, sign };
}
