/** Coverage tracker: CRM reducers reachable from crm module UI. */
export const CRM_UI_REDUCERS = [
  "add_contact_to_segment",
  "archive_contact_identity",
  "assign_contact_role",
  "assign_tag_to_contact",
  "complete_activity",
  "convert_lead_to_customer",
  "convert_opportunity_to_sale_order",
  "create_activity",
  "create_contact",
  "create_contact_identity",
  "create_contact_segment",
  "create_contact_tag",
  "create_lead",
  "create_opportunity",
  "create_opportunity_line",
  "delete_contact",
  "delete_lead",
  "end_contact_role",
  "find_duplicate_contacts",
  "import_contact_csv",
  "import_lead_csv",
  "import_opportunity_csv",
  "merge_contacts",
  "update_contact",
  "update_contact_address",
  "update_contact_business",
  "update_contact_details",
  "update_contact_identity",
  "update_lead_address",
  "update_lead_details",
  "update_lead_revenue",
  "update_opportunity",
  "verify_contact_identity",
] as const
