import type { EntryTableConfig, EntryData } from "@lumiere/ui"
import type { FormField } from "@lumiere/ui"

// Sample product form fields for view/edit modal
export const productFormFields: FormField[] = [
  {
    id: "image",
    name: "image",
    type: "text",
    label: "Image URL",
    placeholder: "https://example.com/image.jpg",
    width: "full",
  },
  {
    id: "name",
    name: "name",
    type: "text",
    label: "Product Name",
    placeholder: "Enter product name",
    required: true,
    width: "1/2",
  },
  {
    id: "sku",
    name: "sku",
    type: "text",
    label: "SKU",
    placeholder: "PRD-001",
    width: "1/2",
  },
  {
    id: "category",
    name: "category",
    type: "select",
    label: "Category",
    width: "1/2",
    options: [
      { value: "electronics", label: "Electronics" },
      { value: "clothing", label: "Clothing" },
      { value: "furniture", label: "Furniture" },
      { value: "food", label: "Food & Beverage" },
    ],
  },
  {
    id: "price",
    name: "price",
    type: "number",
    label: "Price",
    placeholder: "0.00",
    required: true,
    width: "1/2",
  },
  {
    id: "stock",
    name: "stock",
    type: "number",
    label: "Stock Quantity",
    placeholder: "0",
    width: "1/2",
  },
  {
    id: "status",
    name: "status",
    type: "select",
    label: "Status",
    width: "1/2",
    options: [
      { value: "active", label: "Active" },
      { value: "inactive", label: "Inactive" },
      { value: "out_of_stock", label: "Out of Stock" },
    ],
  },
  {
    id: "description",
    name: "description",
    type: "textarea",
    label: "Description",
    placeholder: "Enter product description...",
    width: "full",
    rows: 3,
  },
  {
    id: "featured",
    name: "featured",
    type: "switch",
    label: "Featured Product",
    width: "1/2",
  },
]

// Product table configuration
export const productTableConfig: EntryTableConfig = {
  id: "products",
  title: "Product Inventory",
  description: "Manage your product catalog and inventory",
  columns: [
    {
      id: "image",
      key: "image",
      label: "Image",
      type: "image",
      size: "sm",
      rounded: true,
      width: "sm",
    },
    {
      id: "name",
      key: "name",
      label: "Product Name",
      type: "text",
      sortable: true,
      width: "lg",
    },
    {
      id: "sku",
      key: "sku",
      label: "SKU",
      type: "text",
      width: "md",
    },
    {
      id: "category",
      key: "category",
      label: "Category",
      type: "badge",
      variants: {
        electronics: { label: "Electronics", color: "info" },
        clothing: { label: "Clothing", color: "primary" },
        furniture: { label: "Furniture", color: "warning" },
        food: { label: "Food", color: "success" },
      },
    },
    {
      id: "price",
      key: "price",
      label: "Price",
      type: "currency",
      sortable: true,
      align: "right",
    },
    {
      id: "stock",
      key: "stock",
      label: "Stock",
      type: "number",
      sortable: true,
      align: "right",
    },
    {
      id: "status",
      key: "status",
      label: "Status",
      type: "status",
      statuses: {
        active: { label: "Active", color: "green", icon: "check" },
        inactive: { label: "Inactive", color: "gray", icon: "minus" },
        out_of_stock: { label: "Out of Stock", color: "red", icon: "x" },
      },
    },
  ],
  formFields: productFormFields,
  features: {
    search: true,
    sort: true,
    pagination: true,
    selection: true,
    export: true,
  },
  pageSize: 5,
  pageSizeOptions: [5, 10, 20],
  onRowClick: "view",
  actions: {
    view: true,
    edit: true,
    delete: true,
  },
  imagePlaceholder: "/placeholder-product.png",
}

// Sample product data
export const sampleProducts: EntryData[] = [
  {
    id: "1",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=100&h=100&fit=crop",
    name: "Wireless Headphones Pro",
    sku: "WHP-001",
    category: "electronics",
    price: 299.99,
    stock: 145,
    status: "active",
    description: "Premium wireless headphones with noise cancellation",
    featured: true,
  },
  {
    id: "2",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=100&h=100&fit=crop",
    name: "Smart Watch Series X",
    sku: "SWX-002",
    category: "electronics",
    price: 449.99,
    stock: 89,
    status: "active",
    description: "Advanced smartwatch with health monitoring",
    featured: true,
  },
  {
    id: "3",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=100&h=100&fit=crop",
    name: "Running Shoes Elite",
    sku: "RSE-003",
    category: "clothing",
    price: 179.99,
    stock: 234,
    status: "active",
    description: "Professional running shoes with advanced cushioning",
    featured: false,
  },
  {
    id: "4",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=100&h=100&fit=crop",
    name: "Modern Sofa Set",
    sku: "MSS-004",
    category: "furniture",
    price: 1299.99,
    stock: 12,
    status: "active",
    description: "Contemporary 3-piece sofa set",
    featured: false,
  },
  {
    id: "5",
    image: "https://images.unsplash.com/photo-1560343090-f0409e92791a?w=100&h=100&fit=crop",
    name: "Organic Coffee Beans",
    sku: "OCB-005",
    category: "food",
    price: 24.99,
    stock: 0,
    status: "out_of_stock",
    description: "Premium organic coffee beans from Colombia",
    featured: false,
  },
  {
    id: "6",
    image: "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=100&h=100&fit=crop",
    name: "Vintage Desk Lamp",
    sku: "VDL-006",
    category: "furniture",
    price: 89.99,
    stock: 67,
    status: "active",
    description: "Elegant vintage-style desk lamp",
    featured: false,
  },
  {
    id: "7",
    image: "",
    name: "Basic T-Shirt Pack",
    sku: "BTS-007",
    category: "clothing",
    price: 49.99,
    stock: 456,
    status: "active",
    description: "5-pack of basic cotton t-shirts",
    featured: false,
  },
  {
    id: "8",
    image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=100&h=100&fit=crop",
    name: "Smart Home Hub",
    sku: "SHH-008",
    category: "electronics",
    price: 149.99,
    stock: 0,
    status: "out_of_stock",
    description: "Central hub for smart home devices",
    featured: true,
  },
]

// Customer table configuration
export const customerFormFields: FormField[] = [
  {
    id: "avatar",
    name: "avatar",
    type: "text",
    label: "Avatar URL",
    placeholder: "https://example.com/avatar.jpg",
    width: "full",
  },
  {
    id: "name",
    name: "name",
    type: "text",
    label: "Full Name",
    required: true,
    width: "1/2",
  },
  {
    id: "email",
    name: "email",
    type: "email",
    label: "Email Address",
    required: true,
    width: "1/2",
  },
  {
    id: "phone",
    name: "phone",
    type: "tel",
    label: "Phone Number",
    width: "1/2",
  },
  {
    id: "company",
    name: "company",
    type: "text",
    label: "Company",
    width: "1/2",
  },
  {
    id: "tier",
    name: "tier",
    type: "select",
    label: "Customer Tier",
    width: "1/2",
    options: [
      { value: "bronze", label: "Bronze" },
      { value: "silver", label: "Silver" },
      { value: "gold", label: "Gold" },
      { value: "platinum", label: "Platinum" },
    ],
  },
  {
    id: "status",
    name: "status",
    type: "select",
    label: "Status",
    width: "1/2",
    options: [
      { value: "active", label: "Active" },
      { value: "inactive", label: "Inactive" },
      { value: "pending", label: "Pending" },
    ],
  },
  {
    id: "notes",
    name: "notes",
    type: "textarea",
    label: "Notes",
    width: "full",
    rows: 3,
  },
]

export const customerTableConfig: EntryTableConfig = {
  id: "customers",
  title: "Customer Directory",
  description: "Manage your customer relationships",
  columns: [
    {
      id: "avatar",
      key: "avatar",
      label: "",
      type: "avatar",
      fallbackKey: "name",
      size: "sm",
      width: "xs",
    },
    {
      id: "name",
      key: "name",
      label: "Name",
      type: "text",
      sortable: true,
      width: "lg",
    },
    {
      id: "email",
      key: "email",
      label: "Email",
      type: "text",
      width: "lg",
    },
    {
      id: "company",
      key: "company",
      label: "Company",
      type: "text",
      width: "md",
    },
    {
      id: "tier",
      key: "tier",
      label: "Tier",
      type: "badge",
      variants: {
        bronze: { label: "Bronze", color: "default" },
        silver: { label: "Silver", color: "secondary" },
        gold: { label: "Gold", color: "warning" },
        platinum: { label: "Platinum", color: "primary" },
      },
    },
    {
      id: "totalSpent",
      key: "totalSpent",
      label: "Total Spent",
      type: "currency",
      sortable: true,
      align: "right",
    },
    {
      id: "status",
      key: "status",
      label: "Status",
      type: "status",
      statuses: {
        active: { label: "Active", color: "green", icon: "check" },
        inactive: { label: "Inactive", color: "gray", icon: "minus" },
        pending: { label: "Pending", color: "yellow", icon: "clock" },
      },
    },
  ],
  formFields: customerFormFields,
  features: {
    search: true,
    sort: true,
    pagination: true,
    selection: true,
  },
  pageSize: 5,
  onRowClick: "view",
  actions: {
    view: true,
    edit: true,
    delete: true,
  },
}

export const sampleCustomers: EntryData[] = [
  {
    id: "1",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    name: "John Anderson",
    email: "john.anderson@email.com",
    phone: "+1 (555) 123-4567",
    company: "Tech Solutions Inc.",
    tier: "platinum",
    totalSpent: 12450.00,
    status: "active",
    notes: "Key enterprise client",
  },
  {
    id: "2",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    name: "Sarah Mitchell",
    email: "sarah.m@email.com",
    phone: "+1 (555) 234-5678",
    company: "Creative Agency",
    tier: "gold",
    totalSpent: 8920.50,
    status: "active",
  },
  {
    id: "3",
    avatar: "",
    name: "Michael Chen",
    email: "m.chen@email.com",
    phone: "+1 (555) 345-6789",
    company: "StartupXYZ",
    tier: "silver",
    totalSpent: 3450.00,
    status: "active",
  },
  {
    id: "4",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
    name: "David Wilson",
    email: "d.wilson@email.com",
    phone: "+1 (555) 456-7890",
    company: "Wilson & Co.",
    tier: "bronze",
    totalSpent: 890.00,
    status: "pending",
  },
  {
    id: "5",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    name: "Emily Rodriguez",
    email: "emily.r@email.com",
    phone: "+1 (555) 567-8901",
    company: "Design Studio",
    tier: "gold",
    totalSpent: 6780.25,
    status: "active",
  },
  {
    id: "6",
    avatar: "",
    name: "James Thompson",
    email: "j.thompson@email.com",
    phone: "+1 (555) 678-9012",
    company: "",
    tier: "bronze",
    totalSpent: 245.00,
    status: "inactive",
  },
]
