/** Coverage tracker: documents / knowledge base reducers reachable from module UI. */
export const DOCUMENTS_UI_REDUCERS = [
  "acknowledge_insight",
  "add_article_member",
  "add_document_version",
  "approve_document_processing_job",
  "complete_document_processing_job",
  "create_document",
  "create_document_folder",
  "create_document_processing_job",
  "create_knowledge_article",
  "create_knowledge_category",
  "delete_document",
  "delete_knowledge_article",
  "delete_knowledge_category",
  "import_knowledge_article_csv",
  "import_knowledge_category_csv",
  "lock_document",
  "lock_knowledge_article",
  "record_document_view",
  "remove_article_member",
  "set_article_published",
  "unlock_document",
  "unlock_knowledge_article",
  "update_document",
  "update_knowledge_article",
  "update_knowledge_category",
] as const
