/** Coverage tracker: HR reducers reachable via toolbar forms, row actions, and CSV imports. */
export const HR_UI_REDUCERS = [
  "approve_leave",
  "archive_employee",
  "cancel_contract",
  "confirm_payslip",
  "cancel_payslip",
  "create_contract",
  "create_department",
  "create_employee",
  "create_job_position",
  "create_leave_request",
  "create_leave_type",
  "create_payroll_structure",
  "create_payslip",
  "create_salary_rule",
  "expire_contract",
  "import_hr_contract_csv",
  "import_hr_department_csv",
  "import_hr_employee_csv",
  "import_hr_job_position_csv",
  "import_hr_leave_csv",
  "import_hr_leave_type_csv",
  "import_hr_payroll_structure_csv",
  "import_hr_payslip_csv",
  "import_hr_resource_csv",
  "import_hr_salary_rule_csv",
  "open_contract",
  "refuse_leave",
  "reset_leave_to_draft",
  "update_contract",
  "update_department",
  "update_employee",
  "update_job_position",
  "update_leave_type",
] as const
