//! Hydration manifest generator.
//!
//! Reads `lumiere-codegen/hydration-policies.json`, validates each policy
//! against the schema IR, and emits `crates/stdb-auth/assets/hydration-manifest.json`.
//!
//! ## Purpose
//!
//! A hydration policy declares that a reducer may target an archived row by
//! id.  At call time the api-server checks whether the target row is absent
//! from STDB; if so it hydrates the row from PG before invoking the reducer
//! (see sliding-window-cold-tier.md §7).  The manifest is the codegen-checked
//! source of truth for which reducers need this orchestration.
//!
//! ## Validation performed
//!
//! 1. `reducer` is non-empty.
//! 2. `table` exists in the schema manifest and is one of the archive
//!    candidates (the row must be archive-capable for hydration to apply).
//! 3. `id_arg` is a non-empty dotted path beginning with `args.`
//!    (e.g. `"args.move_id"`).
//!
//! Full reducer-argument validation (does `args.move_id` exist on the named
//! reducer, with the right type?) is deferred until the reducer manifest is
//! introduced as part of the offline-sync work; the schema IR today only
//! covers tables and enums, not reducer signatures.

use anyhow::{bail, Context, Result};
use serde_json::Value;

use crate::schema_ir::LumiereSchemaManifest;

/// Emit the validated hydration manifest JSON.
///
/// `policies_json` is the raw `hydration-policies.json` text.  `archive_tables`
/// is the set of table names that are active archive candidates (from
/// `archive-candidates.json`); a policy must reference one of these, since
/// hydration only applies to archive-capable rows.
pub fn emit_hydration_manifest(
    policies_json: &str,
    schema_manifest: &LumiereSchemaManifest,
    archive_tables: &[String],
) -> Result<String> {
    let config: Value =
        serde_json::from_str(policies_json).context("parse hydration-policies.json")?;

    let policies = config["policies"]
        .as_array()
        .context("hydration-policies.json: missing 'policies' array")?;

    let mut out: Vec<Value> = Vec::with_capacity(policies.len());

    for (i, p) in policies.iter().enumerate() {
        let reducer = p["reducer"]
            .as_str()
            .with_context(|| format!("policies[{i}].reducer is not a string"))?;
        let table = p["table"]
            .as_str()
            .with_context(|| format!("policies[{i}].table is not a string"))?;
        let id_arg = p["id_arg"]
            .as_str()
            .with_context(|| format!("policies[{i}].id_arg is not a string"))?;

        if reducer.trim().is_empty() {
            bail!("policies[{i}]: reducer must not be empty");
        }
        if table.trim().is_empty() {
            bail!("policies[{i}]: table must not be empty");
        }
        if id_arg.trim().is_empty() {
            bail!("policies[{i}] (reducer '{reducer}'): id_arg must not be empty");
        }
        if !id_arg.trim().starts_with("args.") {
            bail!(
                "policies[{i}] (reducer '{reducer}'): id_arg '{id_arg}' must be a dotted \
                 path beginning with 'args.' (e.g. 'args.move_id')"
            );
        }

        // The table must exist in the schema manifest.
        if !schema_manifest.tables.iter().any(|t| t.sql_name == table) {
            bail!(
                "policies[{i}] (reducer '{reducer}'): table '{table}' not found in \
                 schema manifest. Re-run `make generate-stdb-rust-sdk && make codegen`."
            );
        }

        // The table must be an active archive candidate.
        if !archive_tables.iter().any(|t| t == table) {
            bail!(
                "policies[{i}] (reducer '{reducer}'): table '{table}' is not an active \
                 archive candidate. Hydration only applies to archive-capable tables."
            );
        }

        out.push(serde_json::json!({
            "reducer": reducer,
            "table": table,
            "id_arg": id_arg,
        }));
    }

    let manifest = serde_json::json!({
        "version": 1,
        "_comment": "Auto-generated by lumiere-codegen from hydration-policies.json. Do not edit.",
        "policies": out,
    });

    serde_json::to_string_pretty(&manifest).context("serialise hydration manifest")
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema_ir::*;

    fn manifest_with(table: &str) -> LumiereSchemaManifest {
        LumiereSchemaManifest {
            version: 1,
            tables: vec![GeneratedTableSchema {
                rust_name: "SaleOrder".into(),
                sql_name: table.to_string(),
                primary_key: GeneratedPrimaryKey {
                    column_name: "id".into(),
                    ty: GeneratedType::U64,
                },
                columns: vec![GeneratedColumn {
                    name: "id".into(),
                    sql_name: "id".into(),
                    ty: GeneratedType::U64,
                    nullable: false,
                }],
                indexes: vec![],
            }],
            enum_types: vec![],
        }
    }

    #[test]
    fn empty_policies_emit_empty_manifest() {
        let m = manifest_with("sale_order");
        let json = r#"{"version":1,"policies":[]}"#;
        let out = emit_hydration_manifest(json, &m, &["sale_order".to_string()]).unwrap();
        let parsed: Value = serde_json::from_str(&out).unwrap();
        assert_eq!(parsed["version"], 1);
        assert_eq!(parsed["policies"].as_array().unwrap().len(), 0);
    }

    #[test]
    fn valid_policy_emits_entry() {
        let m = manifest_with("sale_order");
        let json = r#"{"version":1,"policies":[{"reducer":"confirm_sale_order","table":"sale_order","id_arg":"args.order_id"}]}"#;
        let out = emit_hydration_manifest(json, &m, &["sale_order".to_string()]).unwrap();
        let parsed: Value = serde_json::from_str(&out).unwrap();
        assert_eq!(parsed["policies"][0]["reducer"], "confirm_sale_order");
        assert_eq!(parsed["policies"][0]["table"], "sale_order");
        assert_eq!(parsed["policies"][0]["id_arg"], "args.order_id");
    }

    #[test]
    fn rejects_empty_reducer() {
        let m = manifest_with("sale_order");
        let json =
            r#"{"version":1,"policies":[{"reducer":"","table":"sale_order","id_arg":"args.id"}]}"#;
        assert!(emit_hydration_manifest(json, &m, &["sale_order".to_string()]).is_err());
    }

    #[test]
    fn rejects_bad_id_arg_path() {
        let m = manifest_with("sale_order");
        let json = r#"{"version":1,"policies":[{"reducer":"r","table":"sale_order","id_arg":"order_id"}]}"#;
        assert!(emit_hydration_manifest(json, &m, &["sale_order".to_string()]).is_err());
    }

    #[test]
    fn rejects_table_not_in_schema() {
        let m = manifest_with("sale_order");
        let json =
            r#"{"version":1,"policies":[{"reducer":"r","table":"missing","id_arg":"args.id"}]}"#;
        assert!(emit_hydration_manifest(json, &m, &["sale_order".to_string()]).is_err());
    }

    #[test]
    fn rejects_table_not_an_archive_candidate() {
        let m = manifest_with("sale_order");
        let json =
            r#"{"version":1,"policies":[{"reducer":"r","table":"sale_order","id_arg":"args.id"}]}"#;
        // sale_order exists in schema but is not in the active archive list.
        assert!(emit_hydration_manifest(json, &m, &[]).is_err());
    }
}
