// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  PaymentState,
  PaymentType,
  PartnerType,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  organizationId: __t.u64().name("organization_id"),
  companyId: __t.u64().name("company_id"),
  name: __t.option(__t.string()),
  moveId: __t.option(__t.u64()).name("move_id"),
  get paymentType() {
    return PaymentType.name("payment_type");
  },
  get partnerType() {
    return PartnerType.name("partner_type");
  },
  partnerId: __t.u64().name("partner_id"),
  amount: __t.f64(),
  currencyId: __t.u64().name("currency_id"),
  date: __t.timestamp(),
  journalId: __t.u64().name("journal_id"),
  ref: __t.option(__t.string()),
  memo: __t.option(__t.string()),
  reconciledInvoiceIds: __t.array(__t.u64()).name("reconciled_invoice_ids"),
  reconciledBillIds: __t.array(__t.u64()).name("reconciled_bill_ids"),
  get state() {
    return PaymentState;
  },
  createdAt: __t.timestamp().name("created_at"),
  createUid: __t.identity().name("create_uid"),
});
