// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  organizationId: __t.u64().name("organization_id"),
  barcode: __t.string(),
  barcodeType: __t.string().name("barcode_type"),
  productId: __t.option(__t.u64()).name("product_id"),
  lotId: __t.option(__t.u64()).name("lot_id"),
  locationId: __t.option(__t.u64()).name("location_id"),
  packageId: __t.option(__t.u64()).name("package_id"),
  quantity: __t.option(__t.f64()),
  uomId: __t.option(__t.u64()).name("uom_id"),
  userId: __t.identity().name("user_id"),
  sessionId: __t.option(__t.string()).name("session_id"),
  deviceId: __t.option(__t.string()).name("device_id"),
  scannedAt: __t.timestamp().name("scanned_at"),
  processed: __t.bool(),
  processedAt: __t.option(__t.timestamp()).name("processed_at"),
  errorMessage: __t.option(__t.string()).name("error_message"),
  contextType: __t.option(__t.string()).name("context_type"),
  contextId: __t.option(__t.u64()).name("context_id"),
  metadata: __t.option(__t.string()),
});
