// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  organizationId: __t.u64().name("organization_id"),
  companyId: __t.u64().name("company_id"),
  userIdentity: __t.identity().name("user_identity"),
  grantedBy: __t.identity().name("granted_by"),
  grantedAt: __t.timestamp().name("granted_at"),
  isActive: __t.bool().name("is_active"),
  metadata: __t.option(__t.string()),
});
