// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  PartnerType,
  PaymentDirection,
  PaymentTransactionStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  organizationId: __t.u64().name("organization_id"),
  companyId: __t.u64().name("company_id"),
  paymentAccountId: __t.u64().name("payment_account_id"),
  get direction() {
    return PaymentDirection;
  },
  get partnerType() {
    return PartnerType.name("partner_type");
  },
  partnerId: __t.u64().name("partner_id"),
  externalReference: __t.option(__t.string()).name("external_reference"),
  referenceFingerprint: __t.string().name("reference_fingerprint"),
  grossExternalAmount: __t.f64().name("gross_external_amount"),
  settlementAmount: __t.f64().name("settlement_amount"),
  netAccountAmount: __t.f64().name("net_account_amount"),
  currencyId: __t.u64().name("currency_id"),
  occurredAt: __t.timestamp().name("occurred_at"),
  get status() {
    return PaymentTransactionStatus;
  },
  accountPaymentId: __t.option(__t.u64()).name("account_payment_id"),
  sourceEntity: __t.option(__t.string()).name("source_entity"),
  sourceEntityId: __t.option(__t.u64()).name("source_entity_id"),
  evidenceDocumentIds: __t.array(__t.u64()).name("evidence_document_ids"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  createdBy: __t.identity().name("created_by"),
  updatedBy: __t.identity().name("updated_by"),
  voidedAt: __t.option(__t.timestamp()).name("voided_at"),
  metadata: __t.option(__t.string()),
});
