// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  organizationId: __t.u64().name("organization_id"),
  companyId: __t.u64().name("company_id"),
  timesheetId: __t.u64().name("timesheet_id"),
  actor: __t.identity(),
  decision: __t.string(),
  reason: __t.option(__t.string()),
  hours: __t.f64(),
  sellRate: __t.f64().name("sell_rate"),
  costRate: __t.f64().name("cost_rate"),
  currencyId: __t.u64().name("currency_id"),
  decidedAt: __t.timestamp().name("decided_at"),
});
