// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  organizationId: __t.u64().name("organization_id"),
  categoryId: __t.u64().name("category_id"),
  name: __t.string(),
  symbol: __t.string(),
  factor: __t.f64(),
  rounding: __t.f64(),
  timesBigger: __t.f64().name("times_bigger"),
  isReferenceUnit: __t.bool().name("is_reference_unit"),
  isActive: __t.bool().name("is_active"),
  createdAt: __t.timestamp().name("created_at"),
  metadata: __t.option(__t.string()),
});
