//! Accounting Module Form Configurations
//!
//! This module provides form configurations for Accounting.
//! Includes forms for: Invoices, Journal Entries, Accounts, Taxes

import type { FormRegistryEntry } from "../types"

export const accountingForms: FormRegistryEntry[] = [
  // Invoice Form
  {
    moduleId: "accounting",
    formId: "new-invoice",
    name: "New Invoice",
    description: "Create a new invoice",
    icon: "FileText",
    category: "Invoices",
    defaultConfig: () => ({
      moduleId: "accounting",
      formId: "new-invoice",
      name: "New Invoice",
      description: "Create a new invoice",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "invoice_number",
          name: "invoice_number",
          label: "Invoice Number",
          fieldType: "Text",
          placeholder: "Auto-generated",
          validation: { required: false },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "customer",
          name: "customer",
          label: "Customer",
          fieldType: "UserSelect",
          validation: { required: true },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "invoice_date",
          name: "invoice_date",
          label: "Invoice Date",
          fieldType: "Date",
          validation: { required: true },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "due_date",
          name: "due_date",
          label: "Due Date",
          fieldType: "Date",
          validation: { required: true },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "status",
          name: "status",
          label: "Status",
          fieldType: "Select",
          options: [
            { value: "draft", label: "Draft", color: "gray" },
            { value: "sent", label: "Sent", color: "blue" },
            { value: "viewed", label: "Viewed", color: "yellow" },
            { value: "paid", label: "Paid", color: "green" },
            { value: "partial", label: "Partial", color: "orange" },
            { value: "overdue", label: "Overdue", color: "red" },
            { value: "cancelled", label: "Cancelled", color: "gray" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "currency",
          name: "currency",
          label: "Currency",
          fieldType: "Select",
          options: [
            { value: "USD", label: "USD", color: "blue" },
            { value: "EUR", label: "EUR", color: "green" },
            { value: "GBP", label: "GBP", color: "purple" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "payment_terms",
          name: "payment_terms",
          label: "Payment Terms",
          fieldType: "Select",
          options: [
            { value: "immediate", label: "Immediate", color: "red" },
            { value: "net-15", label: "Net 15", color: "orange" },
            { value: "net-30", label: "Net 30", color: "yellow" },
            { value: "net-45", label: "Net 45", color: "blue" },
            { value: "net-60", label: "Net 60", color: "purple" },
          ],
          validation: { required: false },
          aiSuggestions: [],
          order: 7,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "notes",
          name: "notes",
          label: "Notes",
          fieldType: "Textarea",
          placeholder: "Invoice notes...",
          validation: { required: false },
          aiSuggestions: [],
          order: 8,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "tags",
          name: "tags",
          label: "Tags",
          fieldType: "Tags",
          validation: { required: false },
          aiSuggestions: [],
          order: 9,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["invoice_number", "customer", "invoice_date", "due_date", "status", "currency", "payment_terms", "notes", "tags"],
          requiredFields: ["customer", "invoice_date", "due_date", "status"],
          defaultPrompts: [],
        },
        "role-manager": {
          roleId: "role-manager",
          enabledFields: ["invoice_number", "customer", "invoice_date", "due_date", "status", "payment_terms", "notes", "tags"],
          requiredFields: ["customer", "invoice_date", "due_date"],
          defaultPrompts: [],
        },
      },
    }),
  },

  // Account Form
  {
    moduleId: "accounting",
    formId: "new-account",
    name: "New Account",
    description: "Create a new chart of accounts entry",
    icon: "Landmark",
    category: "Accounts",
    defaultConfig: () => ({
      moduleId: "accounting",
      formId: "new-account",
      name: "New Account",
      description: "Create a new chart of accounts entry",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "account_code",
          name: "account_code",
          label: "Account Code",
          fieldType: "Text",
          placeholder: "e.g., 1000",
          validation: { required: true },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "account_name",
          name: "account_name",
          label: "Account Name",
          fieldType: "Text",
          placeholder: "Account name",
          validation: { required: true },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "account_type",
          name: "account_type",
          label: "Account Type",
          fieldType: "Select",
          options: [
            { value: "asset", label: "Asset", color: "blue" },
            { value: "liability", label: "Liability", color: "red" },
            { value: "equity", label: "Equity", color: "purple" },
            { value: "revenue", label: "Revenue", color: "green" },
            { value: "expense", label: "Expense", color: "orange" },
            { value: "cost-of-sales", label: "Cost of Sales", color: "yellow" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "parent_account",
          name: "parent_account",
          label: "Parent Account",
          fieldType: "Text",
          placeholder: "Parent account code (optional)",
          validation: { required: false },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "description",
          name: "description",
          label: "Description",
          fieldType: "Textarea",
          validation: { required: false },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "is_active",
          name: "is_active",
          label: "Active",
          fieldType: "Switch",
          validation: { required: false },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "is_bank_account",
          name: "is_bank_account",
          label: "Bank Account",
          fieldType: "Switch",
          validation: { required: false },
          aiSuggestions: [],
          order: 7,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["account_code", "account_name", "account_type", "parent_account", "description", "is_active", "is_bank_account"],
          requiredFields: ["account_code", "account_name", "account_type"],
          defaultPrompts: [],
        },
      },
    }),
  },

  // Tax Configuration Form
  {
    moduleId: "accounting",
    formId: "new-tax",
    name: "New Tax Rate",
    description: "Configure tax rates and rules",
    icon: "Percent",
    category: "Taxes",
    defaultConfig: () => ({
      moduleId: "accounting",
      formId: "new-tax",
      name: "New Tax Rate",
      description: "Configure tax rates and rules",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "name",
          name: "name",
          label: "Tax Name",
          fieldType: "Text",
          placeholder: "e.g., Sales Tax",
          validation: { required: true },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Full",
        },
        {
          fieldId: "rate",
          name: "rate",
          label: "Tax Rate (%)",
          fieldType: "Number",
          placeholder: "0.00",
          validation: { required: true, min: 0, max: 100 },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "tax_type",
          name: "tax_type",
          label: "Tax Type",
          fieldType: "Select",
          options: [
            { value: "sales", label: "Sales Tax", color: "blue" },
            { value: "purchase", label: "Purchase Tax", color: "green" },
            { value: "vat", label: "VAT", color: "purple" },
            { value: "gst", label: "GST", color: "orange" },
            { value: "other", label: "Other", color: "gray" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "is_active",
          name: "is_active",
          label: "Active",
          fieldType: "Switch",
          validation: { required: false },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "description",
          name: "description",
          label: "Description",
          fieldType: "Textarea",
          validation: { required: false },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["name", "rate", "tax_type", "is_active", "description"],
          requiredFields: ["name", "rate", "tax_type"],
          defaultPrompts: [],
        },
      },
    }),
  },
]
