//! Calendar Module Form Configurations
//!
//! This module provides form configurations for Calendar/Events.

import type { FormRegistryEntry } from "../types"

export const calendarForms: FormRegistryEntry[] = [
  // Event Form
  {
    moduleId: "calendar",
    formId: "new-event",
    name: "New Event",
    description: "Create a new calendar event",
    icon: "Calendar",
    category: "Events",
    defaultConfig: () => ({
      moduleId: "calendar",
      formId: "new-event",
      name: "New Event",
      description: "Create a new calendar event",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "title",
          name: "title",
          label: "Event Title",
          fieldType: "Text",
          placeholder: "Enter event title",
          validation: { required: true, minLength: 3 },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Full",
        },
        {
          fieldId: "description",
          name: "description",
          label: "Description",
          fieldType: "Textarea",
          validation: { required: false },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "start_date",
          name: "start_date",
          label: "Start Date & Time",
          fieldType: "DateTime",
          validation: { required: true },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "end_date",
          name: "end_date",
          label: "End Date & Time",
          fieldType: "DateTime",
          validation: { required: true },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "all_day",
          name: "all_day",
          label: "All Day Event",
          fieldType: "Switch",
          validation: { required: false },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "location",
          name: "location",
          label: "Location",
          fieldType: "Text",
          placeholder: "Event location",
          validation: { required: false },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "attendees",
          name: "attendees",
          label: "Attendees",
          fieldType: "UserSelect",
          validation: { required: false },
          aiSuggestions: [],
          order: 7,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "reminder",
          name: "reminder",
          label: "Reminder",
          fieldType: "Select",
          options: [
            { value: "none", label: "No reminder", color: "gray" },
            { value: "5min", label: "5 minutes before", color: "blue" },
            { value: "15min", label: "15 minutes before", color: "green" },
            { value: "30min", label: "30 minutes before", color: "purple" },
            { value: "1hour", label: "1 hour before", color: "orange" },
            { value: "1day", label: "1 day before", color: "red" },
          ],
          validation: { required: false },
          aiSuggestions: [],
          order: 8,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "tags",
          name: "tags",
          label: "Tags",
          fieldType: "Tags",
          validation: { required: false },
          aiSuggestions: [],
          order: 9,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["title", "description", "start_date", "end_date", "all_day", "location", "attendees", "reminder", "tags"],
          requiredFields: ["title", "start_date", "end_date"],
          defaultPrompts: [],
        },
        "role-manager": {
          roleId: "role-manager",
          enabledFields: ["title", "description", "start_date", "end_date", "all_day", "location", "attendees", "reminder", "tags"],
          requiredFields: ["title", "start_date", "end_date"],
          defaultPrompts: [],
        },
      },
    }),
  },
]
