//! CRM Module Form Configurations
//!
//! This module provides form configurations for CRM (Customer Relationship Management).
//! Includes forms for: Leads, Opportunities, Contacts, Activities

import type { FormRegistryEntry } from "../types"

export const crmForms: FormRegistryEntry[] = [
  // Lead Creation Form
  {
    moduleId: "crm",
    formId: "new-lead",
    name: "New Lead",
    description: "Create a new lead in the CRM system",
    icon: "UserPlus",
    category: "Leads",
    defaultConfig: () => ({
      moduleId: "crm",
      formId: "new-lead",
      name: "New Lead",
      description: "Create a new lead in the CRM system",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "first_name",
          name: "first_name",
          label: "First Name",
          fieldType: "Text",
          placeholder: "Enter first name",
          validation: { required: true, minLength: 1, maxLength: 50 },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "last_name",
          name: "last_name",
          label: "Last Name",
          fieldType: "Text",
          placeholder: "Enter last name",
          validation: { required: true, minLength: 1, maxLength: 50 },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "email",
          name: "email",
          label: "Email Address",
          fieldType: "Email",
          placeholder: "email@example.com",
          validation: { required: true, pattern: "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$" },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "phone",
          name: "phone",
          label: "Phone Number",
          fieldType: "Tel",
          placeholder: "+1 (555) 000-0000",
          validation: { required: false },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "company",
          name: "company",
          label: "Company",
          fieldType: "Text",
          placeholder: "Company name",
          validation: { required: false, maxLength: 100 },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "job_title",
          name: "job_title",
          label: "Job Title",
          fieldType: "Text",
          placeholder: "Enter job title",
          validation: { required: false, maxLength: 100 },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "lead_source",
          name: "lead_source",
          label: "Lead Source",
          fieldType: "Select",
          options: [
            { value: "website", label: "Website", color: "blue" },
            { value: "referral", label: "Referral", color: "green" },
            { value: "linkedin", label: "LinkedIn", color: "blue" },
            { value: "cold-call", label: "Cold Call", color: "gray" },
            { value: "trade-show", label: "Trade Show", color: "purple" },
            { value: "email-campaign", label: "Email Campaign", color: "orange" },
            { value: "other", label: "Other", color: "gray" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 7,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "lead_status",
          name: "lead_status",
          label: "Lead Status",
          fieldType: "Select",
          options: [
            { value: "new", label: "New", color: "blue" },
            { value: "contacted", label: "Contacted", color: "yellow" },
            { value: "qualified", label: "Qualified", color: "green" },
            { value: "unqualified", label: "Unqualified", color: "red" },
            { value: "converted", label: "Converted", color: "teal" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 8,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "lead_score",
          name: "lead_score",
          label: "Lead Score",
          fieldType: "Rating",
          validation: { required: false, min: 1, max: 5 },
          aiSuggestions: [],
          order: 9,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "estimated_value",
          name: "estimated_value",
          label: "Estimated Value",
          fieldType: "Number",
          placeholder: "Enter estimated deal value",
          validation: { required: false, min: 0 },
          aiSuggestions: [],
          order: 10,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "notes",
          name: "notes",
          label: "Notes",
          fieldType: "Textarea",
          placeholder: "Additional notes about this lead...",
          validation: { required: false },
          aiSuggestions: [],
          order: 11,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "tags",
          name: "tags",
          label: "Tags",
          fieldType: "Tags",
          placeholder: "Add tags...",
          validation: { required: false },
          aiSuggestions: [],
          order: 12,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["first_name", "last_name", "email", "phone", "company", "job_title", "lead_source", "lead_status", "lead_score", "estimated_value", "notes", "tags"],
          requiredFields: ["first_name", "last_name", "email", "lead_source", "lead_status"],
          defaultPrompts: [],
        },
        "role-manager": {
          roleId: "role-manager",
          enabledFields: ["first_name", "last_name", "email", "phone", "company", "job_title", "lead_source", "lead_status", "lead_score", "estimated_value", "notes", "tags"],
          requiredFields: ["first_name", "last_name", "email", "lead_source", "lead_status"],
          defaultPrompts: [],
        },
        "role-sales": {
          roleId: "role-sales",
          enabledFields: ["first_name", "last_name", "email", "phone", "company", "job_title", "lead_source", "lead_status", "lead_score", "estimated_value", "notes", "tags"],
          requiredFields: ["first_name", "last_name", "email", "lead_status"],
          defaultPrompts: [],
        },
      },
    }),
  },

  // Opportunity Form
  {
    moduleId: "crm",
    formId: "new-opportunity",
    name: "New Opportunity",
    description: "Create a new sales opportunity",
    icon: "TrendingUp",
    category: "Opportunities",
    defaultConfig: () => ({
      moduleId: "crm",
      formId: "new-opportunity",
      name: "New Opportunity",
      description: "Create a new sales opportunity",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "opportunity_name",
          name: "opportunity_name",
          label: "Opportunity Name",
          fieldType: "Text",
          placeholder: "Enter opportunity name",
          validation: { required: true, minLength: 3, maxLength: 100 },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Full",
        },
        {
          fieldId: "contact",
          name: "contact",
          label: "Contact",
          fieldType: "UserSelect",
          validation: { required: true },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "account",
          name: "account",
          label: "Account",
          fieldType: "Text",
          placeholder: "Company name",
          validation: { required: true },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "stage",
          name: "stage",
          label: "Stage",
          fieldType: "Select",
          options: [
            { value: "prospecting", label: "Prospecting", color: "gray" },
            { value: "qualification", label: "Qualification", color: "blue" },
            { value: "proposal", label: "Proposal", color: "yellow" },
            { value: "negotiation", label: "Negotiation", color: "orange" },
            { value: "closed-won", label: "Closed Won", color: "green" },
            { value: "closed-lost", label: "Closed Lost", color: "red" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "amount",
          name: "amount",
          label: "Amount",
          fieldType: "Number",
          placeholder: "Deal amount",
          validation: { required: true, min: 0 },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "probability",
          name: "probability",
          label: "Probability (%)",
          fieldType: "Slider",
          defaultValue: "50",
          validation: { required: false, min: 0, max: 100 },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "expected_close_date",
          name: "expected_close_date",
          label: "Expected Close Date",
          fieldType: "Date",
          validation: { required: true },
          aiSuggestions: [],
          order: 7,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "source",
          name: "source",
          label: "Source",
          fieldType: "Select",
          options: [
            { value: "new-business", label: "New Business", color: "blue" },
            { value: "existing-business", label: "Existing Business", color: "green" },
            { value: "renewal", label: "Renewal", color: "teal" },
            { value: "upsell", label: "Upsell", color: "purple" },
            { value: "cross-sell", label: "Cross-sell", color: "orange" },
          ],
          validation: { required: false },
          aiSuggestions: [],
          order: 8,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "next_step",
          name: "next_step",
          label: "Next Step",
          fieldType: "Textarea",
          placeholder: "Describe the next step...",
          validation: { required: false },
          aiSuggestions: ["Schedule demo call", "Send proposal", "Follow up on pricing", "Contract review"],
          order: 9,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "description",
          name: "description",
          label: "Description",
          fieldType: "Textarea",
          placeholder: "Opportunity details...",
          validation: { required: false },
          aiSuggestions: [],
          order: 10,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "tags",
          name: "tags",
          label: "Tags",
          fieldType: "Tags",
          validation: { required: false },
          aiSuggestions: [],
          order: 11,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["opportunity_name", "contact", "account", "stage", "amount", "probability", "expected_close_date", "source", "next_step", "description", "tags"],
          requiredFields: ["opportunity_name", "contact", "account", "stage", "amount", "expected_close_date"],
          defaultPrompts: [],
        },
        "role-manager": {
          roleId: "role-manager",
          enabledFields: ["opportunity_name", "contact", "account", "stage", "amount", "probability", "expected_close_date", "source", "next_step", "description", "tags"],
          requiredFields: ["opportunity_name", "contact", "stage", "amount", "expected_close_date"],
          defaultPrompts: [],
        },
        "role-sales": {
          roleId: "role-sales",
          enabledFields: ["opportunity_name", "contact", "account", "stage", "amount", "probability", "expected_close_date", "next_step", "description", "tags"],
          requiredFields: ["opportunity_name", "contact", "stage", "amount"],
          defaultPrompts: [],
        },
      },
    }),
  },

  // Contact Form
  {
    moduleId: "crm",
    formId: "new-contact",
    name: "New Contact",
    description: "Create a new contact",
    icon: "User",
    category: "Contacts",
    defaultConfig: () => ({
      moduleId: "crm",
      formId: "new-contact",
      name: "New Contact",
      description: "Create a new contact",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "first_name",
          name: "first_name",
          label: "First Name",
          fieldType: "Text",
          validation: { required: true },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "last_name",
          name: "last_name",
          label: "Last Name",
          fieldType: "Text",
          validation: { required: true },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "email",
          name: "email",
          label: "Email",
          fieldType: "Email",
          validation: { required: true },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "phone",
          name: "phone",
          label: "Phone",
          fieldType: "Tel",
          validation: { required: false },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "mobile",
          name: "mobile",
          label: "Mobile",
          fieldType: "Tel",
          validation: { required: false },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "company",
          name: "company",
          label: "Company",
          fieldType: "Text",
          validation: { required: false },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "job_title",
          name: "job_title",
          label: "Job Title",
          fieldType: "Text",
          validation: { required: false },
          aiSuggestions: [],
          order: 7,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "department",
          name: "department",
          label: "Department",
          fieldType: "Text",
          validation: { required: false },
          aiSuggestions: [],
          order: 8,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "address",
          name: "address",
          label: "Address",
          fieldType: "Textarea",
          validation: { required: false },
          aiSuggestions: [],
          order: 9,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "notes",
          name: "notes",
          label: "Notes",
          fieldType: "Textarea",
          validation: { required: false },
          aiSuggestions: [],
          order: 10,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "tags",
          name: "tags",
          label: "Tags",
          fieldType: "Tags",
          validation: { required: false },
          aiSuggestions: [],
          order: 11,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["first_name", "last_name", "email", "phone", "mobile", "company", "job_title", "department", "address", "notes", "tags"],
          requiredFields: ["first_name", "last_name", "email"],
          defaultPrompts: [],
        },
        "role-sales": {
          roleId: "role-sales",
          enabledFields: ["first_name", "last_name", "email", "phone", "company", "job_title", "notes", "tags"],
          requiredFields: ["first_name", "last_name", "email"],
          defaultPrompts: [],
        },
      },
    }),
  },

  // Activity Form
  {
    moduleId: "crm",
    formId: "new-activity",
    name: "New Activity",
    description: "Log a new activity (call, email, meeting)",
    icon: "Activity",
    category: "Activities",
    defaultConfig: () => ({
      moduleId: "crm",
      formId: "new-activity",
      name: "New Activity",
      description: "Log a new activity (call, email, meeting)",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "activity_type",
          name: "activity_type",
          label: "Activity Type",
          fieldType: "Select",
          options: [
            { value: "call", label: "Phone Call", color: "green" },
            { value: "email", label: "Email", color: "blue" },
            { value: "meeting", label: "Meeting", color: "purple" },
            { value: "task", label: "Task", color: "yellow" },
            { value: "note", label: "Note", color: "gray" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "subject",
          name: "subject",
          label: "Subject",
          fieldType: "Text",
          placeholder: "Activity subject",
          validation: { required: true },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "contact",
          name: "contact",
          label: "Contact",
          fieldType: "UserSelect",
          validation: { required: false },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "related_to",
          name: "related_to",
          label: "Related To",
          fieldType: "Text",
          placeholder: "Opportunity or account name",
          validation: { required: false },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "date",
          name: "date",
          label: "Date",
          fieldType: "DateTime",
          validation: { required: true },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "duration",
          name: "duration",
          label: "Duration (minutes)",
          fieldType: "Number",
          placeholder: "30",
          validation: { required: false, min: 0 },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "description",
          name: "description",
          label: "Description",
          fieldType: "Textarea",
          validation: { required: false },
          aiSuggestions: [],
          order: 7,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "completed",
          name: "completed",
          label: "Completed",
          fieldType: "Switch",
          validation: { required: false },
          aiSuggestions: [],
          order: 8,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["activity_type", "subject", "contact", "related_to", "date", "duration", "description", "completed"],
          requiredFields: ["activity_type", "subject", "date"],
          defaultPrompts: [],
        },
        "role-sales": {
          roleId: "role-sales",
          enabledFields: ["activity_type", "subject", "contact", "related_to", "date", "duration", "description", "completed"],
          requiredFields: ["activity_type", "subject", "date"],
          defaultPrompts: [],
        },
      },
    }),
  },
]
