//! Expenses Module Form Configurations
//!
//! This module provides form configurations for Expenses.
//! Includes forms for: Expenses, Expense Reports

import type { FormRegistryEntry } from "../types"

export const expensesForms: FormRegistryEntry[] = [
  // Expense Form
  {
    moduleId: "expenses",
    formId: "new-expense",
    name: "New Expense",
    description: "Submit a new expense",
    icon: "Receipt",
    category: "Expenses",
    defaultConfig: () => ({
      moduleId: "expenses",
      formId: "new-expense",
      name: "New Expense",
      description: "Submit a new expense",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "description",
          name: "description",
          label: "Description",
          fieldType: "Text",
          placeholder: "What was this expense for?",
          validation: { required: true, minLength: 3 },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Full",
        },
        {
          fieldId: "amount",
          name: "amount",
          label: "Amount",
          fieldType: "Number",
          placeholder: "0.00",
          validation: { required: true, min: 0.01 },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "currency",
          name: "currency",
          label: "Currency",
          fieldType: "Select",
          options: [
            { value: "USD", label: "USD", color: "blue" },
            { value: "EUR", label: "EUR", color: "green" },
            { value: "GBP", label: "GBP", color: "purple" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "category",
          name: "category",
          label: "Category",
          fieldType: "Select",
          options: [
            { value: "travel", label: "Travel", color: "blue" },
            { value: "meals", label: "Meals & Entertainment", color: "green" },
            { value: "supplies", label: "Office Supplies", color: "orange" },
            { value: "software", label: "Software & Subscriptions", color: "purple" },
            { value: "equipment", label: "Equipment", color: "teal" },
            { value: "training", label: "Training & Education", color: "pink" },
            { value: "other", label: "Other", color: "gray" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "date",
          name: "date",
          label: "Date",
          fieldType: "Date",
          validation: { required: true },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "vendor",
          name: "vendor",
          label: "Vendor",
          fieldType: "Text",
          placeholder: "Where was this purchased?",
          validation: { required: false },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "notes",
          name: "notes",
          label: "Notes",
          fieldType: "Textarea",
          validation: { required: false },
          aiSuggestions: [],
          order: 7,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "receipt",
          name: "receipt",
          label: "Receipt",
          fieldType: "File",
          validation: { required: false },
          aiSuggestions: [],
          order: 8,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["description", "amount", "currency", "category", "date", "vendor", "notes", "receipt"],
          requiredFields: ["description", "amount", "currency", "category", "date"],
          defaultPrompts: [],
        },
        "role-manager": {
          roleId: "role-manager",
          enabledFields: ["description", "amount", "currency", "category", "date", "vendor", "notes", "receipt"],
          requiredFields: ["description", "amount", "category", "date"],
          defaultPrompts: [],
        },
      },
    }),
  },

  // Expense Report Form
  {
    moduleId: "expenses",
    formId: "new-expense-report",
    name: "New Expense Report",
    description: "Create an expense report to group multiple expenses",
    icon: "FileText",
    category: "Reports",
    defaultConfig: () => ({
      moduleId: "expenses",
      formId: "new-expense-report",
      name: "New Expense Report",
      description: "Create an expense report to group multiple expenses",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "title",
          name: "title",
          label: "Report Title",
          fieldType: "Text",
          placeholder: "e.g., Business Trip - March 2024",
          validation: { required: true },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Full",
        },
        {
          fieldId: "period_start",
          name: "period_start",
          label: "Period Start",
          fieldType: "Date",
          validation: { required: true },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "period_end",
          name: "period_end",
          label: "Period End",
          fieldType: "Date",
          validation: { required: true },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "notes",
          name: "notes",
          label: "Notes",
          fieldType: "Textarea",
          validation: { required: false },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["title", "period_start", "period_end", "notes"],
          requiredFields: ["title", "period_start", "period_end"],
          defaultPrompts: [],
        },
        "role-manager": {
          roleId: "role-manager",
          enabledFields: ["title", "period_start", "period_end", "notes"],
          requiredFields: ["title", "period_start", "period_end"],
          defaultPrompts: [],
        },
      },
    }),
  },
]
