//! Helpdesk Module Form Configurations
//!
//! This module provides form configurations for Helpdesk/Support.
//! Includes forms for: Support Tickets

import type { FormRegistryEntry } from "../types"

export const helpdeskForms: FormRegistryEntry[] = [
  // Support Ticket Form
  {
    moduleId: "helpdesk",
    formId: "new-ticket",
    name: "New Ticket",
    description: "Create a new support ticket",
    icon: "LifeBuoy",
    category: "Tickets",
    defaultConfig: () => ({
      moduleId: "helpdesk",
      formId: "new-ticket",
      name: "New Ticket",
      description: "Create a new support ticket",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "subject",
          name: "subject",
          label: "Subject",
          fieldType: "Text",
          placeholder: "Brief description of the issue",
          validation: { required: true, minLength: 5 },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Full",
        },
        {
          fieldId: "description",
          name: "description",
          label: "Description",
          fieldType: "Textarea",
          placeholder: "Detailed description of your issue...",
          validation: { required: true, minLength: 20 },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "category",
          name: "category",
          label: "Category",
          fieldType: "Select",
          options: [
            { value: "technical", label: "Technical Issue", color: "red" },
            { value: "billing", label: "Billing", color: "green" },
            { value: "account", label: "Account", color: "blue" },
            { value: "feature", label: "Feature Request", color: "purple" },
            { value: "other", label: "Other", color: "gray" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "priority",
          name: "priority",
          label: "Priority",
          fieldType: "Select",
          options: [
            { value: "low", label: "Low", color: "gray" },
            { value: "medium", label: "Medium", color: "blue" },
            { value: "high", label: "High", color: "orange" },
            { value: "urgent", label: "Urgent", color: "red" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "attachments",
          name: "attachments",
          label: "Attachments",
          fieldType: "File",
          validation: { required: false },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "tags",
          name: "tags",
          label: "Tags",
          fieldType: "Tags",
          validation: { required: false },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["subject", "description", "category", "priority", "attachments", "tags"],
          requiredFields: ["subject", "description", "category", "priority"],
          defaultPrompts: [],
        },
        "role-manager": {
          roleId: "role-manager",
          enabledFields: ["subject", "description", "category", "priority", "attachments", "tags"],
          requiredFields: ["subject", "description", "category", "priority"],
          defaultPrompts: [],
        },
      },
    }),
  },
]
