//! HR Module Form Configurations
//!
//! This module provides form configurations for Human Resources.
//! Includes forms for: Employees, Leave Requests, Contracts

import type { FormRegistryEntry } from "../types"

export const hrForms: FormRegistryEntry[] = [
  // Employee Form
  {
    moduleId: "hr",
    formId: "new-employee",
    name: "New Employee",
    description: "Add a new employee to the system",
    icon: "Users",
    category: "Employees",
    defaultConfig: () => ({
      moduleId: "hr",
      formId: "new-employee",
      name: "New Employee",
      description: "Add a new employee to the system",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "first_name",
          name: "first_name",
          label: "First Name",
          fieldType: "Text",
          validation: { required: true },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "last_name",
          name: "last_name",
          label: "Last Name",
          fieldType: "Text",
          validation: { required: true },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "email",
          name: "email",
          label: "Email",
          fieldType: "Email",
          validation: { required: true },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "phone",
          name: "phone",
          label: "Phone",
          fieldType: "Tel",
          validation: { required: false },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "department",
          name: "department",
          label: "Department",
          fieldType: "Select",
          options: [
            { value: "engineering", label: "Engineering", color: "blue" },
            { value: "sales", label: "Sales", color: "green" },
            { value: "marketing", label: "Marketing", color: "purple" },
            { value: "hr", label: "Human Resources", color: "pink" },
            { value: "finance", label: "Finance", color: "yellow" },
            { value: "operations", label: "Operations", color: "orange" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "position",
          name: "position",
          label: "Position",
          fieldType: "Text",
          placeholder: "Job title",
          validation: { required: true },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "hire_date",
          name: "hire_date",
          label: "Hire Date",
          fieldType: "Date",
          validation: { required: true },
          aiSuggestions: [],
          order: 7,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "employment_type",
          name: "employment_type",
          label: "Employment Type",
          fieldType: "Select",
          options: [
            { value: "full-time", label: "Full-time", color: "green" },
            { value: "part-time", label: "Part-time", color: "blue" },
            { value: "contract", label: "Contract", color: "yellow" },
            { value: "intern", label: "Intern", color: "purple" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 8,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "manager",
          name: "manager",
          label: "Reports To",
          fieldType: "UserSelect",
          validation: { required: false },
          aiSuggestions: [],
          order: 9,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "address",
          name: "address",
          label: "Address",
          fieldType: "Textarea",
          validation: { required: false },
          aiSuggestions: [],
          order: 10,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "notes",
          name: "notes",
          label: "Notes",
          fieldType: "Textarea",
          validation: { required: false },
          aiSuggestions: [],
          order: 11,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["first_name", "last_name", "email", "phone", "department", "position", "hire_date", "employment_type", "manager", "address", "notes"],
          requiredFields: ["first_name", "last_name", "email", "department", "position", "hire_date"],
          defaultPrompts: [],
        },
        "role-manager": {
          roleId: "role-manager",
          enabledFields: ["first_name", "last_name", "email", "phone", "department", "position", "manager", "notes"],
          requiredFields: ["first_name", "last_name", "email", "department", "position"],
          defaultPrompts: [],
        },
      },
    }),
  },

  // Leave Request Form
  {
    moduleId: "hr",
    formId: "new-leave-request",
    name: "New Leave Request",
    description: "Submit a leave or time-off request",
    icon: "CalendarOff",
    category: "Leave",
    defaultConfig: () => ({
      moduleId: "hr",
      formId: "new-leave-request",
      name: "New Leave Request",
      description: "Submit a leave or time-off request",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "leave_type",
          name: "leave_type",
          label: "Leave Type",
          fieldType: "Select",
          options: [
            { value: "vacation", label: "Vacation", color: "blue" },
            { value: "sick", label: "Sick Leave", color: "red" },
            { value: "personal", label: "Personal", color: "purple" },
            { value: "parental", label: "Parental Leave", color: "pink" },
            { value: "bereavement", label: "Bereavement", color: "gray" },
            { value: "unpaid", label: "Unpaid Leave", color: "orange" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "start_date",
          name: "start_date",
          label: "Start Date",
          fieldType: "Date",
          validation: { required: true },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "end_date",
          name: "end_date",
          label: "End Date",
          fieldType: "Date",
          validation: { required: true },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "half_day",
          name: "half_day",
          label: "Half Day",
          fieldType: "Switch",
          validation: { required: false },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "reason",
          name: "reason",
          label: "Reason",
          fieldType: "Textarea",
          placeholder: "Provide a reason for your leave request...",
          validation: { required: true, minLength: 10 },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "notes",
          name: "notes",
          label: "Additional Notes",
          fieldType: "Textarea",
          validation: { required: false },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["leave_type", "start_date", "end_date", "half_day", "reason", "notes"],
          requiredFields: ["leave_type", "start_date", "end_date", "reason"],
          defaultPrompts: [],
        },
        "role-manager": {
          roleId: "role-manager",
          enabledFields: ["leave_type", "start_date", "end_date", "half_day", "reason", "notes"],
          requiredFields: ["leave_type", "start_date", "end_date", "reason"],
          defaultPrompts: [],
        },
      },
    }),
  },

  // Contract Form
  {
    moduleId: "hr",
    formId: "new-contract",
    name: "New Contract",
    description: "Create an employment contract",
    icon: "FileSignature",
    category: "Contracts",
    defaultConfig: () => ({
      moduleId: "hr",
      formId: "new-contract",
      name: "New Contract",
      description: "Create an employment contract",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "employee",
          name: "employee",
          label: "Employee",
          fieldType: "UserSelect",
          validation: { required: true },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "contract_type",
          name: "contract_type",
          label: "Contract Type",
          fieldType: "Select",
          options: [
            { value: "permanent", label: "Permanent", color: "green" },
            { value: "fixed-term", label: "Fixed Term", color: "blue" },
            { value: "part-time", label: "Part-time", color: "yellow" },
            { value: "contractor", label: "Contractor", color: "purple" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "start_date",
          name: "start_date",
          label: "Start Date",
          fieldType: "Date",
          validation: { required: true },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "end_date",
          name: "end_date",
          label: "End Date",
          fieldType: "Date",
          validation: { required: false },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "salary",
          name: "salary",
          label: "Salary",
          fieldType: "Number",
          placeholder: "Annual salary",
          validation: { required: true, min: 0 },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "currency",
          name: "currency",
          label: "Currency",
          fieldType: "Select",
          options: [
            { value: "USD", label: "USD", color: "blue" },
            { value: "EUR", label: "EUR", color: "green" },
            { value: "GBP", label: "GBP", color: "purple" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "notes",
          name: "notes",
          label: "Notes",
          fieldType: "Textarea",
          validation: { required: false },
          aiSuggestions: [],
          order: 7,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["employee", "contract_type", "start_date", "end_date", "salary", "currency", "notes"],
          requiredFields: ["employee", "contract_type", "start_date", "salary"],
          defaultPrompts: [],
        },
      },
    }),
  },
]
