//! Inventory Module Form Configurations
//!
//! This module provides form configurations for Inventory management.
//! Includes forms for: Products, Transfers, Adjustments

import type { FormRegistryEntry } from "../types"

export const inventoryForms: FormRegistryEntry[] = [
  // Product Form
  {
    moduleId: "inventory",
    formId: "new-product",
    name: "New Product",
    description: "Create a new product in inventory",
    icon: "Package",
    category: "Products",
    defaultConfig: () => ({
      moduleId: "inventory",
      formId: "new-product",
      name: "New Product",
      description: "Create a new product in inventory",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "sku",
          name: "sku",
          label: "SKU",
          fieldType: "Text",
          placeholder: "Product SKU",
          validation: { required: true, minLength: 3, maxLength: 50 },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "name",
          name: "name",
          label: "Product Name",
          fieldType: "Text",
          placeholder: "Enter product name",
          validation: { required: true, minLength: 2, maxLength: 100 },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "category",
          name: "category",
          label: "Category",
          fieldType: "Select",
          options: [
            { value: "electronics", label: "Electronics", color: "blue" },
            { value: "clothing", label: "Clothing", color: "purple" },
            { value: "food", label: "Food & Beverages", color: "green" },
            { value: "office", label: "Office Supplies", color: "yellow" },
            { value: "raw-materials", label: "Raw Materials", color: "orange" },
            { value: "finished-goods", label: "Finished Goods", color: "teal" },
            { value: "other", label: "Other", color: "gray" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "description",
          name: "description",
          label: "Description",
          fieldType: "Textarea",
          placeholder: "Product description...",
          validation: { required: false },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "unit_cost",
          name: "unit_cost",
          label: "Unit Cost",
          fieldType: "Number",
          placeholder: "0.00",
          validation: { required: true, min: 0 },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "unit_price",
          name: "unit_price",
          label: "Unit Price",
          fieldType: "Number",
          placeholder: "0.00",
          validation: { required: true, min: 0 },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "reorder_level",
          name: "reorder_level",
          label: "Reorder Level",
          fieldType: "Number",
          placeholder: "Minimum stock level",
          validation: { required: false, min: 0 },
          aiSuggestions: [],
          order: 7,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "reorder_quantity",
          name: "reorder_quantity",
          label: "Reorder Quantity",
          fieldType: "Number",
          placeholder: "Quantity to reorder",
          validation: { required: false, min: 1 },
          aiSuggestions: [],
          order: 8,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "weight",
          name: "weight",
          label: "Weight (kg)",
          fieldType: "Number",
          placeholder: "0.00",
          validation: { required: false, min: 0 },
          aiSuggestions: [],
          order: 9,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "dimensions",
          name: "dimensions",
          label: "Dimensions (LxWxH)",
          fieldType: "Text",
          placeholder: "e.g., 10x20x5 cm",
          validation: { required: false },
          aiSuggestions: [],
          order: 10,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "is_active",
          name: "is_active",
          label: "Active",
          fieldType: "Switch",
          validation: { required: false },
          aiSuggestions: [],
          order: 11,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "is_serialized",
          name: "is_serialized",
          label: "Track Serial Numbers",
          fieldType: "Switch",
          validation: { required: false },
          aiSuggestions: [],
          order: 12,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "tags",
          name: "tags",
          label: "Tags",
          fieldType: "Tags",
          validation: { required: false },
          aiSuggestions: [],
          order: 13,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["sku", "name", "category", "description", "unit_cost", "unit_price", "reorder_level", "reorder_quantity", "weight", "dimensions", "is_active", "is_serialized", "tags"],
          requiredFields: ["sku", "name", "category", "unit_price"],
          defaultPrompts: [],
        },
        "role-manager": {
          roleId: "role-manager",
          enabledFields: ["sku", "name", "category", "description", "unit_cost", "unit_price", "reorder_level", "reorder_quantity", "is_active", "tags"],
          requiredFields: ["sku", "name", "category", "unit_price"],
          defaultPrompts: [],
        },
        "role-warehouse": {
          roleId: "role-warehouse",
          enabledFields: ["sku", "name", "category", "reorder_level", "is_active"],
          requiredFields: ["sku", "name", "category"],
          defaultPrompts: [],
        },
      },
    }),
  },

  // Transfer Form
  {
    moduleId: "inventory",
    formId: "new-transfer",
    name: "New Transfer",
    description: "Create a stock transfer between warehouses",
    icon: "ArrowLeftRight",
    category: "Transfers",
    defaultConfig: () => ({
      moduleId: "inventory",
      formId: "new-transfer",
      name: "New Transfer",
      description: "Create a stock transfer between warehouses",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "transfer_number",
          name: "transfer_number",
          label: "Transfer Number",
          fieldType: "Text",
          placeholder: "Auto-generated",
          validation: { required: false },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "from_warehouse",
          name: "from_warehouse",
          label: "From Warehouse",
          fieldType: "Select",
          options: [
            { value: "warehouse-a", label: "Warehouse A", color: "blue" },
            { value: "warehouse-b", label: "Warehouse B", color: "green" },
            { value: "warehouse-c", label: "Warehouse C", color: "purple" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "to_warehouse",
          name: "to_warehouse",
          label: "To Warehouse",
          fieldType: "Select",
          options: [
            { value: "warehouse-a", label: "Warehouse A", color: "blue" },
            { value: "warehouse-b", label: "Warehouse B", color: "green" },
            { value: "warehouse-c", label: "Warehouse C", color: "purple" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "transfer_date",
          name: "transfer_date",
          label: "Transfer Date",
          fieldType: "Date",
          validation: { required: true },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "status",
          name: "status",
          label: "Status",
          fieldType: "Select",
          options: [
            { value: "draft", label: "Draft", color: "gray" },
            { value: "pending", label: "Pending", color: "yellow" },
            { value: "in-transit", label: "In Transit", color: "blue" },
            { value: "completed", label: "Completed", color: "green" },
            { value: "cancelled", label: "Cancelled", color: "red" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "notes",
          name: "notes",
          label: "Notes",
          fieldType: "Textarea",
          placeholder: "Transfer notes...",
          validation: { required: false },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "tags",
          name: "tags",
          label: "Tags",
          fieldType: "Tags",
          validation: { required: false },
          aiSuggestions: [],
          order: 7,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["transfer_number", "from_warehouse", "to_warehouse", "transfer_date", "status", "notes", "tags"],
          requiredFields: ["from_warehouse", "to_warehouse", "transfer_date", "status"],
          defaultPrompts: [],
        },
        "role-manager": {
          roleId: "role-manager",
          enabledFields: ["transfer_number", "from_warehouse", "to_warehouse", "transfer_date", "status", "notes"],
          requiredFields: ["from_warehouse", "to_warehouse", "transfer_date", "status"],
          defaultPrompts: [],
        },
        "role-warehouse": {
          roleId: "role-warehouse",
          enabledFields: ["from_warehouse", "to_warehouse", "transfer_date", "status", "notes"],
          requiredFields: ["from_warehouse", "to_warehouse", "transfer_date"],
          defaultPrompts: [],
        },
      },
    }),
  },

  // Inventory Adjustment Form
  {
    moduleId: "inventory",
    formId: "new-inventory-adjustment",
    name: "New Adjustment",
    description: "Record inventory adjustments (damaged, lost, found)",
    icon: "SlidersHorizontal",
    category: "Adjustments",
    defaultConfig: () => ({
      moduleId: "inventory",
      formId: "new-inventory-adjustment",
      name: "New Adjustment",
      description: "Record inventory adjustments (damaged, lost, found)",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "adjustment_number",
          name: "adjustment_number",
          label: "Adjustment Number",
          fieldType: "Text",
          validation: { required: false },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "reason",
          name: "reason",
          label: "Reason",
          fieldType: "Select",
          options: [
            { value: "damaged", label: "Damaged Goods", color: "red" },
            { value: "lost", label: "Lost/Missing", color: "orange" },
            { value: "found", label: "Found Items", color: "green" },
            { value: "expired", label: "Expired", color: "yellow" },
            { value: "cycle-count", label: "Cycle Count", color: "blue" },
            { value: "theft", label: "Theft", color: "red" },
            { value: "other", label: "Other", color: "gray" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "adjustment_date",
          name: "adjustment_date",
          label: "Adjustment Date",
          fieldType: "Date",
          validation: { required: true },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "warehouse",
          name: "warehouse",
          label: "Warehouse",
          fieldType: "Select",
          options: [
            { value: "warehouse-a", label: "Warehouse A", color: "blue" },
            { value: "warehouse-b", label: "Warehouse B", color: "green" },
            { value: "warehouse-c", label: "Warehouse C", color: "purple" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "description",
          name: "description",
          label: "Description",
          fieldType: "Textarea",
          placeholder: "Detailed explanation...",
          validation: { required: true, minLength: 10 },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "tags",
          name: "tags",
          label: "Tags",
          fieldType: "Tags",
          validation: { required: false },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["adjustment_number", "reason", "adjustment_date", "warehouse", "description", "tags"],
          requiredFields: ["reason", "adjustment_date", "warehouse", "description"],
          defaultPrompts: [],
        },
        "role-manager": {
          roleId: "role-manager",
          enabledFields: ["adjustment_number", "reason", "adjustment_date", "warehouse", "description", "tags"],
          requiredFields: ["reason", "adjustment_date", "warehouse", "description"],
          defaultPrompts: [],
        },
        "role-warehouse": {
          roleId: "role-warehouse",
          enabledFields: ["reason", "adjustment_date", "warehouse", "description"],
          requiredFields: ["reason", "adjustment_date", "warehouse", "description"],
          defaultPrompts: [],
        },
      },
    }),
  },
]
