//! Manufacturing Module Form Configurations
//!
//! This module provides form configurations for Manufacturing.
//! Includes forms for: BOM, Work Orders, Production Orders

import type { FormRegistryEntry } from "../types"

export const manufacturingForms: FormRegistryEntry[] = [
  // Bill of Materials Form
  {
    moduleId: "manufacturing",
    formId: "new-bom",
    name: "New Bill of Materials",
    description: "Create a bill of materials for a product",
    icon: "ClipboardList",
    category: "BOM",
    defaultConfig: () => ({
      moduleId: "manufacturing",
      formId: "new-bom",
      name: "New Bill of Materials",
      description: "Create a bill of materials for a product",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "name",
          name: "name",
          label: "BOM Name",
          fieldType: "Text",
          placeholder: "e.g., Widget BOM v1",
          validation: { required: true },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Full",
        },
        {
          fieldId: "product",
          name: "product",
          label: "Finished Product",
          fieldType: "Text",
          placeholder: "Product name",
          validation: { required: true },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "quantity",
          name: "quantity",
          label: "Batch Quantity",
          fieldType: "Number",
          placeholder: "1",
          validation: { required: true, min: 1 },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "version",
          name: "version",
          label: "Version",
          fieldType: "Text",
          placeholder: "e.g., 1.0",
          validation: { required: false },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "is_active",
          name: "is_active",
          label: "Active",
          fieldType: "Switch",
          validation: { required: false },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "notes",
          name: "notes",
          label: "Notes",
          fieldType: "Textarea",
          validation: { required: false },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["name", "product", "quantity", "version", "is_active", "notes"],
          requiredFields: ["name", "product", "quantity"],
          defaultPrompts: [],
        },
      },
    }),
  },

  // Work Order Form
  {
    moduleId: "manufacturing",
    formId: "new-work-order",
    name: "New Work Order",
    description: "Create a manufacturing work order",
    icon: "Wrench",
    category: "Work Orders",
    defaultConfig: () => ({
      moduleId: "manufacturing",
      formId: "new-work-order",
      name: "New Work Order",
      description: "Create a manufacturing work order",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "work_order_number",
          name: "work_order_number",
          label: "Work Order Number",
          fieldType: "Text",
          validation: { required: false },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "product",
          name: "product",
          label: "Product",
          fieldType: "Text",
          validation: { required: true },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "quantity",
          name: "quantity",
          label: "Quantity to Produce",
          fieldType: "Number",
          validation: { required: true, min: 1 },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "status",
          name: "status",
          label: "Status",
          fieldType: "Select",
          options: [
            { value: "planned", label: "Planned", color: "gray" },
            { value: "in-progress", label: "In Progress", color: "blue" },
            { value: "on-hold", label: "On Hold", color: "yellow" },
            { value: "completed", label: "Completed", color: "green" },
            { value: "cancelled", label: "Cancelled", color: "red" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "priority",
          name: "priority",
          label: "Priority",
          fieldType: "Select",
          options: [
            { value: "low", label: "Low", color: "gray" },
            { value: "normal", label: "Normal", color: "blue" },
            { value: "high", label: "High", color: "orange" },
            { value: "urgent", label: "Urgent", color: "red" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "due_date",
          name: "due_date",
          label: "Due Date",
          fieldType: "Date",
          validation: { required: false },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "notes",
          name: "notes",
          label: "Notes",
          fieldType: "Textarea",
          validation: { required: false },
          aiSuggestions: [],
          order: 7,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["work_order_number", "product", "quantity", "status", "priority", "due_date", "notes"],
          requiredFields: ["product", "quantity", "status"],
          defaultPrompts: [],
        },
      },
    }),
  },
]
