//! Projects Module Form Configurations
//!
//! This module provides form configurations for Project Management.
//! Includes forms for: Projects, Tasks

import type { FormRegistryEntry } from "../types"

export const projectsForms: FormRegistryEntry[] = [
  // Project Form
  {
    moduleId: "projects",
    formId: "new-project",
    name: "New Project",
    description: "Create a new project",
    icon: "FolderKanban",
    category: "Projects",
    defaultConfig: () => ({
      moduleId: "projects",
      formId: "new-project",
      name: "New Project",
      description: "Create a new project",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "name",
          name: "name",
          label: "Project Name",
          fieldType: "Text",
          placeholder: "Enter project name",
          validation: { required: true, minLength: 3 },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Full",
        },
        {
          fieldId: "description",
          name: "description",
          label: "Description",
          fieldType: "Textarea",
          placeholder: "Project description...",
          validation: { required: true, minLength: 20 },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "client",
          name: "client",
          label: "Client",
          fieldType: "Text",
          placeholder: "Client name",
          validation: { required: false },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "status",
          name: "status",
          label: "Status",
          fieldType: "Select",
          options: [
            { value: "planning", label: "Planning", color: "gray" },
            { value: "active", label: "Active", color: "blue" },
            { value: "on-hold", label: "On Hold", color: "yellow" },
            { value: "completed", label: "Completed", color: "green" },
            { value: "cancelled", label: "Cancelled", color: "red" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "start_date",
          name: "start_date",
          label: "Start Date",
          fieldType: "Date",
          validation: { required: true },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "end_date",
          name: "end_date",
          label: "End Date",
          fieldType: "Date",
          validation: { required: false },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "budget",
          name: "budget",
          label: "Budget",
          fieldType: "Number",
          placeholder: "Project budget",
          validation: { required: false, min: 0 },
          aiSuggestions: [],
          order: 7,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "priority",
          name: "priority",
          label: "Priority",
          fieldType: "Select",
          options: [
            { value: "low", label: "Low", color: "gray" },
            { value: "medium", label: "Medium", color: "blue" },
            { value: "high", label: "High", color: "orange" },
            { value: "critical", label: "Critical", color: "red" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 8,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "tags",
          name: "tags",
          label: "Tags",
          fieldType: "Tags",
          validation: { required: false },
          aiSuggestions: [],
          order: 9,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["name", "description", "client", "status", "start_date", "end_date", "budget", "priority", "tags"],
          requiredFields: ["name", "description", "status", "start_date", "priority"],
          defaultPrompts: [],
        },
        "role-manager": {
          roleId: "role-manager",
          enabledFields: ["name", "description", "client", "status", "start_date", "end_date", "priority", "tags"],
          requiredFields: ["name", "description", "status", "start_date", "priority"],
          defaultPrompts: [],
        },
      },
    }),
  },

  // Task Form
  {
    moduleId: "projects",
    formId: "new-task",
    name: "New Task",
    description: "Create a new project task",
    icon: "CheckSquare",
    category: "Tasks",
    defaultConfig: () => ({
      moduleId: "projects",
      formId: "new-task",
      name: "New Task",
      description: "Create a new project task",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "title",
          name: "title",
          label: "Task Title",
          fieldType: "Text",
          placeholder: "Enter task title",
          validation: { required: true, minLength: 3 },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Full",
        },
        {
          fieldId: "description",
          name: "description",
          label: "Description",
          fieldType: "Textarea",
          validation: { required: false },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "assignee",
          name: "assignee",
          label: "Assignee",
          fieldType: "UserSelect",
          validation: { required: false },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "status",
          name: "status",
          label: "Status",
          fieldType: "Select",
          options: [
            { value: "todo", label: "To Do", color: "gray" },
            { value: "in-progress", label: "In Progress", color: "blue" },
            { value: "review", label: "In Review", color: "yellow" },
            { value: "done", label: "Done", color: "green" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "priority",
          name: "priority",
          label: "Priority",
          fieldType: "Select",
          options: [
            { value: "low", label: "Low", color: "gray" },
            { value: "medium", label: "Medium", color: "blue" },
            { value: "high", label: "High", color: "orange" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "due_date",
          name: "due_date",
          label: "Due Date",
          fieldType: "Date",
          validation: { required: false },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "estimated_hours",
          name: "estimated_hours",
          label: "Estimated Hours",
          fieldType: "Number",
          placeholder: "0",
          validation: { required: false, min: 0 },
          aiSuggestions: [],
          order: 7,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "tags",
          name: "tags",
          label: "Tags",
          fieldType: "Tags",
          validation: { required: false },
          aiSuggestions: [],
          order: 8,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["title", "description", "assignee", "status", "priority", "due_date", "estimated_hours", "tags"],
          requiredFields: ["title", "status", "priority"],
          defaultPrompts: [],
        },
        "role-manager": {
          roleId: "role-manager",
          enabledFields: ["title", "description", "assignee", "status", "priority", "due_date", "estimated_hours", "tags"],
          requiredFields: ["title", "status", "priority"],
          defaultPrompts: [],
        },
      },
    }),
  },
]
