//! Proposals Module Form Configurations
//!
//! This module provides form configurations for Proposals.

import type { FormRegistryEntry } from "../types"

export const proposalsForms: FormRegistryEntry[] = [
  // Proposal Form
  {
    moduleId: "proposals",
    formId: "new-proposal",
    name: "New Proposal",
    description: "Create a new proposal",
    icon: "FileText",
    category: "Proposals",
    defaultConfig: () => ({
      moduleId: "proposals",
      formId: "new-proposal",
      name: "New Proposal",
      description: "Create a new proposal",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "title",
          name: "title",
          label: "Proposal Title",
          fieldType: "Text",
          placeholder: "Enter proposal title",
          validation: { required: true, minLength: 3 },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Full",
        },
        {
          fieldId: "client",
          name: "client",
          label: "Client",
          fieldType: "UserSelect",
          validation: { required: true },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "status",
          name: "status",
          label: "Status",
          fieldType: "Select",
          options: [
            { value: "draft", label: "Draft", color: "gray" },
            { value: "sent", label: "Sent", color: "blue" },
            { value: "viewed", label: "Viewed", color: "yellow" },
            { value: "negotiating", label: "Negotiating", color: "orange" },
            { value: "accepted", label: "Accepted", color: "green" },
            { value: "rejected", label: "Rejected", color: "red" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "valid_until",
          name: "valid_until",
          label: "Valid Until",
          fieldType: "Date",
          validation: { required: true },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "amount",
          name: "amount",
          label: "Total Amount",
          fieldType: "Number",
          placeholder: "0.00",
          validation: { required: true, min: 0 },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "description",
          name: "description",
          label: "Description",
          fieldType: "Textarea",
          placeholder: "Proposal description...",
          validation: { required: false },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "notes",
          name: "notes",
          label: "Internal Notes",
          fieldType: "Textarea",
          validation: { required: false },
          aiSuggestions: [],
          order: 7,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "tags",
          name: "tags",
          label: "Tags",
          fieldType: "Tags",
          validation: { required: false },
          aiSuggestions: [],
          order: 8,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["title", "client", "status", "valid_until", "amount", "description", "notes", "tags"],
          requiredFields: ["title", "client", "status", "valid_until", "amount"],
          defaultPrompts: [],
        },
        "role-manager": {
          roleId: "role-manager",
          enabledFields: ["title", "client", "status", "valid_until", "amount", "description", "notes", "tags"],
          requiredFields: ["title", "client", "status", "valid_until", "amount"],
          defaultPrompts: [],
        },
        "role-sales": {
          roleId: "role-sales",
          enabledFields: ["title", "client", "status", "valid_until", "amount", "description", "tags"],
          requiredFields: ["title", "client", "status", "valid_until", "amount"],
          defaultPrompts: [],
        },
      },
    }),
  },
]
