//! Purchasing Module Form Configurations
//!
//! This module provides form configurations for Purchasing.
//! Includes forms for: Purchase Orders, Requisitions

import type { FormRegistryEntry } from "../types"

export const purchasingForms: FormRegistryEntry[] = [
  // Purchase Order Form
  {
    moduleId: "purchasing",
    formId: "new-purchase-order",
    name: "New Purchase Order",
    description: "Create a new purchase order",
    icon: "ShoppingBag",
    category: "Purchasing",
    defaultConfig: () => ({
      moduleId: "purchasing",
      formId: "new-purchase-order",
      name: "New Purchase Order",
      description: "Create a new purchase order",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "po_number",
          name: "po_number",
          label: "PO Number",
          fieldType: "Text",
          placeholder: "Auto-generated",
          validation: { required: false },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "vendor",
          name: "vendor",
          label: "Vendor",
          fieldType: "Text",
          placeholder: "Vendor name",
          validation: { required: true },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "order_date",
          name: "order_date",
          label: "Order Date",
          fieldType: "Date",
          validation: { required: true },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "expected_date",
          name: "expected_date",
          label: "Expected Delivery Date",
          fieldType: "Date",
          validation: { required: false },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "status",
          name: "status",
          label: "Status",
          fieldType: "Select",
          options: [
            { value: "draft", label: "Draft", color: "gray" },
            { value: "sent", label: "Sent", color: "blue" },
            { value: "acknowledged", label: "Acknowledged", color: "yellow" },
            { value: "received", label: "Received", color: "green" },
            { value: "cancelled", label: "Cancelled", color: "red" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "payment_terms",
          name: "payment_terms",
          label: "Payment Terms",
          fieldType: "Select",
          options: [
            { value: "immediate", label: "Immediate", color: "red" },
            { value: "net-15", label: "Net 15", color: "orange" },
            { value: "net-30", label: "Net 30", color: "yellow" },
            { value: "net-45", label: "Net 45", color: "blue" },
            { value: "net-60", label: "Net 60", color: "purple" },
          ],
          validation: { required: false },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "notes",
          name: "notes",
          label: "Notes",
          fieldType: "Textarea",
          validation: { required: false },
          aiSuggestions: [],
          order: 7,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "tags",
          name: "tags",
          label: "Tags",
          fieldType: "Tags",
          validation: { required: false },
          aiSuggestions: [],
          order: 8,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["po_number", "vendor", "order_date", "expected_date", "status", "payment_terms", "notes", "tags"],
          requiredFields: ["vendor", "order_date", "status"],
          defaultPrompts: [],
        },
        "role-manager": {
          roleId: "role-manager",
          enabledFields: ["po_number", "vendor", "order_date", "expected_date", "status", "notes", "tags"],
          requiredFields: ["vendor", "order_date", "status"],
          defaultPrompts: [],
        },
      },
    }),
  },

  // Purchase Requisition Form
  {
    moduleId: "purchasing",
    formId: "new-purchase-requisition",
    name: "New Requisition",
    description: "Create a purchase requisition request",
    icon: "FilePlus",
    category: "Requisitions",
    defaultConfig: () => ({
      moduleId: "purchasing",
      formId: "new-purchase-requisition",
      name: "New Requisition",
      description: "Create a purchase requisition request",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "title",
          name: "title",
          label: "Title",
          fieldType: "Text",
          placeholder: "Requisition title",
          validation: { required: true },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Full",
        },
        {
          fieldId: "requested_by",
          name: "requested_by",
          label: "Requested By",
          fieldType: "UserSelect",
          validation: { required: true },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "department",
          name: "department",
          label: "Department",
          fieldType: "Select",
          options: [
            { value: "engineering", label: "Engineering", color: "blue" },
            { value: "sales", label: "Sales", color: "green" },
            { value: "marketing", label: "Marketing", color: "purple" },
            { value: "operations", label: "Operations", color: "orange" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "justification",
          name: "justification",
          label: "Business Justification",
          fieldType: "Textarea",
          placeholder: "Explain why this purchase is needed...",
          validation: { required: true, minLength: 20 },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "estimated_amount",
          name: "estimated_amount",
          label: "Estimated Amount",
          fieldType: "Number",
          placeholder: "0.00",
          validation: { required: true, min: 0 },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "priority",
          name: "priority",
          label: "Priority",
          fieldType: "Select",
          options: [
            { value: "low", label: "Low", color: "gray" },
            { value: "normal", label: "Normal", color: "blue" },
            { value: "high", label: "High", color: "orange" },
            { value: "urgent", label: "Urgent", color: "red" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "notes",
          name: "notes",
          label: "Notes",
          fieldType: "Textarea",
          validation: { required: false },
          aiSuggestions: [],
          order: 7,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["title", "requested_by", "department", "justification", "estimated_amount", "priority", "notes"],
          requiredFields: ["title", "requested_by", "justification", "estimated_amount", "priority"],
          defaultPrompts: [],
        },
        "role-manager": {
          roleId: "role-manager",
          enabledFields: ["title", "requested_by", "department", "justification", "estimated_amount", "priority", "notes"],
          requiredFields: ["title", "requested_by", "justification", "estimated_amount"],
          defaultPrompts: [],
        },
      },
    }),
  },
]
