//! Reports Module Form Configurations
//!
//! This module provides form configurations for Reports.

import type { FormRegistryEntry } from "../types"

export const reportsForms: FormRegistryEntry[] = [
  // Report Generation Form
  {
    moduleId: "reports",
    formId: "generate-report",
    name: "Generate Report",
    description: "Generate a new report",
    icon: "BarChart",
    category: "Reports",
    defaultConfig: () => ({
      moduleId: "reports",
      formId: "generate-report",
      name: "Generate Report",
      description: "Generate a new report",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "report_type",
          name: "report_type",
          label: "Report Type",
          fieldType: "Select",
          options: [
            { value: "sales", label: "Sales Report", color: "green" },
            { value: "inventory", label: "Inventory Report", color: "blue" },
            { value: "financial", label: "Financial Report", color: "purple" },
            { value: "hr", label: "HR Report", color: "pink" },
            { value: "project", label: "Project Report", color: "orange" },
            { value: "custom", label: "Custom Report", color: "gray" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "title",
          name: "title",
          label: "Report Title",
          fieldType: "Text",
          placeholder: "Enter report title",
          validation: { required: true },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Full",
        },
        {
          fieldId: "date_from",
          name: "date_from",
          label: "From Date",
          fieldType: "Date",
          validation: { required: true },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "date_to",
          name: "date_to",
          label: "To Date",
          fieldType: "Date",
          validation: { required: true },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "format",
          name: "format",
          label: "Output Format",
          fieldType: "Select",
          options: [
            { value: "pdf", label: "PDF", color: "red" },
            { value: "excel", label: "Excel", color: "green" },
            { value: "csv", label: "CSV", color: "blue" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "notes",
          name: "notes",
          label: "Notes",
          fieldType: "Textarea",
          validation: { required: false },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["report_type", "title", "date_from", "date_to", "format", "notes"],
          requiredFields: ["report_type", "title", "date_from", "date_to", "format"],
          defaultPrompts: [],
        },
        "role-manager": {
          roleId: "role-manager",
          enabledFields: ["report_type", "title", "date_from", "date_to", "format", "notes"],
          requiredFields: ["report_type", "title", "date_from", "date_to"],
          defaultPrompts: [],
        },
      },
    }),
  },
]
