//! Sales Module Form Configurations
//!
//! This module provides form configurations for Sales module.
//! Includes forms for: Sale Orders, Price Lists

import type { FormRegistryEntry } from "../types"

export const salesForms: FormRegistryEntry[] = [
  // Sale Order Form
  {
    moduleId: "sales",
    formId: "new-sale-order",
    name: "New Sale Order",
    description: "Create a new sales order",
    icon: "ShoppingCart",
    category: "Sales",
    defaultConfig: () => ({
      moduleId: "sales",
      formId: "new-sale-order",
      name: "New Sale Order",
      description: "Create a new sales order",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "order_number",
          name: "order_number",
          label: "Order Number",
          fieldType: "Text",
          placeholder: "Auto-generated if left blank",
          validation: { required: false },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "customer",
          name: "customer",
          label: "Customer",
          fieldType: "UserSelect",
          validation: { required: true },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "order_date",
          name: "order_date",
          label: "Order Date",
          fieldType: "Date",
          validation: { required: true },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "delivery_date",
          name: "delivery_date",
          label: "Delivery Date",
          fieldType: "Date",
          validation: { required: false },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "status",
          name: "status",
          label: "Status",
          fieldType: "Select",
          options: [
            { value: "draft", label: "Draft", color: "gray" },
            { value: "confirmed", label: "Confirmed", color: "blue" },
            { value: "processing", label: "Processing", color: "yellow" },
            { value: "shipped", label: "Shipped", color: "purple" },
            { value: "delivered", label: "Delivered", color: "green" },
            { value: "cancelled", label: "Cancelled", color: "red" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "payment_terms",
          name: "payment_terms",
          label: "Payment Terms",
          fieldType: "Select",
          options: [
            { value: "immediate", label: "Immediate", color: "red" },
            { value: "net-15", label: "Net 15", color: "orange" },
            { value: "net-30", label: "Net 30", color: "yellow" },
            { value: "net-45", label: "Net 45", color: "blue" },
            { value: "net-60", label: "Net 60", color: "purple" },
            { value: "cash", label: "Cash on Delivery", color: "green" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "shipping_method",
          name: "shipping_method",
          label: "Shipping Method",
          fieldType: "Select",
          options: [
            { value: "standard", label: "Standard Shipping", color: "gray" },
            { value: "express", label: "Express Shipping", color: "blue" },
            { value: "overnight", label: "Overnight", color: "red" },
            { value: "pickup", label: "Customer Pickup", color: "green" },
          ],
          validation: { required: false },
          aiSuggestions: [],
          order: 7,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "shipping_address",
          name: "shipping_address",
          label: "Shipping Address",
          fieldType: "Textarea",
          placeholder: "Full shipping address",
          validation: { required: true },
          aiSuggestions: [],
          order: 8,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "billing_address",
          name: "billing_address",
          label: "Billing Address",
          fieldType: "Textarea",
          placeholder: "Full billing address",
          validation: { required: true },
          aiSuggestions: [],
          order: 9,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "notes",
          name: "notes",
          label: "Notes",
          fieldType: "Textarea",
          placeholder: "Additional notes for this order...",
          validation: { required: false },
          aiSuggestions: [],
          order: 10,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "discount_percent",
          name: "discount_percent",
          label: "Discount %",
          fieldType: "Number",
          placeholder: "0",
          defaultValue: "0",
          validation: { required: false, min: 0, max: 100 },
          aiSuggestions: [],
          order: 11,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "tax_rate",
          name: "tax_rate",
          label: "Tax Rate %",
          fieldType: "Number",
          placeholder: "0",
          defaultValue: "0",
          validation: { required: false, min: 0, max: 100 },
          aiSuggestions: [],
          order: 12,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "tags",
          name: "tags",
          label: "Tags",
          fieldType: "Tags",
          validation: { required: false },
          aiSuggestions: [],
          order: 13,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["order_number", "customer", "order_date", "delivery_date", "status", "payment_terms", "shipping_method", "shipping_address", "billing_address", "notes", "discount_percent", "tax_rate", "tags"],
          requiredFields: ["customer", "order_date", "status", "shipping_address", "billing_address"],
          defaultPrompts: [],
        },
        "role-manager": {
          roleId: "role-manager",
          enabledFields: ["order_number", "customer", "order_date", "delivery_date", "status", "payment_terms", "shipping_method", "shipping_address", "billing_address", "notes", "discount_percent", "tax_rate", "tags"],
          requiredFields: ["customer", "order_date", "status", "shipping_address"],
          defaultPrompts: [],
        },
        "role-sales": {
          roleId: "role-sales",
          enabledFields: ["customer", "order_date", "delivery_date", "status", "shipping_method", "shipping_address", "notes", "tags"],
          requiredFields: ["customer", "order_date", "status", "shipping_address"],
          defaultPrompts: [],
        },
      },
    }),
  },

  // Price List Form
  {
    moduleId: "sales",
    formId: "new-pricelist",
    name: "New Price List",
    description: "Create a new price list for products",
    icon: "DollarSign",
    category: "Pricing",
    defaultConfig: () => ({
      moduleId: "sales",
      formId: "new-pricelist",
      name: "New Price List",
      description: "Create a new price list for products",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "name",
          name: "name",
          label: "Price List Name",
          fieldType: "Text",
          placeholder: "e.g., Retail Prices 2024",
          validation: { required: true, minLength: 2, maxLength: 100 },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Full",
        },
        {
          fieldId: "description",
          name: "description",
          label: "Description",
          fieldType: "Textarea",
          placeholder: "Describe this price list...",
          validation: { required: false },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "currency",
          name: "currency",
          label: "Currency",
          fieldType: "Select",
          options: [
            { value: "USD", label: "USD - US Dollar", color: "blue" },
            { value: "EUR", label: "EUR - Euro", color: "green" },
            { value: "GBP", label: "GBP - British Pound", color: "purple" },
            { value: "CAD", label: "CAD - Canadian Dollar", color: "red" },
            { value: "AUD", label: "AUD - Australian Dollar", color: "yellow" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "valid_from",
          name: "valid_from",
          label: "Valid From",
          fieldType: "Date",
          validation: { required: true },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "valid_until",
          name: "valid_until",
          label: "Valid Until",
          fieldType: "Date",
          validation: { required: false },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "is_active",
          name: "is_active",
          label: "Active",
          fieldType: "Switch",
          validation: { required: false },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "discount_type",
          name: "discount_type",
          label: "Default Discount Type",
          fieldType: "Select",
          options: [
            { value: "percentage", label: "Percentage (%)", color: "blue" },
            { value: "fixed", label: "Fixed Amount", color: "green" },
            { value: "none", label: "No Discount", color: "gray" },
          ],
          validation: { required: false },
          aiSuggestions: [],
          order: 7,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "notes",
          name: "notes",
          label: "Notes",
          fieldType: "Textarea",
          validation: { required: false },
          aiSuggestions: [],
          order: 8,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["name", "description", "currency", "valid_from", "valid_until", "is_active", "discount_type", "notes"],
          requiredFields: ["name", "currency", "valid_from", "is_active"],
          defaultPrompts: [],
        },
        "role-manager": {
          roleId: "role-manager",
          enabledFields: ["name", "description", "currency", "valid_from", "valid_until", "is_active", "discount_type", "notes"],
          requiredFields: ["name", "currency", "valid_from"],
          defaultPrompts: [],
        },
      },
    }),
  },
]
