//! Subscriptions Module Form Configurations
//!
//! This module provides form configurations for Subscriptions.

import type { FormRegistryEntry } from "../types"

export const subscriptionsForms: FormRegistryEntry[] = [
  // Subscription Form
  {
    moduleId: "subscriptions",
    formId: "new-subscription",
    name: "New Subscription",
    description: "Create a new subscription",
    icon: "RefreshCw",
    category: "Subscriptions",
    defaultConfig: () => ({
      moduleId: "subscriptions",
      formId: "new-subscription",
      name: "New Subscription",
      description: "Create a new subscription",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "name",
          name: "name",
          label: "Subscription Name",
          fieldType: "Text",
          placeholder: "e.g., Monthly Service",
          validation: { required: true },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Full",
        },
        {
          fieldId: "customer",
          name: "customer",
          label: "Customer",
          fieldType: "UserSelect",
          validation: { required: true },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "plan",
          name: "plan",
          label: "Plan",
          fieldType: "Select",
          options: [
            { value: "basic", label: "Basic", color: "gray" },
            { value: "standard", label: "Standard", color: "blue" },
            { value: "premium", label: "Premium", color: "purple" },
            { value: "enterprise", label: "Enterprise", color: "gold" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "amount",
          name: "amount",
          label: "Amount",
          fieldType: "Number",
          placeholder: "0.00",
          validation: { required: true, min: 0 },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "billing_cycle",
          name: "billing_cycle",
          label: "Billing Cycle",
          fieldType: "Select",
          options: [
            { value: "monthly", label: "Monthly", color: "blue" },
            { value: "quarterly", label: "Quarterly", color: "green" },
            { value: "yearly", label: "Yearly", color: "purple" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "start_date",
          name: "start_date",
          label: "Start Date",
          fieldType: "Date",
          validation: { required: true },
          aiSuggestions: [],
          order: 6,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "end_date",
          name: "end_date",
          label: "End Date",
          fieldType: "Date",
          validation: { required: false },
          aiSuggestions: [],
          order: 7,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "status",
          name: "status",
          label: "Status",
          fieldType: "Select",
          options: [
            { value: "active", label: "Active", color: "green" },
            { value: "paused", label: "Paused", color: "yellow" },
            { value: "cancelled", label: "Cancelled", color: "red" },
            { value: "expired", label: "Expired", color: "gray" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 8,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "notes",
          name: "notes",
          label: "Notes",
          fieldType: "Textarea",
          validation: { required: false },
          aiSuggestions: [],
          order: 9,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["name", "customer", "plan", "amount", "billing_cycle", "start_date", "end_date", "status", "notes"],
          requiredFields: ["name", "customer", "plan", "amount", "start_date", "status"],
          defaultPrompts: [],
        },
      },
    }),
  },

  // Plan Form
  {
    moduleId: "subscriptions",
    formId: "new-plan",
    name: "New Plan",
    description: "Create a new subscription plan",
    icon: "Layers",
    category: "Plans",
    defaultConfig: () => ({
      moduleId: "subscriptions",
      formId: "new-plan",
      name: "New Plan",
      description: "Create a new subscription plan",
      isSystemDefault: true,
      fields: [
        {
          fieldId: "name",
          name: "name",
          label: "Plan Name",
          fieldType: "Text",
          placeholder: "e.g., Premium Plan",
          validation: { required: true },
          aiSuggestions: [],
          order: 1,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Full",
        },
        {
          fieldId: "description",
          name: "description",
          label: "Description",
          fieldType: "Textarea",
          validation: { required: false },
          aiSuggestions: [],
          order: 2,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Full",
        },
        {
          fieldId: "price",
          name: "price",
          label: "Price",
          fieldType: "Number",
          placeholder: "0.00",
          validation: { required: true, min: 0 },
          aiSuggestions: [],
          order: 3,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
        {
          fieldId: "billing_cycle",
          name: "billing_cycle",
          label: "Billing Cycle",
          fieldType: "Select",
          options: [
            { value: "monthly", label: "Monthly", color: "blue" },
            { value: "quarterly", label: "Quarterly", color: "green" },
            { value: "yearly", label: "Yearly", color: "purple" },
          ],
          validation: { required: true },
          aiSuggestions: [],
          order: 4,
          isSystem: true,
          isEnabled: true,
          showInList: false,
          width: "Half",
        },
        {
          fieldId: "is_active",
          name: "is_active",
          label: "Active",
          fieldType: "Switch",
          validation: { required: false },
          aiSuggestions: [],
          order: 5,
          isSystem: true,
          isEnabled: true,
          showInList: true,
          width: "Half",
        },
      ],
      roleConfigs: {
        "role-admin": {
          roleId: "role-admin",
          enabledFields: ["name", "description", "price", "billing_cycle", "is_active"],
          requiredFields: ["name", "price", "billing_cycle"],
          defaultPrompts: [],
        },
      },
    }),
  },
]
