[package]
name = "iot-gateway"
version.workspace = true
edition.workspace = true

[[bin]]
name = "iot-gateway"
path = "src/main.rs"

[dependencies]
axum = { workspace = true, features = ["macros", "ws"] }
tokio.workspace = true
tower-http.workspace = true
serde.workspace = true
serde_json.workspace = true
rumqttc = "0.24"
stdb-client.workspace = true
dotenvy.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
thiserror.workspace = true
dashmap.workspace = true
