#!/usr/bin/env python3
"""Emit a reviewed SQLite projection from the existing Rust-derived schema IR."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
POLICY = ROOT / "lumiere-codegen/offline-projection-policy.json"
OUTPUT = ROOT / "frontend/packages/offline/src/generated/product-category.ts"
IDENTIFIER = re.compile(r"^[a-z][a-z0-9_]*$")
# Deliberately bounded to the first projection. Unsupported types fail closed.
TYPES = {
    "U64": ("text", "TEXT", "u64"),
    "U32": ("integer", "INTEGER", "u32"),
    "String": ("text", "TEXT", "stringValue"),
}


def render(manifest: dict, policy: dict) -> str:
    if manifest.get("version") != 1 or policy.get("version") != 1:
        raise ValueError("unsupported schema or projection policy version")
    if policy.get("mode") != "read-only":
        raise ValueError("this emitter only supports read-only projections")
    tables = [t for t in manifest["tables"] if t["sql_name"] == policy["table"]]
    if len(tables) != 1:
        raise ValueError("projection table must resolve exactly once")
    table = tables[0]
    columns = {c["sql_name"]: c for c in table["columns"]}
    fields = policy["fields"]
    if len(fields) != len(set(fields)) or not {"id", "organization_id", "company_id"} <= set(fields):
        raise ValueError("projection needs unique identity and scope fields")
    if table["primary_key"] != {"column_name": "id", "ty": "U64"}:
        raise ValueError("unsupported primary key")
    selected = [columns[field] for field in fields]
    if any(not IDENTIFIER.fullmatch(name) for name in [table["sql_name"], *fields]):
        raise ValueError("invalid SQL identifier")
    for column in selected:
        if column["ty"] not in TYPES:
            raise ValueError(f"unsupported projection type: {column['ty']}")
    for field in ("id", "organization_id"):
        if columns[field]["ty"] != "U64" or columns[field]["nullable"]:
            raise ValueError("identity and organization must be non-null U64")
    if columns["company_id"]["ty"] != "U64" or not columns["company_id"]["nullable"]:
        raise ValueError("company projection requires nullable U64")
    # Only the reviewed fields affect compatibility; unrelated schema changes do not.
    semantic = {"policy": policy, "columns": selected}
    digest = hashlib.sha256(json.dumps(semantic, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
    drizzle_fields = []
    sql_fields = ['"_lumiere_scope" TEXT NOT NULL']
    decoder = []
    for column in selected:
        field = column["sql_name"]
        builder, sql_type, codec = TYPES[column["ty"]]
        nullable = column["nullable"]
        drizzle_fields.append(f'    {field}: {builder}("{field}")' + ("" if nullable else ".notNull()") + ",")
        sql_fields.append(f'"{field}" {sql_type}' + ("" if nullable else " NOT NULL"))
        expr = f'{codec}(row.{field})'
        if nullable:
            expr = f'row.{field} === null ? null : {expr}'
        decoder.append(f"    {field}: {expr},")
    sql_fields.append('PRIMARY KEY ("_lumiere_scope", "id")')
    ddl = f'CREATE TABLE IF NOT EXISTS "{table["sql_name"]}" (' + ", ".join(sql_fields) + ");"
    return "\n".join([
        "// Generated by scripts/generate-offline-projection.py. Do not edit.",
        'import {', '  integer,', '  primaryKey,', '  sqliteTable,', '  text,', '} from "drizzle-orm/sqlite-core";',
        'import { objectValue, stringValue, u32, u64 } from "../codecs.ts";',
        "",
        'export const projectionSchemaHash =', f'  "sha256:{digest}";',
        f'export const projectionResource = "{policy["resource"]}";',
        f'export const projectionTable = "{table["sql_name"]}";',
        'export const projectionFields = [', *[f'  "{field}",' for field in fields], '] as const;',
        'export const projectionDdl =', f"  '{ddl}';",
        "",
        'export const productCategory = sqliteTable(', '  projectionTable,', '  {',
        '    _lumiere_scope: text("_lumiere_scope").notNull(),',
        *drizzle_fields,
        '  },', '  (table) => [primaryKey({ columns: [table._lumiere_scope, table.id] })],', ');',
        "",
        'export type ProductCategory = Omit<', '  typeof productCategory.$inferSelect,', '  "_lumiere_scope"', '>;',
        "",
        "export function decodeProductCategory(value: unknown): ProductCategory {",
        "  const row = objectValue(value, projectionFields);",
        "  return {", *decoder, "  };", "}", "",
    ])


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("manifest", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render(json.loads(args.manifest.read_text()), json.loads(POLICY.read_text()))
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != content:
            raise SystemExit("offline projection drift; run make generate-offline-projection")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(content)


if __name__ == "__main__":
    main()
