import { expect, test } from "@playwright/test"

import {
  callReducerBff,
  expectNoAppError,
  fetchDefaultCompanyId,
  fetchSessionOrganizationId,
  gotoModule,
  isAiGatewayAvailable,
  openErpAiChat,
  scalarQueryId,
  selectEntityRowByText,
  smokeName,
  submitForm,
  waitForEntityActionEnabled,
} from "./helpers"

const none = { none: [] as [] }
const some = <T,>(value: T) => ({ some: value })

/**
 * MVP step 14: AI business insight via ERP Assistant RAG (skipped when gateway is down).
 */
test.describe("MVP AI RAG insight", { tag: "@p0" }, () => {
  test("assistant responds to a business question", async ({ page }) => {
    test.setTimeout(90_000)

    if (!(await isAiGatewayAvailable(page))) {
      if (process.env.E2E_REQUIRE_AI === "1") {
        throw new Error("E2E_REQUIRE_AI=1 but ai-gateway health check failed")
      }
      test.skip(true, "ai-gateway health check unavailable in this environment")
    }

    await page.goto("/overview")
    await expect(page).not.toHaveURL(/\/sign-in(?:\?|$)/)

    await openErpAiChat(page)
    await page.getByTestId("erp-ai-chat-input").fill("Summarize our open sales pipeline in one sentence.")
    await page.getByTestId("erp-ai-chat-send").click()

    const assistantMessage = page.getByTestId("erp-ai-chat-message-assistant").last()
    await expect(assistantMessage).toBeVisible({ timeout: 60_000 })
    await expect(assistantMessage).not.toHaveText(/^(|thinking…|thinking\.\.\.)$/i)
    await expectNoAppError(page)
  })
})

/**
 * AI-009: persisted AI insight creation + acknowledge lifecycle.
 *
 * Backend: `create_ai_insight` (spacetimedb/src/ai/intelligence.rs) inserts an
 * `AiInsight` row scoped by `organization_id` + optional `company_id`, with
 * `severity` (InsightSeverity enum) and a `CreateAiInsightParams` payload.
 * `acknowledge_insight` flips `is_acknowledged` for an un-dismissed insight.
 *
 * Setup goes through the reducer BFF (matching accounting-post-reconcile.spec.ts)
 * since insights are generated by AI integrations, not a user-facing create form.
 * The UI assertion covers the Documents → Insights tab surfacing the new row and
 * the toolbar Acknowledge action flipping the row state.
 */
test.describe("AI-009 AI insight creation + acknowledge", { tag: "@p0" }, () => {
  test("creates an AI insight via reducer and acknowledges it from the documents insights tab", async ({
    page,
  }) => {
    test.setTimeout(120_000)

    const organizationId = await fetchSessionOrganizationId(page)
    const companyId = await fetchDefaultCompanyId(page)
    const title = smokeName("ai009-insight")

    await callReducerBff(page, "create_ai_insight", [
      organizationId,
      some(companyId),
      {
        severity: { tag: "High" },
        title,
        description: "Inventory turnover dropped below target for three consecutive weeks.",
        recommendations: ["Review slow-moving SKUs", "Schedule a procurement cycle audit"],
        related_model: "stock_quant",
        confidence: 0.87,
        tags: ["inventory", "turnover"],
        related_id: none,
        generated_by: none,
        impact_score: some(0.72),
        priority: some(2),
        metadata: some(JSON.stringify({ test: "ai-009", title })),
      },
    ])

    let insightId = 0
    await expect
      .poll(
        async () => {
          const res = await page.request.get("/api/query/ai-insights")
          if (!res.ok()) return 0
          const json = (await res.json()) as {
            data?: Array<{ id?: unknown; title?: string; dismissed?: unknown; isAcknowledged?: unknown }>
          }
          const row = (json.data ?? []).find((r) => String(r.title ?? "") === title)
          if (!row) return 0
          insightId = scalarQueryId(row.id) ?? 0
          return insightId
        },
        { timeout: 30_000 },
      )
      .toBeGreaterThan(0)

    await gotoModule(page, "/documents", "documents")
    await page.getByTestId("module-tab-documents-document-insights").click()
    await expect(page.getByTestId("module-view-documents")).toBeVisible()

    await selectEntityRowByText(page, title)
    await waitForEntityActionEnabled(page, "entity-action-ack-insight")
    await page.getByTestId("entity-action-ack-insight").click()

    const ackFormId = "acknowledge-document-insight"
    await expect(page.getByTestId(`form-modal-${ackFormId}`)).toBeVisible()
    await submitForm(page, ackFormId)

    await expect
      .poll(
        async () => {
          const res = await page.request.get("/api/query/ai-insights")
          if (!res.ok()) return false
          const json = (await res.json()) as {
            data?: Array<{ id?: unknown; title?: string; isAcknowledged?: unknown }>
          }
          const row = (json.data ?? []).find((r) => scalarQueryId(r.id) === insightId)
          if (!row) return false
          const ack = row.isAcknowledged
          if (typeof ack === "boolean") return ack
          if (typeof ack === "object" && ack !== null && "some" in (ack as Record<string, unknown>)) {
            return Boolean((ack as { some: unknown }).some)
          }
          return false
        },
        { timeout: 30_000 },
      )
      .toBe(true)

    await expectNoAppError(page)
  })
})
