// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AiSkillFixture {
    pub id: u64,
    pub fixture_key: String,
    pub organization_id: u64,
    pub skill_id: u64,
    pub name: String,
    pub description: Option<String>,
    pub input_json: String,
    pub expected_output_json: String,
    pub created_by: __sdk::Identity,
    pub created_at: __sdk::Timestamp,
    pub metadata: Option<String>,
}

impl __sdk::InModule for AiSkillFixture {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AiSkillFixture`.
///
/// Provides typed access to columns for query building.
pub struct AiSkillFixtureCols {
    pub id: __sdk::__query_builder::Col<AiSkillFixture, u64>,
    pub fixture_key: __sdk::__query_builder::Col<AiSkillFixture, String>,
    pub organization_id: __sdk::__query_builder::Col<AiSkillFixture, u64>,
    pub skill_id: __sdk::__query_builder::Col<AiSkillFixture, u64>,
    pub name: __sdk::__query_builder::Col<AiSkillFixture, String>,
    pub description: __sdk::__query_builder::Col<AiSkillFixture, Option<String>>,
    pub input_json: __sdk::__query_builder::Col<AiSkillFixture, String>,
    pub expected_output_json: __sdk::__query_builder::Col<AiSkillFixture, String>,
    pub created_by: __sdk::__query_builder::Col<AiSkillFixture, __sdk::Identity>,
    pub created_at: __sdk::__query_builder::Col<AiSkillFixture, __sdk::Timestamp>,
    pub metadata: __sdk::__query_builder::Col<AiSkillFixture, Option<String>>,
}

impl __sdk::__query_builder::HasCols for AiSkillFixture {
    type Cols = AiSkillFixtureCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AiSkillFixtureCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            fixture_key: __sdk::__query_builder::Col::new(table_name, "fixture_key"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            skill_id: __sdk::__query_builder::Col::new(table_name, "skill_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
            input_json: __sdk::__query_builder::Col::new(table_name, "input_json"),
            expected_output_json: __sdk::__query_builder::Col::new(
                table_name,
                "expected_output_json",
            ),
            created_by: __sdk::__query_builder::Col::new(table_name, "created_by"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            metadata: __sdk::__query_builder::Col::new(table_name, "metadata"),
        }
    }
}

/// Indexed column accessor struct for the table `AiSkillFixture`.
///
/// Provides typed access to indexed columns for query building.
pub struct AiSkillFixtureIxCols {
    pub fixture_key: __sdk::__query_builder::IxCol<AiSkillFixture, String>,
    pub id: __sdk::__query_builder::IxCol<AiSkillFixture, u64>,
    pub organization_id: __sdk::__query_builder::IxCol<AiSkillFixture, u64>,
    pub skill_id: __sdk::__query_builder::IxCol<AiSkillFixture, u64>,
}

impl __sdk::__query_builder::HasIxCols for AiSkillFixture {
    type IxCols = AiSkillFixtureIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AiSkillFixtureIxCols {
            fixture_key: __sdk::__query_builder::IxCol::new(table_name, "fixture_key"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            organization_id: __sdk::__query_builder::IxCol::new(table_name, "organization_id"),
            skill_id: __sdk::__query_builder::IxCol::new(table_name, "skill_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AiSkillFixture {}
