// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ai_team_member_skill_type::AiTeamMemberSkill;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ai_team_member_skill`.
///
/// Obtain a handle from the [`AiTeamMemberSkillTableAccess::ai_team_member_skill`] method on [`super::RemoteTables`],
/// like `ctx.db.ai_team_member_skill()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ai_team_member_skill().on_insert(...)`.
pub struct AiTeamMemberSkillTableHandle<'ctx> {
    imp: __sdk::TableHandle<AiTeamMemberSkill>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ai_team_member_skill`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AiTeamMemberSkillTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AiTeamMemberSkillTableHandle`], which mediates access to the table `ai_team_member_skill`.
    fn ai_team_member_skill(&self) -> AiTeamMemberSkillTableHandle<'_>;
}

impl AiTeamMemberSkillTableAccess for super::RemoteTables {
    fn ai_team_member_skill(&self) -> AiTeamMemberSkillTableHandle<'_> {
        AiTeamMemberSkillTableHandle {
            imp: self
                .imp
                .get_table::<AiTeamMemberSkill>("ai_team_member_skill"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AiTeamMemberSkillInsertCallbackId(__sdk::CallbackId);
pub struct AiTeamMemberSkillDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AiTeamMemberSkillTableHandle<'ctx> {
    type Row = AiTeamMemberSkill;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AiTeamMemberSkill> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AiTeamMemberSkillInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AiTeamMemberSkillInsertCallbackId {
        AiTeamMemberSkillInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AiTeamMemberSkillInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AiTeamMemberSkillDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AiTeamMemberSkillDeleteCallbackId {
        AiTeamMemberSkillDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AiTeamMemberSkillDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AiTeamMemberSkillUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AiTeamMemberSkillTableHandle<'ctx> {
    type UpdateCallbackId = AiTeamMemberSkillUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AiTeamMemberSkillUpdateCallbackId {
        AiTeamMemberSkillUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AiTeamMemberSkillUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ai_team_member_skill`,
/// which allows point queries on the field of the same name
/// via the [`AiTeamMemberSkillIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ai_team_member_skill().id().find(...)`.
pub struct AiTeamMemberSkillIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AiTeamMemberSkill, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AiTeamMemberSkillTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ai_team_member_skill`.
    pub fn id(&self) -> AiTeamMemberSkillIdUnique<'ctx> {
        AiTeamMemberSkillIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AiTeamMemberSkillIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<AiTeamMemberSkill> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AiTeamMemberSkill>("ai_team_member_skill");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AiTeamMemberSkill>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AiTeamMemberSkill>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AiTeamMemberSkill`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ai_team_member_skillQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AiTeamMemberSkill`.
    fn ai_team_member_skill(&self) -> __sdk::__query_builder::Table<AiTeamMemberSkill>;
}

impl ai_team_member_skillQueryTableAccess for __sdk::QueryTableAccessor {
    fn ai_team_member_skill(&self) -> __sdk::__query_builder::Table<AiTeamMemberSkill> {
        __sdk::__query_builder::Table::new("ai_team_member_skill")
    }
}
