// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AppendAiAgentRunStepParams {
    pub step_no: u32,
    pub tool_name: String,
    pub input_hash: String,
    pub output_summary: String,
    pub output_row_count: Option<u32>,
    pub citations_json: Option<String>,
    pub duration_ms: u64,
    pub error_message: Option<String>,
}

impl __sdk::InModule for AppendAiAgentRunStepParams {
    type Module = super::RemoteModule;
}
