// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ApprovalRule {
    pub id: u64,
    pub organization_id: u64,
    pub company_id: Option<u64>,
    pub name: String,
    pub description: Option<String>,
    pub model: String,
    pub action: String,
    pub rule_type: String,
    pub threshold: f64,
    pub approver_role_id: Option<u64>,
    pub sequence: u32,
    pub is_active: bool,
    pub create_uid: __sdk::Identity,
    pub create_date: __sdk::Timestamp,
    pub write_uid: __sdk::Identity,
    pub write_date: __sdk::Timestamp,
    pub metadata: Option<String>,
}

impl __sdk::InModule for ApprovalRule {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ApprovalRule`.
///
/// Provides typed access to columns for query building.
pub struct ApprovalRuleCols {
    pub id: __sdk::__query_builder::Col<ApprovalRule, u64>,
    pub organization_id: __sdk::__query_builder::Col<ApprovalRule, u64>,
    pub company_id: __sdk::__query_builder::Col<ApprovalRule, Option<u64>>,
    pub name: __sdk::__query_builder::Col<ApprovalRule, String>,
    pub description: __sdk::__query_builder::Col<ApprovalRule, Option<String>>,
    pub model: __sdk::__query_builder::Col<ApprovalRule, String>,
    pub action: __sdk::__query_builder::Col<ApprovalRule, String>,
    pub rule_type: __sdk::__query_builder::Col<ApprovalRule, String>,
    pub threshold: __sdk::__query_builder::Col<ApprovalRule, f64>,
    pub approver_role_id: __sdk::__query_builder::Col<ApprovalRule, Option<u64>>,
    pub sequence: __sdk::__query_builder::Col<ApprovalRule, u32>,
    pub is_active: __sdk::__query_builder::Col<ApprovalRule, bool>,
    pub create_uid: __sdk::__query_builder::Col<ApprovalRule, __sdk::Identity>,
    pub create_date: __sdk::__query_builder::Col<ApprovalRule, __sdk::Timestamp>,
    pub write_uid: __sdk::__query_builder::Col<ApprovalRule, __sdk::Identity>,
    pub write_date: __sdk::__query_builder::Col<ApprovalRule, __sdk::Timestamp>,
    pub metadata: __sdk::__query_builder::Col<ApprovalRule, Option<String>>,
}

impl __sdk::__query_builder::HasCols for ApprovalRule {
    type Cols = ApprovalRuleCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ApprovalRuleCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            company_id: __sdk::__query_builder::Col::new(table_name, "company_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
            model: __sdk::__query_builder::Col::new(table_name, "model"),
            action: __sdk::__query_builder::Col::new(table_name, "action"),
            rule_type: __sdk::__query_builder::Col::new(table_name, "rule_type"),
            threshold: __sdk::__query_builder::Col::new(table_name, "threshold"),
            approver_role_id: __sdk::__query_builder::Col::new(table_name, "approver_role_id"),
            sequence: __sdk::__query_builder::Col::new(table_name, "sequence"),
            is_active: __sdk::__query_builder::Col::new(table_name, "is_active"),
            create_uid: __sdk::__query_builder::Col::new(table_name, "create_uid"),
            create_date: __sdk::__query_builder::Col::new(table_name, "create_date"),
            write_uid: __sdk::__query_builder::Col::new(table_name, "write_uid"),
            write_date: __sdk::__query_builder::Col::new(table_name, "write_date"),
            metadata: __sdk::__query_builder::Col::new(table_name, "metadata"),
        }
    }
}

/// Indexed column accessor struct for the table `ApprovalRule`.
///
/// Provides typed access to indexed columns for query building.
pub struct ApprovalRuleIxCols {
    pub id: __sdk::__query_builder::IxCol<ApprovalRule, u64>,
    pub model: __sdk::__query_builder::IxCol<ApprovalRule, String>,
    pub organization_id: __sdk::__query_builder::IxCol<ApprovalRule, u64>,
}

impl __sdk::__query_builder::HasIxCols for ApprovalRule {
    type IxCols = ApprovalRuleIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ApprovalRuleIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            model: __sdk::__query_builder::IxCol::new(table_name, "model"),
            organization_id: __sdk::__query_builder::IxCol::new(table_name, "organization_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ApprovalRule {}
