// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ApproveProposalArgs {
    pub organization_id: u64,
    pub company_id: u64,
    pub proposal_id: u64,
}

impl From<ApproveProposalArgs> for super::Reducer {
    fn from(args: ApproveProposalArgs) -> Self {
        Self::ApproveProposal {
            organization_id: args.organization_id,
            company_id: args.company_id,
            proposal_id: args.proposal_id,
        }
    }
}

impl __sdk::InModule for ApproveProposalArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `approve_proposal`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait approve_proposal {
    /// Request that the remote module invoke the reducer `approve_proposal` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`approve_proposal:approve_proposal_then`] to run a callback after the reducer completes.
    fn approve_proposal(
        &self,
        organization_id: u64,
        company_id: u64,
        proposal_id: u64,
    ) -> __sdk::Result<()> {
        self.approve_proposal_then(organization_id, company_id, proposal_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `approve_proposal` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn approve_proposal_then(
        &self,
        organization_id: u64,
        company_id: u64,
        proposal_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl approve_proposal for super::RemoteReducers {
    fn approve_proposal_then(
        &self,
        organization_id: u64,
        company_id: u64,
        proposal_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ApproveProposalArgs {
                organization_id,
                company_id,
                proposal_id,
            },
            callback,
        )
    }
}
