// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ArchiveAiChatSessionArgs {
    pub organization_id: u64,
    pub company_id: u64,
    pub session_key: String,
    pub archived: bool,
}

impl From<ArchiveAiChatSessionArgs> for super::Reducer {
    fn from(args: ArchiveAiChatSessionArgs) -> Self {
        Self::ArchiveAiChatSession {
            organization_id: args.organization_id,
            company_id: args.company_id,
            session_key: args.session_key,
            archived: args.archived,
        }
    }
}

impl __sdk::InModule for ArchiveAiChatSessionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `archive_ai_chat_session`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait archive_ai_chat_session {
    /// Request that the remote module invoke the reducer `archive_ai_chat_session` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`archive_ai_chat_session:archive_ai_chat_session_then`] to run a callback after the reducer completes.
    fn archive_ai_chat_session(
        &self,
        organization_id: u64,
        company_id: u64,
        session_key: String,
        archived: bool,
    ) -> __sdk::Result<()> {
        self.archive_ai_chat_session_then(
            organization_id,
            company_id,
            session_key,
            archived,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `archive_ai_chat_session` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn archive_ai_chat_session_then(
        &self,
        organization_id: u64,
        company_id: u64,
        session_key: String,
        archived: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl archive_ai_chat_session for super::RemoteReducers {
    fn archive_ai_chat_session_then(
        &self,
        organization_id: u64,
        company_id: u64,
        session_key: String,
        archived: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ArchiveAiChatSessionArgs {
                organization_id,
                company_id,
                session_key,
                archived,
            },
            callback,
        )
    }
}
