// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::archive_employee_params_type::ArchiveEmployeeParams;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ArchiveEmployeeArgs {
    pub organization_id: u64,
    pub company_id: u64,
    pub employee_id: u64,
    pub params: ArchiveEmployeeParams,
}

impl From<ArchiveEmployeeArgs> for super::Reducer {
    fn from(args: ArchiveEmployeeArgs) -> Self {
        Self::ArchiveEmployee {
            organization_id: args.organization_id,
            company_id: args.company_id,
            employee_id: args.employee_id,
            params: args.params,
        }
    }
}

impl __sdk::InModule for ArchiveEmployeeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `archive_employee`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait archive_employee {
    /// Request that the remote module invoke the reducer `archive_employee` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`archive_employee:archive_employee_then`] to run a callback after the reducer completes.
    fn archive_employee(
        &self,
        organization_id: u64,
        company_id: u64,
        employee_id: u64,
        params: ArchiveEmployeeParams,
    ) -> __sdk::Result<()> {
        self.archive_employee_then(organization_id, company_id, employee_id, params, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `archive_employee` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn archive_employee_then(
        &self,
        organization_id: u64,
        company_id: u64,
        employee_id: u64,
        params: ArchiveEmployeeParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl archive_employee for super::RemoteReducers {
    fn archive_employee_then(
        &self,
        organization_id: u64,
        company_id: u64,
        employee_id: u64,
        params: ArchiveEmployeeParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ArchiveEmployeeArgs {
                organization_id,
                company_id,
                employee_id,
                params,
            },
            callback,
        )
    }
}
