// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AssignTeamMemberSkillParams {
    pub team_member_id: u64,
    pub skill_id: u64,
    pub is_default: bool,
    pub module_hint: Option<String>,
}

impl __sdk::InModule for AssignTeamMemberSkillParams {
    type Module = super::RemoteModule;
}
