// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BankMatchCandidate {
    pub id: u64,
    pub organization_id: u64,
    pub statement_line_id: u64,
    pub match_type: String,
    pub entity_id: u64,
    pub amount: f64,
    pub rule_id: Option<u64>,
    pub score: u32,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for BankMatchCandidate {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BankMatchCandidate`.
///
/// Provides typed access to columns for query building.
pub struct BankMatchCandidateCols {
    pub id: __sdk::__query_builder::Col<BankMatchCandidate, u64>,
    pub organization_id: __sdk::__query_builder::Col<BankMatchCandidate, u64>,
    pub statement_line_id: __sdk::__query_builder::Col<BankMatchCandidate, u64>,
    pub match_type: __sdk::__query_builder::Col<BankMatchCandidate, String>,
    pub entity_id: __sdk::__query_builder::Col<BankMatchCandidate, u64>,
    pub amount: __sdk::__query_builder::Col<BankMatchCandidate, f64>,
    pub rule_id: __sdk::__query_builder::Col<BankMatchCandidate, Option<u64>>,
    pub score: __sdk::__query_builder::Col<BankMatchCandidate, u32>,
    pub created_at: __sdk::__query_builder::Col<BankMatchCandidate, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for BankMatchCandidate {
    type Cols = BankMatchCandidateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BankMatchCandidateCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            statement_line_id: __sdk::__query_builder::Col::new(table_name, "statement_line_id"),
            match_type: __sdk::__query_builder::Col::new(table_name, "match_type"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            amount: __sdk::__query_builder::Col::new(table_name, "amount"),
            rule_id: __sdk::__query_builder::Col::new(table_name, "rule_id"),
            score: __sdk::__query_builder::Col::new(table_name, "score"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `BankMatchCandidate`.
///
/// Provides typed access to indexed columns for query building.
pub struct BankMatchCandidateIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<BankMatchCandidate, u64>,
    pub id: __sdk::__query_builder::IxCol<BankMatchCandidate, u64>,
    pub organization_id: __sdk::__query_builder::IxCol<BankMatchCandidate, u64>,
    pub statement_line_id: __sdk::__query_builder::IxCol<BankMatchCandidate, u64>,
}

impl __sdk::__query_builder::HasIxCols for BankMatchCandidate {
    type IxCols = BankMatchCandidateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BankMatchCandidateIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            organization_id: __sdk::__query_builder::IxCol::new(table_name, "organization_id"),
            statement_line_id: __sdk::__query_builder::IxCol::new(table_name, "statement_line_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BankMatchCandidate {}
