// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::billing_account_type::BillingAccount;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `billing_account`.
///
/// Obtain a handle from the [`BillingAccountTableAccess::billing_account`] method on [`super::RemoteTables`],
/// like `ctx.db.billing_account()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.billing_account().on_insert(...)`.
pub struct BillingAccountTableHandle<'ctx> {
    imp: __sdk::TableHandle<BillingAccount>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `billing_account`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BillingAccountTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BillingAccountTableHandle`], which mediates access to the table `billing_account`.
    fn billing_account(&self) -> BillingAccountTableHandle<'_>;
}

impl BillingAccountTableAccess for super::RemoteTables {
    fn billing_account(&self) -> BillingAccountTableHandle<'_> {
        BillingAccountTableHandle {
            imp: self.imp.get_table::<BillingAccount>("billing_account"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BillingAccountInsertCallbackId(__sdk::CallbackId);
pub struct BillingAccountDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BillingAccountTableHandle<'ctx> {
    type Row = BillingAccount;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BillingAccount> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BillingAccountInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BillingAccountInsertCallbackId {
        BillingAccountInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BillingAccountInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BillingAccountDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BillingAccountDeleteCallbackId {
        BillingAccountDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BillingAccountDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct BillingAccountUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BillingAccountTableHandle<'ctx> {
    type UpdateCallbackId = BillingAccountUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BillingAccountUpdateCallbackId {
        BillingAccountUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BillingAccountUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `billing_account`,
/// which allows point queries on the field of the same name
/// via the [`BillingAccountIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.billing_account().id().find(...)`.
pub struct BillingAccountIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<BillingAccount, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BillingAccountTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `billing_account`.
    pub fn id(&self) -> BillingAccountIdUnique<'ctx> {
        BillingAccountIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BillingAccountIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<BillingAccount> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BillingAccount>("billing_account");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BillingAccount>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BillingAccount>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BillingAccount`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait billing_accountQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BillingAccount`.
    fn billing_account(&self) -> __sdk::__query_builder::Table<BillingAccount>;
}

impl billing_accountQueryTableAccess for __sdk::QueryTableAccessor {
    fn billing_account(&self) -> __sdk::__query_builder::Table<BillingAccount> {
        __sdk::__query_builder::Table::new("billing_account")
    }
}
