// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BudgetPost {
    pub id: u64,
    pub organization_id: u64,
    pub name: String,
    pub code: Option<String>,
    pub description: Option<String>,
    pub account_ids: Vec<u64>,
    pub company_id: u64,
    pub is_active: bool,
    pub create_uid: Option<__sdk::Identity>,
    pub create_date: Option<__sdk::Timestamp>,
    pub write_uid: Option<__sdk::Identity>,
    pub write_date: Option<__sdk::Timestamp>,
    pub metadata: Option<String>,
}

impl __sdk::InModule for BudgetPost {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BudgetPost`.
///
/// Provides typed access to columns for query building.
pub struct BudgetPostCols {
    pub id: __sdk::__query_builder::Col<BudgetPost, u64>,
    pub organization_id: __sdk::__query_builder::Col<BudgetPost, u64>,
    pub name: __sdk::__query_builder::Col<BudgetPost, String>,
    pub code: __sdk::__query_builder::Col<BudgetPost, Option<String>>,
    pub description: __sdk::__query_builder::Col<BudgetPost, Option<String>>,
    pub account_ids: __sdk::__query_builder::Col<BudgetPost, Vec<u64>>,
    pub company_id: __sdk::__query_builder::Col<BudgetPost, u64>,
    pub is_active: __sdk::__query_builder::Col<BudgetPost, bool>,
    pub create_uid: __sdk::__query_builder::Col<BudgetPost, Option<__sdk::Identity>>,
    pub create_date: __sdk::__query_builder::Col<BudgetPost, Option<__sdk::Timestamp>>,
    pub write_uid: __sdk::__query_builder::Col<BudgetPost, Option<__sdk::Identity>>,
    pub write_date: __sdk::__query_builder::Col<BudgetPost, Option<__sdk::Timestamp>>,
    pub metadata: __sdk::__query_builder::Col<BudgetPost, Option<String>>,
}

impl __sdk::__query_builder::HasCols for BudgetPost {
    type Cols = BudgetPostCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BudgetPostCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            code: __sdk::__query_builder::Col::new(table_name, "code"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
            account_ids: __sdk::__query_builder::Col::new(table_name, "account_ids"),
            company_id: __sdk::__query_builder::Col::new(table_name, "company_id"),
            is_active: __sdk::__query_builder::Col::new(table_name, "is_active"),
            create_uid: __sdk::__query_builder::Col::new(table_name, "create_uid"),
            create_date: __sdk::__query_builder::Col::new(table_name, "create_date"),
            write_uid: __sdk::__query_builder::Col::new(table_name, "write_uid"),
            write_date: __sdk::__query_builder::Col::new(table_name, "write_date"),
            metadata: __sdk::__query_builder::Col::new(table_name, "metadata"),
        }
    }
}

/// Indexed column accessor struct for the table `BudgetPost`.
///
/// Provides typed access to indexed columns for query building.
pub struct BudgetPostIxCols {
    pub company_id: __sdk::__query_builder::IxCol<BudgetPost, u64>,
    pub id: __sdk::__query_builder::IxCol<BudgetPost, u64>,
    pub organization_id: __sdk::__query_builder::IxCol<BudgetPost, u64>,
}

impl __sdk::__query_builder::HasIxCols for BudgetPost {
    type IxCols = BudgetPostIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BudgetPostIxCols {
            company_id: __sdk::__query_builder::IxCol::new(table_name, "company_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            organization_id: __sdk::__query_builder::IxCol::new(table_name, "organization_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BudgetPost {}
