// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CheckMoAvailabilityArgs {
    pub organization_id: u64,
    pub company_id: u64,
    pub mo_id: u64,
}

impl From<CheckMoAvailabilityArgs> for super::Reducer {
    fn from(args: CheckMoAvailabilityArgs) -> Self {
        Self::CheckMoAvailability {
            organization_id: args.organization_id,
            company_id: args.company_id,
            mo_id: args.mo_id,
        }
    }
}

impl __sdk::InModule for CheckMoAvailabilityArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `check_mo_availability`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait check_mo_availability {
    /// Request that the remote module invoke the reducer `check_mo_availability` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`check_mo_availability:check_mo_availability_then`] to run a callback after the reducer completes.
    fn check_mo_availability(
        &self,
        organization_id: u64,
        company_id: u64,
        mo_id: u64,
    ) -> __sdk::Result<()> {
        self.check_mo_availability_then(organization_id, company_id, mo_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `check_mo_availability` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn check_mo_availability_then(
        &self,
        organization_id: u64,
        company_id: u64,
        mo_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl check_mo_availability for super::RemoteReducers {
    fn check_mo_availability_then(
        &self,
        organization_id: u64,
        company_id: u64,
        mo_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CheckMoAvailabilityArgs {
                organization_id,
                company_id,
                mo_id,
            },
            callback,
        )
    }
}
