// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClaimAiSkillCertificationArgs {
    pub organization_id: u64,
    pub request_id: u64,
}

impl From<ClaimAiSkillCertificationArgs> for super::Reducer {
    fn from(args: ClaimAiSkillCertificationArgs) -> Self {
        Self::ClaimAiSkillCertification {
            organization_id: args.organization_id,
            request_id: args.request_id,
        }
    }
}

impl __sdk::InModule for ClaimAiSkillCertificationArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `claim_ai_skill_certification`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait claim_ai_skill_certification {
    /// Request that the remote module invoke the reducer `claim_ai_skill_certification` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`claim_ai_skill_certification:claim_ai_skill_certification_then`] to run a callback after the reducer completes.
    fn claim_ai_skill_certification(
        &self,
        organization_id: u64,
        request_id: u64,
    ) -> __sdk::Result<()> {
        self.claim_ai_skill_certification_then(organization_id, request_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `claim_ai_skill_certification` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn claim_ai_skill_certification_then(
        &self,
        organization_id: u64,
        request_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl claim_ai_skill_certification for super::RemoteReducers {
    fn claim_ai_skill_certification_then(
        &self,
        organization_id: u64,
        request_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ClaimAiSkillCertificationArgs {
                organization_id,
                request_id,
            },
            callback,
        )
    }
}
