// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::claim_queue_job_params_type::ClaimQueueJobParams;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClaimQueueJobArgs {
    pub organization_id: u64,
    pub job_id: u64,
    pub params: ClaimQueueJobParams,
}

impl From<ClaimQueueJobArgs> for super::Reducer {
    fn from(args: ClaimQueueJobArgs) -> Self {
        Self::ClaimQueueJob {
            organization_id: args.organization_id,
            job_id: args.job_id,
            params: args.params,
        }
    }
}

impl __sdk::InModule for ClaimQueueJobArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `claim_queue_job`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait claim_queue_job {
    /// Request that the remote module invoke the reducer `claim_queue_job` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`claim_queue_job:claim_queue_job_then`] to run a callback after the reducer completes.
    fn claim_queue_job(
        &self,
        organization_id: u64,
        job_id: u64,
        params: ClaimQueueJobParams,
    ) -> __sdk::Result<()> {
        self.claim_queue_job_then(organization_id, job_id, params, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `claim_queue_job` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn claim_queue_job_then(
        &self,
        organization_id: u64,
        job_id: u64,
        params: ClaimQueueJobParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl claim_queue_job for super::RemoteReducers {
    fn claim_queue_job_then(
        &self,
        organization_id: u64,
        job_id: u64,
        params: ClaimQueueJobParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ClaimQueueJobArgs {
                organization_id,
                job_id,
                params,
            },
            callback,
        )
    }
}
