// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Company {
    pub id: u64,
    pub external_id: String,
    pub organization_id: u64,
    pub name: String,
    pub code: String,
    pub is_parent: bool,
    pub parent_id: Option<u64>,
    pub currency_id: u64,
    pub fiscal_year_end_month: u8,
    pub fiscal_year_end_day: u8,
    pub tax_id: Option<String>,
    pub company_registry: Option<String>,
    pub address_street: Option<String>,
    pub address_city: Option<String>,
    pub address_zip: Option<String>,
    pub address_country_code: Option<String>,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
    pub deleted_at: Option<__sdk::Timestamp>,
    pub metadata: Option<String>,
}

impl __sdk::InModule for Company {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Company`.
///
/// Provides typed access to columns for query building.
pub struct CompanyCols {
    pub id: __sdk::__query_builder::Col<Company, u64>,
    pub external_id: __sdk::__query_builder::Col<Company, String>,
    pub organization_id: __sdk::__query_builder::Col<Company, u64>,
    pub name: __sdk::__query_builder::Col<Company, String>,
    pub code: __sdk::__query_builder::Col<Company, String>,
    pub is_parent: __sdk::__query_builder::Col<Company, bool>,
    pub parent_id: __sdk::__query_builder::Col<Company, Option<u64>>,
    pub currency_id: __sdk::__query_builder::Col<Company, u64>,
    pub fiscal_year_end_month: __sdk::__query_builder::Col<Company, u8>,
    pub fiscal_year_end_day: __sdk::__query_builder::Col<Company, u8>,
    pub tax_id: __sdk::__query_builder::Col<Company, Option<String>>,
    pub company_registry: __sdk::__query_builder::Col<Company, Option<String>>,
    pub address_street: __sdk::__query_builder::Col<Company, Option<String>>,
    pub address_city: __sdk::__query_builder::Col<Company, Option<String>>,
    pub address_zip: __sdk::__query_builder::Col<Company, Option<String>>,
    pub address_country_code: __sdk::__query_builder::Col<Company, Option<String>>,
    pub created_at: __sdk::__query_builder::Col<Company, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<Company, __sdk::Timestamp>,
    pub deleted_at: __sdk::__query_builder::Col<Company, Option<__sdk::Timestamp>>,
    pub metadata: __sdk::__query_builder::Col<Company, Option<String>>,
}

impl __sdk::__query_builder::HasCols for Company {
    type Cols = CompanyCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CompanyCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            external_id: __sdk::__query_builder::Col::new(table_name, "external_id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            code: __sdk::__query_builder::Col::new(table_name, "code"),
            is_parent: __sdk::__query_builder::Col::new(table_name, "is_parent"),
            parent_id: __sdk::__query_builder::Col::new(table_name, "parent_id"),
            currency_id: __sdk::__query_builder::Col::new(table_name, "currency_id"),
            fiscal_year_end_month: __sdk::__query_builder::Col::new(
                table_name,
                "fiscal_year_end_month",
            ),
            fiscal_year_end_day: __sdk::__query_builder::Col::new(
                table_name,
                "fiscal_year_end_day",
            ),
            tax_id: __sdk::__query_builder::Col::new(table_name, "tax_id"),
            company_registry: __sdk::__query_builder::Col::new(table_name, "company_registry"),
            address_street: __sdk::__query_builder::Col::new(table_name, "address_street"),
            address_city: __sdk::__query_builder::Col::new(table_name, "address_city"),
            address_zip: __sdk::__query_builder::Col::new(table_name, "address_zip"),
            address_country_code: __sdk::__query_builder::Col::new(
                table_name,
                "address_country_code",
            ),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
            deleted_at: __sdk::__query_builder::Col::new(table_name, "deleted_at"),
            metadata: __sdk::__query_builder::Col::new(table_name, "metadata"),
        }
    }
}

/// Indexed column accessor struct for the table `Company`.
///
/// Provides typed access to indexed columns for query building.
pub struct CompanyIxCols {
    pub id: __sdk::__query_builder::IxCol<Company, u64>,
    pub organization_id: __sdk::__query_builder::IxCol<Company, u64>,
}

impl __sdk::__query_builder::HasIxCols for Company {
    type IxCols = CompanyIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CompanyIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            organization_id: __sdk::__query_builder::IxCol::new(table_name, "organization_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Company {}
