// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::company_type::Company;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `company`.
///
/// Obtain a handle from the [`CompanyTableAccess::company`] method on [`super::RemoteTables`],
/// like `ctx.db.company()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.company().on_insert(...)`.
pub struct CompanyTableHandle<'ctx> {
    imp: __sdk::TableHandle<Company>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `company`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CompanyTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CompanyTableHandle`], which mediates access to the table `company`.
    fn company(&self) -> CompanyTableHandle<'_>;
}

impl CompanyTableAccess for super::RemoteTables {
    fn company(&self) -> CompanyTableHandle<'_> {
        CompanyTableHandle {
            imp: self.imp.get_table::<Company>("company"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CompanyInsertCallbackId(__sdk::CallbackId);
pub struct CompanyDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CompanyTableHandle<'ctx> {
    type Row = Company;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Company> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CompanyInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CompanyInsertCallbackId {
        CompanyInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CompanyInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CompanyDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CompanyDeleteCallbackId {
        CompanyDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CompanyDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CompanyUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CompanyTableHandle<'ctx> {
    type UpdateCallbackId = CompanyUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CompanyUpdateCallbackId {
        CompanyUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CompanyUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `company`,
/// which allows point queries on the field of the same name
/// via the [`CompanyIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.company().id().find(...)`.
pub struct CompanyIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Company, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CompanyTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `company`.
    pub fn id(&self) -> CompanyIdUnique<'ctx> {
        CompanyIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CompanyIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Company> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Company>("company");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Company>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Company>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Company`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait companyQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Company`.
    fn company(&self) -> __sdk::__query_builder::Table<Company>;
}

impl companyQueryTableAccess for __sdk::QueryTableAccessor {
    fn company(&self) -> __sdk::__query_builder::Table<Company> {
        __sdk::__query_builder::Table::new("company")
    }
}
