// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ConfirmPayslipParams {
    pub company_id: Option<u64>,
    pub gross_wage: f64,
    pub net_wage: f64,
    pub calculation_source: String,
}

impl __sdk::InModule for ConfirmPayslipParams {
    type Module = super::RemoteModule;
}
