// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::consolidation_company_rate_type::ConsolidationCompanyRate;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `consolidation_company_rate`.
///
/// Obtain a handle from the [`ConsolidationCompanyRateTableAccess::consolidation_company_rate`] method on [`super::RemoteTables`],
/// like `ctx.db.consolidation_company_rate()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.consolidation_company_rate().on_insert(...)`.
pub struct ConsolidationCompanyRateTableHandle<'ctx> {
    imp: __sdk::TableHandle<ConsolidationCompanyRate>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `consolidation_company_rate`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ConsolidationCompanyRateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ConsolidationCompanyRateTableHandle`], which mediates access to the table `consolidation_company_rate`.
    fn consolidation_company_rate(&self) -> ConsolidationCompanyRateTableHandle<'_>;
}

impl ConsolidationCompanyRateTableAccess for super::RemoteTables {
    fn consolidation_company_rate(&self) -> ConsolidationCompanyRateTableHandle<'_> {
        ConsolidationCompanyRateTableHandle {
            imp: self
                .imp
                .get_table::<ConsolidationCompanyRate>("consolidation_company_rate"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ConsolidationCompanyRateInsertCallbackId(__sdk::CallbackId);
pub struct ConsolidationCompanyRateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ConsolidationCompanyRateTableHandle<'ctx> {
    type Row = ConsolidationCompanyRate;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ConsolidationCompanyRate> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ConsolidationCompanyRateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ConsolidationCompanyRateInsertCallbackId {
        ConsolidationCompanyRateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ConsolidationCompanyRateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ConsolidationCompanyRateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ConsolidationCompanyRateDeleteCallbackId {
        ConsolidationCompanyRateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ConsolidationCompanyRateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ConsolidationCompanyRateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ConsolidationCompanyRateTableHandle<'ctx> {
    type UpdateCallbackId = ConsolidationCompanyRateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ConsolidationCompanyRateUpdateCallbackId {
        ConsolidationCompanyRateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ConsolidationCompanyRateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `consolidation_company_rate`,
/// which allows point queries on the field of the same name
/// via the [`ConsolidationCompanyRateIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.consolidation_company_rate().id().find(...)`.
pub struct ConsolidationCompanyRateIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ConsolidationCompanyRate, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ConsolidationCompanyRateTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `consolidation_company_rate`.
    pub fn id(&self) -> ConsolidationCompanyRateIdUnique<'ctx> {
        ConsolidationCompanyRateIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ConsolidationCompanyRateIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ConsolidationCompanyRate> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<ConsolidationCompanyRate>("consolidation_company_rate");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ConsolidationCompanyRate>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ConsolidationCompanyRate>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ConsolidationCompanyRate`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait consolidation_company_rateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ConsolidationCompanyRate`.
    fn consolidation_company_rate(&self)
        -> __sdk::__query_builder::Table<ConsolidationCompanyRate>;
}

impl consolidation_company_rateQueryTableAccess for __sdk::QueryTableAccessor {
    fn consolidation_company_rate(
        &self,
    ) -> __sdk::__query_builder::Table<ConsolidationCompanyRate> {
        __sdk::__query_builder::Table::new("consolidation_company_rate")
    }
}
