// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::segment_rule_field_type::SegmentRuleField;
use super::segment_rule_op_type::SegmentRuleOp;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ContactSegmentRule {
    pub id: u64,
    pub organization_id: u64,
    pub segment_id: u64,
    pub sequence: i32,
    pub field: SegmentRuleField,
    pub op: SegmentRuleOp,
    pub value_text: Option<String>,
    pub value_id: Option<u64>,
    pub created_at: __sdk::Timestamp,
    pub metadata: Option<String>,
}

impl __sdk::InModule for ContactSegmentRule {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ContactSegmentRule`.
///
/// Provides typed access to columns for query building.
pub struct ContactSegmentRuleCols {
    pub id: __sdk::__query_builder::Col<ContactSegmentRule, u64>,
    pub organization_id: __sdk::__query_builder::Col<ContactSegmentRule, u64>,
    pub segment_id: __sdk::__query_builder::Col<ContactSegmentRule, u64>,
    pub sequence: __sdk::__query_builder::Col<ContactSegmentRule, i32>,
    pub field: __sdk::__query_builder::Col<ContactSegmentRule, SegmentRuleField>,
    pub op: __sdk::__query_builder::Col<ContactSegmentRule, SegmentRuleOp>,
    pub value_text: __sdk::__query_builder::Col<ContactSegmentRule, Option<String>>,
    pub value_id: __sdk::__query_builder::Col<ContactSegmentRule, Option<u64>>,
    pub created_at: __sdk::__query_builder::Col<ContactSegmentRule, __sdk::Timestamp>,
    pub metadata: __sdk::__query_builder::Col<ContactSegmentRule, Option<String>>,
}

impl __sdk::__query_builder::HasCols for ContactSegmentRule {
    type Cols = ContactSegmentRuleCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ContactSegmentRuleCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            segment_id: __sdk::__query_builder::Col::new(table_name, "segment_id"),
            sequence: __sdk::__query_builder::Col::new(table_name, "sequence"),
            field: __sdk::__query_builder::Col::new(table_name, "field"),
            op: __sdk::__query_builder::Col::new(table_name, "op"),
            value_text: __sdk::__query_builder::Col::new(table_name, "value_text"),
            value_id: __sdk::__query_builder::Col::new(table_name, "value_id"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            metadata: __sdk::__query_builder::Col::new(table_name, "metadata"),
        }
    }
}

/// Indexed column accessor struct for the table `ContactSegmentRule`.
///
/// Provides typed access to indexed columns for query building.
pub struct ContactSegmentRuleIxCols {
    pub id: __sdk::__query_builder::IxCol<ContactSegmentRule, u64>,
    pub organization_id: __sdk::__query_builder::IxCol<ContactSegmentRule, u64>,
    pub segment_id: __sdk::__query_builder::IxCol<ContactSegmentRule, u64>,
}

impl __sdk::__query_builder::HasIxCols for ContactSegmentRule {
    type IxCols = ContactSegmentRuleIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ContactSegmentRuleIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            organization_id: __sdk::__query_builder::IxCol::new(table_name, "organization_id"),
            segment_id: __sdk::__query_builder::IxCol::new(table_name, "segment_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ContactSegmentRule {}
