// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ContactIdentityVerificationAuthority {
    pub id: u8,
    pub issuer_identity: __sdk::Identity,
    pub configured_by: __sdk::Identity,
    pub configured_at: __sdk::Timestamp,
}

impl __sdk::InModule for ContactIdentityVerificationAuthority {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ContactIdentityVerificationAuthority`.
///
/// Provides typed access to columns for query building.
pub struct ContactIdentityVerificationAuthorityCols {
    pub id: __sdk::__query_builder::Col<ContactIdentityVerificationAuthority, u8>,
    pub issuer_identity:
        __sdk::__query_builder::Col<ContactIdentityVerificationAuthority, __sdk::Identity>,
    pub configured_by:
        __sdk::__query_builder::Col<ContactIdentityVerificationAuthority, __sdk::Identity>,
    pub configured_at:
        __sdk::__query_builder::Col<ContactIdentityVerificationAuthority, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for ContactIdentityVerificationAuthority {
    type Cols = ContactIdentityVerificationAuthorityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ContactIdentityVerificationAuthorityCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            issuer_identity: __sdk::__query_builder::Col::new(table_name, "issuer_identity"),
            configured_by: __sdk::__query_builder::Col::new(table_name, "configured_by"),
            configured_at: __sdk::__query_builder::Col::new(table_name, "configured_at"),
        }
    }
}

/// Indexed column accessor struct for the table `ContactIdentityVerificationAuthority`.
///
/// Provides typed access to indexed columns for query building.
pub struct ContactIdentityVerificationAuthorityIxCols {
    pub id: __sdk::__query_builder::IxCol<ContactIdentityVerificationAuthority, u8>,
}

impl __sdk::__query_builder::HasIxCols for ContactIdentityVerificationAuthority {
    type IxCols = ContactIdentityVerificationAuthorityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ContactIdentityVerificationAuthorityIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ContactIdentityVerificationAuthority {}
