// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::contact_type::Contact;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `contact`.
///
/// Obtain a handle from the [`ContactTableAccess::contact`] method on [`super::RemoteTables`],
/// like `ctx.db.contact()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.contact().on_insert(...)`.
pub struct ContactTableHandle<'ctx> {
    imp: __sdk::TableHandle<Contact>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `contact`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ContactTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ContactTableHandle`], which mediates access to the table `contact`.
    fn contact(&self) -> ContactTableHandle<'_>;
}

impl ContactTableAccess for super::RemoteTables {
    fn contact(&self) -> ContactTableHandle<'_> {
        ContactTableHandle {
            imp: self.imp.get_table::<Contact>("contact"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ContactInsertCallbackId(__sdk::CallbackId);
pub struct ContactDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ContactTableHandle<'ctx> {
    type Row = Contact;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Contact> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ContactInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ContactInsertCallbackId {
        ContactInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ContactInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ContactDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ContactDeleteCallbackId {
        ContactDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ContactDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ContactUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ContactTableHandle<'ctx> {
    type UpdateCallbackId = ContactUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ContactUpdateCallbackId {
        ContactUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ContactUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `contact`,
/// which allows point queries on the field of the same name
/// via the [`ContactIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.contact().id().find(...)`.
pub struct ContactIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Contact, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ContactTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `contact`.
    pub fn id(&self) -> ContactIdUnique<'ctx> {
        ContactIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ContactIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Contact> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Contact>("contact");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Contact>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Contact>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Contact`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait contactQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Contact`.
    fn contact(&self) -> __sdk::__query_builder::Table<Contact>;
}

impl contactQueryTableAccess for __sdk::QueryTableAccessor {
    fn contact(&self) -> __sdk::__query_builder::Table<Contact> {
        __sdk::__query_builder::Table::new("contact")
    }
}
