// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::contact_communication_preference_type::ContactCommunicationPreference;
use super::message_channel_type::MessageChannel;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `contact_communication_preference`.
///
/// Obtain a handle from the [`ContactCommunicationPreferenceTableAccess::contact_communication_preference`] method on [`super::RemoteTables`],
/// like `ctx.db.contact_communication_preference()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.contact_communication_preference().on_insert(...)`.
pub struct ContactCommunicationPreferenceTableHandle<'ctx> {
    imp: __sdk::TableHandle<ContactCommunicationPreference>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `contact_communication_preference`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ContactCommunicationPreferenceTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ContactCommunicationPreferenceTableHandle`], which mediates access to the table `contact_communication_preference`.
    fn contact_communication_preference(&self) -> ContactCommunicationPreferenceTableHandle<'_>;
}

impl ContactCommunicationPreferenceTableAccess for super::RemoteTables {
    fn contact_communication_preference(&self) -> ContactCommunicationPreferenceTableHandle<'_> {
        ContactCommunicationPreferenceTableHandle {
            imp: self
                .imp
                .get_table::<ContactCommunicationPreference>("contact_communication_preference"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ContactCommunicationPreferenceInsertCallbackId(__sdk::CallbackId);
pub struct ContactCommunicationPreferenceDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ContactCommunicationPreferenceTableHandle<'ctx> {
    type Row = ContactCommunicationPreference;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ContactCommunicationPreference> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ContactCommunicationPreferenceInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ContactCommunicationPreferenceInsertCallbackId {
        ContactCommunicationPreferenceInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ContactCommunicationPreferenceInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ContactCommunicationPreferenceDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ContactCommunicationPreferenceDeleteCallbackId {
        ContactCommunicationPreferenceDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ContactCommunicationPreferenceDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ContactCommunicationPreferenceUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ContactCommunicationPreferenceTableHandle<'ctx> {
    type UpdateCallbackId = ContactCommunicationPreferenceUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ContactCommunicationPreferenceUpdateCallbackId {
        ContactCommunicationPreferenceUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ContactCommunicationPreferenceUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `contact_communication_preference`,
/// which allows point queries on the field of the same name
/// via the [`ContactCommunicationPreferenceIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.contact_communication_preference().id().find(...)`.
pub struct ContactCommunicationPreferenceIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ContactCommunicationPreference, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ContactCommunicationPreferenceTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `contact_communication_preference`.
    pub fn id(&self) -> ContactCommunicationPreferenceIdUnique<'ctx> {
        ContactCommunicationPreferenceIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ContactCommunicationPreferenceIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ContactCommunicationPreference> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<ContactCommunicationPreference>("contact_communication_preference");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ContactCommunicationPreference>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<ContactCommunicationPreference>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ContactCommunicationPreference`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait contact_communication_preferenceQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ContactCommunicationPreference`.
    fn contact_communication_preference(
        &self,
    ) -> __sdk::__query_builder::Table<ContactCommunicationPreference>;
}

impl contact_communication_preferenceQueryTableAccess for __sdk::QueryTableAccessor {
    fn contact_communication_preference(
        &self,
    ) -> __sdk::__query_builder::Table<ContactCommunicationPreference> {
        __sdk::__query_builder::Table::new("contact_communication_preference")
    }
}
