// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ContactSegment {
    pub id: u64,
    pub organization_id: u64,
    pub name: String,
    pub description: Option<String>,
    pub domain: Option<String>,
    pub is_dynamic: bool,
    pub member_count: i32,
    pub color: Option<String>,
    pub parent_id: Option<u64>,
    pub is_active: bool,
    pub created_by: __sdk::Identity,
    pub created_at: __sdk::Timestamp,
    pub metadata: Option<String>,
}

impl __sdk::InModule for ContactSegment {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ContactSegment`.
///
/// Provides typed access to columns for query building.
pub struct ContactSegmentCols {
    pub id: __sdk::__query_builder::Col<ContactSegment, u64>,
    pub organization_id: __sdk::__query_builder::Col<ContactSegment, u64>,
    pub name: __sdk::__query_builder::Col<ContactSegment, String>,
    pub description: __sdk::__query_builder::Col<ContactSegment, Option<String>>,
    pub domain: __sdk::__query_builder::Col<ContactSegment, Option<String>>,
    pub is_dynamic: __sdk::__query_builder::Col<ContactSegment, bool>,
    pub member_count: __sdk::__query_builder::Col<ContactSegment, i32>,
    pub color: __sdk::__query_builder::Col<ContactSegment, Option<String>>,
    pub parent_id: __sdk::__query_builder::Col<ContactSegment, Option<u64>>,
    pub is_active: __sdk::__query_builder::Col<ContactSegment, bool>,
    pub created_by: __sdk::__query_builder::Col<ContactSegment, __sdk::Identity>,
    pub created_at: __sdk::__query_builder::Col<ContactSegment, __sdk::Timestamp>,
    pub metadata: __sdk::__query_builder::Col<ContactSegment, Option<String>>,
}

impl __sdk::__query_builder::HasCols for ContactSegment {
    type Cols = ContactSegmentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ContactSegmentCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
            domain: __sdk::__query_builder::Col::new(table_name, "domain"),
            is_dynamic: __sdk::__query_builder::Col::new(table_name, "is_dynamic"),
            member_count: __sdk::__query_builder::Col::new(table_name, "member_count"),
            color: __sdk::__query_builder::Col::new(table_name, "color"),
            parent_id: __sdk::__query_builder::Col::new(table_name, "parent_id"),
            is_active: __sdk::__query_builder::Col::new(table_name, "is_active"),
            created_by: __sdk::__query_builder::Col::new(table_name, "created_by"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            metadata: __sdk::__query_builder::Col::new(table_name, "metadata"),
        }
    }
}

/// Indexed column accessor struct for the table `ContactSegment`.
///
/// Provides typed access to indexed columns for query building.
pub struct ContactSegmentIxCols {
    pub id: __sdk::__query_builder::IxCol<ContactSegment, u64>,
    pub organization_id: __sdk::__query_builder::IxCol<ContactSegment, u64>,
}

impl __sdk::__query_builder::HasIxCols for ContactSegment {
    type IxCols = ContactSegmentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ContactSegmentIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            organization_id: __sdk::__query_builder::IxCol::new(table_name, "organization_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ContactSegment {}
