// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CreateLossCategoryParams {
    pub company_id: Option<u64>,
    pub name: String,
    pub category: String,
    pub sequence: u32,
    pub metadata: Option<String>,
}

impl __sdk::InModule for CreateLossCategoryParams {
    type Module = super::RemoteModule;
}
