// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CreateAiSkillCertificationEnvironmentParams {
    pub fixture_id: u64,
    pub environment_key: String,
    pub dataset_json: String,
    pub virtual_files_json: String,
    pub metadata: Option<String>,
}

impl __sdk::InModule for CreateAiSkillCertificationEnvironmentParams {
    type Module = super::RemoteModule;
}
