// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CreateAiSkillFixtureParams {
    pub skill_id: u64,
    pub fixture_key: String,
    pub name: String,
    pub description: Option<String>,
    pub input_json: String,
    pub expected_output_json: String,
    pub metadata: Option<String>,
}

impl __sdk::InModule for CreateAiSkillFixtureParams {
    type Module = super::RemoteModule;
}
