// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CreateAiSkillParams {
    pub skill_key: String,
    pub name: String,
    pub description: Option<String>,
    pub category: String,
    pub prompt_template: String,
    pub required_tools: Vec<String>,
    pub optional_tools: Vec<String>,
    pub default_max_steps: u32,
    pub default_max_tool_calls: u32,
    pub output_schema: Option<String>,
    pub config_schema: Option<String>,
    pub dataset_specs: Option<String>,
    pub allowed_action_drafts: Vec<String>,
    pub is_active: bool,
    pub is_system: bool,
    pub metadata: Option<String>,
}

impl __sdk::InModule for CreateAiSkillParams {
    type Module = super::RemoteModule;
}
