// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::create_payment_term_params_type::CreatePaymentTermParams;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreatePaymentTermArgs {
    pub organization_id: u64,
    pub params: CreatePaymentTermParams,
}

impl From<CreatePaymentTermArgs> for super::Reducer {
    fn from(args: CreatePaymentTermArgs) -> Self {
        Self::CreatePaymentTerm {
            organization_id: args.organization_id,
            params: args.params,
        }
    }
}

impl __sdk::InModule for CreatePaymentTermArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_payment_term`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_payment_term {
    /// Request that the remote module invoke the reducer `create_payment_term` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_payment_term:create_payment_term_then`] to run a callback after the reducer completes.
    fn create_payment_term(
        &self,
        organization_id: u64,
        params: CreatePaymentTermParams,
    ) -> __sdk::Result<()> {
        self.create_payment_term_then(organization_id, params, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_payment_term` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_payment_term_then(
        &self,
        organization_id: u64,
        params: CreatePaymentTermParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_payment_term for super::RemoteReducers {
    fn create_payment_term_then(
        &self,
        organization_id: u64,
        params: CreatePaymentTermParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreatePaymentTermArgs {
                organization_id,
                params,
            },
            callback,
        )
    }
}
