// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CreateFormConfigParams {
    pub module_id: String,
    pub form_id: String,
    pub name: String,
    pub description: Option<String>,
    pub is_system_default: bool,
}

impl __sdk::InModule for CreateFormConfigParams {
    type Module = super::RemoteModule;
}
