// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CreateSalaryRuleParams {
    pub name: String,
    pub code: String,
    pub structure_id: u64,
    pub category: String,
    pub condition_type: String,
    pub amount_type: String,
    pub amount_fix: f64,
    pub amount_percentage: f64,
    pub sequence: u32,
    pub is_active: bool,
}

impl __sdk::InModule for CreateSalaryRuleParams {
    type Module = super::RemoteModule;
}
