// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CreateUomParams {
    pub category_id: u64,
    pub name: String,
    pub symbol: String,
    pub factor: f64,
    pub rounding: f64,
    pub times_bigger: f64,
    pub is_reference_unit: bool,
    pub is_active: bool,
    pub metadata: Option<String>,
}

impl __sdk::InModule for CreateUomParams {
    type Module = super::RemoteModule;
}
