// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CreateAiActionDraftParams {
    pub reducer_name: String,
    pub params_json: String,
    pub summary: String,
    pub confidence: f64,
    pub elevated: bool,
    pub warnings_json: Option<String>,
    pub source_query: Option<String>,
    pub ui_context_json: Option<String>,
    pub expires_at: Option<__sdk::Timestamp>,
    pub metadata: Option<String>,
}

impl __sdk::InModule for CreateAiActionDraftParams {
    type Module = super::RemoteModule;
}
