// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::create_subscription_tax_settle_intent_params_type::CreateSubscriptionTaxSettleIntentParams;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateSubscriptionTaxSettleIntentArgs {
    pub organization_id: u64,
    pub company_id: u64,
    pub subscription_id: u64,
    pub params: CreateSubscriptionTaxSettleIntentParams,
}

impl From<CreateSubscriptionTaxSettleIntentArgs> for super::Reducer {
    fn from(args: CreateSubscriptionTaxSettleIntentArgs) -> Self {
        Self::CreateSubscriptionTaxSettleIntent {
            organization_id: args.organization_id,
            company_id: args.company_id,
            subscription_id: args.subscription_id,
            params: args.params,
        }
    }
}

impl __sdk::InModule for CreateSubscriptionTaxSettleIntentArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_subscription_tax_settle_intent`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_subscription_tax_settle_intent {
    /// Request that the remote module invoke the reducer `create_subscription_tax_settle_intent` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_subscription_tax_settle_intent:create_subscription_tax_settle_intent_then`] to run a callback after the reducer completes.
    fn create_subscription_tax_settle_intent(
        &self,
        organization_id: u64,
        company_id: u64,
        subscription_id: u64,
        params: CreateSubscriptionTaxSettleIntentParams,
    ) -> __sdk::Result<()> {
        self.create_subscription_tax_settle_intent_then(
            organization_id,
            company_id,
            subscription_id,
            params,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `create_subscription_tax_settle_intent` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_subscription_tax_settle_intent_then(
        &self,
        organization_id: u64,
        company_id: u64,
        subscription_id: u64,
        params: CreateSubscriptionTaxSettleIntentParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_subscription_tax_settle_intent for super::RemoteReducers {
    fn create_subscription_tax_settle_intent_then(
        &self,
        organization_id: u64,
        company_id: u64,
        subscription_id: u64,
        params: CreateSubscriptionTaxSettleIntentParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateSubscriptionTaxSettleIntentArgs {
                organization_id,
                company_id,
                subscription_id,
                params,
            },
            callback,
        )
    }
}
