// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CreatePackagingMaterialParams {
    pub name: String,
    pub material_type: String,
    pub weight: f64,
    pub max_weight: f64,
    pub length: f64,
    pub width: f64,
    pub height: f64,
    pub volume: f64,
    pub cost: f64,
    pub currency_id: u64,
    pub barcode: Option<String>,
    pub is_active: bool,
    pub metadata: Option<String>,
}

impl __sdk::InModule for CreatePackagingMaterialParams {
    type Module = super::RemoteModule;
}
