// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::ticket_priority_type::TicketPriority;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CreateTicketParams {
    pub team_id: u64,
    pub stage_id: u64,
    pub name: String,
    pub description: Option<String>,
    pub priority: TicketPriority,
    pub partner_id: Option<u64>,
    pub partner_name: Option<String>,
    pub partner_email: Option<String>,
    pub sla_id: Option<u64>,
    pub sla_deadline: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for CreateTicketParams {
    type Module = super::RemoteModule;
}
