// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::create_hr_labor_cost_snapshot_params_type::CreateHrLaborCostSnapshotParams;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateHrLaborCostSnapshotArgs {
    pub organization_id: u64,
    pub company_id: u64,
    pub params: CreateHrLaborCostSnapshotParams,
}

impl From<CreateHrLaborCostSnapshotArgs> for super::Reducer {
    fn from(args: CreateHrLaborCostSnapshotArgs) -> Self {
        Self::CreateHrLaborCostSnapshot {
            organization_id: args.organization_id,
            company_id: args.company_id,
            params: args.params,
        }
    }
}

impl __sdk::InModule for CreateHrLaborCostSnapshotArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_hr_labor_cost_snapshot`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_hr_labor_cost_snapshot {
    /// Request that the remote module invoke the reducer `create_hr_labor_cost_snapshot` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_hr_labor_cost_snapshot:create_hr_labor_cost_snapshot_then`] to run a callback after the reducer completes.
    fn create_hr_labor_cost_snapshot(
        &self,
        organization_id: u64,
        company_id: u64,
        params: CreateHrLaborCostSnapshotParams,
    ) -> __sdk::Result<()> {
        self.create_hr_labor_cost_snapshot_then(organization_id, company_id, params, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_hr_labor_cost_snapshot` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_hr_labor_cost_snapshot_then(
        &self,
        organization_id: u64,
        company_id: u64,
        params: CreateHrLaborCostSnapshotParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_hr_labor_cost_snapshot for super::RemoteReducers {
    fn create_hr_labor_cost_snapshot_then(
        &self,
        organization_id: u64,
        company_id: u64,
        params: CreateHrLaborCostSnapshotParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateHrLaborCostSnapshotArgs {
                organization_id,
                company_id,
                params,
            },
            callback,
        )
    }
}
