// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::create_intercompany_transaction_params_type::CreateIntercompanyTransactionParams;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateIntercompanyTransactionArgs {
    pub organization_id: u64,
    pub origin_company_id: u64,
    pub params: CreateIntercompanyTransactionParams,
}

impl From<CreateIntercompanyTransactionArgs> for super::Reducer {
    fn from(args: CreateIntercompanyTransactionArgs) -> Self {
        Self::CreateIntercompanyTransaction {
            organization_id: args.organization_id,
            origin_company_id: args.origin_company_id,
            params: args.params,
        }
    }
}

impl __sdk::InModule for CreateIntercompanyTransactionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_intercompany_transaction`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_intercompany_transaction {
    /// Request that the remote module invoke the reducer `create_intercompany_transaction` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_intercompany_transaction:create_intercompany_transaction_then`] to run a callback after the reducer completes.
    fn create_intercompany_transaction(
        &self,
        organization_id: u64,
        origin_company_id: u64,
        params: CreateIntercompanyTransactionParams,
    ) -> __sdk::Result<()> {
        self.create_intercompany_transaction_then(
            organization_id,
            origin_company_id,
            params,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `create_intercompany_transaction` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_intercompany_transaction_then(
        &self,
        organization_id: u64,
        origin_company_id: u64,
        params: CreateIntercompanyTransactionParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_intercompany_transaction for super::RemoteReducers {
    fn create_intercompany_transaction_then(
        &self,
        organization_id: u64,
        origin_company_id: u64,
        params: CreateIntercompanyTransactionParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateIntercompanyTransactionArgs {
                organization_id,
                origin_company_id,
                params,
            },
            callback,
        )
    }
}
