// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CreateProductSupplierInfoParams {
    pub partner_id: u64,
    pub product_tmpl_id: Option<u64>,
    pub product_id: Option<u64>,
    pub min_qty: f64,
    pub price: f64,
    pub currency_id: u64,
    pub delay: i32,
    pub sequence: i32,
    pub product_name: Option<String>,
    pub product_code: Option<String>,
    pub date_start: Option<__sdk::Timestamp>,
    pub date_end: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for CreateProductSupplierInfoParams {
    type Module = super::RemoteModule;
}
