// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CreateActivityParams {
    pub activity_type: String,
    pub summary: String,
    pub priority: String,
    pub state: String,
    pub auto: bool,
    pub is_system: bool,
    pub is_done: bool,
    pub note: Option<String>,
    pub date_deadline: Option<__sdk::Timestamp>,
    pub date_done: Option<__sdk::Timestamp>,
    pub assigned_to: Option<__sdk::Identity>,
    pub res_model: Option<String>,
    pub res_id: Option<u64>,
    pub duration: Option<i32>,
    pub location: Option<String>,
    pub video_url: Option<String>,
    pub metadata: Option<String>,
}

impl __sdk::InModule for CreateActivityParams {
    type Module = super::RemoteModule;
}
