// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CreateBadDebtWriteOffParams {
    pub partner_id: u64,
    pub move_id: u64,
    pub amount: f64,
    pub journal_id: u64,
    pub receivable_account_id: u64,
    pub write_off_account_id: u64,
    pub date: __sdk::Timestamp,
    pub reference: Option<String>,
    pub metadata: Option<String>,
}

impl __sdk::InModule for CreateBadDebtWriteOffParams {
    type Module = super::RemoteModule;
}
