// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CreateReportTemplateParams {
    pub name: String,
    pub model: String,
    pub report_type: String,
    pub orientation: String,
    pub margin_top: f64,
    pub margin_bottom: f64,
    pub margin_left: f64,
    pub margin_right: f64,
    pub header_line: bool,
    pub footer_line: bool,
    pub attachment_use: bool,
    pub multi_company: bool,
    pub is_active: bool,
    pub description: Option<String>,
    pub template_content: Option<String>,
    pub paper_format: Option<String>,
    pub print_report_name: Option<String>,
    pub attachment: Option<String>,
    pub metadata: Option<String>,
}

impl __sdk::InModule for CreateReportTemplateParams {
    type Module = super::RemoteModule;
}
