// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateFleetVehicleArgs {
    pub organization_id: u64,
    pub name: String,
    pub vehicle_type: String,
    pub license_plate: Option<String>,
    pub driver_name: Option<String>,
}

impl From<CreateFleetVehicleArgs> for super::Reducer {
    fn from(args: CreateFleetVehicleArgs) -> Self {
        Self::CreateFleetVehicle {
            organization_id: args.organization_id,
            name: args.name,
            vehicle_type: args.vehicle_type,
            license_plate: args.license_plate,
            driver_name: args.driver_name,
        }
    }
}

impl __sdk::InModule for CreateFleetVehicleArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_fleet_vehicle`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_fleet_vehicle {
    /// Request that the remote module invoke the reducer `create_fleet_vehicle` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_fleet_vehicle:create_fleet_vehicle_then`] to run a callback after the reducer completes.
    fn create_fleet_vehicle(
        &self,
        organization_id: u64,
        name: String,
        vehicle_type: String,
        license_plate: Option<String>,
        driver_name: Option<String>,
    ) -> __sdk::Result<()> {
        self.create_fleet_vehicle_then(
            organization_id,
            name,
            vehicle_type,
            license_plate,
            driver_name,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `create_fleet_vehicle` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_fleet_vehicle_then(
        &self,
        organization_id: u64,
        name: String,
        vehicle_type: String,
        license_plate: Option<String>,
        driver_name: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_fleet_vehicle for super::RemoteReducers {
    fn create_fleet_vehicle_then(
        &self,
        organization_id: u64,
        name: String,
        vehicle_type: String,
        license_plate: Option<String>,
        driver_name: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateFleetVehicleArgs {
                organization_id,
                name,
                vehicle_type,
                license_plate,
                driver_name,
            },
            callback,
        )
    }
}
