// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::create_mrp_production_params_type::CreateMrpProductionParams;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateManufacturingOrderArgs {
    pub organization_id: u64,
    pub params: CreateMrpProductionParams,
}

impl From<CreateManufacturingOrderArgs> for super::Reducer {
    fn from(args: CreateManufacturingOrderArgs) -> Self {
        Self::CreateManufacturingOrder {
            organization_id: args.organization_id,
            params: args.params,
        }
    }
}

impl __sdk::InModule for CreateManufacturingOrderArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_manufacturing_order`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_manufacturing_order {
    /// Request that the remote module invoke the reducer `create_manufacturing_order` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_manufacturing_order:create_manufacturing_order_then`] to run a callback after the reducer completes.
    fn create_manufacturing_order(
        &self,
        organization_id: u64,
        params: CreateMrpProductionParams,
    ) -> __sdk::Result<()> {
        self.create_manufacturing_order_then(organization_id, params, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_manufacturing_order` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_manufacturing_order_then(
        &self,
        organization_id: u64,
        params: CreateMrpProductionParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_manufacturing_order for super::RemoteReducers {
    fn create_manufacturing_order_then(
        &self,
        organization_id: u64,
        params: CreateMrpProductionParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateManufacturingOrderArgs {
                organization_id,
                params,
            },
            callback,
        )
    }
}
