// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DismissInsightArgs {
    pub organization_id: u64,
    pub company_id: Option<u64>,
    pub insight_id: u64,
}

impl From<DismissInsightArgs> for super::Reducer {
    fn from(args: DismissInsightArgs) -> Self {
        Self::DismissInsight {
            organization_id: args.organization_id,
            company_id: args.company_id,
            insight_id: args.insight_id,
        }
    }
}

impl __sdk::InModule for DismissInsightArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `dismiss_insight`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait dismiss_insight {
    /// Request that the remote module invoke the reducer `dismiss_insight` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`dismiss_insight:dismiss_insight_then`] to run a callback after the reducer completes.
    fn dismiss_insight(
        &self,
        organization_id: u64,
        company_id: Option<u64>,
        insight_id: u64,
    ) -> __sdk::Result<()> {
        self.dismiss_insight_then(organization_id, company_id, insight_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `dismiss_insight` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn dismiss_insight_then(
        &self,
        organization_id: u64,
        company_id: Option<u64>,
        insight_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl dismiss_insight for super::RemoteReducers {
    fn dismiss_insight_then(
        &self,
        organization_id: u64,
        company_id: Option<u64>,
        insight_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DismissInsightArgs {
                organization_id,
                company_id,
                insight_id,
            },
            callback,
        )
    }
}
