// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DocumentVersion {
    pub id: u64,
    pub organization_id: u64,
    pub document_id: u64,
    pub version_number: u32,
    pub name: String,
    pub file_name: String,
    pub file_size: u64,
    pub mimetype: String,
    pub checksum: Option<String>,
    pub url: String,
    pub changes_description: Option<String>,
    pub created_by: __sdk::Identity,
    pub created_at: __sdk::Timestamp,
    pub is_current: bool,
    pub metadata: Option<String>,
}

impl __sdk::InModule for DocumentVersion {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DocumentVersion`.
///
/// Provides typed access to columns for query building.
pub struct DocumentVersionCols {
    pub id: __sdk::__query_builder::Col<DocumentVersion, u64>,
    pub organization_id: __sdk::__query_builder::Col<DocumentVersion, u64>,
    pub document_id: __sdk::__query_builder::Col<DocumentVersion, u64>,
    pub version_number: __sdk::__query_builder::Col<DocumentVersion, u32>,
    pub name: __sdk::__query_builder::Col<DocumentVersion, String>,
    pub file_name: __sdk::__query_builder::Col<DocumentVersion, String>,
    pub file_size: __sdk::__query_builder::Col<DocumentVersion, u64>,
    pub mimetype: __sdk::__query_builder::Col<DocumentVersion, String>,
    pub checksum: __sdk::__query_builder::Col<DocumentVersion, Option<String>>,
    pub url: __sdk::__query_builder::Col<DocumentVersion, String>,
    pub changes_description: __sdk::__query_builder::Col<DocumentVersion, Option<String>>,
    pub created_by: __sdk::__query_builder::Col<DocumentVersion, __sdk::Identity>,
    pub created_at: __sdk::__query_builder::Col<DocumentVersion, __sdk::Timestamp>,
    pub is_current: __sdk::__query_builder::Col<DocumentVersion, bool>,
    pub metadata: __sdk::__query_builder::Col<DocumentVersion, Option<String>>,
}

impl __sdk::__query_builder::HasCols for DocumentVersion {
    type Cols = DocumentVersionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DocumentVersionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            document_id: __sdk::__query_builder::Col::new(table_name, "document_id"),
            version_number: __sdk::__query_builder::Col::new(table_name, "version_number"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            file_name: __sdk::__query_builder::Col::new(table_name, "file_name"),
            file_size: __sdk::__query_builder::Col::new(table_name, "file_size"),
            mimetype: __sdk::__query_builder::Col::new(table_name, "mimetype"),
            checksum: __sdk::__query_builder::Col::new(table_name, "checksum"),
            url: __sdk::__query_builder::Col::new(table_name, "url"),
            changes_description: __sdk::__query_builder::Col::new(
                table_name,
                "changes_description",
            ),
            created_by: __sdk::__query_builder::Col::new(table_name, "created_by"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            is_current: __sdk::__query_builder::Col::new(table_name, "is_current"),
            metadata: __sdk::__query_builder::Col::new(table_name, "metadata"),
        }
    }
}

/// Indexed column accessor struct for the table `DocumentVersion`.
///
/// Provides typed access to indexed columns for query building.
pub struct DocumentVersionIxCols {
    pub document_id: __sdk::__query_builder::IxCol<DocumentVersion, u64>,
    pub id: __sdk::__query_builder::IxCol<DocumentVersion, u64>,
    pub organization_id: __sdk::__query_builder::IxCol<DocumentVersion, u64>,
}

impl __sdk::__query_builder::HasIxCols for DocumentVersion {
    type IxCols = DocumentVersionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DocumentVersionIxCols {
            document_id: __sdk::__query_builder::IxCol::new(table_name, "document_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            organization_id: __sdk::__query_builder::IxCol::new(table_name, "organization_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for DocumentVersion {}
