// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DocumentSequence {
    pub doc_type: String,
    pub next_number: u64,
}

impl __sdk::InModule for DocumentSequence {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DocumentSequence`.
///
/// Provides typed access to columns for query building.
pub struct DocumentSequenceCols {
    pub doc_type: __sdk::__query_builder::Col<DocumentSequence, String>,
    pub next_number: __sdk::__query_builder::Col<DocumentSequence, u64>,
}

impl __sdk::__query_builder::HasCols for DocumentSequence {
    type Cols = DocumentSequenceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DocumentSequenceCols {
            doc_type: __sdk::__query_builder::Col::new(table_name, "doc_type"),
            next_number: __sdk::__query_builder::Col::new(table_name, "next_number"),
        }
    }
}

/// Indexed column accessor struct for the table `DocumentSequence`.
///
/// Provides typed access to indexed columns for query building.
pub struct DocumentSequenceIxCols {
    pub doc_type: __sdk::__query_builder::IxCol<DocumentSequence, String>,
}

impl __sdk::__query_builder::HasIxCols for DocumentSequence {
    type IxCols = DocumentSequenceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DocumentSequenceIxCols {
            doc_type: __sdk::__query_builder::IxCol::new(table_name, "doc_type"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for DocumentSequence {}
