// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EndContactRelationshipArgs {
    pub organization_id: u64,
    pub relationship_id: u64,
}

impl From<EndContactRelationshipArgs> for super::Reducer {
    fn from(args: EndContactRelationshipArgs) -> Self {
        Self::EndContactRelationship {
            organization_id: args.organization_id,
            relationship_id: args.relationship_id,
        }
    }
}

impl __sdk::InModule for EndContactRelationshipArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `end_contact_relationship`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait end_contact_relationship {
    /// Request that the remote module invoke the reducer `end_contact_relationship` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`end_contact_relationship:end_contact_relationship_then`] to run a callback after the reducer completes.
    fn end_contact_relationship(
        &self,
        organization_id: u64,
        relationship_id: u64,
    ) -> __sdk::Result<()> {
        self.end_contact_relationship_then(organization_id, relationship_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `end_contact_relationship` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn end_contact_relationship_then(
        &self,
        organization_id: u64,
        relationship_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl end_contact_relationship for super::RemoteReducers {
    fn end_contact_relationship_then(
        &self,
        organization_id: u64,
        relationship_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            EndContactRelationshipArgs {
                organization_id,
                relationship_id,
            },
            callback,
        )
    }
}
