// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::expense_sheet_state_type::ExpenseSheetState;
use super::hr_expense_sheet_type::HrExpenseSheet;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `expense_sheet`.
///
/// Obtain a handle from the [`ExpenseSheetTableAccess::expense_sheet`] method on [`super::RemoteTables`],
/// like `ctx.db.expense_sheet()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.expense_sheet().on_insert(...)`.
pub struct ExpenseSheetTableHandle<'ctx> {
    imp: __sdk::TableHandle<HrExpenseSheet>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `expense_sheet`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ExpenseSheetTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ExpenseSheetTableHandle`], which mediates access to the table `expense_sheet`.
    fn expense_sheet(&self) -> ExpenseSheetTableHandle<'_>;
}

impl ExpenseSheetTableAccess for super::RemoteTables {
    fn expense_sheet(&self) -> ExpenseSheetTableHandle<'_> {
        ExpenseSheetTableHandle {
            imp: self.imp.get_table::<HrExpenseSheet>("expense_sheet"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ExpenseSheetInsertCallbackId(__sdk::CallbackId);
pub struct ExpenseSheetDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ExpenseSheetTableHandle<'ctx> {
    type Row = HrExpenseSheet;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = HrExpenseSheet> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ExpenseSheetInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ExpenseSheetInsertCallbackId {
        ExpenseSheetInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ExpenseSheetInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ExpenseSheetDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ExpenseSheetDeleteCallbackId {
        ExpenseSheetDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ExpenseSheetDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ExpenseSheetUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ExpenseSheetTableHandle<'ctx> {
    type UpdateCallbackId = ExpenseSheetUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ExpenseSheetUpdateCallbackId {
        ExpenseSheetUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ExpenseSheetUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `expense_sheet`,
/// which allows point queries on the field of the same name
/// via the [`ExpenseSheetIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.expense_sheet().id().find(...)`.
pub struct ExpenseSheetIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<HrExpenseSheet, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ExpenseSheetTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `expense_sheet`.
    pub fn id(&self) -> ExpenseSheetIdUnique<'ctx> {
        ExpenseSheetIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ExpenseSheetIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<HrExpenseSheet> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<HrExpenseSheet>("expense_sheet");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<HrExpenseSheet>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<HrExpenseSheet>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `HrExpenseSheet`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait expense_sheetQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `HrExpenseSheet`.
    fn expense_sheet(&self) -> __sdk::__query_builder::Table<HrExpenseSheet>;
}

impl expense_sheetQueryTableAccess for __sdk::QueryTableAccessor {
    fn expense_sheet(&self) -> __sdk::__query_builder::Table<HrExpenseSheet> {
        __sdk::__query_builder::Table::new("expense_sheet")
    }
}
