// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::form_config_type::FormConfig;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `form_config`.
///
/// Obtain a handle from the [`FormConfigTableAccess::form_config`] method on [`super::RemoteTables`],
/// like `ctx.db.form_config()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.form_config().on_insert(...)`.
pub struct FormConfigTableHandle<'ctx> {
    imp: __sdk::TableHandle<FormConfig>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `form_config`.
///
/// Implemented for [`super::RemoteTables`].
pub trait FormConfigTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`FormConfigTableHandle`], which mediates access to the table `form_config`.
    fn form_config(&self) -> FormConfigTableHandle<'_>;
}

impl FormConfigTableAccess for super::RemoteTables {
    fn form_config(&self) -> FormConfigTableHandle<'_> {
        FormConfigTableHandle {
            imp: self.imp.get_table::<FormConfig>("form_config"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct FormConfigInsertCallbackId(__sdk::CallbackId);
pub struct FormConfigDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for FormConfigTableHandle<'ctx> {
    type Row = FormConfig;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FormConfig> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = FormConfigInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FormConfigInsertCallbackId {
        FormConfigInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FormConfigInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = FormConfigDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FormConfigDeleteCallbackId {
        FormConfigDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FormConfigDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct FormConfigUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for FormConfigTableHandle<'ctx> {
    type UpdateCallbackId = FormConfigUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FormConfigUpdateCallbackId {
        FormConfigUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FormConfigUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `form_config`,
/// which allows point queries on the field of the same name
/// via the [`FormConfigIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.form_config().id().find(...)`.
pub struct FormConfigIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<FormConfig, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> FormConfigTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `form_config`.
    pub fn id(&self) -> FormConfigIdUnique<'ctx> {
        FormConfigIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> FormConfigIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<FormConfig> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<FormConfig>("form_config");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<FormConfig>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<FormConfig>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `FormConfig`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait form_configQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `FormConfig`.
    fn form_config(&self) -> __sdk::__query_builder::Table<FormConfig>;
}

impl form_configQueryTableAccess for __sdk::QueryTableAccessor {
    fn form_config(&self) -> __sdk::__query_builder::Table<FormConfig> {
        __sdk::__query_builder::Table::new("form_config")
    }
}
