// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::fx_revaluation_run_type::FxRevaluationRun;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `fx_revaluation_run`.
///
/// Obtain a handle from the [`FxRevaluationRunTableAccess::fx_revaluation_run`] method on [`super::RemoteTables`],
/// like `ctx.db.fx_revaluation_run()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.fx_revaluation_run().on_insert(...)`.
pub struct FxRevaluationRunTableHandle<'ctx> {
    imp: __sdk::TableHandle<FxRevaluationRun>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `fx_revaluation_run`.
///
/// Implemented for [`super::RemoteTables`].
pub trait FxRevaluationRunTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`FxRevaluationRunTableHandle`], which mediates access to the table `fx_revaluation_run`.
    fn fx_revaluation_run(&self) -> FxRevaluationRunTableHandle<'_>;
}

impl FxRevaluationRunTableAccess for super::RemoteTables {
    fn fx_revaluation_run(&self) -> FxRevaluationRunTableHandle<'_> {
        FxRevaluationRunTableHandle {
            imp: self.imp.get_table::<FxRevaluationRun>("fx_revaluation_run"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct FxRevaluationRunInsertCallbackId(__sdk::CallbackId);
pub struct FxRevaluationRunDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for FxRevaluationRunTableHandle<'ctx> {
    type Row = FxRevaluationRun;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FxRevaluationRun> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = FxRevaluationRunInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FxRevaluationRunInsertCallbackId {
        FxRevaluationRunInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FxRevaluationRunInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = FxRevaluationRunDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FxRevaluationRunDeleteCallbackId {
        FxRevaluationRunDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FxRevaluationRunDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct FxRevaluationRunUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for FxRevaluationRunTableHandle<'ctx> {
    type UpdateCallbackId = FxRevaluationRunUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FxRevaluationRunUpdateCallbackId {
        FxRevaluationRunUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FxRevaluationRunUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `fx_revaluation_run`,
/// which allows point queries on the field of the same name
/// via the [`FxRevaluationRunIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.fx_revaluation_run().id().find(...)`.
pub struct FxRevaluationRunIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<FxRevaluationRun, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> FxRevaluationRunTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `fx_revaluation_run`.
    pub fn id(&self) -> FxRevaluationRunIdUnique<'ctx> {
        FxRevaluationRunIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> FxRevaluationRunIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<FxRevaluationRun> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<FxRevaluationRun>("fx_revaluation_run");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<FxRevaluationRun>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<FxRevaluationRun>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `FxRevaluationRun`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait fx_revaluation_runQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `FxRevaluationRun`.
    fn fx_revaluation_run(&self) -> __sdk::__query_builder::Table<FxRevaluationRun>;
}

impl fx_revaluation_runQueryTableAccess for __sdk::QueryTableAccessor {
    fn fx_revaluation_run(&self) -> __sdk::__query_builder::Table<FxRevaluationRun> {
        __sdk::__query_builder::Table::new("fx_revaluation_run")
    }
}
