// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct HrJobPosition {
    pub id: u64,
    pub organization_id: u64,
    pub company_id: u64,
    pub name: String,
    pub department_id: Option<u64>,
    pub expected_employees: u32,
    pub no_of_employee: u32,
    pub description: Option<String>,
    pub requirements: Option<String>,
    pub state: String,
    pub is_active: bool,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for HrJobPosition {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `HrJobPosition`.
///
/// Provides typed access to columns for query building.
pub struct HrJobPositionCols {
    pub id: __sdk::__query_builder::Col<HrJobPosition, u64>,
    pub organization_id: __sdk::__query_builder::Col<HrJobPosition, u64>,
    pub company_id: __sdk::__query_builder::Col<HrJobPosition, u64>,
    pub name: __sdk::__query_builder::Col<HrJobPosition, String>,
    pub department_id: __sdk::__query_builder::Col<HrJobPosition, Option<u64>>,
    pub expected_employees: __sdk::__query_builder::Col<HrJobPosition, u32>,
    pub no_of_employee: __sdk::__query_builder::Col<HrJobPosition, u32>,
    pub description: __sdk::__query_builder::Col<HrJobPosition, Option<String>>,
    pub requirements: __sdk::__query_builder::Col<HrJobPosition, Option<String>>,
    pub state: __sdk::__query_builder::Col<HrJobPosition, String>,
    pub is_active: __sdk::__query_builder::Col<HrJobPosition, bool>,
    pub created_at: __sdk::__query_builder::Col<HrJobPosition, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for HrJobPosition {
    type Cols = HrJobPositionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        HrJobPositionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            company_id: __sdk::__query_builder::Col::new(table_name, "company_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            department_id: __sdk::__query_builder::Col::new(table_name, "department_id"),
            expected_employees: __sdk::__query_builder::Col::new(table_name, "expected_employees"),
            no_of_employee: __sdk::__query_builder::Col::new(table_name, "no_of_employee"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
            requirements: __sdk::__query_builder::Col::new(table_name, "requirements"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
            is_active: __sdk::__query_builder::Col::new(table_name, "is_active"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `HrJobPosition`.
///
/// Provides typed access to indexed columns for query building.
pub struct HrJobPositionIxCols {
    pub department_id: __sdk::__query_builder::IxCol<HrJobPosition, Option<u64>>,
    pub id: __sdk::__query_builder::IxCol<HrJobPosition, u64>,
    pub organization_id: __sdk::__query_builder::IxCol<HrJobPosition, u64>,
}

impl __sdk::__query_builder::HasIxCols for HrJobPosition {
    type IxCols = HrJobPositionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        HrJobPositionIxCols {
            department_id: __sdk::__query_builder::IxCol::new(table_name, "department_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            organization_id: __sdk::__query_builder::IxCol::new(table_name, "organization_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for HrJobPosition {}
