// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::hr_leave_allocation_type::HrLeaveAllocation;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `hr_leave_allocation`.
///
/// Obtain a handle from the [`HrLeaveAllocationTableAccess::hr_leave_allocation`] method on [`super::RemoteTables`],
/// like `ctx.db.hr_leave_allocation()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.hr_leave_allocation().on_insert(...)`.
pub struct HrLeaveAllocationTableHandle<'ctx> {
    imp: __sdk::TableHandle<HrLeaveAllocation>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `hr_leave_allocation`.
///
/// Implemented for [`super::RemoteTables`].
pub trait HrLeaveAllocationTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`HrLeaveAllocationTableHandle`], which mediates access to the table `hr_leave_allocation`.
    fn hr_leave_allocation(&self) -> HrLeaveAllocationTableHandle<'_>;
}

impl HrLeaveAllocationTableAccess for super::RemoteTables {
    fn hr_leave_allocation(&self) -> HrLeaveAllocationTableHandle<'_> {
        HrLeaveAllocationTableHandle {
            imp: self
                .imp
                .get_table::<HrLeaveAllocation>("hr_leave_allocation"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct HrLeaveAllocationInsertCallbackId(__sdk::CallbackId);
pub struct HrLeaveAllocationDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for HrLeaveAllocationTableHandle<'ctx> {
    type Row = HrLeaveAllocation;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = HrLeaveAllocation> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = HrLeaveAllocationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HrLeaveAllocationInsertCallbackId {
        HrLeaveAllocationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: HrLeaveAllocationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = HrLeaveAllocationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HrLeaveAllocationDeleteCallbackId {
        HrLeaveAllocationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: HrLeaveAllocationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct HrLeaveAllocationUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for HrLeaveAllocationTableHandle<'ctx> {
    type UpdateCallbackId = HrLeaveAllocationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> HrLeaveAllocationUpdateCallbackId {
        HrLeaveAllocationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: HrLeaveAllocationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `hr_leave_allocation`,
/// which allows point queries on the field of the same name
/// via the [`HrLeaveAllocationIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.hr_leave_allocation().id().find(...)`.
pub struct HrLeaveAllocationIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<HrLeaveAllocation, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> HrLeaveAllocationTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `hr_leave_allocation`.
    pub fn id(&self) -> HrLeaveAllocationIdUnique<'ctx> {
        HrLeaveAllocationIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> HrLeaveAllocationIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<HrLeaveAllocation> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<HrLeaveAllocation>("hr_leave_allocation");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<HrLeaveAllocation>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<HrLeaveAllocation>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `HrLeaveAllocation`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait hr_leave_allocationQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `HrLeaveAllocation`.
    fn hr_leave_allocation(&self) -> __sdk::__query_builder::Table<HrLeaveAllocation>;
}

impl hr_leave_allocationQueryTableAccess for __sdk::QueryTableAccessor {
    fn hr_leave_allocation(&self) -> __sdk::__query_builder::Table<HrLeaveAllocation> {
        __sdk::__query_builder::Table::new("hr_leave_allocation")
    }
}
