// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::intercompany_rule_type::IntercompanyRule;
use super::rule_type_type::RuleType;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `intercompany_rule`.
///
/// Obtain a handle from the [`IntercompanyRuleTableAccess::intercompany_rule`] method on [`super::RemoteTables`],
/// like `ctx.db.intercompany_rule()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.intercompany_rule().on_insert(...)`.
pub struct IntercompanyRuleTableHandle<'ctx> {
    imp: __sdk::TableHandle<IntercompanyRule>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `intercompany_rule`.
///
/// Implemented for [`super::RemoteTables`].
pub trait IntercompanyRuleTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`IntercompanyRuleTableHandle`], which mediates access to the table `intercompany_rule`.
    fn intercompany_rule(&self) -> IntercompanyRuleTableHandle<'_>;
}

impl IntercompanyRuleTableAccess for super::RemoteTables {
    fn intercompany_rule(&self) -> IntercompanyRuleTableHandle<'_> {
        IntercompanyRuleTableHandle {
            imp: self.imp.get_table::<IntercompanyRule>("intercompany_rule"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct IntercompanyRuleInsertCallbackId(__sdk::CallbackId);
pub struct IntercompanyRuleDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for IntercompanyRuleTableHandle<'ctx> {
    type Row = IntercompanyRule;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = IntercompanyRule> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = IntercompanyRuleInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> IntercompanyRuleInsertCallbackId {
        IntercompanyRuleInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: IntercompanyRuleInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = IntercompanyRuleDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> IntercompanyRuleDeleteCallbackId {
        IntercompanyRuleDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: IntercompanyRuleDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct IntercompanyRuleUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for IntercompanyRuleTableHandle<'ctx> {
    type UpdateCallbackId = IntercompanyRuleUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> IntercompanyRuleUpdateCallbackId {
        IntercompanyRuleUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: IntercompanyRuleUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `intercompany_rule`,
/// which allows point queries on the field of the same name
/// via the [`IntercompanyRuleIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.intercompany_rule().id().find(...)`.
pub struct IntercompanyRuleIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<IntercompanyRule, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> IntercompanyRuleTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `intercompany_rule`.
    pub fn id(&self) -> IntercompanyRuleIdUnique<'ctx> {
        IntercompanyRuleIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> IntercompanyRuleIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<IntercompanyRule> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<IntercompanyRule>("intercompany_rule");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<IntercompanyRule>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<IntercompanyRule>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `IntercompanyRule`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait intercompany_ruleQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `IntercompanyRule`.
    fn intercompany_rule(&self) -> __sdk::__query_builder::Table<IntercompanyRule>;
}

impl intercompany_ruleQueryTableAccess for __sdk::QueryTableAccessor {
    fn intercompany_rule(&self) -> __sdk::__query_builder::Table<IntercompanyRule> {
        __sdk::__query_builder::Table::new("intercompany_rule")
    }
}
