// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InventoryIntegrationIntent {
    pub id: u64,
    pub organization_id: u64,
    pub company_id: u64,
    pub provider: String,
    pub intent_type: String,
    pub warehouse_id: Option<u64>,
    pub picking_id: Option<u64>,
    pub status: String,
    pub idempotency_key: String,
    pub request_payload: Option<String>,
    pub last_error: Option<String>,
    pub external_reference: Option<String>,
    pub attempt_count: u32,
    pub create_uid: __sdk::Identity,
    pub create_date: __sdk::Timestamp,
    pub write_uid: __sdk::Identity,
    pub write_date: __sdk::Timestamp,
    pub metadata: Option<String>,
}

impl __sdk::InModule for InventoryIntegrationIntent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InventoryIntegrationIntent`.
///
/// Provides typed access to columns for query building.
pub struct InventoryIntegrationIntentCols {
    pub id: __sdk::__query_builder::Col<InventoryIntegrationIntent, u64>,
    pub organization_id: __sdk::__query_builder::Col<InventoryIntegrationIntent, u64>,
    pub company_id: __sdk::__query_builder::Col<InventoryIntegrationIntent, u64>,
    pub provider: __sdk::__query_builder::Col<InventoryIntegrationIntent, String>,
    pub intent_type: __sdk::__query_builder::Col<InventoryIntegrationIntent, String>,
    pub warehouse_id: __sdk::__query_builder::Col<InventoryIntegrationIntent, Option<u64>>,
    pub picking_id: __sdk::__query_builder::Col<InventoryIntegrationIntent, Option<u64>>,
    pub status: __sdk::__query_builder::Col<InventoryIntegrationIntent, String>,
    pub idempotency_key: __sdk::__query_builder::Col<InventoryIntegrationIntent, String>,
    pub request_payload: __sdk::__query_builder::Col<InventoryIntegrationIntent, Option<String>>,
    pub last_error: __sdk::__query_builder::Col<InventoryIntegrationIntent, Option<String>>,
    pub external_reference: __sdk::__query_builder::Col<InventoryIntegrationIntent, Option<String>>,
    pub attempt_count: __sdk::__query_builder::Col<InventoryIntegrationIntent, u32>,
    pub create_uid: __sdk::__query_builder::Col<InventoryIntegrationIntent, __sdk::Identity>,
    pub create_date: __sdk::__query_builder::Col<InventoryIntegrationIntent, __sdk::Timestamp>,
    pub write_uid: __sdk::__query_builder::Col<InventoryIntegrationIntent, __sdk::Identity>,
    pub write_date: __sdk::__query_builder::Col<InventoryIntegrationIntent, __sdk::Timestamp>,
    pub metadata: __sdk::__query_builder::Col<InventoryIntegrationIntent, Option<String>>,
}

impl __sdk::__query_builder::HasCols for InventoryIntegrationIntent {
    type Cols = InventoryIntegrationIntentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InventoryIntegrationIntentCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            company_id: __sdk::__query_builder::Col::new(table_name, "company_id"),
            provider: __sdk::__query_builder::Col::new(table_name, "provider"),
            intent_type: __sdk::__query_builder::Col::new(table_name, "intent_type"),
            warehouse_id: __sdk::__query_builder::Col::new(table_name, "warehouse_id"),
            picking_id: __sdk::__query_builder::Col::new(table_name, "picking_id"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            idempotency_key: __sdk::__query_builder::Col::new(table_name, "idempotency_key"),
            request_payload: __sdk::__query_builder::Col::new(table_name, "request_payload"),
            last_error: __sdk::__query_builder::Col::new(table_name, "last_error"),
            external_reference: __sdk::__query_builder::Col::new(table_name, "external_reference"),
            attempt_count: __sdk::__query_builder::Col::new(table_name, "attempt_count"),
            create_uid: __sdk::__query_builder::Col::new(table_name, "create_uid"),
            create_date: __sdk::__query_builder::Col::new(table_name, "create_date"),
            write_uid: __sdk::__query_builder::Col::new(table_name, "write_uid"),
            write_date: __sdk::__query_builder::Col::new(table_name, "write_date"),
            metadata: __sdk::__query_builder::Col::new(table_name, "metadata"),
        }
    }
}

/// Indexed column accessor struct for the table `InventoryIntegrationIntent`.
///
/// Provides typed access to indexed columns for query building.
pub struct InventoryIntegrationIntentIxCols {
    pub id: __sdk::__query_builder::IxCol<InventoryIntegrationIntent, u64>,
    pub idempotency_key: __sdk::__query_builder::IxCol<InventoryIntegrationIntent, String>,
    pub organization_id: __sdk::__query_builder::IxCol<InventoryIntegrationIntent, u64>,
    pub status: __sdk::__query_builder::IxCol<InventoryIntegrationIntent, String>,
}

impl __sdk::__query_builder::HasIxCols for InventoryIntegrationIntent {
    type IxCols = InventoryIntegrationIntentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InventoryIntegrationIntentIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            idempotency_key: __sdk::__query_builder::IxCol::new(table_name, "idempotency_key"),
            organization_id: __sdk::__query_builder::IxCol::new(table_name, "organization_id"),
            status: __sdk::__query_builder::IxCol::new(table_name, "status"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InventoryIntegrationIntent {}
