// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::inventory_close_type::InventoryClose;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `inventory_close`.
///
/// Obtain a handle from the [`InventoryCloseTableAccess::inventory_close`] method on [`super::RemoteTables`],
/// like `ctx.db.inventory_close()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.inventory_close().on_insert(...)`.
pub struct InventoryCloseTableHandle<'ctx> {
    imp: __sdk::TableHandle<InventoryClose>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `inventory_close`.
///
/// Implemented for [`super::RemoteTables`].
pub trait InventoryCloseTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`InventoryCloseTableHandle`], which mediates access to the table `inventory_close`.
    fn inventory_close(&self) -> InventoryCloseTableHandle<'_>;
}

impl InventoryCloseTableAccess for super::RemoteTables {
    fn inventory_close(&self) -> InventoryCloseTableHandle<'_> {
        InventoryCloseTableHandle {
            imp: self.imp.get_table::<InventoryClose>("inventory_close"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct InventoryCloseInsertCallbackId(__sdk::CallbackId);
pub struct InventoryCloseDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for InventoryCloseTableHandle<'ctx> {
    type Row = InventoryClose;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = InventoryClose> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = InventoryCloseInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InventoryCloseInsertCallbackId {
        InventoryCloseInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: InventoryCloseInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = InventoryCloseDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InventoryCloseDeleteCallbackId {
        InventoryCloseDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: InventoryCloseDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct InventoryCloseUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for InventoryCloseTableHandle<'ctx> {
    type UpdateCallbackId = InventoryCloseUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> InventoryCloseUpdateCallbackId {
        InventoryCloseUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: InventoryCloseUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `inventory_close`,
/// which allows point queries on the field of the same name
/// via the [`InventoryCloseIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.inventory_close().id().find(...)`.
pub struct InventoryCloseIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<InventoryClose, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> InventoryCloseTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `inventory_close`.
    pub fn id(&self) -> InventoryCloseIdUnique<'ctx> {
        InventoryCloseIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> InventoryCloseIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<InventoryClose> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<InventoryClose>("inventory_close");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<InventoryClose>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<InventoryClose>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `InventoryClose`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait inventory_closeQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `InventoryClose`.
    fn inventory_close(&self) -> __sdk::__query_builder::Table<InventoryClose>;
}

impl inventory_closeQueryTableAccess for __sdk::QueryTableAccessor {
    fn inventory_close(&self) -> __sdk::__query_builder::Table<InventoryClose> {
        __sdk::__query_builder::Table::new("inventory_close")
    }
}
