// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct IoTTelemetry {
    pub id: u64,
    pub device_id: u64,
    pub organization_id: u64,
    pub company_id: u64,
    pub sensor_type: String,
    pub value: f64,
    pub raw_value: Option<String>,
    pub unit: String,
    pub quality: String,
    pub recorded_at: __sdk::Timestamp,
}

impl __sdk::InModule for IoTTelemetry {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `IoTTelemetry`.
///
/// Provides typed access to columns for query building.
pub struct IoTTelemetryCols {
    pub id: __sdk::__query_builder::Col<IoTTelemetry, u64>,
    pub device_id: __sdk::__query_builder::Col<IoTTelemetry, u64>,
    pub organization_id: __sdk::__query_builder::Col<IoTTelemetry, u64>,
    pub company_id: __sdk::__query_builder::Col<IoTTelemetry, u64>,
    pub sensor_type: __sdk::__query_builder::Col<IoTTelemetry, String>,
    pub value: __sdk::__query_builder::Col<IoTTelemetry, f64>,
    pub raw_value: __sdk::__query_builder::Col<IoTTelemetry, Option<String>>,
    pub unit: __sdk::__query_builder::Col<IoTTelemetry, String>,
    pub quality: __sdk::__query_builder::Col<IoTTelemetry, String>,
    pub recorded_at: __sdk::__query_builder::Col<IoTTelemetry, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for IoTTelemetry {
    type Cols = IoTTelemetryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        IoTTelemetryCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            device_id: __sdk::__query_builder::Col::new(table_name, "device_id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            company_id: __sdk::__query_builder::Col::new(table_name, "company_id"),
            sensor_type: __sdk::__query_builder::Col::new(table_name, "sensor_type"),
            value: __sdk::__query_builder::Col::new(table_name, "value"),
            raw_value: __sdk::__query_builder::Col::new(table_name, "raw_value"),
            unit: __sdk::__query_builder::Col::new(table_name, "unit"),
            quality: __sdk::__query_builder::Col::new(table_name, "quality"),
            recorded_at: __sdk::__query_builder::Col::new(table_name, "recorded_at"),
        }
    }
}

/// Indexed column accessor struct for the table `IoTTelemetry`.
///
/// Provides typed access to indexed columns for query building.
pub struct IoTTelemetryIxCols {
    pub device_id: __sdk::__query_builder::IxCol<IoTTelemetry, u64>,
    pub id: __sdk::__query_builder::IxCol<IoTTelemetry, u64>,
    pub organization_id: __sdk::__query_builder::IxCol<IoTTelemetry, u64>,
}

impl __sdk::__query_builder::HasIxCols for IoTTelemetry {
    type IxCols = IoTTelemetryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        IoTTelemetryIxCols {
            device_id: __sdk::__query_builder::IxCol::new(table_name, "device_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            organization_id: __sdk::__query_builder::IxCol::new(table_name, "organization_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for IoTTelemetry {}
