// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct KnowledgeArticlePresence {
    pub id: u64,
    pub organization_id: u64,
    pub article_id: u64,
    pub user_id: __sdk::Identity,
    pub user_name: String,
    pub last_seen: __sdk::Timestamp,
}

impl __sdk::InModule for KnowledgeArticlePresence {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `KnowledgeArticlePresence`.
///
/// Provides typed access to columns for query building.
pub struct KnowledgeArticlePresenceCols {
    pub id: __sdk::__query_builder::Col<KnowledgeArticlePresence, u64>,
    pub organization_id: __sdk::__query_builder::Col<KnowledgeArticlePresence, u64>,
    pub article_id: __sdk::__query_builder::Col<KnowledgeArticlePresence, u64>,
    pub user_id: __sdk::__query_builder::Col<KnowledgeArticlePresence, __sdk::Identity>,
    pub user_name: __sdk::__query_builder::Col<KnowledgeArticlePresence, String>,
    pub last_seen: __sdk::__query_builder::Col<KnowledgeArticlePresence, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for KnowledgeArticlePresence {
    type Cols = KnowledgeArticlePresenceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        KnowledgeArticlePresenceCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            article_id: __sdk::__query_builder::Col::new(table_name, "article_id"),
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
            user_name: __sdk::__query_builder::Col::new(table_name, "user_name"),
            last_seen: __sdk::__query_builder::Col::new(table_name, "last_seen"),
        }
    }
}

/// Indexed column accessor struct for the table `KnowledgeArticlePresence`.
///
/// Provides typed access to indexed columns for query building.
pub struct KnowledgeArticlePresenceIxCols {
    pub article_id: __sdk::__query_builder::IxCol<KnowledgeArticlePresence, u64>,
    pub id: __sdk::__query_builder::IxCol<KnowledgeArticlePresence, u64>,
    pub user_id: __sdk::__query_builder::IxCol<KnowledgeArticlePresence, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for KnowledgeArticlePresence {
    type IxCols = KnowledgeArticlePresenceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        KnowledgeArticlePresenceIxCols {
            article_id: __sdk::__query_builder::IxCol::new(table_name, "article_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            user_id: __sdk::__query_builder::IxCol::new(table_name, "user_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for KnowledgeArticlePresence {}
