// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::lead_lost_reason_type::LeadLostReason;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `lead_lost_reason`.
///
/// Obtain a handle from the [`LeadLostReasonTableAccess::lead_lost_reason`] method on [`super::RemoteTables`],
/// like `ctx.db.lead_lost_reason()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.lead_lost_reason().on_insert(...)`.
pub struct LeadLostReasonTableHandle<'ctx> {
    imp: __sdk::TableHandle<LeadLostReason>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `lead_lost_reason`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LeadLostReasonTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LeadLostReasonTableHandle`], which mediates access to the table `lead_lost_reason`.
    fn lead_lost_reason(&self) -> LeadLostReasonTableHandle<'_>;
}

impl LeadLostReasonTableAccess for super::RemoteTables {
    fn lead_lost_reason(&self) -> LeadLostReasonTableHandle<'_> {
        LeadLostReasonTableHandle {
            imp: self.imp.get_table::<LeadLostReason>("lead_lost_reason"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LeadLostReasonInsertCallbackId(__sdk::CallbackId);
pub struct LeadLostReasonDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LeadLostReasonTableHandle<'ctx> {
    type Row = LeadLostReason;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LeadLostReason> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LeadLostReasonInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LeadLostReasonInsertCallbackId {
        LeadLostReasonInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LeadLostReasonInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LeadLostReasonDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LeadLostReasonDeleteCallbackId {
        LeadLostReasonDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LeadLostReasonDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct LeadLostReasonUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LeadLostReasonTableHandle<'ctx> {
    type UpdateCallbackId = LeadLostReasonUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LeadLostReasonUpdateCallbackId {
        LeadLostReasonUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LeadLostReasonUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `lead_lost_reason`,
/// which allows point queries on the field of the same name
/// via the [`LeadLostReasonIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.lead_lost_reason().id().find(...)`.
pub struct LeadLostReasonIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<LeadLostReason, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LeadLostReasonTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `lead_lost_reason`.
    pub fn id(&self) -> LeadLostReasonIdUnique<'ctx> {
        LeadLostReasonIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LeadLostReasonIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<LeadLostReason> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LeadLostReason>("lead_lost_reason");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LeadLostReason>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LeadLostReason>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LeadLostReason`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait lead_lost_reasonQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LeadLostReason`.
    fn lead_lost_reason(&self) -> __sdk::__query_builder::Table<LeadLostReason>;
}

impl lead_lost_reasonQueryTableAccess for __sdk::QueryTableAccessor {
    fn lead_lost_reason(&self) -> __sdk::__query_builder::Table<LeadLostReason> {
        __sdk::__query_builder::Table::new("lead_lost_reason")
    }
}
