// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::link_subcontractor_cost_params_type::LinkSubcontractorCostParams;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct LinkSubcontractorCostToProjectArgs {
    pub organization_id: u64,
    pub company_id: u64,
    pub params: LinkSubcontractorCostParams,
}

impl From<LinkSubcontractorCostToProjectArgs> for super::Reducer {
    fn from(args: LinkSubcontractorCostToProjectArgs) -> Self {
        Self::LinkSubcontractorCostToProject {
            organization_id: args.organization_id,
            company_id: args.company_id,
            params: args.params,
        }
    }
}

impl __sdk::InModule for LinkSubcontractorCostToProjectArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `link_subcontractor_cost_to_project`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait link_subcontractor_cost_to_project {
    /// Request that the remote module invoke the reducer `link_subcontractor_cost_to_project` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`link_subcontractor_cost_to_project:link_subcontractor_cost_to_project_then`] to run a callback after the reducer completes.
    fn link_subcontractor_cost_to_project(
        &self,
        organization_id: u64,
        company_id: u64,
        params: LinkSubcontractorCostParams,
    ) -> __sdk::Result<()> {
        self.link_subcontractor_cost_to_project_then(organization_id, company_id, params, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `link_subcontractor_cost_to_project` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn link_subcontractor_cost_to_project_then(
        &self,
        organization_id: u64,
        company_id: u64,
        params: LinkSubcontractorCostParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl link_subcontractor_cost_to_project for super::RemoteReducers {
    fn link_subcontractor_cost_to_project_then(
        &self,
        organization_id: u64,
        company_id: u64,
        params: LinkSubcontractorCostParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            LinkSubcontractorCostToProjectArgs {
                organization_id,
                company_id,
                params,
            },
            callback,
        )
    }
}
