// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::mrp_bom_line_type::MrpBomLine;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `mrp_bom_line`.
///
/// Obtain a handle from the [`MrpBomLineTableAccess::mrp_bom_line`] method on [`super::RemoteTables`],
/// like `ctx.db.mrp_bom_line()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.mrp_bom_line().on_insert(...)`.
pub struct MrpBomLineTableHandle<'ctx> {
    imp: __sdk::TableHandle<MrpBomLine>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `mrp_bom_line`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MrpBomLineTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MrpBomLineTableHandle`], which mediates access to the table `mrp_bom_line`.
    fn mrp_bom_line(&self) -> MrpBomLineTableHandle<'_>;
}

impl MrpBomLineTableAccess for super::RemoteTables {
    fn mrp_bom_line(&self) -> MrpBomLineTableHandle<'_> {
        MrpBomLineTableHandle {
            imp: self.imp.get_table::<MrpBomLine>("mrp_bom_line"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MrpBomLineInsertCallbackId(__sdk::CallbackId);
pub struct MrpBomLineDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MrpBomLineTableHandle<'ctx> {
    type Row = MrpBomLine;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MrpBomLine> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MrpBomLineInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MrpBomLineInsertCallbackId {
        MrpBomLineInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MrpBomLineInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MrpBomLineDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MrpBomLineDeleteCallbackId {
        MrpBomLineDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MrpBomLineDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MrpBomLineUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MrpBomLineTableHandle<'ctx> {
    type UpdateCallbackId = MrpBomLineUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MrpBomLineUpdateCallbackId {
        MrpBomLineUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MrpBomLineUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `mrp_bom_line`,
/// which allows point queries on the field of the same name
/// via the [`MrpBomLineIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.mrp_bom_line().id().find(...)`.
pub struct MrpBomLineIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MrpBomLine, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MrpBomLineTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `mrp_bom_line`.
    pub fn id(&self) -> MrpBomLineIdUnique<'ctx> {
        MrpBomLineIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MrpBomLineIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MrpBomLine> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MrpBomLine>("mrp_bom_line");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MrpBomLine>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MrpBomLine>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MrpBomLine`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait mrp_bom_lineQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MrpBomLine`.
    fn mrp_bom_line(&self) -> __sdk::__query_builder::Table<MrpBomLine>;
}

impl mrp_bom_lineQueryTableAccess for __sdk::QueryTableAccessor {
    fn mrp_bom_line(&self) -> __sdk::__query_builder::Table<MrpBomLine> {
        __sdk::__query_builder::Table::new("mrp_bom_line")
    }
}
