// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::opportunity_stage_type::OpportunityStage;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `opp_stage`.
///
/// Obtain a handle from the [`OppStageTableAccess::opp_stage`] method on [`super::RemoteTables`],
/// like `ctx.db.opp_stage()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.opp_stage().on_insert(...)`.
pub struct OppStageTableHandle<'ctx> {
    imp: __sdk::TableHandle<OpportunityStage>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `opp_stage`.
///
/// Implemented for [`super::RemoteTables`].
pub trait OppStageTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`OppStageTableHandle`], which mediates access to the table `opp_stage`.
    fn opp_stage(&self) -> OppStageTableHandle<'_>;
}

impl OppStageTableAccess for super::RemoteTables {
    fn opp_stage(&self) -> OppStageTableHandle<'_> {
        OppStageTableHandle {
            imp: self.imp.get_table::<OpportunityStage>("opp_stage"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct OppStageInsertCallbackId(__sdk::CallbackId);
pub struct OppStageDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for OppStageTableHandle<'ctx> {
    type Row = OpportunityStage;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = OpportunityStage> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = OppStageInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> OppStageInsertCallbackId {
        OppStageInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: OppStageInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = OppStageDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> OppStageDeleteCallbackId {
        OppStageDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: OppStageDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct OppStageUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for OppStageTableHandle<'ctx> {
    type UpdateCallbackId = OppStageUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> OppStageUpdateCallbackId {
        OppStageUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: OppStageUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `opp_stage`,
/// which allows point queries on the field of the same name
/// via the [`OppStageIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.opp_stage().id().find(...)`.
pub struct OppStageIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<OpportunityStage, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> OppStageTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `opp_stage`.
    pub fn id(&self) -> OppStageIdUnique<'ctx> {
        OppStageIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> OppStageIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<OpportunityStage> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<OpportunityStage>("opp_stage");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<OpportunityStage>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<OpportunityStage>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `OpportunityStage`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait opp_stageQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `OpportunityStage`.
    fn opp_stage(&self) -> __sdk::__query_builder::Table<OpportunityStage>;
}

impl opp_stageQueryTableAccess for __sdk::QueryTableAccessor {
    fn opp_stage(&self) -> __sdk::__query_builder::Table<OpportunityStage> {
        __sdk::__query_builder::Table::new("opp_stage")
    }
}
