// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct OrgSchemaMigration {
    pub id: u64,
    pub organization_id: u64,
    pub version: u64,
    pub name: String,
    pub applied_at: __sdk::Timestamp,
    pub applied_by: __sdk::Identity,
}

impl __sdk::InModule for OrgSchemaMigration {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `OrgSchemaMigration`.
///
/// Provides typed access to columns for query building.
pub struct OrgSchemaMigrationCols {
    pub id: __sdk::__query_builder::Col<OrgSchemaMigration, u64>,
    pub organization_id: __sdk::__query_builder::Col<OrgSchemaMigration, u64>,
    pub version: __sdk::__query_builder::Col<OrgSchemaMigration, u64>,
    pub name: __sdk::__query_builder::Col<OrgSchemaMigration, String>,
    pub applied_at: __sdk::__query_builder::Col<OrgSchemaMigration, __sdk::Timestamp>,
    pub applied_by: __sdk::__query_builder::Col<OrgSchemaMigration, __sdk::Identity>,
}

impl __sdk::__query_builder::HasCols for OrgSchemaMigration {
    type Cols = OrgSchemaMigrationCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        OrgSchemaMigrationCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            version: __sdk::__query_builder::Col::new(table_name, "version"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            applied_at: __sdk::__query_builder::Col::new(table_name, "applied_at"),
            applied_by: __sdk::__query_builder::Col::new(table_name, "applied_by"),
        }
    }
}

/// Indexed column accessor struct for the table `OrgSchemaMigration`.
///
/// Provides typed access to indexed columns for query building.
pub struct OrgSchemaMigrationIxCols {
    pub id: __sdk::__query_builder::IxCol<OrgSchemaMigration, u64>,
    pub organization_id: __sdk::__query_builder::IxCol<OrgSchemaMigration, u64>,
}

impl __sdk::__query_builder::HasIxCols for OrgSchemaMigration {
    type IxCols = OrgSchemaMigrationIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        OrgSchemaMigrationIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            organization_id: __sdk::__query_builder::IxCol::new(table_name, "organization_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for OrgSchemaMigration {}
