// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::payment_reversal_type::PaymentReversal;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `payment_reversal`.
///
/// Obtain a handle from the [`PaymentReversalTableAccess::payment_reversal`] method on [`super::RemoteTables`],
/// like `ctx.db.payment_reversal()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.payment_reversal().on_insert(...)`.
pub struct PaymentReversalTableHandle<'ctx> {
    imp: __sdk::TableHandle<PaymentReversal>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `payment_reversal`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PaymentReversalTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PaymentReversalTableHandle`], which mediates access to the table `payment_reversal`.
    fn payment_reversal(&self) -> PaymentReversalTableHandle<'_>;
}

impl PaymentReversalTableAccess for super::RemoteTables {
    fn payment_reversal(&self) -> PaymentReversalTableHandle<'_> {
        PaymentReversalTableHandle {
            imp: self.imp.get_table::<PaymentReversal>("payment_reversal"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PaymentReversalInsertCallbackId(__sdk::CallbackId);
pub struct PaymentReversalDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PaymentReversalTableHandle<'ctx> {
    type Row = PaymentReversal;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PaymentReversal> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PaymentReversalInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PaymentReversalInsertCallbackId {
        PaymentReversalInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PaymentReversalInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PaymentReversalDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PaymentReversalDeleteCallbackId {
        PaymentReversalDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PaymentReversalDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PaymentReversalUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PaymentReversalTableHandle<'ctx> {
    type UpdateCallbackId = PaymentReversalUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PaymentReversalUpdateCallbackId {
        PaymentReversalUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PaymentReversalUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `payment_reversal`,
/// which allows point queries on the field of the same name
/// via the [`PaymentReversalIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.payment_reversal().id().find(...)`.
pub struct PaymentReversalIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PaymentReversal, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PaymentReversalTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `payment_reversal`.
    pub fn id(&self) -> PaymentReversalIdUnique<'ctx> {
        PaymentReversalIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PaymentReversalIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PaymentReversal> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PaymentReversal>("payment_reversal");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PaymentReversal>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PaymentReversal>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PaymentReversal`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait payment_reversalQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PaymentReversal`.
    fn payment_reversal(&self) -> __sdk::__query_builder::Table<PaymentReversal>;
}

impl payment_reversalQueryTableAccess for __sdk::QueryTableAccessor {
    fn payment_reversal(&self) -> __sdk::__query_builder::Table<PaymentReversal> {
        __sdk::__query_builder::Table::new("payment_reversal")
    }
}
