// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::pos_loyalty_program_type::PosLoyaltyProgram;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `pos_loyalty_program`.
///
/// Obtain a handle from the [`PosLoyaltyProgramTableAccess::pos_loyalty_program`] method on [`super::RemoteTables`],
/// like `ctx.db.pos_loyalty_program()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.pos_loyalty_program().on_insert(...)`.
pub struct PosLoyaltyProgramTableHandle<'ctx> {
    imp: __sdk::TableHandle<PosLoyaltyProgram>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `pos_loyalty_program`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PosLoyaltyProgramTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PosLoyaltyProgramTableHandle`], which mediates access to the table `pos_loyalty_program`.
    fn pos_loyalty_program(&self) -> PosLoyaltyProgramTableHandle<'_>;
}

impl PosLoyaltyProgramTableAccess for super::RemoteTables {
    fn pos_loyalty_program(&self) -> PosLoyaltyProgramTableHandle<'_> {
        PosLoyaltyProgramTableHandle {
            imp: self
                .imp
                .get_table::<PosLoyaltyProgram>("pos_loyalty_program"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PosLoyaltyProgramInsertCallbackId(__sdk::CallbackId);
pub struct PosLoyaltyProgramDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PosLoyaltyProgramTableHandle<'ctx> {
    type Row = PosLoyaltyProgram;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PosLoyaltyProgram> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PosLoyaltyProgramInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PosLoyaltyProgramInsertCallbackId {
        PosLoyaltyProgramInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PosLoyaltyProgramInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PosLoyaltyProgramDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PosLoyaltyProgramDeleteCallbackId {
        PosLoyaltyProgramDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PosLoyaltyProgramDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PosLoyaltyProgramUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PosLoyaltyProgramTableHandle<'ctx> {
    type UpdateCallbackId = PosLoyaltyProgramUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PosLoyaltyProgramUpdateCallbackId {
        PosLoyaltyProgramUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PosLoyaltyProgramUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `pos_loyalty_program`,
/// which allows point queries on the field of the same name
/// via the [`PosLoyaltyProgramIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.pos_loyalty_program().id().find(...)`.
pub struct PosLoyaltyProgramIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PosLoyaltyProgram, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PosLoyaltyProgramTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `pos_loyalty_program`.
    pub fn id(&self) -> PosLoyaltyProgramIdUnique<'ctx> {
        PosLoyaltyProgramIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PosLoyaltyProgramIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PosLoyaltyProgram> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PosLoyaltyProgram>("pos_loyalty_program");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PosLoyaltyProgram>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PosLoyaltyProgram>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PosLoyaltyProgram`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait pos_loyalty_programQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PosLoyaltyProgram`.
    fn pos_loyalty_program(&self) -> __sdk::__query_builder::Table<PosLoyaltyProgram>;
}

impl pos_loyalty_programQueryTableAccess for __sdk::QueryTableAccessor {
    fn pos_loyalty_program(&self) -> __sdk::__query_builder::Table<PosLoyaltyProgram> {
        __sdk::__query_builder::Table::new("pos_loyalty_program")
    }
}
