// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::pos_order_state_type::PosOrderState;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PosOrder {
    pub id: u64,
    pub organization_id: u64,
    pub uid: String,
    pub ticket_number: Option<String>,
    pub session_id: u64,
    pub config_id: u64,
    pub state: PosOrderState,
    pub user_id: __sdk::Identity,
    pub amount_paid: f64,
    pub amount_return: f64,
    pub amount_tax: f64,
    pub amount_total: f64,
    pub amount_discount: f64,
    pub amount_delivery: f64,
    pub amount_subtotal: f64,
    pub company_id: u64,
    pub pricelist_id: u64,
    pub partner_id: Option<u64>,
    pub sequence_number: u32,
    pub loyalty_points: f64,
    pub to_invoice: bool,
    pub is_tipped: bool,
    pub tip_amount: f64,
    pub access_token: Option<String>,
    pub lines: Vec<u64>,
    pub statement_ids: Vec<u64>,
    pub pos_reference: Option<String>,
    pub sale_journal: u64,
    pub account_move: Option<u64>,
    pub picking_id: Option<u64>,
    pub picking_type_id: Option<u64>,
    pub location_id: u64,
    pub note: Option<String>,
    pub nb_print: u32,
    pub pos_name: Option<String>,
    pub pos_version: Option<String>,
    pub pos_session_version: Option<String>,
    pub crm_team_id: Option<u64>,
    pub procurement_group_id: Option<u64>,
    pub margin: f64,
    pub margin_percent: f64,
    pub is_partially_paid: bool,
    pub shipping_date: Option<__sdk::Timestamp>,
    pub last_order_preparation_change: Option<String>,
    pub date_order: __sdk::Timestamp,
    pub create_uid: __sdk::Identity,
    pub create_date: __sdk::Timestamp,
    pub write_uid: __sdk::Identity,
    pub write_date: __sdk::Timestamp,
    pub metadata: Option<String>,
    pub cold_eligible_at: Option<__sdk::Timestamp>,
    pub archive_version: u64,
}

impl __sdk::InModule for PosOrder {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PosOrder`.
///
/// Provides typed access to columns for query building.
pub struct PosOrderCols {
    pub id: __sdk::__query_builder::Col<PosOrder, u64>,
    pub organization_id: __sdk::__query_builder::Col<PosOrder, u64>,
    pub uid: __sdk::__query_builder::Col<PosOrder, String>,
    pub ticket_number: __sdk::__query_builder::Col<PosOrder, Option<String>>,
    pub session_id: __sdk::__query_builder::Col<PosOrder, u64>,
    pub config_id: __sdk::__query_builder::Col<PosOrder, u64>,
    pub state: __sdk::__query_builder::Col<PosOrder, PosOrderState>,
    pub user_id: __sdk::__query_builder::Col<PosOrder, __sdk::Identity>,
    pub amount_paid: __sdk::__query_builder::Col<PosOrder, f64>,
    pub amount_return: __sdk::__query_builder::Col<PosOrder, f64>,
    pub amount_tax: __sdk::__query_builder::Col<PosOrder, f64>,
    pub amount_total: __sdk::__query_builder::Col<PosOrder, f64>,
    pub amount_discount: __sdk::__query_builder::Col<PosOrder, f64>,
    pub amount_delivery: __sdk::__query_builder::Col<PosOrder, f64>,
    pub amount_subtotal: __sdk::__query_builder::Col<PosOrder, f64>,
    pub company_id: __sdk::__query_builder::Col<PosOrder, u64>,
    pub pricelist_id: __sdk::__query_builder::Col<PosOrder, u64>,
    pub partner_id: __sdk::__query_builder::Col<PosOrder, Option<u64>>,
    pub sequence_number: __sdk::__query_builder::Col<PosOrder, u32>,
    pub loyalty_points: __sdk::__query_builder::Col<PosOrder, f64>,
    pub to_invoice: __sdk::__query_builder::Col<PosOrder, bool>,
    pub is_tipped: __sdk::__query_builder::Col<PosOrder, bool>,
    pub tip_amount: __sdk::__query_builder::Col<PosOrder, f64>,
    pub access_token: __sdk::__query_builder::Col<PosOrder, Option<String>>,
    pub lines: __sdk::__query_builder::Col<PosOrder, Vec<u64>>,
    pub statement_ids: __sdk::__query_builder::Col<PosOrder, Vec<u64>>,
    pub pos_reference: __sdk::__query_builder::Col<PosOrder, Option<String>>,
    pub sale_journal: __sdk::__query_builder::Col<PosOrder, u64>,
    pub account_move: __sdk::__query_builder::Col<PosOrder, Option<u64>>,
    pub picking_id: __sdk::__query_builder::Col<PosOrder, Option<u64>>,
    pub picking_type_id: __sdk::__query_builder::Col<PosOrder, Option<u64>>,
    pub location_id: __sdk::__query_builder::Col<PosOrder, u64>,
    pub note: __sdk::__query_builder::Col<PosOrder, Option<String>>,
    pub nb_print: __sdk::__query_builder::Col<PosOrder, u32>,
    pub pos_name: __sdk::__query_builder::Col<PosOrder, Option<String>>,
    pub pos_version: __sdk::__query_builder::Col<PosOrder, Option<String>>,
    pub pos_session_version: __sdk::__query_builder::Col<PosOrder, Option<String>>,
    pub crm_team_id: __sdk::__query_builder::Col<PosOrder, Option<u64>>,
    pub procurement_group_id: __sdk::__query_builder::Col<PosOrder, Option<u64>>,
    pub margin: __sdk::__query_builder::Col<PosOrder, f64>,
    pub margin_percent: __sdk::__query_builder::Col<PosOrder, f64>,
    pub is_partially_paid: __sdk::__query_builder::Col<PosOrder, bool>,
    pub shipping_date: __sdk::__query_builder::Col<PosOrder, Option<__sdk::Timestamp>>,
    pub last_order_preparation_change: __sdk::__query_builder::Col<PosOrder, Option<String>>,
    pub date_order: __sdk::__query_builder::Col<PosOrder, __sdk::Timestamp>,
    pub create_uid: __sdk::__query_builder::Col<PosOrder, __sdk::Identity>,
    pub create_date: __sdk::__query_builder::Col<PosOrder, __sdk::Timestamp>,
    pub write_uid: __sdk::__query_builder::Col<PosOrder, __sdk::Identity>,
    pub write_date: __sdk::__query_builder::Col<PosOrder, __sdk::Timestamp>,
    pub metadata: __sdk::__query_builder::Col<PosOrder, Option<String>>,
    pub cold_eligible_at: __sdk::__query_builder::Col<PosOrder, Option<__sdk::Timestamp>>,
    pub archive_version: __sdk::__query_builder::Col<PosOrder, u64>,
}

impl __sdk::__query_builder::HasCols for PosOrder {
    type Cols = PosOrderCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PosOrderCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            uid: __sdk::__query_builder::Col::new(table_name, "uid"),
            ticket_number: __sdk::__query_builder::Col::new(table_name, "ticket_number"),
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            config_id: __sdk::__query_builder::Col::new(table_name, "config_id"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
            amount_paid: __sdk::__query_builder::Col::new(table_name, "amount_paid"),
            amount_return: __sdk::__query_builder::Col::new(table_name, "amount_return"),
            amount_tax: __sdk::__query_builder::Col::new(table_name, "amount_tax"),
            amount_total: __sdk::__query_builder::Col::new(table_name, "amount_total"),
            amount_discount: __sdk::__query_builder::Col::new(table_name, "amount_discount"),
            amount_delivery: __sdk::__query_builder::Col::new(table_name, "amount_delivery"),
            amount_subtotal: __sdk::__query_builder::Col::new(table_name, "amount_subtotal"),
            company_id: __sdk::__query_builder::Col::new(table_name, "company_id"),
            pricelist_id: __sdk::__query_builder::Col::new(table_name, "pricelist_id"),
            partner_id: __sdk::__query_builder::Col::new(table_name, "partner_id"),
            sequence_number: __sdk::__query_builder::Col::new(table_name, "sequence_number"),
            loyalty_points: __sdk::__query_builder::Col::new(table_name, "loyalty_points"),
            to_invoice: __sdk::__query_builder::Col::new(table_name, "to_invoice"),
            is_tipped: __sdk::__query_builder::Col::new(table_name, "is_tipped"),
            tip_amount: __sdk::__query_builder::Col::new(table_name, "tip_amount"),
            access_token: __sdk::__query_builder::Col::new(table_name, "access_token"),
            lines: __sdk::__query_builder::Col::new(table_name, "lines"),
            statement_ids: __sdk::__query_builder::Col::new(table_name, "statement_ids"),
            pos_reference: __sdk::__query_builder::Col::new(table_name, "pos_reference"),
            sale_journal: __sdk::__query_builder::Col::new(table_name, "sale_journal"),
            account_move: __sdk::__query_builder::Col::new(table_name, "account_move"),
            picking_id: __sdk::__query_builder::Col::new(table_name, "picking_id"),
            picking_type_id: __sdk::__query_builder::Col::new(table_name, "picking_type_id"),
            location_id: __sdk::__query_builder::Col::new(table_name, "location_id"),
            note: __sdk::__query_builder::Col::new(table_name, "note"),
            nb_print: __sdk::__query_builder::Col::new(table_name, "nb_print"),
            pos_name: __sdk::__query_builder::Col::new(table_name, "pos_name"),
            pos_version: __sdk::__query_builder::Col::new(table_name, "pos_version"),
            pos_session_version: __sdk::__query_builder::Col::new(
                table_name,
                "pos_session_version",
            ),
            crm_team_id: __sdk::__query_builder::Col::new(table_name, "crm_team_id"),
            procurement_group_id: __sdk::__query_builder::Col::new(
                table_name,
                "procurement_group_id",
            ),
            margin: __sdk::__query_builder::Col::new(table_name, "margin"),
            margin_percent: __sdk::__query_builder::Col::new(table_name, "margin_percent"),
            is_partially_paid: __sdk::__query_builder::Col::new(table_name, "is_partially_paid"),
            shipping_date: __sdk::__query_builder::Col::new(table_name, "shipping_date"),
            last_order_preparation_change: __sdk::__query_builder::Col::new(
                table_name,
                "last_order_preparation_change",
            ),
            date_order: __sdk::__query_builder::Col::new(table_name, "date_order"),
            create_uid: __sdk::__query_builder::Col::new(table_name, "create_uid"),
            create_date: __sdk::__query_builder::Col::new(table_name, "create_date"),
            write_uid: __sdk::__query_builder::Col::new(table_name, "write_uid"),
            write_date: __sdk::__query_builder::Col::new(table_name, "write_date"),
            metadata: __sdk::__query_builder::Col::new(table_name, "metadata"),
            cold_eligible_at: __sdk::__query_builder::Col::new(table_name, "cold_eligible_at"),
            archive_version: __sdk::__query_builder::Col::new(table_name, "archive_version"),
        }
    }
}

/// Indexed column accessor struct for the table `PosOrder`.
///
/// Provides typed access to indexed columns for query building.
pub struct PosOrderIxCols {
    pub id: __sdk::__query_builder::IxCol<PosOrder, u64>,
    pub organization_id: __sdk::__query_builder::IxCol<PosOrder, u64>,
    pub partner_id: __sdk::__query_builder::IxCol<PosOrder, Option<u64>>,
    pub session_id: __sdk::__query_builder::IxCol<PosOrder, u64>,
}

impl __sdk::__query_builder::HasIxCols for PosOrder {
    type IxCols = PosOrderIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PosOrderIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            organization_id: __sdk::__query_builder::IxCol::new(table_name, "organization_id"),
            partner_id: __sdk::__query_builder::IxCol::new(table_name, "partner_id"),
            session_id: __sdk::__query_builder::IxCol::new(table_name, "session_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PosOrder {}
