// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::payment_status_type::PaymentStatus;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PosPayment {
    pub id: u64,
    pub order_id: u64,
    pub payment_method_id: u64,
    pub session_id: u64,
    pub company_id: u64,
    pub currency_id: u64,
    pub amount: f64,
    pub payment_status: PaymentStatus,
    pub payment_date: __sdk::Timestamp,
    pub ticket: Option<String>,
    pub transaction_id: Option<String>,
    pub card_type: Option<String>,
    pub cardholder_name: Option<String>,
    pub card_number: Option<String>,
    pub is_change: bool,
    pub name: String,
    pub create_uid: __sdk::Identity,
    pub create_date: __sdk::Timestamp,
    pub write_uid: __sdk::Identity,
    pub write_date: __sdk::Timestamp,
    pub metadata: Option<String>,
}

impl __sdk::InModule for PosPayment {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PosPayment`.
///
/// Provides typed access to columns for query building.
pub struct PosPaymentCols {
    pub id: __sdk::__query_builder::Col<PosPayment, u64>,
    pub order_id: __sdk::__query_builder::Col<PosPayment, u64>,
    pub payment_method_id: __sdk::__query_builder::Col<PosPayment, u64>,
    pub session_id: __sdk::__query_builder::Col<PosPayment, u64>,
    pub company_id: __sdk::__query_builder::Col<PosPayment, u64>,
    pub currency_id: __sdk::__query_builder::Col<PosPayment, u64>,
    pub amount: __sdk::__query_builder::Col<PosPayment, f64>,
    pub payment_status: __sdk::__query_builder::Col<PosPayment, PaymentStatus>,
    pub payment_date: __sdk::__query_builder::Col<PosPayment, __sdk::Timestamp>,
    pub ticket: __sdk::__query_builder::Col<PosPayment, Option<String>>,
    pub transaction_id: __sdk::__query_builder::Col<PosPayment, Option<String>>,
    pub card_type: __sdk::__query_builder::Col<PosPayment, Option<String>>,
    pub cardholder_name: __sdk::__query_builder::Col<PosPayment, Option<String>>,
    pub card_number: __sdk::__query_builder::Col<PosPayment, Option<String>>,
    pub is_change: __sdk::__query_builder::Col<PosPayment, bool>,
    pub name: __sdk::__query_builder::Col<PosPayment, String>,
    pub create_uid: __sdk::__query_builder::Col<PosPayment, __sdk::Identity>,
    pub create_date: __sdk::__query_builder::Col<PosPayment, __sdk::Timestamp>,
    pub write_uid: __sdk::__query_builder::Col<PosPayment, __sdk::Identity>,
    pub write_date: __sdk::__query_builder::Col<PosPayment, __sdk::Timestamp>,
    pub metadata: __sdk::__query_builder::Col<PosPayment, Option<String>>,
}

impl __sdk::__query_builder::HasCols for PosPayment {
    type Cols = PosPaymentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PosPaymentCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            order_id: __sdk::__query_builder::Col::new(table_name, "order_id"),
            payment_method_id: __sdk::__query_builder::Col::new(table_name, "payment_method_id"),
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            company_id: __sdk::__query_builder::Col::new(table_name, "company_id"),
            currency_id: __sdk::__query_builder::Col::new(table_name, "currency_id"),
            amount: __sdk::__query_builder::Col::new(table_name, "amount"),
            payment_status: __sdk::__query_builder::Col::new(table_name, "payment_status"),
            payment_date: __sdk::__query_builder::Col::new(table_name, "payment_date"),
            ticket: __sdk::__query_builder::Col::new(table_name, "ticket"),
            transaction_id: __sdk::__query_builder::Col::new(table_name, "transaction_id"),
            card_type: __sdk::__query_builder::Col::new(table_name, "card_type"),
            cardholder_name: __sdk::__query_builder::Col::new(table_name, "cardholder_name"),
            card_number: __sdk::__query_builder::Col::new(table_name, "card_number"),
            is_change: __sdk::__query_builder::Col::new(table_name, "is_change"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            create_uid: __sdk::__query_builder::Col::new(table_name, "create_uid"),
            create_date: __sdk::__query_builder::Col::new(table_name, "create_date"),
            write_uid: __sdk::__query_builder::Col::new(table_name, "write_uid"),
            write_date: __sdk::__query_builder::Col::new(table_name, "write_date"),
            metadata: __sdk::__query_builder::Col::new(table_name, "metadata"),
        }
    }
}

/// Indexed column accessor struct for the table `PosPayment`.
///
/// Provides typed access to indexed columns for query building.
pub struct PosPaymentIxCols {
    pub id: __sdk::__query_builder::IxCol<PosPayment, u64>,
    pub session_id: __sdk::__query_builder::IxCol<PosPayment, u64>,
}

impl __sdk::__query_builder::HasIxCols for PosPayment {
    type IxCols = PosPaymentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PosPaymentIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            session_id: __sdk::__query_builder::IxCol::new(table_name, "session_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PosPayment {}
