// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ProductCategory {
    pub id: u64,
    pub organization_id: u64,
    pub name: String,
    pub parent_id: Option<u64>,
    pub sequence: u32,
    pub deleted_at: Option<__sdk::Timestamp>,
    pub company_id: Option<u64>,
    pub create_uid: __sdk::Identity,
    pub create_date: __sdk::Timestamp,
    pub write_uid: __sdk::Identity,
    pub write_date: __sdk::Timestamp,
    pub metadata: Option<String>,
}

impl __sdk::InModule for ProductCategory {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ProductCategory`.
///
/// Provides typed access to columns for query building.
pub struct ProductCategoryCols {
    pub id: __sdk::__query_builder::Col<ProductCategory, u64>,
    pub organization_id: __sdk::__query_builder::Col<ProductCategory, u64>,
    pub name: __sdk::__query_builder::Col<ProductCategory, String>,
    pub parent_id: __sdk::__query_builder::Col<ProductCategory, Option<u64>>,
    pub sequence: __sdk::__query_builder::Col<ProductCategory, u32>,
    pub deleted_at: __sdk::__query_builder::Col<ProductCategory, Option<__sdk::Timestamp>>,
    pub company_id: __sdk::__query_builder::Col<ProductCategory, Option<u64>>,
    pub create_uid: __sdk::__query_builder::Col<ProductCategory, __sdk::Identity>,
    pub create_date: __sdk::__query_builder::Col<ProductCategory, __sdk::Timestamp>,
    pub write_uid: __sdk::__query_builder::Col<ProductCategory, __sdk::Identity>,
    pub write_date: __sdk::__query_builder::Col<ProductCategory, __sdk::Timestamp>,
    pub metadata: __sdk::__query_builder::Col<ProductCategory, Option<String>>,
}

impl __sdk::__query_builder::HasCols for ProductCategory {
    type Cols = ProductCategoryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ProductCategoryCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            parent_id: __sdk::__query_builder::Col::new(table_name, "parent_id"),
            sequence: __sdk::__query_builder::Col::new(table_name, "sequence"),
            deleted_at: __sdk::__query_builder::Col::new(table_name, "deleted_at"),
            company_id: __sdk::__query_builder::Col::new(table_name, "company_id"),
            create_uid: __sdk::__query_builder::Col::new(table_name, "create_uid"),
            create_date: __sdk::__query_builder::Col::new(table_name, "create_date"),
            write_uid: __sdk::__query_builder::Col::new(table_name, "write_uid"),
            write_date: __sdk::__query_builder::Col::new(table_name, "write_date"),
            metadata: __sdk::__query_builder::Col::new(table_name, "metadata"),
        }
    }
}

/// Indexed column accessor struct for the table `ProductCategory`.
///
/// Provides typed access to indexed columns for query building.
pub struct ProductCategoryIxCols {
    pub id: __sdk::__query_builder::IxCol<ProductCategory, u64>,
    pub name: __sdk::__query_builder::IxCol<ProductCategory, String>,
    pub organization_id: __sdk::__query_builder::IxCol<ProductCategory, u64>,
    pub parent_id: __sdk::__query_builder::IxCol<ProductCategory, Option<u64>>,
    pub sequence: __sdk::__query_builder::IxCol<ProductCategory, u32>,
}

impl __sdk::__query_builder::HasIxCols for ProductCategory {
    type IxCols = ProductCategoryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ProductCategoryIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            name: __sdk::__query_builder::IxCol::new(table_name, "name"),
            organization_id: __sdk::__query_builder::IxCol::new(table_name, "organization_id"),
            parent_id: __sdk::__query_builder::IxCol::new(table_name, "parent_id"),
            sequence: __sdk::__query_builder::IxCol::new(table_name, "sequence"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ProductCategory {}
