// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ProjectSubcontractorCost {
    pub id: u64,
    pub organization_id: u64,
    pub company_id: u64,
    pub project_id: u64,
    pub purchase_order_id: Option<u64>,
    pub purchase_order_line_id: Option<u64>,
    pub vendor_bill_move_id: Option<u64>,
    pub vendor_bill_line_id: Option<u64>,
    pub partner_id: Option<u64>,
    pub amount: f64,
    pub currency_id: u64,
    pub name: Option<String>,
    pub active: bool,
    pub create_uid: __sdk::Identity,
    pub create_date: __sdk::Timestamp,
    pub write_uid: __sdk::Identity,
    pub write_date: __sdk::Timestamp,
    pub metadata: Option<String>,
}

impl __sdk::InModule for ProjectSubcontractorCost {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ProjectSubcontractorCost`.
///
/// Provides typed access to columns for query building.
pub struct ProjectSubcontractorCostCols {
    pub id: __sdk::__query_builder::Col<ProjectSubcontractorCost, u64>,
    pub organization_id: __sdk::__query_builder::Col<ProjectSubcontractorCost, u64>,
    pub company_id: __sdk::__query_builder::Col<ProjectSubcontractorCost, u64>,
    pub project_id: __sdk::__query_builder::Col<ProjectSubcontractorCost, u64>,
    pub purchase_order_id: __sdk::__query_builder::Col<ProjectSubcontractorCost, Option<u64>>,
    pub purchase_order_line_id: __sdk::__query_builder::Col<ProjectSubcontractorCost, Option<u64>>,
    pub vendor_bill_move_id: __sdk::__query_builder::Col<ProjectSubcontractorCost, Option<u64>>,
    pub vendor_bill_line_id: __sdk::__query_builder::Col<ProjectSubcontractorCost, Option<u64>>,
    pub partner_id: __sdk::__query_builder::Col<ProjectSubcontractorCost, Option<u64>>,
    pub amount: __sdk::__query_builder::Col<ProjectSubcontractorCost, f64>,
    pub currency_id: __sdk::__query_builder::Col<ProjectSubcontractorCost, u64>,
    pub name: __sdk::__query_builder::Col<ProjectSubcontractorCost, Option<String>>,
    pub active: __sdk::__query_builder::Col<ProjectSubcontractorCost, bool>,
    pub create_uid: __sdk::__query_builder::Col<ProjectSubcontractorCost, __sdk::Identity>,
    pub create_date: __sdk::__query_builder::Col<ProjectSubcontractorCost, __sdk::Timestamp>,
    pub write_uid: __sdk::__query_builder::Col<ProjectSubcontractorCost, __sdk::Identity>,
    pub write_date: __sdk::__query_builder::Col<ProjectSubcontractorCost, __sdk::Timestamp>,
    pub metadata: __sdk::__query_builder::Col<ProjectSubcontractorCost, Option<String>>,
}

impl __sdk::__query_builder::HasCols for ProjectSubcontractorCost {
    type Cols = ProjectSubcontractorCostCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ProjectSubcontractorCostCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            company_id: __sdk::__query_builder::Col::new(table_name, "company_id"),
            project_id: __sdk::__query_builder::Col::new(table_name, "project_id"),
            purchase_order_id: __sdk::__query_builder::Col::new(table_name, "purchase_order_id"),
            purchase_order_line_id: __sdk::__query_builder::Col::new(
                table_name,
                "purchase_order_line_id",
            ),
            vendor_bill_move_id: __sdk::__query_builder::Col::new(
                table_name,
                "vendor_bill_move_id",
            ),
            vendor_bill_line_id: __sdk::__query_builder::Col::new(
                table_name,
                "vendor_bill_line_id",
            ),
            partner_id: __sdk::__query_builder::Col::new(table_name, "partner_id"),
            amount: __sdk::__query_builder::Col::new(table_name, "amount"),
            currency_id: __sdk::__query_builder::Col::new(table_name, "currency_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            active: __sdk::__query_builder::Col::new(table_name, "active"),
            create_uid: __sdk::__query_builder::Col::new(table_name, "create_uid"),
            create_date: __sdk::__query_builder::Col::new(table_name, "create_date"),
            write_uid: __sdk::__query_builder::Col::new(table_name, "write_uid"),
            write_date: __sdk::__query_builder::Col::new(table_name, "write_date"),
            metadata: __sdk::__query_builder::Col::new(table_name, "metadata"),
        }
    }
}

/// Indexed column accessor struct for the table `ProjectSubcontractorCost`.
///
/// Provides typed access to indexed columns for query building.
pub struct ProjectSubcontractorCostIxCols {
    pub company_id: __sdk::__query_builder::IxCol<ProjectSubcontractorCost, u64>,
    pub id: __sdk::__query_builder::IxCol<ProjectSubcontractorCost, u64>,
    pub organization_id: __sdk::__query_builder::IxCol<ProjectSubcontractorCost, u64>,
    pub project_id: __sdk::__query_builder::IxCol<ProjectSubcontractorCost, u64>,
    pub purchase_order_line_id:
        __sdk::__query_builder::IxCol<ProjectSubcontractorCost, Option<u64>>,
}

impl __sdk::__query_builder::HasIxCols for ProjectSubcontractorCost {
    type IxCols = ProjectSubcontractorCostIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ProjectSubcontractorCostIxCols {
            company_id: __sdk::__query_builder::IxCol::new(table_name, "company_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            organization_id: __sdk::__query_builder::IxCol::new(table_name, "organization_id"),
            project_id: __sdk::__query_builder::IxCol::new(table_name, "project_id"),
            purchase_order_line_id: __sdk::__query_builder::IxCol::new(
                table_name,
                "purchase_order_line_id",
            ),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ProjectSubcontractorCost {}
