// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ProjectTimesheetApproval {
    pub id: u64,
    pub organization_id: u64,
    pub company_id: u64,
    pub timesheet_id: u64,
    pub actor: __sdk::Identity,
    pub decision: String,
    pub reason: Option<String>,
    pub hours: f64,
    pub sell_rate: f64,
    pub cost_rate: f64,
    pub currency_id: u64,
    pub decided_at: __sdk::Timestamp,
}

impl __sdk::InModule for ProjectTimesheetApproval {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ProjectTimesheetApproval`.
///
/// Provides typed access to columns for query building.
pub struct ProjectTimesheetApprovalCols {
    pub id: __sdk::__query_builder::Col<ProjectTimesheetApproval, u64>,
    pub organization_id: __sdk::__query_builder::Col<ProjectTimesheetApproval, u64>,
    pub company_id: __sdk::__query_builder::Col<ProjectTimesheetApproval, u64>,
    pub timesheet_id: __sdk::__query_builder::Col<ProjectTimesheetApproval, u64>,
    pub actor: __sdk::__query_builder::Col<ProjectTimesheetApproval, __sdk::Identity>,
    pub decision: __sdk::__query_builder::Col<ProjectTimesheetApproval, String>,
    pub reason: __sdk::__query_builder::Col<ProjectTimesheetApproval, Option<String>>,
    pub hours: __sdk::__query_builder::Col<ProjectTimesheetApproval, f64>,
    pub sell_rate: __sdk::__query_builder::Col<ProjectTimesheetApproval, f64>,
    pub cost_rate: __sdk::__query_builder::Col<ProjectTimesheetApproval, f64>,
    pub currency_id: __sdk::__query_builder::Col<ProjectTimesheetApproval, u64>,
    pub decided_at: __sdk::__query_builder::Col<ProjectTimesheetApproval, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for ProjectTimesheetApproval {
    type Cols = ProjectTimesheetApprovalCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ProjectTimesheetApprovalCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            company_id: __sdk::__query_builder::Col::new(table_name, "company_id"),
            timesheet_id: __sdk::__query_builder::Col::new(table_name, "timesheet_id"),
            actor: __sdk::__query_builder::Col::new(table_name, "actor"),
            decision: __sdk::__query_builder::Col::new(table_name, "decision"),
            reason: __sdk::__query_builder::Col::new(table_name, "reason"),
            hours: __sdk::__query_builder::Col::new(table_name, "hours"),
            sell_rate: __sdk::__query_builder::Col::new(table_name, "sell_rate"),
            cost_rate: __sdk::__query_builder::Col::new(table_name, "cost_rate"),
            currency_id: __sdk::__query_builder::Col::new(table_name, "currency_id"),
            decided_at: __sdk::__query_builder::Col::new(table_name, "decided_at"),
        }
    }
}

/// Indexed column accessor struct for the table `ProjectTimesheetApproval`.
///
/// Provides typed access to indexed columns for query building.
pub struct ProjectTimesheetApprovalIxCols {
    pub company_id: __sdk::__query_builder::IxCol<ProjectTimesheetApproval, u64>,
    pub id: __sdk::__query_builder::IxCol<ProjectTimesheetApproval, u64>,
    pub organization_id: __sdk::__query_builder::IxCol<ProjectTimesheetApproval, u64>,
    pub timesheet_id: __sdk::__query_builder::IxCol<ProjectTimesheetApproval, u64>,
}

impl __sdk::__query_builder::HasIxCols for ProjectTimesheetApproval {
    type IxCols = ProjectTimesheetApprovalIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ProjectTimesheetApprovalIxCols {
            company_id: __sdk::__query_builder::IxCol::new(table_name, "company_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            organization_id: __sdk::__query_builder::IxCol::new(table_name, "organization_id"),
            timesheet_id: __sdk::__query_builder::IxCol::new(table_name, "timesheet_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ProjectTimesheetApproval {}
