// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::project_task_stage_type::ProjectTaskStage;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `project_task_stage`.
///
/// Obtain a handle from the [`ProjectTaskStageTableAccess::project_task_stage`] method on [`super::RemoteTables`],
/// like `ctx.db.project_task_stage()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.project_task_stage().on_insert(...)`.
pub struct ProjectTaskStageTableHandle<'ctx> {
    imp: __sdk::TableHandle<ProjectTaskStage>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `project_task_stage`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ProjectTaskStageTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ProjectTaskStageTableHandle`], which mediates access to the table `project_task_stage`.
    fn project_task_stage(&self) -> ProjectTaskStageTableHandle<'_>;
}

impl ProjectTaskStageTableAccess for super::RemoteTables {
    fn project_task_stage(&self) -> ProjectTaskStageTableHandle<'_> {
        ProjectTaskStageTableHandle {
            imp: self.imp.get_table::<ProjectTaskStage>("project_task_stage"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ProjectTaskStageInsertCallbackId(__sdk::CallbackId);
pub struct ProjectTaskStageDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ProjectTaskStageTableHandle<'ctx> {
    type Row = ProjectTaskStage;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ProjectTaskStage> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ProjectTaskStageInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ProjectTaskStageInsertCallbackId {
        ProjectTaskStageInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ProjectTaskStageInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ProjectTaskStageDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ProjectTaskStageDeleteCallbackId {
        ProjectTaskStageDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ProjectTaskStageDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ProjectTaskStageUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ProjectTaskStageTableHandle<'ctx> {
    type UpdateCallbackId = ProjectTaskStageUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ProjectTaskStageUpdateCallbackId {
        ProjectTaskStageUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ProjectTaskStageUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `project_task_stage`,
/// which allows point queries on the field of the same name
/// via the [`ProjectTaskStageIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.project_task_stage().id().find(...)`.
pub struct ProjectTaskStageIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ProjectTaskStage, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ProjectTaskStageTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `project_task_stage`.
    pub fn id(&self) -> ProjectTaskStageIdUnique<'ctx> {
        ProjectTaskStageIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ProjectTaskStageIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ProjectTaskStage> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ProjectTaskStage>("project_task_stage");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ProjectTaskStage>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ProjectTaskStage>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ProjectTaskStage`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait project_task_stageQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ProjectTaskStage`.
    fn project_task_stage(&self) -> __sdk::__query_builder::Table<ProjectTaskStage>;
}

impl project_task_stageQueryTableAccess for __sdk::QueryTableAccessor {
    fn project_task_stage(&self) -> __sdk::__query_builder::Table<ProjectTaskStage> {
        __sdk::__query_builder::Table::new("project_task_stage")
    }
}
