// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ProposalLineItem {
    pub id: u64,
    pub organization_id: u64,
    pub proposal_id: u64,
    pub section_id: Option<u64>,
    pub product_id: u64,
    pub product_name: String,
    pub product_variant_id: Option<u64>,
    pub description: Option<String>,
    pub quantity: f64,
    pub price_unit: f64,
    pub subtotal: f64,
    pub discount: f64,
    pub sequence: u32,
    pub notes: Option<String>,
    pub create_uid: __sdk::Identity,
    pub create_date: __sdk::Timestamp,
    pub write_uid: __sdk::Identity,
    pub write_date: __sdk::Timestamp,
}

impl __sdk::InModule for ProposalLineItem {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ProposalLineItem`.
///
/// Provides typed access to columns for query building.
pub struct ProposalLineItemCols {
    pub id: __sdk::__query_builder::Col<ProposalLineItem, u64>,
    pub organization_id: __sdk::__query_builder::Col<ProposalLineItem, u64>,
    pub proposal_id: __sdk::__query_builder::Col<ProposalLineItem, u64>,
    pub section_id: __sdk::__query_builder::Col<ProposalLineItem, Option<u64>>,
    pub product_id: __sdk::__query_builder::Col<ProposalLineItem, u64>,
    pub product_name: __sdk::__query_builder::Col<ProposalLineItem, String>,
    pub product_variant_id: __sdk::__query_builder::Col<ProposalLineItem, Option<u64>>,
    pub description: __sdk::__query_builder::Col<ProposalLineItem, Option<String>>,
    pub quantity: __sdk::__query_builder::Col<ProposalLineItem, f64>,
    pub price_unit: __sdk::__query_builder::Col<ProposalLineItem, f64>,
    pub subtotal: __sdk::__query_builder::Col<ProposalLineItem, f64>,
    pub discount: __sdk::__query_builder::Col<ProposalLineItem, f64>,
    pub sequence: __sdk::__query_builder::Col<ProposalLineItem, u32>,
    pub notes: __sdk::__query_builder::Col<ProposalLineItem, Option<String>>,
    pub create_uid: __sdk::__query_builder::Col<ProposalLineItem, __sdk::Identity>,
    pub create_date: __sdk::__query_builder::Col<ProposalLineItem, __sdk::Timestamp>,
    pub write_uid: __sdk::__query_builder::Col<ProposalLineItem, __sdk::Identity>,
    pub write_date: __sdk::__query_builder::Col<ProposalLineItem, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for ProposalLineItem {
    type Cols = ProposalLineItemCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ProposalLineItemCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            proposal_id: __sdk::__query_builder::Col::new(table_name, "proposal_id"),
            section_id: __sdk::__query_builder::Col::new(table_name, "section_id"),
            product_id: __sdk::__query_builder::Col::new(table_name, "product_id"),
            product_name: __sdk::__query_builder::Col::new(table_name, "product_name"),
            product_variant_id: __sdk::__query_builder::Col::new(table_name, "product_variant_id"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
            quantity: __sdk::__query_builder::Col::new(table_name, "quantity"),
            price_unit: __sdk::__query_builder::Col::new(table_name, "price_unit"),
            subtotal: __sdk::__query_builder::Col::new(table_name, "subtotal"),
            discount: __sdk::__query_builder::Col::new(table_name, "discount"),
            sequence: __sdk::__query_builder::Col::new(table_name, "sequence"),
            notes: __sdk::__query_builder::Col::new(table_name, "notes"),
            create_uid: __sdk::__query_builder::Col::new(table_name, "create_uid"),
            create_date: __sdk::__query_builder::Col::new(table_name, "create_date"),
            write_uid: __sdk::__query_builder::Col::new(table_name, "write_uid"),
            write_date: __sdk::__query_builder::Col::new(table_name, "write_date"),
        }
    }
}

/// Indexed column accessor struct for the table `ProposalLineItem`.
///
/// Provides typed access to indexed columns for query building.
pub struct ProposalLineItemIxCols {
    pub id: __sdk::__query_builder::IxCol<ProposalLineItem, u64>,
    pub proposal_id: __sdk::__query_builder::IxCol<ProposalLineItem, u64>,
    pub section_id: __sdk::__query_builder::IxCol<ProposalLineItem, Option<u64>>,
}

impl __sdk::__query_builder::HasIxCols for ProposalLineItem {
    type IxCols = ProposalLineItemIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ProposalLineItemIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            proposal_id: __sdk::__query_builder::IxCol::new(table_name, "proposal_id"),
            section_id: __sdk::__query_builder::IxCol::new(table_name, "section_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ProposalLineItem {}
