// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::purchase_approval_delegate_type::PurchaseApprovalDelegate;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `purchase_approval_delegate`.
///
/// Obtain a handle from the [`PurchaseApprovalDelegateTableAccess::purchase_approval_delegate`] method on [`super::RemoteTables`],
/// like `ctx.db.purchase_approval_delegate()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.purchase_approval_delegate().on_insert(...)`.
pub struct PurchaseApprovalDelegateTableHandle<'ctx> {
    imp: __sdk::TableHandle<PurchaseApprovalDelegate>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `purchase_approval_delegate`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PurchaseApprovalDelegateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PurchaseApprovalDelegateTableHandle`], which mediates access to the table `purchase_approval_delegate`.
    fn purchase_approval_delegate(&self) -> PurchaseApprovalDelegateTableHandle<'_>;
}

impl PurchaseApprovalDelegateTableAccess for super::RemoteTables {
    fn purchase_approval_delegate(&self) -> PurchaseApprovalDelegateTableHandle<'_> {
        PurchaseApprovalDelegateTableHandle {
            imp: self
                .imp
                .get_table::<PurchaseApprovalDelegate>("purchase_approval_delegate"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PurchaseApprovalDelegateInsertCallbackId(__sdk::CallbackId);
pub struct PurchaseApprovalDelegateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PurchaseApprovalDelegateTableHandle<'ctx> {
    type Row = PurchaseApprovalDelegate;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PurchaseApprovalDelegate> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PurchaseApprovalDelegateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PurchaseApprovalDelegateInsertCallbackId {
        PurchaseApprovalDelegateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PurchaseApprovalDelegateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PurchaseApprovalDelegateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PurchaseApprovalDelegateDeleteCallbackId {
        PurchaseApprovalDelegateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PurchaseApprovalDelegateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PurchaseApprovalDelegateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PurchaseApprovalDelegateTableHandle<'ctx> {
    type UpdateCallbackId = PurchaseApprovalDelegateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PurchaseApprovalDelegateUpdateCallbackId {
        PurchaseApprovalDelegateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PurchaseApprovalDelegateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `purchase_approval_delegate`,
/// which allows point queries on the field of the same name
/// via the [`PurchaseApprovalDelegateIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.purchase_approval_delegate().id().find(...)`.
pub struct PurchaseApprovalDelegateIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PurchaseApprovalDelegate, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PurchaseApprovalDelegateTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `purchase_approval_delegate`.
    pub fn id(&self) -> PurchaseApprovalDelegateIdUnique<'ctx> {
        PurchaseApprovalDelegateIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PurchaseApprovalDelegateIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PurchaseApprovalDelegate> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<PurchaseApprovalDelegate>("purchase_approval_delegate");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PurchaseApprovalDelegate>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PurchaseApprovalDelegate>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PurchaseApprovalDelegate`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait purchase_approval_delegateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PurchaseApprovalDelegate`.
    fn purchase_approval_delegate(&self)
        -> __sdk::__query_builder::Table<PurchaseApprovalDelegate>;
}

impl purchase_approval_delegateQueryTableAccess for __sdk::QueryTableAccessor {
    fn purchase_approval_delegate(
        &self,
    ) -> __sdk::__query_builder::Table<PurchaseApprovalDelegate> {
        __sdk::__query_builder::Table::new("purchase_approval_delegate")
    }
}
