// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::line_state_type::LineState;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PurchaseOrderLine {
    pub id: u64,
    pub organization_id: u64,
    pub sequence: u32,
    pub product_qty: f64,
    pub product_uom_qty: f64,
    pub date_planned: Option<__sdk::Timestamp>,
    pub date_departure: Option<__sdk::Timestamp>,
    pub date_arrival: Option<__sdk::Timestamp>,
    pub product_uom: u64,
    pub product_id: u64,
    pub product_type: Option<String>,
    pub product_variant_id: Option<u64>,
    pub product_template_id: Option<u64>,
    pub price_unit: f64,
    pub price_subtotal: f64,
    pub price_total: f64,
    pub price_tax: f64,
    pub order_id: u64,
    pub account_analytic_id: Option<u64>,
    pub analytic_tag_ids: Vec<u64>,
    pub company_id: u64,
    pub state: LineState,
    pub invoice_lines: Vec<u64>,
    pub qty_invoiced: f64,
    pub qty_received_method: Vec<String>,
    pub qty_received: f64,
    pub qty_received_manual: f64,
    pub qty_to_invoice: f64,
    pub partner_id: u64,
    pub currency_id: u64,
    pub display_type: Option<String>,
    pub product_no_variant_attribute_value_ids: Vec<u64>,
    pub product_custom_attribute_value_ids: Vec<u64>,
    pub propagate_cancel: bool,
    pub sale_line_id: Option<u64>,
    pub sale_order_id: Option<u64>,
    pub move_dest_ids: Vec<u64>,
    pub move_ids: Vec<u64>,
    pub match_state: String,
    pub lot_id: Option<u64>,
    pub create_uid: __sdk::Identity,
    pub create_date: __sdk::Timestamp,
    pub write_uid: __sdk::Identity,
    pub write_date: __sdk::Timestamp,
    pub metadata: Option<String>,
}

impl __sdk::InModule for PurchaseOrderLine {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PurchaseOrderLine`.
///
/// Provides typed access to columns for query building.
pub struct PurchaseOrderLineCols {
    pub id: __sdk::__query_builder::Col<PurchaseOrderLine, u64>,
    pub organization_id: __sdk::__query_builder::Col<PurchaseOrderLine, u64>,
    pub sequence: __sdk::__query_builder::Col<PurchaseOrderLine, u32>,
    pub product_qty: __sdk::__query_builder::Col<PurchaseOrderLine, f64>,
    pub product_uom_qty: __sdk::__query_builder::Col<PurchaseOrderLine, f64>,
    pub date_planned: __sdk::__query_builder::Col<PurchaseOrderLine, Option<__sdk::Timestamp>>,
    pub date_departure: __sdk::__query_builder::Col<PurchaseOrderLine, Option<__sdk::Timestamp>>,
    pub date_arrival: __sdk::__query_builder::Col<PurchaseOrderLine, Option<__sdk::Timestamp>>,
    pub product_uom: __sdk::__query_builder::Col<PurchaseOrderLine, u64>,
    pub product_id: __sdk::__query_builder::Col<PurchaseOrderLine, u64>,
    pub product_type: __sdk::__query_builder::Col<PurchaseOrderLine, Option<String>>,
    pub product_variant_id: __sdk::__query_builder::Col<PurchaseOrderLine, Option<u64>>,
    pub product_template_id: __sdk::__query_builder::Col<PurchaseOrderLine, Option<u64>>,
    pub price_unit: __sdk::__query_builder::Col<PurchaseOrderLine, f64>,
    pub price_subtotal: __sdk::__query_builder::Col<PurchaseOrderLine, f64>,
    pub price_total: __sdk::__query_builder::Col<PurchaseOrderLine, f64>,
    pub price_tax: __sdk::__query_builder::Col<PurchaseOrderLine, f64>,
    pub order_id: __sdk::__query_builder::Col<PurchaseOrderLine, u64>,
    pub account_analytic_id: __sdk::__query_builder::Col<PurchaseOrderLine, Option<u64>>,
    pub analytic_tag_ids: __sdk::__query_builder::Col<PurchaseOrderLine, Vec<u64>>,
    pub company_id: __sdk::__query_builder::Col<PurchaseOrderLine, u64>,
    pub state: __sdk::__query_builder::Col<PurchaseOrderLine, LineState>,
    pub invoice_lines: __sdk::__query_builder::Col<PurchaseOrderLine, Vec<u64>>,
    pub qty_invoiced: __sdk::__query_builder::Col<PurchaseOrderLine, f64>,
    pub qty_received_method: __sdk::__query_builder::Col<PurchaseOrderLine, Vec<String>>,
    pub qty_received: __sdk::__query_builder::Col<PurchaseOrderLine, f64>,
    pub qty_received_manual: __sdk::__query_builder::Col<PurchaseOrderLine, f64>,
    pub qty_to_invoice: __sdk::__query_builder::Col<PurchaseOrderLine, f64>,
    pub partner_id: __sdk::__query_builder::Col<PurchaseOrderLine, u64>,
    pub currency_id: __sdk::__query_builder::Col<PurchaseOrderLine, u64>,
    pub display_type: __sdk::__query_builder::Col<PurchaseOrderLine, Option<String>>,
    pub product_no_variant_attribute_value_ids:
        __sdk::__query_builder::Col<PurchaseOrderLine, Vec<u64>>,
    pub product_custom_attribute_value_ids:
        __sdk::__query_builder::Col<PurchaseOrderLine, Vec<u64>>,
    pub propagate_cancel: __sdk::__query_builder::Col<PurchaseOrderLine, bool>,
    pub sale_line_id: __sdk::__query_builder::Col<PurchaseOrderLine, Option<u64>>,
    pub sale_order_id: __sdk::__query_builder::Col<PurchaseOrderLine, Option<u64>>,
    pub move_dest_ids: __sdk::__query_builder::Col<PurchaseOrderLine, Vec<u64>>,
    pub move_ids: __sdk::__query_builder::Col<PurchaseOrderLine, Vec<u64>>,
    pub match_state: __sdk::__query_builder::Col<PurchaseOrderLine, String>,
    pub lot_id: __sdk::__query_builder::Col<PurchaseOrderLine, Option<u64>>,
    pub create_uid: __sdk::__query_builder::Col<PurchaseOrderLine, __sdk::Identity>,
    pub create_date: __sdk::__query_builder::Col<PurchaseOrderLine, __sdk::Timestamp>,
    pub write_uid: __sdk::__query_builder::Col<PurchaseOrderLine, __sdk::Identity>,
    pub write_date: __sdk::__query_builder::Col<PurchaseOrderLine, __sdk::Timestamp>,
    pub metadata: __sdk::__query_builder::Col<PurchaseOrderLine, Option<String>>,
}

impl __sdk::__query_builder::HasCols for PurchaseOrderLine {
    type Cols = PurchaseOrderLineCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PurchaseOrderLineCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            sequence: __sdk::__query_builder::Col::new(table_name, "sequence"),
            product_qty: __sdk::__query_builder::Col::new(table_name, "product_qty"),
            product_uom_qty: __sdk::__query_builder::Col::new(table_name, "product_uom_qty"),
            date_planned: __sdk::__query_builder::Col::new(table_name, "date_planned"),
            date_departure: __sdk::__query_builder::Col::new(table_name, "date_departure"),
            date_arrival: __sdk::__query_builder::Col::new(table_name, "date_arrival"),
            product_uom: __sdk::__query_builder::Col::new(table_name, "product_uom"),
            product_id: __sdk::__query_builder::Col::new(table_name, "product_id"),
            product_type: __sdk::__query_builder::Col::new(table_name, "product_type"),
            product_variant_id: __sdk::__query_builder::Col::new(table_name, "product_variant_id"),
            product_template_id: __sdk::__query_builder::Col::new(
                table_name,
                "product_template_id",
            ),
            price_unit: __sdk::__query_builder::Col::new(table_name, "price_unit"),
            price_subtotal: __sdk::__query_builder::Col::new(table_name, "price_subtotal"),
            price_total: __sdk::__query_builder::Col::new(table_name, "price_total"),
            price_tax: __sdk::__query_builder::Col::new(table_name, "price_tax"),
            order_id: __sdk::__query_builder::Col::new(table_name, "order_id"),
            account_analytic_id: __sdk::__query_builder::Col::new(
                table_name,
                "account_analytic_id",
            ),
            analytic_tag_ids: __sdk::__query_builder::Col::new(table_name, "analytic_tag_ids"),
            company_id: __sdk::__query_builder::Col::new(table_name, "company_id"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
            invoice_lines: __sdk::__query_builder::Col::new(table_name, "invoice_lines"),
            qty_invoiced: __sdk::__query_builder::Col::new(table_name, "qty_invoiced"),
            qty_received_method: __sdk::__query_builder::Col::new(
                table_name,
                "qty_received_method",
            ),
            qty_received: __sdk::__query_builder::Col::new(table_name, "qty_received"),
            qty_received_manual: __sdk::__query_builder::Col::new(
                table_name,
                "qty_received_manual",
            ),
            qty_to_invoice: __sdk::__query_builder::Col::new(table_name, "qty_to_invoice"),
            partner_id: __sdk::__query_builder::Col::new(table_name, "partner_id"),
            currency_id: __sdk::__query_builder::Col::new(table_name, "currency_id"),
            display_type: __sdk::__query_builder::Col::new(table_name, "display_type"),
            product_no_variant_attribute_value_ids: __sdk::__query_builder::Col::new(
                table_name,
                "product_no_variant_attribute_value_ids",
            ),
            product_custom_attribute_value_ids: __sdk::__query_builder::Col::new(
                table_name,
                "product_custom_attribute_value_ids",
            ),
            propagate_cancel: __sdk::__query_builder::Col::new(table_name, "propagate_cancel"),
            sale_line_id: __sdk::__query_builder::Col::new(table_name, "sale_line_id"),
            sale_order_id: __sdk::__query_builder::Col::new(table_name, "sale_order_id"),
            move_dest_ids: __sdk::__query_builder::Col::new(table_name, "move_dest_ids"),
            move_ids: __sdk::__query_builder::Col::new(table_name, "move_ids"),
            match_state: __sdk::__query_builder::Col::new(table_name, "match_state"),
            lot_id: __sdk::__query_builder::Col::new(table_name, "lot_id"),
            create_uid: __sdk::__query_builder::Col::new(table_name, "create_uid"),
            create_date: __sdk::__query_builder::Col::new(table_name, "create_date"),
            write_uid: __sdk::__query_builder::Col::new(table_name, "write_uid"),
            write_date: __sdk::__query_builder::Col::new(table_name, "write_date"),
            metadata: __sdk::__query_builder::Col::new(table_name, "metadata"),
        }
    }
}

/// Indexed column accessor struct for the table `PurchaseOrderLine`.
///
/// Provides typed access to indexed columns for query building.
pub struct PurchaseOrderLineIxCols {
    pub id: __sdk::__query_builder::IxCol<PurchaseOrderLine, u64>,
    pub order_id: __sdk::__query_builder::IxCol<PurchaseOrderLine, u64>,
    pub organization_id: __sdk::__query_builder::IxCol<PurchaseOrderLine, u64>,
}

impl __sdk::__query_builder::HasIxCols for PurchaseOrderLine {
    type IxCols = PurchaseOrderLineIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PurchaseOrderLineIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            order_id: __sdk::__query_builder::IxCol::new(table_name, "order_id"),
            organization_id: __sdk::__query_builder::IxCol::new(table_name, "organization_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PurchaseOrderLine {}
