// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PurchaseBlanketOrderLine {
    pub id: u64,
    pub organization_id: u64,
    pub company_id: u64,
    pub blanket_order_id: u64,
    pub product_id: u64,
    pub product_uom: u64,
    pub committed_quantity: f64,
    pub released_quantity: f64,
    pub price_unit: f64,
    pub create_uid: __sdk::Identity,
    pub create_date: __sdk::Timestamp,
    pub write_uid: __sdk::Identity,
    pub write_date: __sdk::Timestamp,
    pub metadata: Option<String>,
}

impl __sdk::InModule for PurchaseBlanketOrderLine {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PurchaseBlanketOrderLine`.
///
/// Provides typed access to columns for query building.
pub struct PurchaseBlanketOrderLineCols {
    pub id: __sdk::__query_builder::Col<PurchaseBlanketOrderLine, u64>,
    pub organization_id: __sdk::__query_builder::Col<PurchaseBlanketOrderLine, u64>,
    pub company_id: __sdk::__query_builder::Col<PurchaseBlanketOrderLine, u64>,
    pub blanket_order_id: __sdk::__query_builder::Col<PurchaseBlanketOrderLine, u64>,
    pub product_id: __sdk::__query_builder::Col<PurchaseBlanketOrderLine, u64>,
    pub product_uom: __sdk::__query_builder::Col<PurchaseBlanketOrderLine, u64>,
    pub committed_quantity: __sdk::__query_builder::Col<PurchaseBlanketOrderLine, f64>,
    pub released_quantity: __sdk::__query_builder::Col<PurchaseBlanketOrderLine, f64>,
    pub price_unit: __sdk::__query_builder::Col<PurchaseBlanketOrderLine, f64>,
    pub create_uid: __sdk::__query_builder::Col<PurchaseBlanketOrderLine, __sdk::Identity>,
    pub create_date: __sdk::__query_builder::Col<PurchaseBlanketOrderLine, __sdk::Timestamp>,
    pub write_uid: __sdk::__query_builder::Col<PurchaseBlanketOrderLine, __sdk::Identity>,
    pub write_date: __sdk::__query_builder::Col<PurchaseBlanketOrderLine, __sdk::Timestamp>,
    pub metadata: __sdk::__query_builder::Col<PurchaseBlanketOrderLine, Option<String>>,
}

impl __sdk::__query_builder::HasCols for PurchaseBlanketOrderLine {
    type Cols = PurchaseBlanketOrderLineCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PurchaseBlanketOrderLineCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            company_id: __sdk::__query_builder::Col::new(table_name, "company_id"),
            blanket_order_id: __sdk::__query_builder::Col::new(table_name, "blanket_order_id"),
            product_id: __sdk::__query_builder::Col::new(table_name, "product_id"),
            product_uom: __sdk::__query_builder::Col::new(table_name, "product_uom"),
            committed_quantity: __sdk::__query_builder::Col::new(table_name, "committed_quantity"),
            released_quantity: __sdk::__query_builder::Col::new(table_name, "released_quantity"),
            price_unit: __sdk::__query_builder::Col::new(table_name, "price_unit"),
            create_uid: __sdk::__query_builder::Col::new(table_name, "create_uid"),
            create_date: __sdk::__query_builder::Col::new(table_name, "create_date"),
            write_uid: __sdk::__query_builder::Col::new(table_name, "write_uid"),
            write_date: __sdk::__query_builder::Col::new(table_name, "write_date"),
            metadata: __sdk::__query_builder::Col::new(table_name, "metadata"),
        }
    }
}

/// Indexed column accessor struct for the table `PurchaseBlanketOrderLine`.
///
/// Provides typed access to indexed columns for query building.
pub struct PurchaseBlanketOrderLineIxCols {
    pub blanket_order_id: __sdk::__query_builder::IxCol<PurchaseBlanketOrderLine, u64>,
    pub id: __sdk::__query_builder::IxCol<PurchaseBlanketOrderLine, u64>,
    pub organization_id: __sdk::__query_builder::IxCol<PurchaseBlanketOrderLine, u64>,
}

impl __sdk::__query_builder::HasIxCols for PurchaseBlanketOrderLine {
    type IxCols = PurchaseBlanketOrderLineIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PurchaseBlanketOrderLineIxCols {
            blanket_order_id: __sdk::__query_builder::IxCol::new(table_name, "blanket_order_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            organization_id: __sdk::__query_builder::IxCol::new(table_name, "organization_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PurchaseBlanketOrderLine {}
