// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::purchase_requisition_type::PurchaseRequisition;
use super::requisition_state_type::RequisitionState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `purchase_requisition`.
///
/// Obtain a handle from the [`PurchaseRequisitionTableAccess::purchase_requisition`] method on [`super::RemoteTables`],
/// like `ctx.db.purchase_requisition()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.purchase_requisition().on_insert(...)`.
pub struct PurchaseRequisitionTableHandle<'ctx> {
    imp: __sdk::TableHandle<PurchaseRequisition>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `purchase_requisition`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PurchaseRequisitionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PurchaseRequisitionTableHandle`], which mediates access to the table `purchase_requisition`.
    fn purchase_requisition(&self) -> PurchaseRequisitionTableHandle<'_>;
}

impl PurchaseRequisitionTableAccess for super::RemoteTables {
    fn purchase_requisition(&self) -> PurchaseRequisitionTableHandle<'_> {
        PurchaseRequisitionTableHandle {
            imp: self
                .imp
                .get_table::<PurchaseRequisition>("purchase_requisition"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PurchaseRequisitionInsertCallbackId(__sdk::CallbackId);
pub struct PurchaseRequisitionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PurchaseRequisitionTableHandle<'ctx> {
    type Row = PurchaseRequisition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PurchaseRequisition> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PurchaseRequisitionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PurchaseRequisitionInsertCallbackId {
        PurchaseRequisitionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PurchaseRequisitionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PurchaseRequisitionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PurchaseRequisitionDeleteCallbackId {
        PurchaseRequisitionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PurchaseRequisitionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PurchaseRequisitionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PurchaseRequisitionTableHandle<'ctx> {
    type UpdateCallbackId = PurchaseRequisitionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PurchaseRequisitionUpdateCallbackId {
        PurchaseRequisitionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PurchaseRequisitionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `purchase_requisition`,
/// which allows point queries on the field of the same name
/// via the [`PurchaseRequisitionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.purchase_requisition().id().find(...)`.
pub struct PurchaseRequisitionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PurchaseRequisition, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PurchaseRequisitionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `purchase_requisition`.
    pub fn id(&self) -> PurchaseRequisitionIdUnique<'ctx> {
        PurchaseRequisitionIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PurchaseRequisitionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PurchaseRequisition> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PurchaseRequisition>("purchase_requisition");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PurchaseRequisition>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PurchaseRequisition>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PurchaseRequisition`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait purchase_requisitionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PurchaseRequisition`.
    fn purchase_requisition(&self) -> __sdk::__query_builder::Table<PurchaseRequisition>;
}

impl purchase_requisitionQueryTableAccess for __sdk::QueryTableAccessor {
    fn purchase_requisition(&self) -> __sdk::__query_builder::Table<PurchaseRequisition> {
        __sdk::__query_builder::Table::new("purchase_requisition")
    }
}
