// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PurchaseReturn {
    pub id: u64,
    pub organization_id: u64,
    pub company_id: u64,
    pub name: String,
    pub purchase_order_id: Option<u64>,
    pub partner_id: u64,
    pub state: String,
    pub return_reason: Option<String>,
    pub picking_id: Option<u64>,
    pub credit_move_id: Option<u64>,
    pub line_ids: Vec<u64>,
    pub create_uid: __sdk::Identity,
    pub create_date: __sdk::Timestamp,
    pub write_uid: __sdk::Identity,
    pub write_date: __sdk::Timestamp,
}

impl __sdk::InModule for PurchaseReturn {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PurchaseReturn`.
///
/// Provides typed access to columns for query building.
pub struct PurchaseReturnCols {
    pub id: __sdk::__query_builder::Col<PurchaseReturn, u64>,
    pub organization_id: __sdk::__query_builder::Col<PurchaseReturn, u64>,
    pub company_id: __sdk::__query_builder::Col<PurchaseReturn, u64>,
    pub name: __sdk::__query_builder::Col<PurchaseReturn, String>,
    pub purchase_order_id: __sdk::__query_builder::Col<PurchaseReturn, Option<u64>>,
    pub partner_id: __sdk::__query_builder::Col<PurchaseReturn, u64>,
    pub state: __sdk::__query_builder::Col<PurchaseReturn, String>,
    pub return_reason: __sdk::__query_builder::Col<PurchaseReturn, Option<String>>,
    pub picking_id: __sdk::__query_builder::Col<PurchaseReturn, Option<u64>>,
    pub credit_move_id: __sdk::__query_builder::Col<PurchaseReturn, Option<u64>>,
    pub line_ids: __sdk::__query_builder::Col<PurchaseReturn, Vec<u64>>,
    pub create_uid: __sdk::__query_builder::Col<PurchaseReturn, __sdk::Identity>,
    pub create_date: __sdk::__query_builder::Col<PurchaseReturn, __sdk::Timestamp>,
    pub write_uid: __sdk::__query_builder::Col<PurchaseReturn, __sdk::Identity>,
    pub write_date: __sdk::__query_builder::Col<PurchaseReturn, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for PurchaseReturn {
    type Cols = PurchaseReturnCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PurchaseReturnCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            company_id: __sdk::__query_builder::Col::new(table_name, "company_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            purchase_order_id: __sdk::__query_builder::Col::new(table_name, "purchase_order_id"),
            partner_id: __sdk::__query_builder::Col::new(table_name, "partner_id"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
            return_reason: __sdk::__query_builder::Col::new(table_name, "return_reason"),
            picking_id: __sdk::__query_builder::Col::new(table_name, "picking_id"),
            credit_move_id: __sdk::__query_builder::Col::new(table_name, "credit_move_id"),
            line_ids: __sdk::__query_builder::Col::new(table_name, "line_ids"),
            create_uid: __sdk::__query_builder::Col::new(table_name, "create_uid"),
            create_date: __sdk::__query_builder::Col::new(table_name, "create_date"),
            write_uid: __sdk::__query_builder::Col::new(table_name, "write_uid"),
            write_date: __sdk::__query_builder::Col::new(table_name, "write_date"),
        }
    }
}

/// Indexed column accessor struct for the table `PurchaseReturn`.
///
/// Provides typed access to indexed columns for query building.
pub struct PurchaseReturnIxCols {
    pub company_id: __sdk::__query_builder::IxCol<PurchaseReturn, u64>,
    pub id: __sdk::__query_builder::IxCol<PurchaseReturn, u64>,
}

impl __sdk::__query_builder::HasIxCols for PurchaseReturn {
    type IxCols = PurchaseReturnIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PurchaseReturnIxCols {
            company_id: __sdk::__query_builder::IxCol::new(table_name, "company_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PurchaseReturn {}
