// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::queue_attempt_outcome_type::QueueAttemptOutcome;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct QueueAttempt {
    pub id: u64,
    pub organization_id: u64,
    pub company_id: Option<u64>,
    pub job_id: u64,
    pub attempt_number: u32,
    pub worker_id: u64,
    pub lease_token: String,
    pub outcome: QueueAttemptOutcome,
    pub lease_expires_at: Option<__sdk::Timestamp>,
    pub available_at: Option<__sdk::Timestamp>,
    pub error_summary: Option<String>,
    pub recorded_by: __sdk::Identity,
    pub recorded_at: __sdk::Timestamp,
}

impl __sdk::InModule for QueueAttempt {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `QueueAttempt`.
///
/// Provides typed access to columns for query building.
pub struct QueueAttemptCols {
    pub id: __sdk::__query_builder::Col<QueueAttempt, u64>,
    pub organization_id: __sdk::__query_builder::Col<QueueAttempt, u64>,
    pub company_id: __sdk::__query_builder::Col<QueueAttempt, Option<u64>>,
    pub job_id: __sdk::__query_builder::Col<QueueAttempt, u64>,
    pub attempt_number: __sdk::__query_builder::Col<QueueAttempt, u32>,
    pub worker_id: __sdk::__query_builder::Col<QueueAttempt, u64>,
    pub lease_token: __sdk::__query_builder::Col<QueueAttempt, String>,
    pub outcome: __sdk::__query_builder::Col<QueueAttempt, QueueAttemptOutcome>,
    pub lease_expires_at: __sdk::__query_builder::Col<QueueAttempt, Option<__sdk::Timestamp>>,
    pub available_at: __sdk::__query_builder::Col<QueueAttempt, Option<__sdk::Timestamp>>,
    pub error_summary: __sdk::__query_builder::Col<QueueAttempt, Option<String>>,
    pub recorded_by: __sdk::__query_builder::Col<QueueAttempt, __sdk::Identity>,
    pub recorded_at: __sdk::__query_builder::Col<QueueAttempt, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for QueueAttempt {
    type Cols = QueueAttemptCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        QueueAttemptCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            company_id: __sdk::__query_builder::Col::new(table_name, "company_id"),
            job_id: __sdk::__query_builder::Col::new(table_name, "job_id"),
            attempt_number: __sdk::__query_builder::Col::new(table_name, "attempt_number"),
            worker_id: __sdk::__query_builder::Col::new(table_name, "worker_id"),
            lease_token: __sdk::__query_builder::Col::new(table_name, "lease_token"),
            outcome: __sdk::__query_builder::Col::new(table_name, "outcome"),
            lease_expires_at: __sdk::__query_builder::Col::new(table_name, "lease_expires_at"),
            available_at: __sdk::__query_builder::Col::new(table_name, "available_at"),
            error_summary: __sdk::__query_builder::Col::new(table_name, "error_summary"),
            recorded_by: __sdk::__query_builder::Col::new(table_name, "recorded_by"),
            recorded_at: __sdk::__query_builder::Col::new(table_name, "recorded_at"),
        }
    }
}

/// Indexed column accessor struct for the table `QueueAttempt`.
///
/// Provides typed access to indexed columns for query building.
pub struct QueueAttemptIxCols {
    pub id: __sdk::__query_builder::IxCol<QueueAttempt, u64>,
    pub job_id: __sdk::__query_builder::IxCol<QueueAttempt, u64>,
    pub organization_id: __sdk::__query_builder::IxCol<QueueAttempt, u64>,
}

impl __sdk::__query_builder::HasIxCols for QueueAttempt {
    type IxCols = QueueAttemptIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        QueueAttemptIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            job_id: __sdk::__query_builder::IxCol::new(table_name, "job_id"),
            organization_id: __sdk::__query_builder::IxCol::new(table_name, "organization_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for QueueAttempt {}
