// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RecordContactIdentityVerificationProofParams {
    pub identity_id: u64,
    pub contact_id: u64,
    pub company_id: Option<u64>,
    pub normalized_e_164: String,
    pub method: String,
    pub provider: String,
    pub provider_reference: String,
    pub evidence_hash: String,
    pub issued_at_micros: i64,
    pub expires_at_micros: i64,
}

impl __sdk::InModule for RecordContactIdentityVerificationProofParams {
    type Module = super::RemoteModule;
}
