// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::record_subscription_payment_failure_params_type::RecordSubscriptionPaymentFailureParams;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecordSubscriptionPaymentFailureArgs {
    pub organization_id: u64,
    pub company_id: u64,
    pub subscription_id: u64,
    pub params: RecordSubscriptionPaymentFailureParams,
}

impl From<RecordSubscriptionPaymentFailureArgs> for super::Reducer {
    fn from(args: RecordSubscriptionPaymentFailureArgs) -> Self {
        Self::RecordSubscriptionPaymentFailure {
            organization_id: args.organization_id,
            company_id: args.company_id,
            subscription_id: args.subscription_id,
            params: args.params,
        }
    }
}

impl __sdk::InModule for RecordSubscriptionPaymentFailureArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `record_subscription_payment_failure`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait record_subscription_payment_failure {
    /// Request that the remote module invoke the reducer `record_subscription_payment_failure` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`record_subscription_payment_failure:record_subscription_payment_failure_then`] to run a callback after the reducer completes.
    fn record_subscription_payment_failure(
        &self,
        organization_id: u64,
        company_id: u64,
        subscription_id: u64,
        params: RecordSubscriptionPaymentFailureParams,
    ) -> __sdk::Result<()> {
        self.record_subscription_payment_failure_then(
            organization_id,
            company_id,
            subscription_id,
            params,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `record_subscription_payment_failure` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn record_subscription_payment_failure_then(
        &self,
        organization_id: u64,
        company_id: u64,
        subscription_id: u64,
        params: RecordSubscriptionPaymentFailureParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl record_subscription_payment_failure for super::RemoteReducers {
    fn record_subscription_payment_failure_then(
        &self,
        organization_id: u64,
        company_id: u64,
        subscription_id: u64,
        params: RecordSubscriptionPaymentFailureParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RecordSubscriptionPaymentFailureArgs {
                organization_id,
                company_id,
                subscription_id,
                params,
            },
            callback,
        )
    }
}
