// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecordGoogleDriveSyncErrorArgs {
    pub connection_id: u64,
    pub organization_id: u64,
    pub error_message: String,
}

impl From<RecordGoogleDriveSyncErrorArgs> for super::Reducer {
    fn from(args: RecordGoogleDriveSyncErrorArgs) -> Self {
        Self::RecordGoogleDriveSyncError {
            connection_id: args.connection_id,
            organization_id: args.organization_id,
            error_message: args.error_message,
        }
    }
}

impl __sdk::InModule for RecordGoogleDriveSyncErrorArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `record_google_drive_sync_error`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait record_google_drive_sync_error {
    /// Request that the remote module invoke the reducer `record_google_drive_sync_error` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`record_google_drive_sync_error:record_google_drive_sync_error_then`] to run a callback after the reducer completes.
    fn record_google_drive_sync_error(
        &self,
        connection_id: u64,
        organization_id: u64,
        error_message: String,
    ) -> __sdk::Result<()> {
        self.record_google_drive_sync_error_then(
            connection_id,
            organization_id,
            error_message,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `record_google_drive_sync_error` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn record_google_drive_sync_error_then(
        &self,
        connection_id: u64,
        organization_id: u64,
        error_message: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl record_google_drive_sync_error for super::RemoteReducers {
    fn record_google_drive_sync_error_then(
        &self,
        connection_id: u64,
        organization_id: u64,
        error_message: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RecordGoogleDriveSyncErrorArgs {
                connection_id,
                organization_id,
                error_message,
            },
            callback,
        )
    }
}
