// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::refuse_expense_sheet_params_type::RefuseExpenseSheetParams;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RefuseExpenseSheetArgs {
    pub organization_id: u64,
    pub sheet_id: u64,
    pub params: RefuseExpenseSheetParams,
}

impl From<RefuseExpenseSheetArgs> for super::Reducer {
    fn from(args: RefuseExpenseSheetArgs) -> Self {
        Self::RefuseExpenseSheet {
            organization_id: args.organization_id,
            sheet_id: args.sheet_id,
            params: args.params,
        }
    }
}

impl __sdk::InModule for RefuseExpenseSheetArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `refuse_expense_sheet`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait refuse_expense_sheet {
    /// Request that the remote module invoke the reducer `refuse_expense_sheet` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`refuse_expense_sheet:refuse_expense_sheet_then`] to run a callback after the reducer completes.
    fn refuse_expense_sheet(
        &self,
        organization_id: u64,
        sheet_id: u64,
        params: RefuseExpenseSheetParams,
    ) -> __sdk::Result<()> {
        self.refuse_expense_sheet_then(organization_id, sheet_id, params, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `refuse_expense_sheet` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn refuse_expense_sheet_then(
        &self,
        organization_id: u64,
        sheet_id: u64,
        params: RefuseExpenseSheetParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl refuse_expense_sheet for super::RemoteReducers {
    fn refuse_expense_sheet_then(
        &self,
        organization_id: u64,
        sheet_id: u64,
        params: RefuseExpenseSheetParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RefuseExpenseSheetArgs {
                organization_id,
                sheet_id,
                params,
            },
            callback,
        )
    }
}
