// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RevokeDelegatedAdminScopeArgs {
    pub organization_id: u64,
    pub scope_id: u64,
}

impl From<RevokeDelegatedAdminScopeArgs> for super::Reducer {
    fn from(args: RevokeDelegatedAdminScopeArgs) -> Self {
        Self::RevokeDelegatedAdminScope {
            organization_id: args.organization_id,
            scope_id: args.scope_id,
        }
    }
}

impl __sdk::InModule for RevokeDelegatedAdminScopeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `revoke_delegated_admin_scope`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait revoke_delegated_admin_scope {
    /// Request that the remote module invoke the reducer `revoke_delegated_admin_scope` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`revoke_delegated_admin_scope:revoke_delegated_admin_scope_then`] to run a callback after the reducer completes.
    fn revoke_delegated_admin_scope(
        &self,
        organization_id: u64,
        scope_id: u64,
    ) -> __sdk::Result<()> {
        self.revoke_delegated_admin_scope_then(organization_id, scope_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `revoke_delegated_admin_scope` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn revoke_delegated_admin_scope_then(
        &self,
        organization_id: u64,
        scope_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl revoke_delegated_admin_scope for super::RemoteReducers {
    fn revoke_delegated_admin_scope_then(
        &self,
        organization_id: u64,
        scope_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RevokeDelegatedAdminScopeArgs {
                organization_id,
                scope_id,
            },
            callback,
        )
    }
}
