// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RollbackImportJobArgs {
    pub organization_id: u64,
    pub job_id: u64,
}

impl From<RollbackImportJobArgs> for super::Reducer {
    fn from(args: RollbackImportJobArgs) -> Self {
        Self::RollbackImportJob {
            organization_id: args.organization_id,
            job_id: args.job_id,
        }
    }
}

impl __sdk::InModule for RollbackImportJobArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `rollback_import_job`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait rollback_import_job {
    /// Request that the remote module invoke the reducer `rollback_import_job` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`rollback_import_job:rollback_import_job_then`] to run a callback after the reducer completes.
    fn rollback_import_job(&self, organization_id: u64, job_id: u64) -> __sdk::Result<()> {
        self.rollback_import_job_then(organization_id, job_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `rollback_import_job` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn rollback_import_job_then(
        &self,
        organization_id: u64,
        job_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl rollback_import_job for super::RemoteReducers {
    fn rollback_import_job_then(
        &self,
        organization_id: u64,
        job_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RollbackImportJobArgs {
                organization_id,
                job_id,
            },
            callback,
        )
    }
}
