// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SaleCpqConstraint {
    pub id: u64,
    pub organization_id: u64,
    pub company_id: u64,
    pub name: String,
    pub rule_json: String,
    pub is_active: bool,
    pub create_uid: __sdk::Identity,
    pub create_date: __sdk::Timestamp,
    pub write_uid: __sdk::Identity,
    pub write_date: __sdk::Timestamp,
    pub metadata: Option<String>,
}

impl __sdk::InModule for SaleCpqConstraint {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SaleCpqConstraint`.
///
/// Provides typed access to columns for query building.
pub struct SaleCpqConstraintCols {
    pub id: __sdk::__query_builder::Col<SaleCpqConstraint, u64>,
    pub organization_id: __sdk::__query_builder::Col<SaleCpqConstraint, u64>,
    pub company_id: __sdk::__query_builder::Col<SaleCpqConstraint, u64>,
    pub name: __sdk::__query_builder::Col<SaleCpqConstraint, String>,
    pub rule_json: __sdk::__query_builder::Col<SaleCpqConstraint, String>,
    pub is_active: __sdk::__query_builder::Col<SaleCpqConstraint, bool>,
    pub create_uid: __sdk::__query_builder::Col<SaleCpqConstraint, __sdk::Identity>,
    pub create_date: __sdk::__query_builder::Col<SaleCpqConstraint, __sdk::Timestamp>,
    pub write_uid: __sdk::__query_builder::Col<SaleCpqConstraint, __sdk::Identity>,
    pub write_date: __sdk::__query_builder::Col<SaleCpqConstraint, __sdk::Timestamp>,
    pub metadata: __sdk::__query_builder::Col<SaleCpqConstraint, Option<String>>,
}

impl __sdk::__query_builder::HasCols for SaleCpqConstraint {
    type Cols = SaleCpqConstraintCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SaleCpqConstraintCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            company_id: __sdk::__query_builder::Col::new(table_name, "company_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            rule_json: __sdk::__query_builder::Col::new(table_name, "rule_json"),
            is_active: __sdk::__query_builder::Col::new(table_name, "is_active"),
            create_uid: __sdk::__query_builder::Col::new(table_name, "create_uid"),
            create_date: __sdk::__query_builder::Col::new(table_name, "create_date"),
            write_uid: __sdk::__query_builder::Col::new(table_name, "write_uid"),
            write_date: __sdk::__query_builder::Col::new(table_name, "write_date"),
            metadata: __sdk::__query_builder::Col::new(table_name, "metadata"),
        }
    }
}

/// Indexed column accessor struct for the table `SaleCpqConstraint`.
///
/// Provides typed access to indexed columns for query building.
pub struct SaleCpqConstraintIxCols {
    pub id: __sdk::__query_builder::IxCol<SaleCpqConstraint, u64>,
    pub organization_id: __sdk::__query_builder::IxCol<SaleCpqConstraint, u64>,
}

impl __sdk::__query_builder::HasIxCols for SaleCpqConstraint {
    type IxCols = SaleCpqConstraintIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SaleCpqConstraintIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            organization_id: __sdk::__query_builder::IxCol::new(table_name, "organization_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SaleCpqConstraint {}
