// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::set_expense_fraud_hold_params_type::SetExpenseFraudHoldParams;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetExpenseFraudHoldArgs {
    pub organization_id: u64,
    pub expense_id: u64,
    pub params: SetExpenseFraudHoldParams,
}

impl From<SetExpenseFraudHoldArgs> for super::Reducer {
    fn from(args: SetExpenseFraudHoldArgs) -> Self {
        Self::SetExpenseFraudHold {
            organization_id: args.organization_id,
            expense_id: args.expense_id,
            params: args.params,
        }
    }
}

impl __sdk::InModule for SetExpenseFraudHoldArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_expense_fraud_hold`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_expense_fraud_hold {
    /// Request that the remote module invoke the reducer `set_expense_fraud_hold` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_expense_fraud_hold:set_expense_fraud_hold_then`] to run a callback after the reducer completes.
    fn set_expense_fraud_hold(
        &self,
        organization_id: u64,
        expense_id: u64,
        params: SetExpenseFraudHoldParams,
    ) -> __sdk::Result<()> {
        self.set_expense_fraud_hold_then(organization_id, expense_id, params, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_expense_fraud_hold` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_expense_fraud_hold_then(
        &self,
        organization_id: u64,
        expense_id: u64,
        params: SetExpenseFraudHoldParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_expense_fraud_hold for super::RemoteReducers {
    fn set_expense_fraud_hold_then(
        &self,
        organization_id: u64,
        expense_id: u64,
        params: SetExpenseFraudHoldParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetExpenseFraudHoldArgs {
                organization_id,
                expense_id,
                params,
            },
            callback,
        )
    }
}
