// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::drive_conflict_policy_type::DriveConflictPolicy;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SetDriveConflictPolicyParams {
    pub conflict_policy: DriveConflictPolicy,
}

impl __sdk::InModule for SetDriveConflictPolicyParams {
    type Module = super::RemoteModule;
}
