// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SetConsolidationCompanyRateParams {
    pub company_id: u64,
    pub period_id: u64,
    pub currency_id: u64,
    pub exchange_rate: f64,
    pub rate_type: String,
    pub effective_date: __sdk::Timestamp,
    pub metadata: Option<String>,
}

impl __sdk::InModule for SetConsolidationCompanyRateParams {
    type Module = super::RemoteModule;
}
