// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::set_document_retention_params_type::SetDocumentRetentionParams;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetDocumentRetentionArgs {
    pub organization_id: u64,
    pub document_id: u64,
    pub params: SetDocumentRetentionParams,
}

impl From<SetDocumentRetentionArgs> for super::Reducer {
    fn from(args: SetDocumentRetentionArgs) -> Self {
        Self::SetDocumentRetention {
            organization_id: args.organization_id,
            document_id: args.document_id,
            params: args.params,
        }
    }
}

impl __sdk::InModule for SetDocumentRetentionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_document_retention`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_document_retention {
    /// Request that the remote module invoke the reducer `set_document_retention` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_document_retention:set_document_retention_then`] to run a callback after the reducer completes.
    fn set_document_retention(
        &self,
        organization_id: u64,
        document_id: u64,
        params: SetDocumentRetentionParams,
    ) -> __sdk::Result<()> {
        self.set_document_retention_then(organization_id, document_id, params, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_document_retention` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_document_retention_then(
        &self,
        organization_id: u64,
        document_id: u64,
        params: SetDocumentRetentionParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_document_retention for super::RemoteReducers {
    fn set_document_retention_then(
        &self,
        organization_id: u64,
        document_id: u64,
        params: SetDocumentRetentionParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetDocumentRetentionArgs {
                organization_id,
                document_id,
                params,
            },
            callback,
        )
    }
}
