// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::stage_bank_statement_import_params_type::StageBankStatementImportParams;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StageBankStatementImportArgs {
    pub organization_id: u64,
    pub company_id: u64,
    pub journal_id: u64,
    pub currency_id: u64,
    pub params: StageBankStatementImportParams,
}

impl From<StageBankStatementImportArgs> for super::Reducer {
    fn from(args: StageBankStatementImportArgs) -> Self {
        Self::StageBankStatementImport {
            organization_id: args.organization_id,
            company_id: args.company_id,
            journal_id: args.journal_id,
            currency_id: args.currency_id,
            params: args.params,
        }
    }
}

impl __sdk::InModule for StageBankStatementImportArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `stage_bank_statement_import`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait stage_bank_statement_import {
    /// Request that the remote module invoke the reducer `stage_bank_statement_import` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`stage_bank_statement_import:stage_bank_statement_import_then`] to run a callback after the reducer completes.
    fn stage_bank_statement_import(
        &self,
        organization_id: u64,
        company_id: u64,
        journal_id: u64,
        currency_id: u64,
        params: StageBankStatementImportParams,
    ) -> __sdk::Result<()> {
        self.stage_bank_statement_import_then(
            organization_id,
            company_id,
            journal_id,
            currency_id,
            params,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `stage_bank_statement_import` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn stage_bank_statement_import_then(
        &self,
        organization_id: u64,
        company_id: u64,
        journal_id: u64,
        currency_id: u64,
        params: StageBankStatementImportParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl stage_bank_statement_import for super::RemoteReducers {
    fn stage_bank_statement_import_then(
        &self,
        organization_id: u64,
        company_id: u64,
        journal_id: u64,
        currency_id: u64,
        params: StageBankStatementImportParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            StageBankStatementImportArgs {
                organization_id,
                company_id,
                journal_id,
                currency_id,
                params,
            },
            callback,
        )
    }
}
