// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct StockLocation {
    pub id: u64,
    pub organization_id: u64,
    pub name: String,
    pub complete_name: Option<String>,
    pub location_id: Option<u64>,
    pub parent_path: String,
    pub child_ids: Vec<u64>,
    pub child_left: u32,
    pub child_right: u32,
    pub usage: String,
    pub company_id: Option<u64>,
    pub scrap_location: bool,
    pub return_location: bool,
    pub valuation_in_account_id: Option<u64>,
    pub valuation_out_account_id: Option<u64>,
    pub active: bool,
    pub comment: Option<String>,
    pub posx: f64,
    pub posy: f64,
    pub posz: f64,
    pub barcode: Option<String>,
    pub cyclic_inventory_frequency: u8,
    pub last_inventory_date: Option<__sdk::Timestamp>,
    pub next_inventory_date: Option<__sdk::Timestamp>,
    pub location_category: String,
    pub is_active: bool,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
    pub metadata: Option<String>,
}

impl __sdk::InModule for StockLocation {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `StockLocation`.
///
/// Provides typed access to columns for query building.
pub struct StockLocationCols {
    pub id: __sdk::__query_builder::Col<StockLocation, u64>,
    pub organization_id: __sdk::__query_builder::Col<StockLocation, u64>,
    pub name: __sdk::__query_builder::Col<StockLocation, String>,
    pub complete_name: __sdk::__query_builder::Col<StockLocation, Option<String>>,
    pub location_id: __sdk::__query_builder::Col<StockLocation, Option<u64>>,
    pub parent_path: __sdk::__query_builder::Col<StockLocation, String>,
    pub child_ids: __sdk::__query_builder::Col<StockLocation, Vec<u64>>,
    pub child_left: __sdk::__query_builder::Col<StockLocation, u32>,
    pub child_right: __sdk::__query_builder::Col<StockLocation, u32>,
    pub usage: __sdk::__query_builder::Col<StockLocation, String>,
    pub company_id: __sdk::__query_builder::Col<StockLocation, Option<u64>>,
    pub scrap_location: __sdk::__query_builder::Col<StockLocation, bool>,
    pub return_location: __sdk::__query_builder::Col<StockLocation, bool>,
    pub valuation_in_account_id: __sdk::__query_builder::Col<StockLocation, Option<u64>>,
    pub valuation_out_account_id: __sdk::__query_builder::Col<StockLocation, Option<u64>>,
    pub active: __sdk::__query_builder::Col<StockLocation, bool>,
    pub comment: __sdk::__query_builder::Col<StockLocation, Option<String>>,
    pub posx: __sdk::__query_builder::Col<StockLocation, f64>,
    pub posy: __sdk::__query_builder::Col<StockLocation, f64>,
    pub posz: __sdk::__query_builder::Col<StockLocation, f64>,
    pub barcode: __sdk::__query_builder::Col<StockLocation, Option<String>>,
    pub cyclic_inventory_frequency: __sdk::__query_builder::Col<StockLocation, u8>,
    pub last_inventory_date: __sdk::__query_builder::Col<StockLocation, Option<__sdk::Timestamp>>,
    pub next_inventory_date: __sdk::__query_builder::Col<StockLocation, Option<__sdk::Timestamp>>,
    pub location_category: __sdk::__query_builder::Col<StockLocation, String>,
    pub is_active: __sdk::__query_builder::Col<StockLocation, bool>,
    pub created_at: __sdk::__query_builder::Col<StockLocation, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<StockLocation, __sdk::Timestamp>,
    pub metadata: __sdk::__query_builder::Col<StockLocation, Option<String>>,
}

impl __sdk::__query_builder::HasCols for StockLocation {
    type Cols = StockLocationCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        StockLocationCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            complete_name: __sdk::__query_builder::Col::new(table_name, "complete_name"),
            location_id: __sdk::__query_builder::Col::new(table_name, "location_id"),
            parent_path: __sdk::__query_builder::Col::new(table_name, "parent_path"),
            child_ids: __sdk::__query_builder::Col::new(table_name, "child_ids"),
            child_left: __sdk::__query_builder::Col::new(table_name, "child_left"),
            child_right: __sdk::__query_builder::Col::new(table_name, "child_right"),
            usage: __sdk::__query_builder::Col::new(table_name, "usage"),
            company_id: __sdk::__query_builder::Col::new(table_name, "company_id"),
            scrap_location: __sdk::__query_builder::Col::new(table_name, "scrap_location"),
            return_location: __sdk::__query_builder::Col::new(table_name, "return_location"),
            valuation_in_account_id: __sdk::__query_builder::Col::new(
                table_name,
                "valuation_in_account_id",
            ),
            valuation_out_account_id: __sdk::__query_builder::Col::new(
                table_name,
                "valuation_out_account_id",
            ),
            active: __sdk::__query_builder::Col::new(table_name, "active"),
            comment: __sdk::__query_builder::Col::new(table_name, "comment"),
            posx: __sdk::__query_builder::Col::new(table_name, "posx"),
            posy: __sdk::__query_builder::Col::new(table_name, "posy"),
            posz: __sdk::__query_builder::Col::new(table_name, "posz"),
            barcode: __sdk::__query_builder::Col::new(table_name, "barcode"),
            cyclic_inventory_frequency: __sdk::__query_builder::Col::new(
                table_name,
                "cyclic_inventory_frequency",
            ),
            last_inventory_date: __sdk::__query_builder::Col::new(
                table_name,
                "last_inventory_date",
            ),
            next_inventory_date: __sdk::__query_builder::Col::new(
                table_name,
                "next_inventory_date",
            ),
            location_category: __sdk::__query_builder::Col::new(table_name, "location_category"),
            is_active: __sdk::__query_builder::Col::new(table_name, "is_active"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
            metadata: __sdk::__query_builder::Col::new(table_name, "metadata"),
        }
    }
}

/// Indexed column accessor struct for the table `StockLocation`.
///
/// Provides typed access to indexed columns for query building.
pub struct StockLocationIxCols {
    pub barcode: __sdk::__query_builder::IxCol<StockLocation, Option<String>>,
    pub id: __sdk::__query_builder::IxCol<StockLocation, u64>,
    pub location_id: __sdk::__query_builder::IxCol<StockLocation, Option<u64>>,
    pub organization_id: __sdk::__query_builder::IxCol<StockLocation, u64>,
}

impl __sdk::__query_builder::HasIxCols for StockLocation {
    type IxCols = StockLocationIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        StockLocationIxCols {
            barcode: __sdk::__query_builder::IxCol::new(table_name, "barcode"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            location_id: __sdk::__query_builder::IxCol::new(table_name, "location_id"),
            organization_id: __sdk::__query_builder::IxCol::new(table_name, "organization_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for StockLocation {}
