// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::subscription_usage_charge_type::SubscriptionUsageCharge;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `subscription_usage_charge`.
///
/// Obtain a handle from the [`SubscriptionUsageChargeTableAccess::subscription_usage_charge`] method on [`super::RemoteTables`],
/// like `ctx.db.subscription_usage_charge()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.subscription_usage_charge().on_insert(...)`.
pub struct SubscriptionUsageChargeTableHandle<'ctx> {
    imp: __sdk::TableHandle<SubscriptionUsageCharge>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `subscription_usage_charge`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SubscriptionUsageChargeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SubscriptionUsageChargeTableHandle`], which mediates access to the table `subscription_usage_charge`.
    fn subscription_usage_charge(&self) -> SubscriptionUsageChargeTableHandle<'_>;
}

impl SubscriptionUsageChargeTableAccess for super::RemoteTables {
    fn subscription_usage_charge(&self) -> SubscriptionUsageChargeTableHandle<'_> {
        SubscriptionUsageChargeTableHandle {
            imp: self
                .imp
                .get_table::<SubscriptionUsageCharge>("subscription_usage_charge"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SubscriptionUsageChargeInsertCallbackId(__sdk::CallbackId);
pub struct SubscriptionUsageChargeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SubscriptionUsageChargeTableHandle<'ctx> {
    type Row = SubscriptionUsageCharge;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SubscriptionUsageCharge> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SubscriptionUsageChargeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SubscriptionUsageChargeInsertCallbackId {
        SubscriptionUsageChargeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SubscriptionUsageChargeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SubscriptionUsageChargeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SubscriptionUsageChargeDeleteCallbackId {
        SubscriptionUsageChargeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SubscriptionUsageChargeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SubscriptionUsageChargeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SubscriptionUsageChargeTableHandle<'ctx> {
    type UpdateCallbackId = SubscriptionUsageChargeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SubscriptionUsageChargeUpdateCallbackId {
        SubscriptionUsageChargeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SubscriptionUsageChargeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `subscription_usage_charge`,
/// which allows point queries on the field of the same name
/// via the [`SubscriptionUsageChargeIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.subscription_usage_charge().id().find(...)`.
pub struct SubscriptionUsageChargeIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SubscriptionUsageCharge, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SubscriptionUsageChargeTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `subscription_usage_charge`.
    pub fn id(&self) -> SubscriptionUsageChargeIdUnique<'ctx> {
        SubscriptionUsageChargeIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SubscriptionUsageChargeIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SubscriptionUsageCharge> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<SubscriptionUsageCharge>("subscription_usage_charge");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SubscriptionUsageCharge>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SubscriptionUsageCharge>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SubscriptionUsageCharge`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait subscription_usage_chargeQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SubscriptionUsageCharge`.
    fn subscription_usage_charge(&self) -> __sdk::__query_builder::Table<SubscriptionUsageCharge>;
}

impl subscription_usage_chargeQueryTableAccess for __sdk::QueryTableAccessor {
    fn subscription_usage_charge(&self) -> __sdk::__query_builder::Table<SubscriptionUsageCharge> {
        __sdk::__query_builder::Table::new("subscription_usage_charge")
    }
}
