// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SubscriptionCommitment {
    pub id: u64,
    pub organization_id: u64,
    pub company_id: u64,
    pub subscription_id: u64,
    pub min_amount: f64,
    pub product_id: Option<u64>,
    pub active: bool,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
    pub metadata: String,
}

impl __sdk::InModule for SubscriptionCommitment {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SubscriptionCommitment`.
///
/// Provides typed access to columns for query building.
pub struct SubscriptionCommitmentCols {
    pub id: __sdk::__query_builder::Col<SubscriptionCommitment, u64>,
    pub organization_id: __sdk::__query_builder::Col<SubscriptionCommitment, u64>,
    pub company_id: __sdk::__query_builder::Col<SubscriptionCommitment, u64>,
    pub subscription_id: __sdk::__query_builder::Col<SubscriptionCommitment, u64>,
    pub min_amount: __sdk::__query_builder::Col<SubscriptionCommitment, f64>,
    pub product_id: __sdk::__query_builder::Col<SubscriptionCommitment, Option<u64>>,
    pub active: __sdk::__query_builder::Col<SubscriptionCommitment, bool>,
    pub created_at: __sdk::__query_builder::Col<SubscriptionCommitment, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<SubscriptionCommitment, __sdk::Timestamp>,
    pub metadata: __sdk::__query_builder::Col<SubscriptionCommitment, String>,
}

impl __sdk::__query_builder::HasCols for SubscriptionCommitment {
    type Cols = SubscriptionCommitmentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SubscriptionCommitmentCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            company_id: __sdk::__query_builder::Col::new(table_name, "company_id"),
            subscription_id: __sdk::__query_builder::Col::new(table_name, "subscription_id"),
            min_amount: __sdk::__query_builder::Col::new(table_name, "min_amount"),
            product_id: __sdk::__query_builder::Col::new(table_name, "product_id"),
            active: __sdk::__query_builder::Col::new(table_name, "active"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
            metadata: __sdk::__query_builder::Col::new(table_name, "metadata"),
        }
    }
}

/// Indexed column accessor struct for the table `SubscriptionCommitment`.
///
/// Provides typed access to indexed columns for query building.
pub struct SubscriptionCommitmentIxCols {
    pub id: __sdk::__query_builder::IxCol<SubscriptionCommitment, u64>,
    pub organization_id: __sdk::__query_builder::IxCol<SubscriptionCommitment, u64>,
    pub subscription_id: __sdk::__query_builder::IxCol<SubscriptionCommitment, u64>,
}

impl __sdk::__query_builder::HasIxCols for SubscriptionCommitment {
    type IxCols = SubscriptionCommitmentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SubscriptionCommitmentIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            organization_id: __sdk::__query_builder::IxCol::new(table_name, "organization_id"),
            subscription_id: __sdk::__query_builder::IxCol::new(table_name, "subscription_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SubscriptionCommitment {}
