// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SubscriptionPaymentIntent {
    pub id: u64,
    pub organization_id: u64,
    pub company_id: u64,
    pub subscription_id: u64,
    pub intent_type: String,
    pub status: String,
    pub idempotency_key: String,
    pub invoice_move_id: Option<u64>,
    pub payment_token_id: Option<u64>,
    pub amount: f64,
    pub currency_id: u64,
    pub fallback_draft_invoice: bool,
    pub last_error: Option<String>,
    pub attempt_count: u32,
    pub applied_at: Option<__sdk::Timestamp>,
    pub created_at: __sdk::Timestamp,
    pub created_by: __sdk::Identity,
    pub metadata: String,
}

impl __sdk::InModule for SubscriptionPaymentIntent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SubscriptionPaymentIntent`.
///
/// Provides typed access to columns for query building.
pub struct SubscriptionPaymentIntentCols {
    pub id: __sdk::__query_builder::Col<SubscriptionPaymentIntent, u64>,
    pub organization_id: __sdk::__query_builder::Col<SubscriptionPaymentIntent, u64>,
    pub company_id: __sdk::__query_builder::Col<SubscriptionPaymentIntent, u64>,
    pub subscription_id: __sdk::__query_builder::Col<SubscriptionPaymentIntent, u64>,
    pub intent_type: __sdk::__query_builder::Col<SubscriptionPaymentIntent, String>,
    pub status: __sdk::__query_builder::Col<SubscriptionPaymentIntent, String>,
    pub idempotency_key: __sdk::__query_builder::Col<SubscriptionPaymentIntent, String>,
    pub invoice_move_id: __sdk::__query_builder::Col<SubscriptionPaymentIntent, Option<u64>>,
    pub payment_token_id: __sdk::__query_builder::Col<SubscriptionPaymentIntent, Option<u64>>,
    pub amount: __sdk::__query_builder::Col<SubscriptionPaymentIntent, f64>,
    pub currency_id: __sdk::__query_builder::Col<SubscriptionPaymentIntent, u64>,
    pub fallback_draft_invoice: __sdk::__query_builder::Col<SubscriptionPaymentIntent, bool>,
    pub last_error: __sdk::__query_builder::Col<SubscriptionPaymentIntent, Option<String>>,
    pub attempt_count: __sdk::__query_builder::Col<SubscriptionPaymentIntent, u32>,
    pub applied_at:
        __sdk::__query_builder::Col<SubscriptionPaymentIntent, Option<__sdk::Timestamp>>,
    pub created_at: __sdk::__query_builder::Col<SubscriptionPaymentIntent, __sdk::Timestamp>,
    pub created_by: __sdk::__query_builder::Col<SubscriptionPaymentIntent, __sdk::Identity>,
    pub metadata: __sdk::__query_builder::Col<SubscriptionPaymentIntent, String>,
}

impl __sdk::__query_builder::HasCols for SubscriptionPaymentIntent {
    type Cols = SubscriptionPaymentIntentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SubscriptionPaymentIntentCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            company_id: __sdk::__query_builder::Col::new(table_name, "company_id"),
            subscription_id: __sdk::__query_builder::Col::new(table_name, "subscription_id"),
            intent_type: __sdk::__query_builder::Col::new(table_name, "intent_type"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            idempotency_key: __sdk::__query_builder::Col::new(table_name, "idempotency_key"),
            invoice_move_id: __sdk::__query_builder::Col::new(table_name, "invoice_move_id"),
            payment_token_id: __sdk::__query_builder::Col::new(table_name, "payment_token_id"),
            amount: __sdk::__query_builder::Col::new(table_name, "amount"),
            currency_id: __sdk::__query_builder::Col::new(table_name, "currency_id"),
            fallback_draft_invoice: __sdk::__query_builder::Col::new(
                table_name,
                "fallback_draft_invoice",
            ),
            last_error: __sdk::__query_builder::Col::new(table_name, "last_error"),
            attempt_count: __sdk::__query_builder::Col::new(table_name, "attempt_count"),
            applied_at: __sdk::__query_builder::Col::new(table_name, "applied_at"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            created_by: __sdk::__query_builder::Col::new(table_name, "created_by"),
            metadata: __sdk::__query_builder::Col::new(table_name, "metadata"),
        }
    }
}

/// Indexed column accessor struct for the table `SubscriptionPaymentIntent`.
///
/// Provides typed access to indexed columns for query building.
pub struct SubscriptionPaymentIntentIxCols {
    pub id: __sdk::__query_builder::IxCol<SubscriptionPaymentIntent, u64>,
    pub idempotency_key: __sdk::__query_builder::IxCol<SubscriptionPaymentIntent, String>,
    pub organization_id: __sdk::__query_builder::IxCol<SubscriptionPaymentIntent, u64>,
    pub status: __sdk::__query_builder::IxCol<SubscriptionPaymentIntent, String>,
    pub subscription_id: __sdk::__query_builder::IxCol<SubscriptionPaymentIntent, u64>,
}

impl __sdk::__query_builder::HasIxCols for SubscriptionPaymentIntent {
    type IxCols = SubscriptionPaymentIntentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SubscriptionPaymentIntentIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            idempotency_key: __sdk::__query_builder::IxCol::new(table_name, "idempotency_key"),
            organization_id: __sdk::__query_builder::IxCol::new(table_name, "organization_id"),
            status: __sdk::__query_builder::IxCol::new(table_name, "status"),
            subscription_id: __sdk::__query_builder::IxCol::new(table_name, "subscription_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SubscriptionPaymentIntent {}
