// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::subscription_usage_event_type::SubscriptionUsageEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `subscription_usage_event`.
///
/// Obtain a handle from the [`SubscriptionUsageEventTableAccess::subscription_usage_event`] method on [`super::RemoteTables`],
/// like `ctx.db.subscription_usage_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.subscription_usage_event().on_insert(...)`.
pub struct SubscriptionUsageEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<SubscriptionUsageEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `subscription_usage_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SubscriptionUsageEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SubscriptionUsageEventTableHandle`], which mediates access to the table `subscription_usage_event`.
    fn subscription_usage_event(&self) -> SubscriptionUsageEventTableHandle<'_>;
}

impl SubscriptionUsageEventTableAccess for super::RemoteTables {
    fn subscription_usage_event(&self) -> SubscriptionUsageEventTableHandle<'_> {
        SubscriptionUsageEventTableHandle {
            imp: self
                .imp
                .get_table::<SubscriptionUsageEvent>("subscription_usage_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SubscriptionUsageEventInsertCallbackId(__sdk::CallbackId);
pub struct SubscriptionUsageEventDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SubscriptionUsageEventTableHandle<'ctx> {
    type Row = SubscriptionUsageEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SubscriptionUsageEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SubscriptionUsageEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SubscriptionUsageEventInsertCallbackId {
        SubscriptionUsageEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SubscriptionUsageEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SubscriptionUsageEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SubscriptionUsageEventDeleteCallbackId {
        SubscriptionUsageEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SubscriptionUsageEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SubscriptionUsageEventUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SubscriptionUsageEventTableHandle<'ctx> {
    type UpdateCallbackId = SubscriptionUsageEventUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SubscriptionUsageEventUpdateCallbackId {
        SubscriptionUsageEventUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SubscriptionUsageEventUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `subscription_usage_event`,
/// which allows point queries on the field of the same name
/// via the [`SubscriptionUsageEventIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.subscription_usage_event().id().find(...)`.
pub struct SubscriptionUsageEventIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SubscriptionUsageEvent, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SubscriptionUsageEventTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `subscription_usage_event`.
    pub fn id(&self) -> SubscriptionUsageEventIdUnique<'ctx> {
        SubscriptionUsageEventIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SubscriptionUsageEventIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SubscriptionUsageEvent> {
        self.imp.find(col_val)
    }
}

/// Access to the `idempotency_key` unique index on the table `subscription_usage_event`,
/// which allows point queries on the field of the same name
/// via the [`SubscriptionUsageEventIdempotencyKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.subscription_usage_event().idempotency_key().find(...)`.
pub struct SubscriptionUsageEventIdempotencyKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SubscriptionUsageEvent, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SubscriptionUsageEventTableHandle<'ctx> {
    /// Get a handle on the `idempotency_key` unique index on the table `subscription_usage_event`.
    pub fn idempotency_key(&self) -> SubscriptionUsageEventIdempotencyKeyUnique<'ctx> {
        SubscriptionUsageEventIdempotencyKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("idempotency_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SubscriptionUsageEventIdempotencyKeyUnique<'ctx> {
    /// Find the subscribed row whose `idempotency_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<SubscriptionUsageEvent> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<SubscriptionUsageEvent>("subscription_usage_event");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("idempotency_key", |row| &row.idempotency_key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SubscriptionUsageEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SubscriptionUsageEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SubscriptionUsageEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait subscription_usage_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SubscriptionUsageEvent`.
    fn subscription_usage_event(&self) -> __sdk::__query_builder::Table<SubscriptionUsageEvent>;
}

impl subscription_usage_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn subscription_usage_event(&self) -> __sdk::__query_builder::Table<SubscriptionUsageEvent> {
        __sdk::__query_builder::Table::new("subscription_usage_event")
    }
}
