// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::subscription_amendment_type::SubscriptionAmendment;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `subscription_amendment`.
///
/// Obtain a handle from the [`SubscriptionAmendmentTableAccess::subscription_amendment`] method on [`super::RemoteTables`],
/// like `ctx.db.subscription_amendment()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.subscription_amendment().on_insert(...)`.
pub struct SubscriptionAmendmentTableHandle<'ctx> {
    imp: __sdk::TableHandle<SubscriptionAmendment>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `subscription_amendment`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SubscriptionAmendmentTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SubscriptionAmendmentTableHandle`], which mediates access to the table `subscription_amendment`.
    fn subscription_amendment(&self) -> SubscriptionAmendmentTableHandle<'_>;
}

impl SubscriptionAmendmentTableAccess for super::RemoteTables {
    fn subscription_amendment(&self) -> SubscriptionAmendmentTableHandle<'_> {
        SubscriptionAmendmentTableHandle {
            imp: self
                .imp
                .get_table::<SubscriptionAmendment>("subscription_amendment"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SubscriptionAmendmentInsertCallbackId(__sdk::CallbackId);
pub struct SubscriptionAmendmentDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SubscriptionAmendmentTableHandle<'ctx> {
    type Row = SubscriptionAmendment;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SubscriptionAmendment> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SubscriptionAmendmentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SubscriptionAmendmentInsertCallbackId {
        SubscriptionAmendmentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SubscriptionAmendmentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SubscriptionAmendmentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SubscriptionAmendmentDeleteCallbackId {
        SubscriptionAmendmentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SubscriptionAmendmentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SubscriptionAmendmentUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SubscriptionAmendmentTableHandle<'ctx> {
    type UpdateCallbackId = SubscriptionAmendmentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SubscriptionAmendmentUpdateCallbackId {
        SubscriptionAmendmentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SubscriptionAmendmentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `subscription_amendment`,
/// which allows point queries on the field of the same name
/// via the [`SubscriptionAmendmentIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.subscription_amendment().id().find(...)`.
pub struct SubscriptionAmendmentIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SubscriptionAmendment, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SubscriptionAmendmentTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `subscription_amendment`.
    pub fn id(&self) -> SubscriptionAmendmentIdUnique<'ctx> {
        SubscriptionAmendmentIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SubscriptionAmendmentIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SubscriptionAmendment> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SubscriptionAmendment>("subscription_amendment");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SubscriptionAmendment>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SubscriptionAmendment>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SubscriptionAmendment`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait subscription_amendmentQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SubscriptionAmendment`.
    fn subscription_amendment(&self) -> __sdk::__query_builder::Table<SubscriptionAmendment>;
}

impl subscription_amendmentQueryTableAccess for __sdk::QueryTableAccessor {
    fn subscription_amendment(&self) -> __sdk::__query_builder::Table<SubscriptionAmendment> {
        __sdk::__query_builder::Table::new("subscription_amendment")
    }
}
