// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UnmatchEliminationEntryArgs {
    pub organization_id: u64,
    pub entry_id: u64,
}

impl From<UnmatchEliminationEntryArgs> for super::Reducer {
    fn from(args: UnmatchEliminationEntryArgs) -> Self {
        Self::UnmatchEliminationEntry {
            organization_id: args.organization_id,
            entry_id: args.entry_id,
        }
    }
}

impl __sdk::InModule for UnmatchEliminationEntryArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `unmatch_elimination_entry`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait unmatch_elimination_entry {
    /// Request that the remote module invoke the reducer `unmatch_elimination_entry` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`unmatch_elimination_entry:unmatch_elimination_entry_then`] to run a callback after the reducer completes.
    fn unmatch_elimination_entry(&self, organization_id: u64, entry_id: u64) -> __sdk::Result<()> {
        self.unmatch_elimination_entry_then(organization_id, entry_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `unmatch_elimination_entry` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn unmatch_elimination_entry_then(
        &self,
        organization_id: u64,
        entry_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl unmatch_elimination_entry for super::RemoteReducers {
    fn unmatch_elimination_entry_then(
        &self,
        organization_id: u64,
        entry_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UnmatchEliminationEntryArgs {
                organization_id,
                entry_id,
            },
            callback,
        )
    }
}
