// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::update_whats_app_credentials_params_type::UpdateWhatsAppCredentialsParams;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateWhatsappCredentialsArgs {
    pub organization_id: u64,
    pub account_id: u64,
    pub params: UpdateWhatsAppCredentialsParams,
}

impl From<UpdateWhatsappCredentialsArgs> for super::Reducer {
    fn from(args: UpdateWhatsappCredentialsArgs) -> Self {
        Self::UpdateWhatsappCredentials {
            organization_id: args.organization_id,
            account_id: args.account_id,
            params: args.params,
        }
    }
}

impl __sdk::InModule for UpdateWhatsappCredentialsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_whatsapp_credentials`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_whatsapp_credentials {
    /// Request that the remote module invoke the reducer `update_whatsapp_credentials` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_whatsapp_credentials:update_whatsapp_credentials_then`] to run a callback after the reducer completes.
    fn update_whatsapp_credentials(
        &self,
        organization_id: u64,
        account_id: u64,
        params: UpdateWhatsAppCredentialsParams,
    ) -> __sdk::Result<()> {
        self.update_whatsapp_credentials_then(organization_id, account_id, params, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_whatsapp_credentials` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_whatsapp_credentials_then(
        &self,
        organization_id: u64,
        account_id: u64,
        params: UpdateWhatsAppCredentialsParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_whatsapp_credentials for super::RemoteReducers {
    fn update_whatsapp_credentials_then(
        &self,
        organization_id: u64,
        account_id: u64,
        params: UpdateWhatsAppCredentialsParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateWhatsappCredentialsArgs {
                organization_id,
                account_id,
                params,
            },
            callback,
        )
    }
}
