// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UpdateContactCategoryParams {
    pub name: Option<String>,
    pub color: Option<Option<String>>,
    pub parent_id: Option<Option<u64>>,
    pub is_active: Option<bool>,
    pub metadata: Option<Option<String>>,
}

impl __sdk::InModule for UpdateContactCategoryParams {
    type Module = super::RemoteModule;
}
