// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::update_quality_team_params_type::UpdateQualityTeamParams;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateQualityTeamArgs {
    pub organization_id: u64,
    pub team_id: u64,
    pub params: UpdateQualityTeamParams,
}

impl From<UpdateQualityTeamArgs> for super::Reducer {
    fn from(args: UpdateQualityTeamArgs) -> Self {
        Self::UpdateQualityTeam {
            organization_id: args.organization_id,
            team_id: args.team_id,
            params: args.params,
        }
    }
}

impl __sdk::InModule for UpdateQualityTeamArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_quality_team`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_quality_team {
    /// Request that the remote module invoke the reducer `update_quality_team` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_quality_team:update_quality_team_then`] to run a callback after the reducer completes.
    fn update_quality_team(
        &self,
        organization_id: u64,
        team_id: u64,
        params: UpdateQualityTeamParams,
    ) -> __sdk::Result<()> {
        self.update_quality_team_then(organization_id, team_id, params, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_quality_team` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_quality_team_then(
        &self,
        organization_id: u64,
        team_id: u64,
        params: UpdateQualityTeamParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_quality_team for super::RemoteReducers {
    fn update_quality_team_then(
        &self,
        organization_id: u64,
        team_id: u64,
        params: UpdateQualityTeamParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateQualityTeamArgs {
                organization_id,
                team_id,
                params,
            },
            callback,
        )
    }
}
