// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateDeviceStatusArgs {
    pub organization_id: u64,
    pub device_id: u64,
    pub status: String,
}

impl From<UpdateDeviceStatusArgs> for super::Reducer {
    fn from(args: UpdateDeviceStatusArgs) -> Self {
        Self::UpdateDeviceStatus {
            organization_id: args.organization_id,
            device_id: args.device_id,
            status: args.status,
        }
    }
}

impl __sdk::InModule for UpdateDeviceStatusArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_device_status`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_device_status {
    /// Request that the remote module invoke the reducer `update_device_status` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_device_status:update_device_status_then`] to run a callback after the reducer completes.
    fn update_device_status(
        &self,
        organization_id: u64,
        device_id: u64,
        status: String,
    ) -> __sdk::Result<()> {
        self.update_device_status_then(organization_id, device_id, status, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_device_status` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_device_status_then(
        &self,
        organization_id: u64,
        device_id: u64,
        status: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_device_status for super::RemoteReducers {
    fn update_device_status_then(
        &self,
        organization_id: u64,
        device_id: u64,
        status: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateDeviceStatusArgs {
                organization_id,
                device_id,
                status,
            },
            callback,
        )
    }
}
