// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UpdatePurchaseOrderLineParams {
    pub product_id: Option<u64>,
    pub quantity: Option<f64>,
    pub uom_id: Option<u64>,
    pub price_unit: Option<f64>,
    pub tax_ids: Option<Vec<u64>>,
    pub date_planned: Option<__sdk::Timestamp>,
    pub product_variant_id: Option<u64>,
    pub account_analytic_id: Option<u64>,
    pub display_type: Option<String>,
    pub propagate_cancel: Option<bool>,
    pub metadata: Option<String>,
}

impl __sdk::InModule for UpdatePurchaseOrderLineParams {
    type Module = super::RemoteModule;
}
