// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::update_contact_core_params_type::UpdateContactCoreParams;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateContactArgs {
    pub organization_id: u64,
    pub contact_id: u64,
    pub params: UpdateContactCoreParams,
}

impl From<UpdateContactArgs> for super::Reducer {
    fn from(args: UpdateContactArgs) -> Self {
        Self::UpdateContact {
            organization_id: args.organization_id,
            contact_id: args.contact_id,
            params: args.params,
        }
    }
}

impl __sdk::InModule for UpdateContactArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_contact`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_contact {
    /// Request that the remote module invoke the reducer `update_contact` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_contact:update_contact_then`] to run a callback after the reducer completes.
    fn update_contact(
        &self,
        organization_id: u64,
        contact_id: u64,
        params: UpdateContactCoreParams,
    ) -> __sdk::Result<()> {
        self.update_contact_then(organization_id, contact_id, params, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_contact` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_contact_then(
        &self,
        organization_id: u64,
        contact_id: u64,
        params: UpdateContactCoreParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_contact for super::RemoteReducers {
    fn update_contact_then(
        &self,
        organization_id: u64,
        contact_id: u64,
        params: UpdateContactCoreParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateContactArgs {
                organization_id,
                contact_id,
                params,
            },
            callback,
        )
    }
}
