// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateWhatsappQualityScoreArgs {
    pub organization_id: u64,
    pub account_id: u64,
    pub quality_score: String,
}

impl From<UpdateWhatsappQualityScoreArgs> for super::Reducer {
    fn from(args: UpdateWhatsappQualityScoreArgs) -> Self {
        Self::UpdateWhatsappQualityScore {
            organization_id: args.organization_id,
            account_id: args.account_id,
            quality_score: args.quality_score,
        }
    }
}

impl __sdk::InModule for UpdateWhatsappQualityScoreArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_whatsapp_quality_score`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_whatsapp_quality_score {
    /// Request that the remote module invoke the reducer `update_whatsapp_quality_score` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_whatsapp_quality_score:update_whatsapp_quality_score_then`] to run a callback after the reducer completes.
    fn update_whatsapp_quality_score(
        &self,
        organization_id: u64,
        account_id: u64,
        quality_score: String,
    ) -> __sdk::Result<()> {
        self.update_whatsapp_quality_score_then(
            organization_id,
            account_id,
            quality_score,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `update_whatsapp_quality_score` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_whatsapp_quality_score_then(
        &self,
        organization_id: u64,
        account_id: u64,
        quality_score: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_whatsapp_quality_score for super::RemoteReducers {
    fn update_whatsapp_quality_score_then(
        &self,
        organization_id: u64,
        account_id: u64,
        quality_score: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateWhatsappQualityScoreArgs {
                organization_id,
                account_id,
                quality_score,
            },
            callback,
        )
    }
}
