// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::upsert_ai_skill_params_type::UpsertAiSkillParams;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertAiSkillArgs {
    pub organization_id: u64,
    pub params: UpsertAiSkillParams,
}

impl From<UpsertAiSkillArgs> for super::Reducer {
    fn from(args: UpsertAiSkillArgs) -> Self {
        Self::UpsertAiSkill {
            organization_id: args.organization_id,
            params: args.params,
        }
    }
}

impl __sdk::InModule for UpsertAiSkillArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_ai_skill`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_ai_skill {
    /// Request that the remote module invoke the reducer `upsert_ai_skill` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_ai_skill:upsert_ai_skill_then`] to run a callback after the reducer completes.
    fn upsert_ai_skill(
        &self,
        organization_id: u64,
        params: UpsertAiSkillParams,
    ) -> __sdk::Result<()> {
        self.upsert_ai_skill_then(organization_id, params, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `upsert_ai_skill` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_ai_skill_then(
        &self,
        organization_id: u64,
        params: UpsertAiSkillParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_ai_skill for super::RemoteReducers {
    fn upsert_ai_skill_then(
        &self,
        organization_id: u64,
        params: UpsertAiSkillParams,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpsertAiSkillArgs {
                organization_id,
                params,
            },
            callback,
        )
    }
}
