// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UpsertProposalProcurementScoreParams {
    pub country_pack_key: String,
    pub score_kind: String,
    pub score_value: f64,
    pub max_value: f64,
    pub notes: Option<String>,
}

impl __sdk::InModule for UpsertProposalProcurementScoreParams {
    type Module = super::RemoteModule;
}
