// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UserRoleAssignment {
    pub id: u64,
    pub user_identity: __sdk::Identity,
    pub role_id: u64,
    pub organization_id: u64,
    pub assigned_by: __sdk::Identity,
    pub assigned_at: __sdk::Timestamp,
    pub expires_at: Option<__sdk::Timestamp>,
    pub is_active: bool,
    pub metadata: Option<String>,
}

impl __sdk::InModule for UserRoleAssignment {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `UserRoleAssignment`.
///
/// Provides typed access to columns for query building.
pub struct UserRoleAssignmentCols {
    pub id: __sdk::__query_builder::Col<UserRoleAssignment, u64>,
    pub user_identity: __sdk::__query_builder::Col<UserRoleAssignment, __sdk::Identity>,
    pub role_id: __sdk::__query_builder::Col<UserRoleAssignment, u64>,
    pub organization_id: __sdk::__query_builder::Col<UserRoleAssignment, u64>,
    pub assigned_by: __sdk::__query_builder::Col<UserRoleAssignment, __sdk::Identity>,
    pub assigned_at: __sdk::__query_builder::Col<UserRoleAssignment, __sdk::Timestamp>,
    pub expires_at: __sdk::__query_builder::Col<UserRoleAssignment, Option<__sdk::Timestamp>>,
    pub is_active: __sdk::__query_builder::Col<UserRoleAssignment, bool>,
    pub metadata: __sdk::__query_builder::Col<UserRoleAssignment, Option<String>>,
}

impl __sdk::__query_builder::HasCols for UserRoleAssignment {
    type Cols = UserRoleAssignmentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        UserRoleAssignmentCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            user_identity: __sdk::__query_builder::Col::new(table_name, "user_identity"),
            role_id: __sdk::__query_builder::Col::new(table_name, "role_id"),
            organization_id: __sdk::__query_builder::Col::new(table_name, "organization_id"),
            assigned_by: __sdk::__query_builder::Col::new(table_name, "assigned_by"),
            assigned_at: __sdk::__query_builder::Col::new(table_name, "assigned_at"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
            is_active: __sdk::__query_builder::Col::new(table_name, "is_active"),
            metadata: __sdk::__query_builder::Col::new(table_name, "metadata"),
        }
    }
}

/// Indexed column accessor struct for the table `UserRoleAssignment`.
///
/// Provides typed access to indexed columns for query building.
pub struct UserRoleAssignmentIxCols {
    pub id: __sdk::__query_builder::IxCol<UserRoleAssignment, u64>,
    pub organization_id: __sdk::__query_builder::IxCol<UserRoleAssignment, u64>,
    pub user_identity: __sdk::__query_builder::IxCol<UserRoleAssignment, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for UserRoleAssignment {
    type IxCols = UserRoleAssignmentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        UserRoleAssignmentIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            organization_id: __sdk::__query_builder::IxCol::new(table_name, "organization_id"),
            user_identity: __sdk::__query_builder::IxCol::new(table_name, "user_identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for UserRoleAssignment {}
