// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::warehouse_task_type::WarehouseTask;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `warehouse_task`.
///
/// Obtain a handle from the [`WarehouseTaskTableAccess::warehouse_task`] method on [`super::RemoteTables`],
/// like `ctx.db.warehouse_task()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.warehouse_task().on_insert(...)`.
pub struct WarehouseTaskTableHandle<'ctx> {
    imp: __sdk::TableHandle<WarehouseTask>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `warehouse_task`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WarehouseTaskTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WarehouseTaskTableHandle`], which mediates access to the table `warehouse_task`.
    fn warehouse_task(&self) -> WarehouseTaskTableHandle<'_>;
}

impl WarehouseTaskTableAccess for super::RemoteTables {
    fn warehouse_task(&self) -> WarehouseTaskTableHandle<'_> {
        WarehouseTaskTableHandle {
            imp: self.imp.get_table::<WarehouseTask>("warehouse_task"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WarehouseTaskInsertCallbackId(__sdk::CallbackId);
pub struct WarehouseTaskDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for WarehouseTaskTableHandle<'ctx> {
    type Row = WarehouseTask;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WarehouseTask> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WarehouseTaskInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WarehouseTaskInsertCallbackId {
        WarehouseTaskInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WarehouseTaskInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WarehouseTaskDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WarehouseTaskDeleteCallbackId {
        WarehouseTaskDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WarehouseTaskDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct WarehouseTaskUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WarehouseTaskTableHandle<'ctx> {
    type UpdateCallbackId = WarehouseTaskUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WarehouseTaskUpdateCallbackId {
        WarehouseTaskUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WarehouseTaskUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `warehouse_task`,
/// which allows point queries on the field of the same name
/// via the [`WarehouseTaskIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.warehouse_task().id().find(...)`.
pub struct WarehouseTaskIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WarehouseTask, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WarehouseTaskTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `warehouse_task`.
    pub fn id(&self) -> WarehouseTaskIdUnique<'ctx> {
        WarehouseTaskIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WarehouseTaskIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<WarehouseTask> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WarehouseTask>("warehouse_task");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<WarehouseTask>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WarehouseTask>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `WarehouseTask`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait warehouse_taskQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `WarehouseTask`.
    fn warehouse_task(&self) -> __sdk::__query_builder::Table<WarehouseTask>;
}

impl warehouse_taskQueryTableAccess for __sdk::QueryTableAccessor {
    fn warehouse_task(&self) -> __sdk::__query_builder::Table<WarehouseTask> {
        __sdk::__query_builder::Table::new("warehouse_task")
    }
}
