// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::workflow_edge_migration_mapping_type::WorkflowEdgeMigrationMapping;
use super::workflow_fork_migration_mapping_type::WorkflowForkMigrationMapping;
use super::workflow_migration_compatibility_type::WorkflowMigrationCompatibility;
use super::workflow_migration_plan_type::WorkflowMigrationPlan;
use super::workflow_node_migration_mapping_type::WorkflowNodeMigrationMapping;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `workflow_migration_plan`.
///
/// Obtain a handle from the [`WorkflowMigrationPlanTableAccess::workflow_migration_plan`] method on [`super::RemoteTables`],
/// like `ctx.db.workflow_migration_plan()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.workflow_migration_plan().on_insert(...)`.
pub struct WorkflowMigrationPlanTableHandle<'ctx> {
    imp: __sdk::TableHandle<WorkflowMigrationPlan>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `workflow_migration_plan`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WorkflowMigrationPlanTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WorkflowMigrationPlanTableHandle`], which mediates access to the table `workflow_migration_plan`.
    fn workflow_migration_plan(&self) -> WorkflowMigrationPlanTableHandle<'_>;
}

impl WorkflowMigrationPlanTableAccess for super::RemoteTables {
    fn workflow_migration_plan(&self) -> WorkflowMigrationPlanTableHandle<'_> {
        WorkflowMigrationPlanTableHandle {
            imp: self
                .imp
                .get_table::<WorkflowMigrationPlan>("workflow_migration_plan"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WorkflowMigrationPlanInsertCallbackId(__sdk::CallbackId);
pub struct WorkflowMigrationPlanDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for WorkflowMigrationPlanTableHandle<'ctx> {
    type Row = WorkflowMigrationPlan;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorkflowMigrationPlan> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WorkflowMigrationPlanInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorkflowMigrationPlanInsertCallbackId {
        WorkflowMigrationPlanInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorkflowMigrationPlanInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WorkflowMigrationPlanDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorkflowMigrationPlanDeleteCallbackId {
        WorkflowMigrationPlanDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorkflowMigrationPlanDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct WorkflowMigrationPlanUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WorkflowMigrationPlanTableHandle<'ctx> {
    type UpdateCallbackId = WorkflowMigrationPlanUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WorkflowMigrationPlanUpdateCallbackId {
        WorkflowMigrationPlanUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WorkflowMigrationPlanUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `workflow_migration_plan`,
/// which allows point queries on the field of the same name
/// via the [`WorkflowMigrationPlanIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.workflow_migration_plan().id().find(...)`.
pub struct WorkflowMigrationPlanIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WorkflowMigrationPlan, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WorkflowMigrationPlanTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `workflow_migration_plan`.
    pub fn id(&self) -> WorkflowMigrationPlanIdUnique<'ctx> {
        WorkflowMigrationPlanIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WorkflowMigrationPlanIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<WorkflowMigrationPlan> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WorkflowMigrationPlan>("workflow_migration_plan");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<WorkflowMigrationPlan>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WorkflowMigrationPlan>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `WorkflowMigrationPlan`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait workflow_migration_planQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `WorkflowMigrationPlan`.
    fn workflow_migration_plan(&self) -> __sdk::__query_builder::Table<WorkflowMigrationPlan>;
}

impl workflow_migration_planQueryTableAccess for __sdk::QueryTableAccessor {
    fn workflow_migration_plan(&self) -> __sdk::__query_builder::Table<WorkflowMigrationPlan> {
        __sdk::__query_builder::Table::new("workflow_migration_plan")
    }
}
