//! Platform-control schema and bootstrap DDL.

use anyhow::{Context, Result};
use deadpool_postgres::Pool;

/// PostgreSQL schema containing global platform-control state.
pub const PLATFORM_SCHEMA: &str = "lumiere_platform";

/// The migration history table used by the API-server migration runner.
pub const SCHEMA_MIGRATION_TABLE: &str = "lumiere_platform.schema_migration";

/// Bootstrap DDL that is safe to run before the numbered migration history
/// can be read.  The remaining four tables are created by
/// [`PLATFORM_CONTROL_DDL`] as a numbered migration.
pub const PLATFORM_SCHEMA_BOOTSTRAP_DDL: &str = r#"
CREATE SCHEMA IF NOT EXISTS lumiere_platform;
CREATE TABLE IF NOT EXISTS lumiere_platform.schema_migration (
    version BIGINT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    change_set BIGINT NOT NULL,
    phase TEXT NOT NULL CHECK (phase IN ('expand', 'project_backfill', 'verify', 'contract')),
    checksum TEXT NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
"#;

/// DDL for platform-global state.  This is authored infrastructure, not a
/// generated ERP relation, and is applied by the durable migration runner.
pub const PLATFORM_CONTROL_DDL: &str = r#"
CREATE SCHEMA IF NOT EXISTS lumiere_platform;

CREATE TABLE IF NOT EXISTS lumiere_platform.schema_migration (
    version BIGINT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    change_set BIGINT NOT NULL,
    phase TEXT NOT NULL CHECK (phase IN ('expand', 'project_backfill', 'verify', 'contract')),
    checksum TEXT NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS lumiere_platform.cold_tier_service_identity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name TEXT NOT NULL,
    platform_id TEXT NOT NULL,
    stdb_identity_hex TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    registered_by TEXT NOT NULL,
    registered_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    retired_at TIMESTAMPTZ,
    CONSTRAINT cold_tier_service_identity_name_platform_unique
        UNIQUE (service_name, platform_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS cold_tier_service_identity_active_name
    ON lumiere_platform.cold_tier_service_identity (service_name)
    WHERE is_active;
CREATE INDEX IF NOT EXISTS cold_tier_service_identity_platform_idx
    ON lumiere_platform.cold_tier_service_identity (platform_id);

CREATE TABLE IF NOT EXISTS lumiere_platform.user_credential (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_user_id TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL,
    stdb_identity_hex TEXT NOT NULL UNIQUE,
    password_hash TEXT,
    workos_user_id TEXT UNIQUE,
    stdb_token_enc TEXT NOT NULL,
    email_verified BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS user_credential_email_lower_unique
    ON lumiere_platform.user_credential (lower(email));
CREATE INDEX IF NOT EXISTS user_credential_platform_user_idx
    ON lumiere_platform.user_credential (platform_user_id);

CREATE TABLE IF NOT EXISTS lumiere_platform.user_profile (
    platform_user_id TEXT PRIMARY KEY,
    stdb_identity_hex TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL,
    email_verified BOOLEAN NOT NULL DEFAULT false,
    name TEXT NOT NULL DEFAULT '',
    first_name TEXT,
    last_name TEXT,
    avatar_url TEXT,
    phone TEXT,
    mobile TEXT,
    timezone TEXT NOT NULL DEFAULT 'UTC',
    language TEXT NOT NULL DEFAULT 'en',
    signature TEXT,
    notification_preferences JSONB,
    ui_preferences JSONB,
    is_active BOOLEAN NOT NULL DEFAULT true,
    is_superuser BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_login TIMESTAMPTZ,
    metadata JSONB
);
CREATE UNIQUE INDEX IF NOT EXISTS user_profile_email_lower_unique
    ON lumiere_platform.user_profile (lower(email));
CREATE INDEX IF NOT EXISTS user_profile_stdb_identity_idx
    ON lumiere_platform.user_profile (stdb_identity_hex);

CREATE TABLE IF NOT EXISTS lumiere_platform.password_reset_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_reset_token_id TEXT NOT NULL UNIQUE,
    platform_user_id TEXT NOT NULL REFERENCES lumiere_platform.user_profile(platform_user_id),
    token_hash TEXT NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS password_reset_token_user_idx
    ON lumiere_platform.password_reset_token (platform_user_id);
CREATE INDEX IF NOT EXISTS password_reset_token_live_idx
    ON lumiere_platform.password_reset_token (token_hash)
    WHERE used_at IS NULL;
"#;

/// Forward-only migration for databases that applied the original platform
/// control schema before reset-token projections gained their own opaque ID.
pub const PLATFORM_RESET_TOKEN_BINDING_DDL: &str = r#"
ALTER TABLE lumiere_platform.password_reset_token
    ADD COLUMN IF NOT EXISTS platform_reset_token_id TEXT;
UPDATE lumiere_platform.password_reset_token
SET platform_reset_token_id = 'legacy_' || id::text
WHERE platform_reset_token_id IS NULL;
ALTER TABLE lumiere_platform.password_reset_token
    ALTER COLUMN platform_reset_token_id SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS password_reset_token_platform_id_unique
    ON lumiere_platform.password_reset_token (platform_reset_token_id);
"#;

/// Ensure only the platform schema exists before the migration history is
/// read.  The numbered migration runner remains the owner of all changes.
pub async fn ensure_schema(pool: &Pool) -> Result<()> {
    let client = pool
        .get()
        .await
        .context("get PG client for platform schema")?;
    client
        .batch_execute(PLATFORM_SCHEMA_BOOTSTRAP_DDL)
        .await
        .context("bootstrap platform-control schema")?;
    Ok(())
}
