import type { TFunction } from "i18next"
import type { FormConfig, HiddenField } from "./form-types"

const agentIdHidden: HiddenField = {
  type: "hidden",
  id: "agentId",
  name: "agentId",
  defaultValue: "",
  required: true,
}

function withAgentIdField(config: FormConfig): FormConfig {
  if (config.sections.length === 0) return config
  const [first, ...rest] = config.sections
  return {
    ...config,
    sections: [{ ...first, fields: [agentIdHidden, ...first.fields] }, ...rest],
  }
}

export function aiAgentCreateFormConfig(t: TFunction): FormConfig {
  return {
    id: "settings-ai-agent-create",
    title: t("settings.ai.createAgentTitle"),
    description: t("settings.ai.createAgentDescription"),
    size: "lg",
    submitLabel: t("settings.ai.create"),
    sections: [
      {
        id: "main",
        fields: [
          {
            type: "text",
            id: "name",
            name: "name",
            label: t("settings.ai.name"),
            required: true,
            width: "full",
            defaultValue: "",
            validation: { minLength: 1 },
          },
          {
            type: "select",
            id: "provider",
            name: "provider",
            label: t("settings.ai.provider"),
            required: true,
            width: "1/2",
            defaultValue: "Mistral",
            options: [
              { value: "Mistral", label: "Mistral" },
              { value: "Gemini", label: "Google Gemini" },
              { value: "Ollama", label: "Ollama" },
            ],
          },
          {
            type: "text",
            id: "model",
            name: "model",
            label: t("settings.ai.model"),
            required: true,
            width: "1/2",
            defaultValue: "mistral-small-latest",
            placeholder: "mistral-small-latest | gemini-2.0-flash | llama3.2",
            validation: { minLength: 1 },
          },
          {
            type: "text",
            id: "description",
            name: "description",
            label: t("settings.ai.description"),
            width: "full",
            defaultValue: "",
          },
          {
            type: "textarea",
            id: "systemPrompt",
            name: "systemPrompt",
            label: t("settings.ai.systemPrompt"),
            width: "full",
            rows: 3,
            defaultValue: "",
          },
          {
            type: "number",
            id: "temperature",
            name: "temperature",
            label: t("settings.ai.temperature"),
            width: "1/2",
            step: 0.1,
            min: 0,
            max: 2,
            defaultValue: 0.7,
          },
          {
            type: "number",
            id: "maxTokens",
            name: "maxTokens",
            label: t("settings.ai.maxTokens"),
            width: "1/2",
            defaultValue: 4096,
            min: 1,
          },
          {
            type: "number",
            id: "rateLimitPerMinute",
            name: "rateLimitPerMinute",
            label: t("settings.ai.rateLimit"),
            width: "1/2",
            defaultValue: 60,
            min: 1,
          },
          {
            type: "number",
            id: "contextWindow",
            name: "contextWindow",
            label: t("settings.ai.contextWindow"),
            width: "1/2",
            defaultValue: 128000,
            min: 1,
          },
          {
            type: "number",
            id: "topP",
            name: "topP",
            label: t("settings.ai.topP"),
            width: "1/2",
            step: 0.01,
            min: 0,
            max: 1,
            defaultValue: 1,
          },
          {
            type: "number",
            id: "frequencyPenalty",
            name: "frequencyPenalty",
            label: t("settings.ai.frequencyPenalty"),
            width: "1/2",
            step: 0.1,
            min: -2,
            max: 2,
            defaultValue: 0,
          },
          {
            type: "number",
            id: "presencePenalty",
            name: "presencePenalty",
            label: t("settings.ai.presencePenalty"),
            width: "1/2",
            step: 0.1,
            min: -2,
            max: 2,
            defaultValue: 0,
          },
          {
            type: "number",
            id: "costPer1KTokens",
            name: "costPer1KTokens",
            label: t("settings.ai.costPer1K"),
            width: "1/2",
            step: 0.0001,
            min: 0,
            defaultValue: 0.005,
          },
          {
            type: "number",
            id: "monthlyBudget",
            name: "monthlyBudget",
            label: t("settings.ai.monthlyBudget"),
            placeholder: t("settings.ai.optional"),
            width: "1/2",
            step: 0.01,
            min: 0,
          },
        ],
      },
    ],
  }
}

export function aiAgentEditFormConfig(t: TFunction): FormConfig {
  return withAgentIdField({
    id: "settings-ai-agent-edit",
    title: t("settings.ai.editAgentTitle"),
    size: "lg",
    submitLabel: t("settings.formConfig.saveChanges"),
    sections: [
      {
        id: "main",
        fields: [
          {
            type: "number",
            id: "temperature",
            name: "temperature",
            label: t("settings.ai.temperature"),
            width: "1/2",
            step: 0.1,
            min: 0,
            max: 2,
            defaultValue: 0.7,
          },
          {
            type: "number",
            id: "maxTokens",
            name: "maxTokens",
            label: t("settings.ai.maxTokens"),
            width: "1/2",
            defaultValue: 4096,
            min: 1,
          },
          {
            type: "number",
            id: "rateLimitPerMinute",
            name: "rateLimitPerMinute",
            label: t("settings.ai.rateLimit"),
            width: "full",
            defaultValue: 60,
            min: 1,
          },
          {
            type: "text",
            id: "contextWindow",
            name: "contextWindow",
            label: t("settings.ai.contextWindow"),
            placeholder: t("settings.ai.optionalLeaveUnchanged"),
            width: "1/2",
            defaultValue: "",
          },
          {
            type: "text",
            id: "topP",
            name: "topP",
            label: t("settings.ai.topP"),
            placeholder: t("settings.ai.optionalLeaveUnchanged"),
            width: "1/2",
            defaultValue: "",
          },
          {
            type: "text",
            id: "frequencyPenalty",
            name: "frequencyPenalty",
            label: t("settings.ai.frequencyPenalty"),
            placeholder: t("settings.ai.optionalLeaveUnchanged"),
            width: "1/2",
            defaultValue: "",
          },
          {
            type: "text",
            id: "presencePenalty",
            name: "presencePenalty",
            label: t("settings.ai.presencePenalty"),
            placeholder: t("settings.ai.optionalLeaveUnchanged"),
            width: "1/2",
            defaultValue: "",
          },
          {
            type: "textarea",
            id: "systemPrompt",
            name: "systemPrompt",
            label: t("settings.ai.systemPrompt"),
            width: "full",
            rows: 4,
            defaultValue: "",
          },
          {
            type: "text",
            id: "monthlyBudget",
            name: "monthlyBudget",
            label: t("settings.ai.monthlyBudget"),
            placeholder: t("settings.ai.optional"),
            width: "full",
            defaultValue: "",
          },
        ],
      },
    ],
  })
}
