import type { TFunction } from "i18next"
import type { FormConfig } from "./form-types"

const emptySelect: Array<{ value: string; label: string; disabled?: boolean }> = []

export const newExpenseForm = (t: TFunction): FormConfig => ({
  id: "new-expense",
  title: t("expenses.forms.newExpense.title"),
  description: t("expenses.forms.newExpense.description"),
  sections: [
    {
      id: "expense-details",
      title: t("expenses.forms.newExpense.sections.expenseDetails"),
      fields: [
        {
          id: "pricelistId",
          name: "pricelistId",
          type: "select",
          label: t("expenses.forms.newExpense.fields.pricelistId"),
          placeholder: t("expenses.forms.newExpense.fields.pricelistPlaceholder"),
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("expenses.forms.newExpense.fields.name"),
          placeholder: t("expenses.forms.newExpense.fields.namePlaceholder"),
          required: true,
          width: "full",
        },
        {
          id: "totalAmount",
          name: "totalAmount",
          type: "number",
          label: t("expenses.forms.newExpense.fields.totalAmount"),
          placeholder: "0.00",
          required: true,
          width: "1/2",
        },
        {
          id: "date",
          name: "date",
          type: "date",
          label: t("expenses.forms.newExpense.fields.date"),
          required: true,
          width: "1/2",
        },
        {
          id: "employeeId",
          name: "employeeId",
          type: "select",
          label: t("expenses.forms.newExpense.fields.employeeId"),
          placeholder: t("expenses.forms.newExpense.fields.employeePlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "quantity",
          name: "quantity",
          type: "number",
          label: t("expenses.forms.newExpense.fields.quantity"),
          placeholder: "1",
          width: "1/2",
        },
        {
          id: "lineKind",
          name: "lineKind",
          type: "select",
          label: t("expenses.forms.newExpense.fields.lineKind"),
          required: true,
          width: "1/2",
          defaultValue: "Standard",
          options: [
            { value: "Standard", label: t("expenses.forms.newExpense.fields.lineKindStandard") },
            { value: "Mileage", label: t("expenses.forms.newExpense.fields.lineKindMileage") },
            { value: "PerDiem", label: t("expenses.forms.newExpense.fields.lineKindPerDiem") },
          ],
        },
        {
          id: "projectId",
          name: "projectId",
          type: "text",
          label: t("expenses.forms.newExpense.fields.projectId"),
          placeholder: t("expenses.forms.newExpense.fields.projectIdPlaceholder"),
          width: "1/2",
        },
        {
          id: "mileageDistance",
          name: "mileageDistance",
          type: "number",
          label: t("expenses.forms.newExpense.fields.mileageDistance"),
          placeholder: "0",
          width: "1/2",
        },
        {
          id: "mileageRateId",
          name: "mileageRateId",
          type: "select",
          label: t("expenses.forms.newExpense.fields.mileageRateId"),
          placeholder: t("expenses.forms.newExpense.fields.rateIdPlaceholder"),
          width: "1/2",
          options: [],
        },
        {
          id: "perDiemDays",
          name: "perDiemDays",
          type: "number",
          label: t("expenses.forms.newExpense.fields.perDiemDays"),
          placeholder: "0",
          width: "1/2",
        },
        {
          id: "perDiemRateId",
          name: "perDiemRateId",
          type: "select",
          label: t("expenses.forms.newExpense.fields.perDiemRateId"),
          placeholder: t("expenses.forms.newExpense.fields.rateIdPlaceholder"),
          width: "1/2",
          options: [],
        },
        {
          id: "productId",
          name: "productId",
          type: "text",
          label: t("expenses.forms.newExpense.fields.productId"),
          placeholder: t("expenses.forms.newExpense.fields.productPlaceholder"),
          width: "1/2",
        },
        {
          id: "taxIds",
          name: "taxIds",
          type: "textarea",
          label: t("expenses.forms.newExpense.fields.taxIds"),
          placeholder: t("expenses.forms.newExpense.fields.taxIdsPlaceholder"),
          width: "1/2",
          rows: 2,
        },
        {
          id: "paymentMode",
          name: "paymentMode",
          type: "select",
          label: t("expenses.forms.newExpense.fields.paymentMode"),
          required: true,
          width: "1/2",
          defaultValue: "OutOfPocket",
          options: [
            {
              value: "OutOfPocket",
              label: t("expenses.forms.newExpense.fields.paymentModeOutOfPocket"),
            },
            {
              value: "CorporateCard",
              label: t("expenses.forms.newExpense.fields.paymentModeCorporateCard"),
            },
          ],
        },
        {
          id: "merchantKey",
          name: "merchantKey",
          type: "text",
          label: t("expenses.forms.newExpense.fields.merchantKey"),
          placeholder: t("expenses.forms.newExpense.fields.merchantKeyPlaceholder"),
          width: "1/2",
        },
        {
          id: "description",
          name: "description",
          type: "textarea",
          label: t("expenses.forms.newExpense.fields.description"),
          placeholder: t("expenses.forms.newExpense.fields.descriptionPlaceholder"),
          width: "full",
          rows: 2,
        },
        {
          id: "storageKey",
          name: "storageKey",
          type: "text",
          label: t("expenses.forms.newExpense.fields.storageKey"),
          placeholder: t("expenses.forms.newExpense.fields.storageKeyPlaceholder"),
          width: "full",
        },
        {
          id: "hasReceipt",
          name: "hasReceipt",
          type: "checkbox",
          label: t("expenses.forms.newExpense.fields.hasReceipt"),
          width: "full",
          defaultValue: true,
        },
      ],
    },
  ],
})

export const newExpenseSheetForm = (t: TFunction): FormConfig => ({
  id: "new-expense-sheet",
  title: t("expenses.forms.newExpenseReport.title"),
  description: t("expenses.forms.newExpenseReport.description"),
  sections: [
    {
      id: "sheet-info",
      title: t("expenses.forms.newExpenseReport.sections.reportDetails"),
      fields: [
        {
          id: "pricelistId",
          name: "pricelistId",
          type: "select",
          label: t("expenses.forms.newExpenseReport.fields.pricelistId"),
          placeholder: t("expenses.forms.newExpenseReport.fields.pricelistPlaceholder"),
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("expenses.forms.newExpenseReport.fields.name"),
          placeholder: t("expenses.forms.newExpenseReport.fields.namePlaceholder"),
          required: true,
          width: "full",
        },
        {
          id: "employeeId",
          name: "employeeId",
          type: "select",
          label: t("expenses.forms.newExpenseReport.fields.employeeId"),
          placeholder: t("expenses.forms.newExpenseReport.fields.employeePlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "accountingDate",
          name: "accountingDate",
          type: "date",
          label: t("expenses.forms.newExpenseReport.fields.accountingDate"),
          width: "1/2",
        },
        {
          id: "notes",
          name: "notes",
          type: "textarea",
          label: t("expenses.forms.newExpenseReport.fields.notes"),
          placeholder: t("expenses.forms.newExpenseReport.fields.notesPlaceholder"),
          width: "full",
          rows: 2,
        },
      ],
    },
  ],
})

export const editExpenseForm = (t: TFunction): FormConfig => ({
  id: "edit-expense",
  title: t("expenses.forms.editExpense.title"),
  description: t("expenses.forms.editExpense.description"),
  sections: [
    {
      id: "edit-expense-details",
      title: t("expenses.forms.editExpense.sections.details"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("expenses.forms.editExpense.fields.name"),
          required: true,
          width: "full",
        },
        {
          id: "unitAmount",
          name: "unitAmount",
          type: "number",
          label: t("expenses.forms.editExpense.fields.unitAmount"),
          placeholder: "0.00",
          required: true,
          width: "1/2",
        },
        {
          id: "quantity",
          name: "quantity",
          type: "number",
          label: t("expenses.forms.editExpense.fields.quantity"),
          placeholder: "1",
          required: true,
          width: "1/2",
        },
        {
          id: "mileageDistance",
          name: "mileageDistance",
          type: "number",
          label: t("expenses.forms.newExpense.fields.mileageDistance"),
          placeholder: "0",
          width: "1/2",
        },
        {
          id: "mileageRateId",
          name: "mileageRateId",
          type: "select",
          label: t("expenses.forms.newExpense.fields.mileageRateId"),
          placeholder: t("expenses.forms.newExpense.fields.rateIdPlaceholder"),
          width: "1/2",
          options: [],
        },
        {
          id: "perDiemDays",
          name: "perDiemDays",
          type: "number",
          label: t("expenses.forms.newExpense.fields.perDiemDays"),
          placeholder: "0",
          width: "1/2",
        },
        {
          id: "perDiemRateId",
          name: "perDiemRateId",
          type: "select",
          label: t("expenses.forms.newExpense.fields.perDiemRateId"),
          placeholder: t("expenses.forms.newExpense.fields.rateIdPlaceholder"),
          width: "1/2",
          options: [],
        },
        {
          id: "productId",
          name: "productId",
          type: "text",
          label: t("expenses.forms.editExpense.fields.productId"),
          placeholder: t("expenses.forms.newExpense.fields.productPlaceholder"),
          width: "1/2",
        },
        {
          id: "taxIds",
          name: "taxIds",
          type: "textarea",
          label: t("expenses.forms.editExpense.fields.taxIds"),
          placeholder: t("expenses.forms.newExpense.fields.taxIdsPlaceholder"),
          width: "1/2",
          rows: 2,
        },
        {
          id: "paymentMode",
          name: "paymentMode",
          type: "select",
          label: t("expenses.forms.editExpense.fields.paymentMode"),
          width: "1/2",
          defaultValue: "OutOfPocket",
          options: [
            {
              value: "OutOfPocket",
              label: t("expenses.forms.newExpense.fields.paymentModeOutOfPocket"),
            },
            {
              value: "CorporateCard",
              label: t("expenses.forms.newExpense.fields.paymentModeCorporateCard"),
            },
          ],
        },
        {
          id: "merchantKey",
          name: "merchantKey",
          type: "text",
          label: t("expenses.forms.editExpense.fields.merchantKey"),
          placeholder: t("expenses.forms.newExpense.fields.merchantKeyPlaceholder"),
          width: "1/2",
        },
        {
          id: "storageKey",
          name: "storageKey",
          type: "text",
          label: t("expenses.forms.newExpense.fields.storageKey"),
          placeholder: t("expenses.forms.newExpense.fields.storageKeyPlaceholder"),
          width: "full",
        },
        {
          id: "hasReceipt",
          name: "hasReceipt",
          type: "checkbox",
          label: t("expenses.forms.editExpense.fields.hasReceipt"),
          width: "full",
          defaultValue: true,
        },
        {
          id: "description",
          name: "description",
          type: "textarea",
          label: t("expenses.forms.editExpense.fields.description"),
          width: "full",
          rows: 2,
        },
      ],
    },
  ],
})

export const addExpenseToReportForm = (t: TFunction): FormConfig => ({
  id: "add-expense-to-report",
  title: t("expenses.forms.addToReport.title"),
  description: t("expenses.forms.addToReport.description"),
  sections: [
    {
      id: "sheet-pick",
      title: t("expenses.forms.addToReport.sections.sheet"),
      fields: [
        {
          id: "sheetId",
          name: "sheetId",
          type: "select",
          label: t("expenses.forms.addToReport.fields.sheetId"),
          placeholder: t("expenses.forms.addToReport.fields.sheetPlaceholder"),
          required: true,
          width: "full",
          options: emptySelect,
        },
      ],
    },
  ],
})

export const postExpenseReportForm = (t: TFunction): FormConfig => ({
  id: "post-expense-report",
  title: t("expenses.forms.postReport.title"),
  description: t("expenses.forms.postReport.description"),
  sections: [
    {
      id: "post-accounts",
      title: t("expenses.forms.postReport.sections.accounts"),
      fields: [
        {
          id: "accountingDate",
          name: "accountingDate",
          type: "date",
          label: t("expenses.forms.postReport.fields.accountingDate"),
          required: true,
          width: "full",
        },
        {
          id: "journalId",
          name: "journalId",
          type: "select",
          label: t("expenses.forms.postReport.fields.journalId"),
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "defaultExpenseAccountId",
          name: "defaultExpenseAccountId",
          type: "select",
          label: t("expenses.forms.postReport.fields.defaultExpenseAccountId"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "payableAccountId",
          name: "payableAccountId",
          type: "select",
          label: t("expenses.forms.postReport.fields.payableAccountId"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "defaultTaxAccountId",
          name: "defaultTaxAccountId",
          type: "select",
          label: t("expenses.forms.postReport.fields.defaultTaxAccountId"),
          required: false,
          width: "full",
          options: emptySelect,
        },
        {
          id: "cardLiabilityAccountId",
          name: "cardLiabilityAccountId",
          type: "select",
          label: t("expenses.forms.postReport.fields.cardLiabilityAccountId"),
          required: false,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "advanceAccountId",
          name: "advanceAccountId",
          type: "select",
          label: t("expenses.forms.postReport.fields.advanceAccountId"),
          required: false,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "fxFeeAccountId",
          name: "fxFeeAccountId",
          type: "select",
          label: t("expenses.forms.postReport.fields.fxFeeAccountId"),
          required: false,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "fxFeeAmount",
          name: "fxFeeAmount",
          type: "number",
          label: t("expenses.forms.postReport.fields.fxFeeAmount"),
          required: false,
          width: "1/2",
        },
      ],
    },
  ],
})

export const reimburseExpenseReportForm = (t: TFunction): FormConfig => ({
  id: "reimburse-expense-report",
  title: t("expenses.forms.reimburseReport.title"),
  description: t("expenses.forms.reimburseReport.description"),
  sections: [
    {
      id: "reimburse-accounts",
      title: t("expenses.forms.reimburseReport.sections.accounts"),
      fields: [
        {
          id: "paymentDate",
          name: "paymentDate",
          type: "date",
          label: t("expenses.forms.reimburseReport.fields.paymentDate"),
          required: true,
          width: "full",
        },
        {
          id: "journalId",
          name: "journalId",
          type: "select",
          label: t("expenses.forms.reimburseReport.fields.journalId"),
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "payableAccountId",
          name: "payableAccountId",
          type: "select",
          label: t("expenses.forms.reimburseReport.fields.payableAccountId"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "liquidityAccountId",
          name: "liquidityAccountId",
          type: "select",
          label: t("expenses.forms.reimburseReport.fields.liquidityAccountId"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "amount",
          name: "amount",
          type: "number",
          label: t("expenses.forms.reimburseReport.fields.amount", {
            defaultValue: "Amount (optional partial)",
          }),
          required: false,
          width: "full",
          description: t("expenses.forms.reimburseReport.fields.amountHint", {
            defaultValue: "Leave empty to pay the full residual. Partial leaves the report Posted.",
          }),
        },
      ],
    },
  ],
})

function allocationLineFields(t: TFunction, n: 1 | 2 | 3 | 4) {
  const required = n === 1
  return [
    {
      id: `analyticAccountId${n}`,
      name: `analyticAccountId${n}`,
      type: "text" as const,
      label: t(`expenses.forms.setAllocations.fields.analyticAccountId${n}`),
      width: "1/2" as const,
    },
    {
      id: `projectId${n}`,
      name: `projectId${n}`,
      type: "text" as const,
      label: t(`expenses.forms.setAllocations.fields.projectId${n}`),
      width: "1/2" as const,
    },
    {
      id: `sharePercent${n}`,
      name: `sharePercent${n}`,
      type: "number" as const,
      label: t(`expenses.forms.setAllocations.fields.sharePercent${n}`),
      required,
      defaultValue: n === 1 ? 100 : undefined,
      width: "1/2" as const,
    },
    {
      id: `billable${n}`,
      name: `billable${n}`,
      type: "checkbox" as const,
      label: t(`expenses.forms.setAllocations.fields.billable${n}`),
      defaultValue: n === 1,
      width: "1/2" as const,
    },
  ]
}

export const setExpenseAllocationsForm = (t: TFunction): FormConfig => ({
  id: "set-expense-allocations",
  title: t("expenses.forms.setAllocations.title"),
  description: t("expenses.forms.setAllocations.description"),
  sections: [
    {
      id: "allocation-lines",
      title: t("expenses.forms.setAllocations.sections.lines"),
      fields: [
        ...allocationLineFields(t, 1),
        ...allocationLineFields(t, 2),
        ...allocationLineFields(t, 3),
        ...allocationLineFields(t, 4),
      ],
    },
  ],
})

export const upsertExpenseMileageRateForm = (t: TFunction): FormConfig => ({
  id: "upsert-expense-mileage-rate",
  title: t("expenses.forms.upsertMileageRate.title"),
  description: t("expenses.forms.upsertMileageRate.description"),
  sections: [
    {
      id: "mileage-rate",
      title: t("expenses.forms.upsertMileageRate.sections.rate"),
      fields: [
        {
          id: "rateId",
          name: "rateId",
          type: "text",
          label: t("expenses.forms.upsertMileageRate.fields.rateId"),
          width: "1/2",
        },
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("expenses.forms.upsertMileageRate.fields.name"),
          required: true,
          width: "1/2",
        },
        {
          id: "currencyId",
          name: "currencyId",
          type: "select",
          label: t("expenses.forms.upsertMileageRate.fields.currencyId"),
          required: true,
          options: [],
          width: "1/2",
        },
        {
          id: "ratePerUnit",
          name: "ratePerUnit",
          type: "number",
          label: t("expenses.forms.upsertMileageRate.fields.ratePerUnit"),
          required: true,
          width: "1/2",
        },
        {
          id: "unit",
          name: "unit",
          type: "select",
          label: t("expenses.forms.upsertMileageRate.fields.unit"),
          required: true,
          defaultValue: "km",
          width: "1/2",
          options: [
            { value: "km", label: "km" },
            { value: "mi", label: "mi" },
          ],
        },
        {
          id: "effectiveFrom",
          name: "effectiveFrom",
          type: "date",
          label: t("expenses.forms.upsertMileageRate.fields.effectiveFrom"),
          width: "1/2",
        },
        {
          id: "effectiveTo",
          name: "effectiveTo",
          type: "date",
          label: t("expenses.forms.upsertMileageRate.fields.effectiveTo"),
          width: "1/2",
        },
        {
          id: "active",
          name: "active",
          type: "checkbox",
          label: t("expenses.forms.upsertMileageRate.fields.active"),
          defaultValue: true,
          width: "full",
        },
      ],
    },
  ],
})

export const upsertExpensePerDiemRateForm = (t: TFunction): FormConfig => ({
  id: "upsert-expense-per-diem-rate",
  title: t("expenses.forms.upsertPerDiemRate.title"),
  description: t("expenses.forms.upsertPerDiemRate.description"),
  sections: [
    {
      id: "per-diem-rate",
      title: t("expenses.forms.upsertPerDiemRate.sections.rate"),
      fields: [
        {
          id: "rateId",
          name: "rateId",
          type: "text",
          label: t("expenses.forms.upsertPerDiemRate.fields.rateId"),
          width: "1/2",
        },
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("expenses.forms.upsertPerDiemRate.fields.name"),
          required: true,
          width: "1/2",
        },
        {
          id: "locationCode",
          name: "locationCode",
          type: "text",
          label: t("expenses.forms.upsertPerDiemRate.fields.locationCode"),
          required: true,
          width: "1/2",
        },
        {
          id: "currencyId",
          name: "currencyId",
          type: "select",
          label: t("expenses.forms.upsertPerDiemRate.fields.currencyId"),
          required: true,
          options: [],
          width: "1/2",
        },
        {
          id: "amountPerDay",
          name: "amountPerDay",
          type: "number",
          label: t("expenses.forms.upsertPerDiemRate.fields.amountPerDay"),
          required: true,
          width: "1/2",
        },
        {
          id: "effectiveFrom",
          name: "effectiveFrom",
          type: "date",
          label: t("expenses.forms.upsertPerDiemRate.fields.effectiveFrom"),
          width: "1/2",
        },
        {
          id: "effectiveTo",
          name: "effectiveTo",
          type: "date",
          label: t("expenses.forms.upsertPerDiemRate.fields.effectiveTo"),
          width: "1/2",
        },
        {
          id: "active",
          name: "active",
          type: "checkbox",
          label: t("expenses.forms.upsertPerDiemRate.fields.active"),
          defaultValue: true,
          width: "full",
        },
      ],
    },
  ],
})

export const projectRebillExpenseReportForm = (t: TFunction): FormConfig => ({
  id: "project-rebill-expense-report",
  title: t("expenses.forms.projectRebill.title"),
  description: t("expenses.forms.projectRebill.description"),
  sections: [
    {
      id: "rebill-accounts",
      title: t("expenses.forms.projectRebill.sections.accounts"),
      fields: [
        {
          id: "invoiceDate",
          name: "invoiceDate",
          type: "date",
          label: t("expenses.forms.projectRebill.fields.invoiceDate"),
          required: true,
          width: "full",
        },
        {
          id: "journalId",
          name: "journalId",
          type: "select",
          label: t("expenses.forms.projectRebill.fields.journalId"),
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "receivableAccountId",
          name: "receivableAccountId",
          type: "select",
          label: t("expenses.forms.projectRebill.fields.receivableAccountId"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "incomeAccountId",
          name: "incomeAccountId",
          type: "select",
          label: t("expenses.forms.projectRebill.fields.incomeAccountId"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
      ],
    },
  ],
})

export const expensesFormConfigs = (t: TFunction): Record<string, FormConfig> => ({
  "new-expense": newExpenseForm(t),
  "new-expense-sheet": newExpenseSheetForm(t),
  "edit-expense": editExpenseForm(t),
  "add-expense-to-report": addExpenseToReportForm(t),
  "post-expense-report": postExpenseReportForm(t),
  "reimburse-expense-report": reimburseExpenseReportForm(t),
  "set-expense-allocations": setExpenseAllocationsForm(t),
  "project-rebill-expense-report": projectRebillExpenseReportForm(t),
  "upsert-expense-mileage-rate": upsertExpenseMileageRateForm(t),
  "upsert-expense-per-diem-rate": upsertExpensePerDiemRateForm(t),
})
