import type { TFunction } from "i18next"
import type { FormConfig } from "./form-types"

const emptySelect: Array<{ value: string; label: string; disabled?: boolean }> = []

export const newExpenseForm = (t: TFunction): FormConfig => ({
  id: "new-expense",
  title: t("expenses.forms.newExpense.title"),
  description: t("expenses.forms.newExpense.description"),
  sections: [
    {
      id: "expense-details",
      title: t("expenses.forms.newExpense.sections.expenseDetails"),
      fields: [
        {
          id: "pricelistId",
          name: "pricelistId",
          type: "select",
          label: t("expenses.forms.newExpense.fields.pricelistId"),
          placeholder: t("expenses.forms.newExpense.fields.pricelistPlaceholder"),
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("expenses.forms.newExpense.fields.name"),
          placeholder: t("expenses.forms.newExpense.fields.namePlaceholder"),
          required: true,
          width: "full",
        },
        {
          id: "totalAmount",
          name: "totalAmount",
          type: "number",
          label: t("expenses.forms.newExpense.fields.totalAmount"),
          placeholder: "0.00",
          required: true,
          width: "1/2",
        },
        {
          id: "date",
          name: "date",
          type: "date",
          label: t("expenses.forms.newExpense.fields.date"),
          required: true,
          width: "1/2",
        },
        {
          id: "employeeId",
          name: "employeeId",
          type: "select",
          label: t("expenses.forms.newExpense.fields.employeeId"),
          placeholder: t("expenses.forms.newExpense.fields.employeePlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "quantity",
          name: "quantity",
          type: "number",
          label: t("expenses.forms.newExpense.fields.quantity"),
          placeholder: "1",
          width: "1/2",
        },
        {
          id: "lineKind",
          name: "lineKind",
          type: "select",
          label: t("expenses.forms.newExpense.fields.lineKind"),
          required: true,
          width: "1/2",
          defaultValue: "Standard",
          options: [
            { value: "Standard", label: t("expenses.forms.newExpense.fields.lineKindStandard") },
            { value: "Mileage", label: t("expenses.forms.newExpense.fields.lineKindMileage") },
            { value: "PerDiem", label: t("expenses.forms.newExpense.fields.lineKindPerDiem") },
          ],
        },
        {
          id: "projectId",
          name: "projectId",
          type: "text",
          label: t("expenses.forms.newExpense.fields.projectId"),
          placeholder: t("expenses.forms.newExpense.fields.projectIdPlaceholder"),
          width: "1/2",
        },
        {
          id: "mileageDistance",
          name: "mileageDistance",
          type: "number",
          label: t("expenses.forms.newExpense.fields.mileageDistance"),
          placeholder: "0",
          width: "1/2",
        },
        {
          id: "mileageRateId",
          name: "mileageRateId",
          type: "text",
          label: t("expenses.forms.newExpense.fields.mileageRateId"),
          placeholder: t("expenses.forms.newExpense.fields.rateIdPlaceholder"),
          width: "1/2",
        },
        {
          id: "perDiemDays",
          name: "perDiemDays",
          type: "number",
          label: t("expenses.forms.newExpense.fields.perDiemDays"),
          placeholder: "0",
          width: "1/2",
        },
        {
          id: "perDiemRateId",
          name: "perDiemRateId",
          type: "text",
          label: t("expenses.forms.newExpense.fields.perDiemRateId"),
          placeholder: t("expenses.forms.newExpense.fields.rateIdPlaceholder"),
          width: "1/2",
        },
        {
          id: "description",
          name: "description",
          type: "textarea",
          label: t("expenses.forms.newExpense.fields.description"),
          placeholder: t("expenses.forms.newExpense.fields.descriptionPlaceholder"),
          width: "full",
          rows: 2,
        },
        {
          id: "hasReceipt",
          name: "hasReceipt",
          type: "checkbox",
          label: t("expenses.forms.newExpense.fields.hasReceipt"),
          width: "full",
          defaultValue: true,
        },
      ],
    },
  ],
})

export const newExpenseSheetForm = (t: TFunction): FormConfig => ({
  id: "new-expense-sheet",
  title: t("expenses.forms.newExpenseReport.title"),
  description: t("expenses.forms.newExpenseReport.description"),
  sections: [
    {
      id: "sheet-info",
      title: t("expenses.forms.newExpenseReport.sections.reportDetails"),
      fields: [
        {
          id: "pricelistId",
          name: "pricelistId",
          type: "select",
          label: t("expenses.forms.newExpenseReport.fields.pricelistId"),
          placeholder: t("expenses.forms.newExpenseReport.fields.pricelistPlaceholder"),
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("expenses.forms.newExpenseReport.fields.name"),
          placeholder: t("expenses.forms.newExpenseReport.fields.namePlaceholder"),
          required: true,
          width: "full",
        },
        {
          id: "employeeId",
          name: "employeeId",
          type: "select",
          label: t("expenses.forms.newExpenseReport.fields.employeeId"),
          placeholder: t("expenses.forms.newExpenseReport.fields.employeePlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "accountingDate",
          name: "accountingDate",
          type: "date",
          label: t("expenses.forms.newExpenseReport.fields.accountingDate"),
          width: "1/2",
        },
        {
          id: "notes",
          name: "notes",
          type: "textarea",
          label: t("expenses.forms.newExpenseReport.fields.notes"),
          placeholder: t("expenses.forms.newExpenseReport.fields.notesPlaceholder"),
          width: "full",
          rows: 2,
        },
      ],
    },
  ],
})

export const editExpenseForm = (t: TFunction): FormConfig => ({
  id: "edit-expense",
  title: t("expenses.forms.editExpense.title"),
  description: t("expenses.forms.editExpense.description"),
  sections: [
    {
      id: "edit-expense-details",
      title: t("expenses.forms.editExpense.sections.details"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("expenses.forms.editExpense.fields.name"),
          required: true,
          width: "full",
        },
        {
          id: "unitAmount",
          name: "unitAmount",
          type: "number",
          label: t("expenses.forms.editExpense.fields.unitAmount"),
          placeholder: "0.00",
          required: true,
          width: "1/2",
        },
        {
          id: "quantity",
          name: "quantity",
          type: "number",
          label: t("expenses.forms.editExpense.fields.quantity"),
          placeholder: "1",
          required: true,
          width: "1/2",
        },
        {
          id: "description",
          name: "description",
          type: "textarea",
          label: t("expenses.forms.editExpense.fields.description"),
          width: "full",
          rows: 2,
        },
      ],
    },
  ],
})

export const addExpenseToReportForm = (t: TFunction): FormConfig => ({
  id: "add-expense-to-report",
  title: t("expenses.forms.addToReport.title"),
  description: t("expenses.forms.addToReport.description"),
  sections: [
    {
      id: "sheet-pick",
      title: t("expenses.forms.addToReport.sections.sheet"),
      fields: [
        {
          id: "sheetId",
          name: "sheetId",
          type: "select",
          label: t("expenses.forms.addToReport.fields.sheetId"),
          placeholder: t("expenses.forms.addToReport.fields.sheetPlaceholder"),
          required: true,
          width: "full",
          options: emptySelect,
        },
      ],
    },
  ],
})

export const postExpenseReportForm = (t: TFunction): FormConfig => ({
  id: "post-expense-report",
  title: t("expenses.forms.postReport.title"),
  description: t("expenses.forms.postReport.description"),
  sections: [
    {
      id: "post-accounts",
      title: t("expenses.forms.postReport.sections.accounts"),
      fields: [
        {
          id: "accountingDate",
          name: "accountingDate",
          type: "date",
          label: t("expenses.forms.postReport.fields.accountingDate"),
          required: true,
          width: "full",
        },
        {
          id: "journalId",
          name: "journalId",
          type: "select",
          label: t("expenses.forms.postReport.fields.journalId"),
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "defaultExpenseAccountId",
          name: "defaultExpenseAccountId",
          type: "select",
          label: t("expenses.forms.postReport.fields.defaultExpenseAccountId"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "payableAccountId",
          name: "payableAccountId",
          type: "select",
          label: t("expenses.forms.postReport.fields.payableAccountId"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "defaultTaxAccountId",
          name: "defaultTaxAccountId",
          type: "select",
          label: t("expenses.forms.postReport.fields.defaultTaxAccountId"),
          required: false,
          width: "full",
          options: emptySelect,
        },
        {
          id: "cardLiabilityAccountId",
          name: "cardLiabilityAccountId",
          type: "select",
          label: t("expenses.forms.postReport.fields.cardLiabilityAccountId"),
          required: false,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "advanceAccountId",
          name: "advanceAccountId",
          type: "select",
          label: t("expenses.forms.postReport.fields.advanceAccountId"),
          required: false,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "fxFeeAccountId",
          name: "fxFeeAccountId",
          type: "select",
          label: t("expenses.forms.postReport.fields.fxFeeAccountId"),
          required: false,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "fxFeeAmount",
          name: "fxFeeAmount",
          type: "number",
          label: t("expenses.forms.postReport.fields.fxFeeAmount"),
          required: false,
          width: "1/2",
        },
      ],
    },
  ],
})

export const reimburseExpenseReportForm = (t: TFunction): FormConfig => ({
  id: "reimburse-expense-report",
  title: t("expenses.forms.reimburseReport.title"),
  description: t("expenses.forms.reimburseReport.description"),
  sections: [
    {
      id: "reimburse-accounts",
      title: t("expenses.forms.reimburseReport.sections.accounts"),
      fields: [
        {
          id: "paymentDate",
          name: "paymentDate",
          type: "date",
          label: t("expenses.forms.reimburseReport.fields.paymentDate"),
          required: true,
          width: "full",
        },
        {
          id: "journalId",
          name: "journalId",
          type: "select",
          label: t("expenses.forms.reimburseReport.fields.journalId"),
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "payableAccountId",
          name: "payableAccountId",
          type: "select",
          label: t("expenses.forms.reimburseReport.fields.payableAccountId"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "liquidityAccountId",
          name: "liquidityAccountId",
          type: "select",
          label: t("expenses.forms.reimburseReport.fields.liquidityAccountId"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
      ],
    },
  ],
})

export const setExpenseAllocationsForm = (t: TFunction): FormConfig => ({
  id: "set-expense-allocations",
  title: t("expenses.forms.setAllocations.title"),
  description: t("expenses.forms.setAllocations.description"),
  sections: [
    {
      id: "allocation-lines",
      title: t("expenses.forms.setAllocations.sections.lines"),
      fields: [
        {
          id: "analyticAccountId1",
          name: "analyticAccountId1",
          type: "text",
          label: t("expenses.forms.setAllocations.fields.analyticAccountId1"),
          width: "1/2",
        },
        {
          id: "projectId1",
          name: "projectId1",
          type: "text",
          label: t("expenses.forms.setAllocations.fields.projectId1"),
          width: "1/2",
        },
        {
          id: "sharePercent1",
          name: "sharePercent1",
          type: "number",
          label: t("expenses.forms.setAllocations.fields.sharePercent1"),
          required: true,
          defaultValue: 100,
          width: "1/2",
        },
        {
          id: "billable1",
          name: "billable1",
          type: "checkbox",
          label: t("expenses.forms.setAllocations.fields.billable1"),
          defaultValue: true,
          width: "1/2",
        },
        {
          id: "analyticAccountId2",
          name: "analyticAccountId2",
          type: "text",
          label: t("expenses.forms.setAllocations.fields.analyticAccountId2"),
          width: "1/2",
        },
        {
          id: "projectId2",
          name: "projectId2",
          type: "text",
          label: t("expenses.forms.setAllocations.fields.projectId2"),
          width: "1/2",
        },
        {
          id: "sharePercent2",
          name: "sharePercent2",
          type: "number",
          label: t("expenses.forms.setAllocations.fields.sharePercent2"),
          width: "1/2",
        },
        {
          id: "billable2",
          name: "billable2",
          type: "checkbox",
          label: t("expenses.forms.setAllocations.fields.billable2"),
          defaultValue: false,
          width: "1/2",
        },
      ],
    },
  ],
})

export const projectRebillExpenseReportForm = (t: TFunction): FormConfig => ({
  id: "project-rebill-expense-report",
  title: t("expenses.forms.projectRebill.title"),
  description: t("expenses.forms.projectRebill.description"),
  sections: [
    {
      id: "rebill-accounts",
      title: t("expenses.forms.projectRebill.sections.accounts"),
      fields: [
        {
          id: "invoiceDate",
          name: "invoiceDate",
          type: "date",
          label: t("expenses.forms.projectRebill.fields.invoiceDate"),
          required: true,
          width: "full",
        },
        {
          id: "journalId",
          name: "journalId",
          type: "select",
          label: t("expenses.forms.projectRebill.fields.journalId"),
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "receivableAccountId",
          name: "receivableAccountId",
          type: "select",
          label: t("expenses.forms.projectRebill.fields.receivableAccountId"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "incomeAccountId",
          name: "incomeAccountId",
          type: "select",
          label: t("expenses.forms.projectRebill.fields.incomeAccountId"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
      ],
    },
  ],
})

export const expensesFormConfigs = (t: TFunction): Record<string, FormConfig> => ({
  "new-expense": newExpenseForm(t),
  "new-expense-sheet": newExpenseSheetForm(t),
  "edit-expense": editExpenseForm(t),
  "add-expense-to-report": addExpenseToReportForm(t),
  "post-expense-report": postExpenseReportForm(t),
  "reimburse-expense-report": reimburseExpenseReportForm(t),
  "set-expense-allocations": setExpenseAllocationsForm(t),
  "project-rebill-expense-report": projectRebillExpenseReportForm(t),
})
