import type { FormConfig } from "./form-types"

export const newOrderForm: FormConfig = {
  id: "new-order",
  title: "Create New Order",
  description: "Enter the details for the new sales order",
  submitLabel: "Create Order",
  cancelLabel: "Cancel",
  showReset: true,
  sections: [
    {
      id: "customer-info",
      title: "Customer Information",
      fields: [
        {
          id: "customer-name",
          name: "customerName",
          type: "text",
          label: "Customer Name",
          placeholder: "Enter customer name",
          required: true,
          width: "1/2",
        },
        {
          id: "customer-email",
          name: "customerEmail",
          type: "email",
          label: "Email Address",
          placeholder: "customer@example.com",
          required: true,
          width: "1/2",
        },
        {
          id: "customer-phone",
          name: "customerPhone",
          type: "tel",
          label: "Phone Number",
          placeholder: "+1 (555) 123-4567",
          width: "1/2",
        },
        {
          id: "customer-company",
          name: "customerCompany",
          type: "text",
          label: "Company",
          placeholder: "Company name",
          width: "1/2",
        },
      ],
    },
    {
      id: "order-details",
      title: "Order Details",
      fields: [
        {
          id: "product",
          name: "product",
          type: "select",
          label: "Product",
          placeholder: "Select a product",
          required: true,
          width: "1/2",
          options: [
            { value: "enterprise", label: "Enterprise Suite - $200/mo" },
            { value: "professional", label: "Professional Plan - $150/mo" },
            { value: "starter", label: "Starter Kit - $50/mo" },
            { value: "addon-a", label: "Add-on Module A - $50/mo" },
            { value: "support", label: "Support Package - $100/mo" },
          ],
        },
        {
          id: "quantity",
          name: "quantity",
          type: "number",
          label: "Quantity",
          placeholder: "1",
          required: true,
          width: "1/4",
          defaultValue: 1,
          validation: { min: 1, max: 100 },
        },
        {
          id: "priority",
          name: "priority",
          type: "select",
          label: "Priority",
          width: "1/4",
          defaultValue: "normal",
          options: [
            { value: "low", label: "Low" },
            { value: "normal", label: "Normal" },
            { value: "high", label: "High" },
            { value: "urgent", label: "Urgent" },
          ],
        },
        {
          id: "billing-cycle",
          name: "billingCycle",
          type: "radio",
          label: "Billing Cycle",
          width: "full",
          defaultValue: "monthly",
          options: [
            { value: "monthly", label: "Monthly" },
            { value: "quarterly", label: "Quarterly (5% off)" },
            { value: "annual", label: "Annual (15% off)" },
          ],
          layout: "horizontal",
        },
        {
          id: "notes",
          name: "notes",
          type: "textarea",
          label: "Order Notes",
          placeholder: "Any special instructions or notes...",
          width: "full",
          rows: 3,
        },
      ],
    },
    {
      id: "options",
      title: "Additional Options",
      fields: [
        {
          id: "express-shipping",
          name: "expressShipping",
          type: "switch",
          label: "Express Shipping (+$25)",
          width: "1/2",
        },
        {
          id: "gift-wrap",
          name: "giftWrap",
          type: "switch",
          label: "Gift Wrap (+$5)",
          width: "1/2",
        },
        {
          id: "terms",
          name: "termsAccepted",
          type: "checkbox",
          label: "I agree to the terms and conditions",
          required: true,
          width: "full",
        },
        {
          id: "newsletter",
          name: "newsletter",
          type: "checkbox",
          label: "Subscribe to our newsletter",
          width: "full",
          defaultValue: true,
        },
      ],
    },
  ],
}

export const newCustomerForm: FormConfig = {
  id: "new-customer",
  title: "Add New Customer",
  description: "Register a new customer in the system",
  submitLabel: "Add Customer",
  cancelLabel: "Cancel",
  sections: [
    {
      id: "basic-info",
      title: "Basic Information",
      fields: [
        {
          id: "first-name",
          name: "firstName",
          type: "text",
          label: "First Name",
          placeholder: "John",
          required: true,
          width: "1/2",
        },
        {
          id: "last-name",
          name: "lastName",
          type: "text",
          label: "Last Name",
          placeholder: "Doe",
          required: true,
          width: "1/2",
        },
        {
          id: "email",
          name: "email",
          type: "email",
          label: "Email",
          placeholder: "john.doe@example.com",
          required: true,
          width: "1/2",
        },
        {
          id: "phone",
          name: "phone",
          type: "tel",
          label: "Phone",
          placeholder: "+1 (555) 123-4567",
          width: "1/2",
        },
      ],
    },
    {
      id: "company-info",
      title: "Company Details",
      fields: [
        {
          id: "company",
          name: "company",
          type: "text",
          label: "Company Name",
          placeholder: "Acme Inc.",
          width: "1/2",
        },
        {
          id: "industry",
          name: "industry",
          type: "select",
          label: "Industry",
          width: "1/2",
          options: [
            { value: "tech", label: "Technology" },
            { value: "finance", label: "Finance" },
            { value: "healthcare", label: "Healthcare" },
            { value: "retail", label: "Retail" },
            { value: "manufacturing", label: "Manufacturing" },
            { value: "other", label: "Other" },
          ],
        },
        {
          id: "website",
          name: "website",
          type: "url",
          label: "Website",
          placeholder: "https://example.com",
          width: "full",
        },
      ],
    },
    {
      id: "preferences",
      title: "Preferences",
      fields: [
        {
          id: "contact-method",
          name: "contactMethod",
          type: "radio",
          label: "Preferred Contact Method",
          width: "full",
          defaultValue: "email",
          options: [
            { value: "email", label: "Email" },
            { value: "phone", label: "Phone" },
            { value: "sms", label: "SMS" },
          ],
          layout: "horizontal",
        },
        {
          id: "marketing",
          name: "marketingConsent",
          type: "switch",
          label: "Receive marketing communications",
          width: "full",
        },
      ],
    },
  ],
}

export const reportForm: FormConfig = {
  id: "generate-report",
  title: "Generate Report",
  description: "Configure and generate a custom report",
  submitLabel: "Generate",
  cancelLabel: "Cancel",
  sections: [
    {
      id: "report-config",
      fields: [
        {
          id: "report-type",
          name: "reportType",
          type: "select",
          label: "Report Type",
          required: true,
          width: "1/2",
          options: [
            { value: "sales", label: "Sales Summary" },
            { value: "inventory", label: "Inventory Report" },
            { value: "customers", label: "Customer Analysis" },
            { value: "financial", label: "Financial Overview" },
          ],
        },
        {
          id: "format",
          name: "format",
          type: "select",
          label: "Export Format",
          required: true,
          width: "1/2",
          defaultValue: "pdf",
          options: [
            { value: "pdf", label: "PDF Document" },
            { value: "excel", label: "Excel Spreadsheet" },
            { value: "csv", label: "CSV File" },
          ],
        },
        {
          id: "date-from",
          name: "dateFrom",
          type: "date",
          label: "From Date",
          required: true,
          width: "1/2",
        },
        {
          id: "date-to",
          name: "dateTo",
          type: "date",
          label: "To Date",
          required: true,
          width: "1/2",
        },
        {
          id: "include-charts",
          name: "includeCharts",
          type: "switch",
          label: "Include visual charts",
          width: "1/2",
          defaultValue: true,
        },
        {
          id: "include-summary",
          name: "includeSummary",
          type: "switch",
          label: "Include executive summary",
          width: "1/2",
          defaultValue: true,
        },
      ],
    },
  ],
}

export const formConfigs: Record<string, FormConfig> = {
  "new-order": newOrderForm,
  "new-customer": newCustomerForm,
  "generate-report": reportForm,
}
