import type { TFunction } from "i18next"
import type { FormConfig } from "./form-types"

const emptySelect: Array<{ value: string; label: string; disabled?: boolean }> = []

export const newProductForm = (t: TFunction): FormConfig => ({
  id: "new-product",
  title: t("inventory.forms.newProduct.title"),
  description: t("inventory.forms.newProduct.description"),
  sections: [
    {
      id: "product-identity",
      title: t("inventory.forms.newProduct.sections.identity"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("inventory.forms.newProduct.fields.name"),
          placeholder: t("inventory.forms.newProduct.fields.namePlaceholder"),
          required: true,
          width: "full",
        },
        {
          id: "defaultCode",
          name: "defaultCode",
          type: "text",
          label: t("inventory.forms.newProduct.fields.defaultCode"),
          placeholder: t("inventory.forms.newProduct.fields.defaultCodePlaceholder"),
          width: "1/2",
        },
        {
          id: "type",
          name: "type",
          type: "select",
          label: t("inventory.forms.newProduct.fields.type"),
          required: true,
          width: "1/2",
          options: [
            { value: "product", label: t("inventory.forms.newProduct.fields.options.product") },
            { value: "consu", label: t("inventory.forms.newProduct.fields.options.consu") },
            { value: "service", label: t("inventory.forms.newProduct.fields.options.service") },
          ],
        },
      ],
    },
    {
      id: "product-classification",
      title: t("inventory.forms.newProduct.sections.classification"),
      fields: [
        {
          id: "categId",
          name: "categId",
          type: "select",
          label: t("inventory.forms.newProduct.fields.categId"),
          placeholder: t("inventory.forms.newProduct.fields.categIdPlaceholder"),
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "uomId",
          name: "uomId",
          type: "select",
          label: t("inventory.forms.newProduct.fields.uomId"),
          placeholder: t("inventory.forms.newProduct.fields.uomIdPlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "uomPoId",
          name: "uomPoId",
          type: "select",
          label: t("inventory.forms.newProduct.fields.uomPoId"),
          placeholder: t("inventory.forms.newProduct.fields.uomPoPlaceholder"),
          required: false,
          width: "1/2",
          options: emptySelect,
        },
      ],
    },
    {
      id: "product-pricing",
      title: t("inventory.forms.newProduct.sections.pricing"),
      fields: [
        {
          id: "pricelistId",
          name: "pricelistId",
          type: "select",
          label: t("inventory.forms.newProduct.fields.pricelistId"),
          placeholder: t("inventory.forms.newProduct.fields.pricelistPlaceholder"),
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "standardPrice",
          name: "standardPrice",
          type: "number",
          label: t("inventory.forms.newProduct.fields.standardPrice"),
          placeholder: t("inventory.forms.newProduct.fields.standardPricePlaceholder"),
          width: "1/2",
        },
        {
          id: "saleOk",
          name: "saleOk",
          type: "checkbox",
          label: t("inventory.forms.newProduct.fields.saleOk"),
          width: "1/2",
        },
        {
          id: "purchaseOk",
          name: "purchaseOk",
          type: "checkbox",
          label: t("inventory.forms.newProduct.fields.purchaseOk"),
          width: "1/2",
        },
      ],
    },
  ],
})

export const newTransferForm = (t: TFunction): FormConfig => ({
  id: "new-transfer",
  title: t("inventory.forms.newTransfer.title"),
  description: t("inventory.forms.newTransfer.description"),
  sections: [
    {
      id: "transfer-info",
      title: t("inventory.forms.newTransfer.sections.transferDetails"),
      fields: [
        {
          id: "pickingTypeId",
          name: "pickingTypeId",
          type: "select",
          label: t("inventory.forms.newTransfer.fields.pickingTypeId"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "locationId",
          name: "locationId",
          type: "select",
          label: t("inventory.forms.newTransfer.fields.locationId"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "locationDestId",
          name: "locationDestId",
          type: "select",
          label: t("inventory.forms.newTransfer.fields.locationDestId"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "scheduledDate",
          name: "scheduledDate",
          type: "date",
          label: t("inventory.forms.newTransfer.fields.scheduledDate"),
          width: "1/2",
        },
        {
          id: "origin",
          name: "origin",
          type: "text",
          label: t("inventory.forms.newTransfer.fields.origin"),
          placeholder: t("inventory.forms.newTransfer.fields.originPlaceholder"),
          width: "full",
        },
      ],
    },
  ],
})

export const newInventoryAdjustmentForm = (t: TFunction): FormConfig => ({
  id: "new-inventory-adjustment",
  title: t("inventory.forms.newInventoryAdjustment.title"),
  description: t("inventory.forms.newInventoryAdjustment.description"),
  sections: [
    {
      id: "adj-info",
      title: t("inventory.forms.newInventoryAdjustment.sections.adjustmentDetails"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("inventory.forms.newInventoryAdjustment.fields.name"),
          placeholder: t("inventory.forms.newInventoryAdjustment.fields.namePlaceholder"),
          required: true,
          width: "1/2",
        },
        {
          id: "date",
          name: "date",
          type: "date",
          label: t("inventory.forms.newInventoryAdjustment.fields.date"),
          width: "1/2",
        },
        {
          id: "productId",
          name: "productId",
          type: "select",
          label: t("inventory.forms.newInventoryAdjustment.fields.productId"),
          placeholder: t("inventory.forms.newInventoryAdjustment.fields.productPlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "locationId",
          name: "locationId",
          type: "select",
          label: t("inventory.forms.newInventoryAdjustment.fields.locationId"),
          placeholder: t("inventory.forms.newInventoryAdjustment.fields.locationPlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "bookQuantity",
          name: "bookQuantity",
          type: "number",
          label: t("inventory.forms.newInventoryAdjustment.fields.bookQuantity"),
          placeholder: t("inventory.forms.newInventoryAdjustment.fields.bookQuantityPlaceholder"),
          width: "1/2",
        },
        {
          id: "inventoryQuantity",
          name: "inventoryQuantity",
          type: "number",
          label: t("inventory.forms.newInventoryAdjustment.fields.inventoryQuantity"),
          required: true,
          width: "1/2",
        },
        {
          id: "countQty",
          name: "countQty",
          type: "number",
          label: t("inventory.forms.newInventoryAdjustment.fields.countQty"),
          placeholder: t("inventory.forms.newInventoryAdjustment.fields.countQtyPlaceholder"),
          width: "1/2",
        },
        {
          id: "standardPrice",
          name: "standardPrice",
          type: "number",
          label: t("inventory.forms.newInventoryAdjustment.fields.standardPrice"),
          width: "1/2",
        },
        {
          id: "reasonCode",
          name: "reasonCode",
          type: "text",
          label: t("inventory.forms.newInventoryAdjustment.fields.reasonCode"),
          placeholder: t("inventory.forms.newInventoryAdjustment.fields.reasonCodePlaceholder"),
          width: "1/2",
        },
        {
          id: "reasonNotes",
          name: "reasonNotes",
          type: "textarea",
          label: t("inventory.forms.newInventoryAdjustment.fields.reasonNotes"),
          placeholder: t("inventory.forms.newInventoryAdjustment.fields.reasonNotesPlaceholder"),
          width: "full",
        },
      ],
    },
  ],
})

export const newStockLocationForm = (t: TFunction): FormConfig => ({
  id: "new-stock-location",
  title: t("inventory.forms.newStockLocation.title"),
  description: t("inventory.forms.newStockLocation.description"),
  sections: [
    {
      id: "loc-main",
      title: t("inventory.forms.newStockLocation.sections.main"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("inventory.forms.newStockLocation.fields.name"),
          placeholder: t("inventory.forms.newStockLocation.fields.namePlaceholder"),
          required: true,
          width: "full",
        },
        {
          id: "usage",
          name: "usage",
          type: "select",
          label: t("inventory.forms.newStockLocation.fields.usage"),
          required: true,
          width: "1/2",
          options: [
            { value: "internal", label: t("inventory.stockLocations.states.internal") },
            { value: "customer", label: t("inventory.stockLocations.states.customer") },
            { value: "supplier", label: t("inventory.stockLocations.states.supplier") },
            { value: "inventory", label: t("inventory.stockLocations.states.inventory") },
            { value: "transit", label: t("inventory.stockLocations.states.transit") },
            { value: "view", label: t("inventory.stockLocations.states.view") },
          ],
        },
        {
          id: "parentLocationId",
          name: "parentLocationId",
          type: "select",
          label: t("inventory.forms.newStockLocation.fields.parentLocationId"),
          width: "1/2",
          options: [{ value: "", label: t("inventory.forms.newStockLocation.fields.parentNone") }],
        },
        {
          id: "barcode",
          name: "barcode",
          type: "text",
          label: t("inventory.forms.newStockLocation.fields.barcode"),
          width: "full",
        },
      ],
    },
  ],
})

export const newWarehouseForm = (t: TFunction): FormConfig => ({
  id: "new-warehouse",
  title: t("inventory.forms.newWarehouse.title"),
  description: t("inventory.forms.newWarehouse.description"),
  sections: [
    {
      id: "wh-identity",
      title: t("inventory.forms.newWarehouse.sections.identity"),
      fields: [
        {
          id: "templateWarehouseId",
          name: "templateWarehouseId",
          type: "select",
          label: t("inventory.forms.newWarehouse.fields.templateWarehouseId"),
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("inventory.forms.newWarehouse.fields.name"),
          required: true,
          width: "1/2",
        },
        {
          id: "code",
          name: "code",
          type: "text",
          label: t("inventory.forms.newWarehouse.fields.code"),
          required: true,
          width: "1/2",
        },
        {
          id: "sequence",
          name: "sequence",
          type: "number",
          label: t("inventory.forms.newWarehouse.fields.sequence"),
          width: "1/2",
        },
        {
          id: "active",
          name: "active",
          type: "checkbox",
          label: t("inventory.forms.newWarehouse.fields.active"),
          width: "1/2",
        },
      ],
    },
  ],
})

export const editWarehouseForm = (t: TFunction): FormConfig => ({
  id: "edit-warehouse",
  title: t("inventory.forms.editWarehouse.title"),
  description: t("inventory.forms.editWarehouse.description"),
  sections: [
    {
      id: "wh-edit",
      title: t("inventory.forms.editWarehouse.sections.main"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("inventory.forms.editWarehouse.fields.name"),
          width: "1/2",
        },
        {
          id: "code",
          name: "code",
          type: "text",
          label: t("inventory.forms.editWarehouse.fields.code"),
          width: "1/2",
        },
        {
          id: "active",
          name: "active",
          type: "checkbox",
          label: t("inventory.forms.editWarehouse.fields.active"),
          width: "1/2",
        },
        {
          id: "sequence",
          name: "sequence",
          type: "number",
          label: t("inventory.forms.editWarehouse.fields.sequence"),
          width: "1/2",
        },
        {
          id: "receptionSteps",
          name: "receptionSteps",
          type: "text",
          label: t("inventory.forms.editWarehouse.fields.receptionSteps"),
          width: "full",
        },
        {
          id: "deliverySteps",
          name: "deliverySteps",
          type: "text",
          label: t("inventory.forms.editWarehouse.fields.deliverySteps"),
          width: "full",
        },
        {
          id: "manufactureSteps",
          name: "manufactureSteps",
          type: "text",
          label: t("inventory.forms.editWarehouse.fields.manufactureSteps"),
          width: "full",
        },
        {
          id: "crossdock",
          name: "crossdock",
          type: "checkbox",
          label: t("inventory.forms.editWarehouse.fields.crossdock"),
          width: "1/2",
        },
        {
          id: "buyToResupply",
          name: "buyToResupply",
          type: "checkbox",
          label: t("inventory.forms.editWarehouse.fields.buyToResupply"),
          width: "1/2",
        },
        {
          id: "manufactureToResupply",
          name: "manufactureToResupply",
          type: "checkbox",
          label: t("inventory.forms.editWarehouse.fields.manufactureToResupply"),
          width: "1/2",
        },
        {
          id: "metadata",
          name: "metadata",
          type: "textarea",
          label: t("inventory.forms.editWarehouse.fields.metadata"),
          width: "full",
        },
      ],
    },
  ],
})

export const editProductForm = (t: TFunction): FormConfig => ({
  id: "edit-product",
  title: t("inventory.forms.editProduct.title"),
  description: t("inventory.forms.editProduct.description"),
  sections: [
    {
      id: "edit-product-main",
      title: t("inventory.forms.editProduct.sections.main"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("inventory.forms.editProduct.fields.name"),
          width: "full",
        },
        {
          id: "standardPrice",
          name: "standardPrice",
          type: "number",
          label: t("inventory.forms.editProduct.fields.standardPrice"),
          width: "1/2",
        },
        {
          id: "listPrice",
          name: "listPrice",
          type: "number",
          label: t("inventory.forms.editProduct.fields.listPrice"),
          width: "1/2",
        },
        {
          id: "description",
          name: "description",
          type: "textarea",
          label: t("inventory.forms.editProduct.fields.description"),
          width: "full",
        },
        {
          id: "saleOk",
          name: "saleOk",
          type: "checkbox",
          label: t("inventory.forms.editProduct.fields.saleOk"),
          width: "1/2",
        },
        {
          id: "purchaseOk",
          name: "purchaseOk",
          type: "checkbox",
          label: t("inventory.forms.editProduct.fields.purchaseOk"),
          width: "1/2",
        },
        {
          id: "active",
          name: "active",
          type: "checkbox",
          label: t("inventory.forms.editProduct.fields.active"),
          width: "1/2",
        },
        {
          id: "isPublished",
          name: "isPublished",
          type: "checkbox",
          label: t("inventory.forms.editProduct.fields.isPublished"),
          width: "1/2",
        },
      ],
    },
  ],
})

export const assignUserToPickingForm = (t: TFunction): FormConfig => ({
  id: "assign-user-picking",
  title: t("inventory.forms.assignUserToPicking.title"),
  description: t("inventory.forms.assignUserToPicking.description"),
  sections: [
    {
      id: "assign-user",
      title: t("inventory.forms.assignUserToPicking.sections.main"),
      fields: [
        {
          id: "userIdentity",
          name: "userIdentity",
          type: "select",
          label: t("inventory.forms.assignUserToPicking.fields.userIdentity"),
          required: false,
          width: "full",
          options: emptySelect,
        },
      ],
    },
  ],
})

export const newProductVariantForm = (t: TFunction): FormConfig => ({
  id: "new-product-variant",
  title: t("inventory.forms.newProductVariant.title"),
  description: t("inventory.forms.newProductVariant.description"),
  sections: [
    {
      id: "variant-main",
      title: t("inventory.forms.newProductVariant.sections.main"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("inventory.forms.newProductVariant.fields.name"),
          required: true,
          width: "full",
        },
        {
          id: "standardPrice",
          name: "standardPrice",
          type: "number",
          label: t("inventory.forms.newProductVariant.fields.standardPrice"),
          required: true,
          width: "1/2",
        },
        {
          id: "lstPrice",
          name: "lstPrice",
          type: "number",
          label: t("inventory.forms.newProductVariant.fields.lstPrice"),
          required: true,
          width: "1/2",
        },
        {
          id: "defaultCode",
          name: "defaultCode",
          type: "text",
          label: t("inventory.forms.newProductVariant.fields.defaultCode"),
          width: "1/2",
        },
        {
          id: "barcode",
          name: "barcode",
          type: "text",
          label: t("inventory.forms.newProductVariant.fields.barcode"),
          width: "1/2",
        },
      ],
    },
  ],
})

export const newQualityCheckForm = (t: TFunction): FormConfig => ({
  id: "new-quality-check",
  title: t("inventory.forms.newQualityCheck.title"),
  description: t("inventory.forms.newQualityCheck.description"),
  sections: [
    {
      id: "check-main",
      title: t("inventory.forms.newQualityCheck.sections.main"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("inventory.forms.newQualityCheck.fields.name"),
          placeholder: t("inventory.forms.newQualityCheck.fields.namePlaceholder"),
          required: true,
          width: "full",
        },
        {
          id: "productId",
          name: "productId",
          type: "select",
          label: t("inventory.forms.newQualityCheck.fields.productId"),
          placeholder: t("inventory.forms.newQualityCheck.fields.productPlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "pointId",
          name: "pointId",
          type: "select",
          label: t("inventory.forms.newQualityCheck.fields.pointId"),
          placeholder: t("inventory.forms.newQualityCheck.fields.pointPlaceholder"),
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "lotId",
          name: "lotId",
          type: "select",
          label: t("inventory.forms.newQualityCheck.fields.lotId"),
          placeholder: t("inventory.forms.newQualityCheck.fields.lotPlaceholder"),
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "teamId",
          name: "teamId",
          type: "select",
          label: t("inventory.forms.newQualityCheck.fields.teamId"),
          placeholder: t("inventory.forms.newQualityCheck.fields.teamPlaceholder"),
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "testType",
          name: "testType",
          type: "select",
          label: t("inventory.forms.newQualityCheck.fields.testType"),
          width: "1/2",
          defaultValue: "measure",
          options: [
            { value: "measure", label: t("inventory.forms.newQualityCheck.fields.testTypes.measure") },
            { value: "picture", label: t("inventory.forms.newQualityCheck.fields.testTypes.picture") },
            { value: "instructions", label: t("inventory.forms.newQualityCheck.fields.testTypes.instructions") },
          ],
        },
        {
          id: "qtyTested",
          name: "qtyTested",
          type: "number",
          label: t("inventory.forms.newQualityCheck.fields.qtyTested"),
          width: "1/2",
          defaultValue: 0,
        },
      ],
    },
  ],
})

export const newQualityAlertForm = (t: TFunction): FormConfig => ({
  id: "new-quality-alert",
  title: t("inventory.forms.newQualityAlert.title"),
  description: t("inventory.forms.newQualityAlert.description"),
  sections: [
    {
      id: "alert-main",
      title: t("inventory.forms.newQualityAlert.sections.main"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("inventory.forms.newQualityAlert.fields.name"),
          placeholder: t("inventory.forms.newQualityAlert.fields.namePlaceholder"),
          required: true,
          width: "full",
        },
        {
          id: "teamId",
          name: "teamId",
          type: "select",
          label: t("inventory.forms.newQualityAlert.fields.teamId"),
          placeholder: t("inventory.forms.newQualityAlert.fields.teamPlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "productId",
          name: "productId",
          type: "select",
          label: t("inventory.forms.newQualityAlert.fields.productId"),
          placeholder: t("inventory.forms.newQualityAlert.fields.productPlaceholder"),
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "pickingId",
          name: "pickingId",
          type: "select",
          label: t("inventory.forms.newQualityAlert.fields.pickingId"),
          placeholder: t("inventory.forms.newQualityAlert.fields.pickingPlaceholder"),
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "description",
          name: "description",
          type: "textarea",
          label: t("inventory.forms.newQualityAlert.fields.description"),
          width: "full",
        },
        {
          id: "priority",
          name: "priority",
          type: "select",
          label: t("inventory.forms.newQualityAlert.fields.priority"),
          width: "1/2",
          defaultValue: "2",
          options: [
            { value: "0", label: t("inventory.forms.newQualityAlert.fields.priorities.normal") },
            { value: "1", label: t("inventory.forms.newQualityAlert.fields.priorities.low") },
            { value: "2", label: t("inventory.forms.newQualityAlert.fields.priorities.high") },
            { value: "3", label: t("inventory.forms.newQualityAlert.fields.priorities.critical") },
          ],
        },
      ],
    },
  ],
})

export const newQualityPointForm = (t: TFunction): FormConfig => ({
  id: "new-quality-point",
  title: t("inventory.forms.newQualityPoint.title"),
  description: t("inventory.forms.newQualityPoint.description"),
  sections: [
    {
      id: "point-main",
      title: t("inventory.forms.newQualityPoint.sections.main"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("inventory.forms.newQualityPoint.fields.name"),
          placeholder: t("inventory.forms.newQualityPoint.fields.namePlaceholder"),
          required: true,
          width: "full",
        },
        {
          id: "productId",
          name: "productId",
          type: "select",
          label: t("inventory.forms.newQualityPoint.fields.productId"),
          placeholder: t("inventory.forms.newQualityPoint.fields.productPlaceholder"),
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "productCategId",
          name: "productCategId",
          type: "select",
          label: t("inventory.forms.newQualityPoint.fields.productCategId"),
          placeholder: t("inventory.forms.newQualityPoint.fields.categoryPlaceholder"),
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "teamId",
          name: "teamId",
          type: "select",
          label: t("inventory.forms.newQualityPoint.fields.teamId"),
          placeholder: t("inventory.forms.newQualityPoint.fields.teamPlaceholder"),
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "checkType",
          name: "checkType",
          type: "select",
          label: t("inventory.forms.newQualityPoint.fields.checkType"),
          width: "1/2",
          defaultValue: "random",
          options: [
            { value: "random", label: t("inventory.forms.newQualityPoint.fields.checkTypes.random") },
            { value: "all", label: t("inventory.forms.newQualityPoint.fields.checkTypes.all") },
          ],
        },
      ],
    },
  ],
})

export const newQualityTeamForm = (t: TFunction): FormConfig => ({
  id: "new-quality-team",
  title: t("inventory.forms.newQualityTeam.title"),
  description: t("inventory.forms.newQualityTeam.description"),
  sections: [
    {
      id: "team-main",
      title: t("inventory.forms.newQualityTeam.sections.main"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("inventory.forms.newQualityTeam.fields.name"),
          placeholder: t("inventory.forms.newQualityTeam.fields.namePlaceholder"),
          required: true,
          width: "full",
        },
        {
          id: "email",
          name: "email",
          type: "email",
          label: t("inventory.forms.newQualityTeam.fields.email"),
          width: "1/2",
        },
        {
          id: "companyId",
          name: "companyId",
          type: "select",
          label: t("inventory.forms.newQualityTeam.fields.companyId"),
          placeholder: t("inventory.forms.newQualityTeam.fields.companyPlaceholder"),
          width: "1/2",
          options: emptySelect,
        },
      ],
    },
  ],
})

export const newBarcodeRuleForm = (t: TFunction): FormConfig => ({
  id: "new-barcode-rule",
  title: t("inventory.forms.newBarcodeRule.title"),
  description: t("inventory.forms.newBarcodeRule.description"),
  sections: [
    {
      id: "rule-main",
      title: t("inventory.forms.newBarcodeRule.sections.main"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("inventory.forms.newBarcodeRule.fields.name"),
          placeholder: t("inventory.forms.newBarcodeRule.fields.namePlaceholder"),
          required: true,
          width: "full",
        },
        {
          id: "pattern",
          name: "pattern",
          type: "text",
          label: t("inventory.forms.newBarcodeRule.fields.pattern"),
          placeholder: t("inventory.forms.newBarcodeRule.fields.patternPlaceholder"),
          required: true,
          width: "full",
        },
        {
          id: "encoding",
          name: "encoding",
          type: "select",
          label: t("inventory.forms.newBarcodeRule.fields.encoding"),
          width: "1/3",
          defaultValue: "any",
          options: [
            { value: "any", label: t("inventory.forms.newBarcodeRule.fields.encodings.any") },
            { value: "ean13", label: "EAN-13" },
            { value: "ean8", label: "EAN-8" },
            { value: "upca", label: "UPC-A" },
            { value: "code39", label: "Code 39" },
            { value: "code128", label: "Code 128" },
          ],
        },
        {
          id: "type",
          name: "type",
          type: "select",
          label: t("inventory.forms.newBarcodeRule.fields.type"),
          width: "1/3",
          defaultValue: "product",
          options: [
            { value: "product", label: t("inventory.forms.newBarcodeRule.fields.types.product") },
            { value: "lot", label: t("inventory.forms.newBarcodeRule.fields.types.lot") },
            { value: "package", label: t("inventory.forms.newBarcodeRule.fields.types.package") },
            { value: "location", label: t("inventory.forms.newBarcodeRule.fields.types.location") },
          ],
        },
        {
          id: "sequence",
          name: "sequence",
          type: "number",
          label: t("inventory.forms.newBarcodeRule.fields.sequence"),
          width: "1/3",
          defaultValue: 100,
        },
      ],
    },
  ],
})

export const newReplenishmentRuleForm = (t: TFunction): FormConfig => ({
  id: "new-replenishment-rule",
  title: t("inventory.forms.newReplenishmentRule.title"),
  description: t("inventory.forms.newReplenishmentRule.description"),
  sections: [
    {
      id: "rule-main",
      title: t("inventory.forms.newReplenishmentRule.sections.main"),
      fields: [
        {
          id: "productId",
          name: "productId",
          type: "select",
          label: t("inventory.forms.newReplenishmentRule.fields.productId"),
          placeholder: t("inventory.forms.newReplenishmentRule.fields.productPlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "locationId",
          name: "locationId",
          type: "select",
          label: t("inventory.forms.newReplenishmentRule.fields.locationId"),
          placeholder: t("inventory.forms.newReplenishmentRule.fields.locationPlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "uomId",
          name: "uomId",
          type: "select",
          label: t("inventory.forms.newReplenishmentRule.fields.uomId"),
          placeholder: t("inventory.forms.newReplenishmentRule.fields.uomPlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "minQty",
          name: "minQty",
          type: "number",
          label: t("inventory.forms.newReplenishmentRule.fields.minQty"),
          required: true,
          width: "1/3",
        },
        {
          id: "maxQty",
          name: "maxQty",
          type: "number",
          label: t("inventory.forms.newReplenishmentRule.fields.maxQty"),
          required: true,
          width: "1/3",
        },
        {
          id: "warehouseId",
          name: "warehouseId",
          type: "select",
          label: t("inventory.forms.newReplenishmentRule.fields.warehouseId"),
          placeholder: t("inventory.forms.newReplenishmentRule.fields.warehousePlaceholder"),
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "routeId",
          name: "routeId",
          type: "select",
          label: t("inventory.forms.newReplenishmentRule.fields.routeId"),
          placeholder: t("inventory.forms.newReplenishmentRule.fields.routePlaceholder"),
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "trigger",
          name: "trigger",
          type: "select",
          label: t("inventory.forms.newReplenishmentRule.fields.trigger"),
          width: "1/2",
          defaultValue: "auto",
          options: [
            { value: "auto", label: t("inventory.forms.newReplenishmentRule.fields.triggers.auto") },
            { value: "manual", label: t("inventory.forms.newReplenishmentRule.fields.triggers.manual") },
            { value: "scheduled", label: t("inventory.forms.newReplenishmentRule.fields.triggers.scheduled") },
          ],
        },
        {
          id: "qtyMultiple",
          name: "qtyMultiple",
          type: "number",
          label: t("inventory.forms.newReplenishmentRule.fields.qtyMultiple"),
          width: "1/3",
          defaultValue: 1,
        },
        {
          id: "leadDays",
          name: "leadDays",
          type: "number",
          label: t("inventory.forms.newReplenishmentRule.fields.leadDays"),
          width: "1/3",
          defaultValue: 0,
        },
        {
          id: "active",
          name: "active",
          type: "checkbox",
          label: t("inventory.forms.newReplenishmentRule.fields.active"),
          width: "1/3",
          defaultValue: true,
        },
      ],
    },
  ],
})

export const newPickingWaveForm = (t: TFunction): FormConfig => ({
  id: "new-picking-wave",
  title: t("inventory.forms.newPickingWave.title"),
  description: t("inventory.forms.newPickingWave.description"),
  sections: [
    {
      id: "wave-main",
      title: t("inventory.forms.newPickingWave.sections.main"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("inventory.forms.newPickingWave.fields.name"),
          placeholder: t("inventory.forms.newPickingWave.fields.namePlaceholder"),
          required: true,
          width: "full",
        },
        {
          id: "scheduledDate",
          name: "scheduledDate",
          type: "datetime",
          label: t("inventory.forms.newPickingWave.fields.scheduledDate"),
          required: true,
          width: "1/2",
        },
        {
          id: "warehouseId",
          name: "warehouseId",
          type: "select",
          label: t("inventory.forms.newPickingWave.fields.warehouseId"),
          placeholder: t("inventory.forms.newPickingWave.fields.warehousePlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "userId",
          name: "userId",
          type: "select",
          label: t("inventory.forms.newPickingWave.fields.userId"),
          placeholder: t("inventory.forms.newPickingWave.fields.userPlaceholder"),
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "pickingTypeId",
          name: "pickingTypeId",
          type: "select",
          label: t("inventory.forms.newPickingWave.fields.pickingTypeId"),
          placeholder: t("inventory.forms.newPickingWave.fields.pickingTypePlaceholder"),
          width: "1/2",
          options: emptySelect,
        },
      ],
    },
  ],
})

export const newProductCategoryForm = (t: TFunction): FormConfig => ({
  id: "new-product-category",
  title: t("inventory.forms.newProductCategory.title"),
  description: t("inventory.forms.newProductCategory.description"),
  sections: [
    {
      id: "category-main",
      title: t("inventory.forms.newProductCategory.sections.main"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("inventory.forms.newProductCategory.fields.name"),
          placeholder: t("inventory.forms.newProductCategory.fields.namePlaceholder"),
          required: true,
          width: "full",
        },
        {
          id: "parentId",
          name: "parentId",
          type: "select",
          label: t("inventory.forms.newProductCategory.fields.parentId"),
          placeholder: t("inventory.forms.newProductCategory.fields.parentPlaceholder"),
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "removalStrategyId",
          name: "removalStrategyId",
          type: "select",
          label: t("inventory.forms.newProductCategory.fields.removalStrategyId"),
          placeholder: t("inventory.forms.newProductCategory.fields.removalStrategyPlaceholder"),
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "costingMethod",
          name: "costingMethod",
          type: "select",
          label: t("inventory.forms.newProductCategory.fields.costingMethod"),
          width: "1/2",
          defaultValue: "standard",
          options: [
            { value: "standard", label: t("inventory.forms.newProductCategory.fields.costingMethods.standard") },
            { value: "fifo", label: t("inventory.forms.newProductCategory.fields.costingMethods.fifo") },
            { value: "average", label: t("inventory.forms.newProductCategory.fields.costingMethods.average") },
            { value: "lifo", label: t("inventory.forms.newProductCategory.fields.costingMethods.lifo") },
          ],
        },
        {
          id: "propertyValuation",
          name: "propertyValuation",
          type: "select",
          label: t("inventory.forms.newProductCategory.fields.propertyValuation"),
          width: "1/2",
          defaultValue: "manual_periodic",
          options: [
            { value: "manual_periodic", label: t("inventory.forms.newProductCategory.fields.valuations.manualPeriodic") },
            { value: "real_time", label: t("inventory.forms.newProductCategory.fields.valuations.realTime") },
          ],
        },
        {
          id: "sequence",
          name: "sequence",
          type: "number",
          label: t("inventory.forms.newProductCategory.fields.sequence"),
          width: "1/2",
          defaultValue: 10,
        },
      ],
    },
  ],
})

export const newStockQuantForm = (t: TFunction): FormConfig => ({
  id: "new-stock-quant",
  title: t("inventory.forms.newStockQuant.title"),
  description: t("inventory.forms.newStockQuant.description"),
  sections: [
    {
      id: "quant-main",
      title: t("inventory.forms.newStockQuant.sections.main"),
      fields: [
        {
          id: "productId",
          name: "productId",
          type: "select",
          label: t("inventory.forms.newStockQuant.fields.productId"),
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "locationId",
          name: "locationId",
          type: "select",
          label: t("inventory.forms.newStockQuant.fields.locationId"),
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "quantity",
          name: "quantity",
          type: "number",
          label: t("inventory.forms.newStockQuant.fields.quantity"),
          required: true,
          width: "1/2",
          defaultValue: 0,
        },
        {
          id: "reservedQuantity",
          name: "reservedQuantity",
          type: "number",
          label: t("inventory.forms.newStockQuant.fields.reservedQuantity"),
          width: "1/2",
          defaultValue: 0,
        },
        {
          id: "cost",
          name: "cost",
          type: "number",
          label: t("inventory.forms.newStockQuant.fields.cost"),
          width: "1/2",
          defaultValue: 0,
        },
      ],
    },
  ],
})

export const newWarehouse3dZoneForm = (t: TFunction): FormConfig => ({
  id: "new-warehouse-3d-zone",
  title: t("inventory.forms.newWarehouse3dZone.title"),
  description: t("inventory.forms.newWarehouse3dZone.description"),
  sections: [
    {
      id: "zone-main",
      title: t("inventory.forms.newWarehouse3dZone.sections.main"),
      fields: [
        {
          id: "warehouseId",
          name: "warehouseId",
          type: "select",
          label: t("inventory.forms.newWarehouse3dZone.fields.warehouseId"),
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "locationId",
          name: "locationId",
          type: "select",
          label: t("inventory.forms.newWarehouse3dZone.fields.locationId"),
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "displayType",
          name: "displayType",
          type: "select",
          label: t("inventory.forms.newWarehouse3dZone.fields.displayType"),
          required: true,
          width: "1/2",
          defaultValue: "Rack",
          options: [
            { value: "Rack", label: t("inventory.forms.newWarehouse3dZone.fields.displayTypes.rack") },
            { value: "Floor", label: t("inventory.forms.newWarehouse3dZone.fields.displayTypes.floor") },
            { value: "Bin", label: t("inventory.forms.newWarehouse3dZone.fields.displayTypes.bin") },
          ],
        },
        {
          id: "color",
          name: "color",
          type: "text",
          label: t("inventory.forms.newWarehouse3dZone.fields.color"),
          width: "1/2",
          defaultValue: "#0e7490",
        },
        {
          id: "width",
          name: "width",
          type: "number",
          label: t("inventory.forms.newWarehouse3dZone.fields.width"),
          width: "1/3",
          defaultValue: 10,
        },
        {
          id: "height",
          name: "height",
          type: "number",
          label: t("inventory.forms.newWarehouse3dZone.fields.height"),
          width: "1/3",
          defaultValue: 3,
        },
        {
          id: "depth",
          name: "depth",
          type: "number",
          label: t("inventory.forms.newWarehouse3dZone.fields.depth"),
          width: "1/3",
          defaultValue: 8,
        },
        {
          id: "rows",
          name: "rows",
          type: "number",
          label: t("inventory.forms.newWarehouse3dZone.fields.rows"),
          width: "1/3",
          defaultValue: 4,
        },
        {
          id: "columns",
          name: "columns",
          type: "number",
          label: t("inventory.forms.newWarehouse3dZone.fields.columns"),
          width: "1/3",
          defaultValue: 8,
        },
        {
          id: "levels",
          name: "levels",
          type: "number",
          label: t("inventory.forms.newWarehouse3dZone.fields.levels"),
          width: "1/3",
          defaultValue: 3,
        },
      ],
    },
  ],
})

export const newProductSupplierLineForm = (t: TFunction): FormConfig => ({
  id: "new-product-supplier-line",
  title: t("inventory.forms.newProductSupplierLine.title"),
  description: t("inventory.forms.newProductSupplierLine.description"),
  sections: [
    {
      id: "supplier-main",
      title: t("inventory.forms.newProductSupplierLine.sections.main"),
      fields: [
        {
          id: "productTmplId",
          name: "productTmplId",
          type: "number",
          label: t("inventory.forms.newProductSupplierLine.fields.productTmplId"),
          description: t("inventory.forms.newProductSupplierLine.fields.productTmplIdHint"),
          width: "1/2",
        },
        {
          id: "partnerId",
          name: "partnerId",
          type: "number",
          label: t("inventory.forms.newProductSupplierLine.fields.partnerId"),
          required: true,
          width: "1/2",
        },
        {
          id: "minQty",
          name: "minQty",
          type: "number",
          label: t("inventory.forms.newProductSupplierLine.fields.minQty"),
          width: "1/2",
          defaultValue: 0,
        },
        {
          id: "price",
          name: "price",
          type: "number",
          label: t("inventory.forms.newProductSupplierLine.fields.price"),
          required: true,
          width: "1/2",
          defaultValue: 0,
        },
        {
          id: "currencyId",
          name: "currencyId",
          type: "select",
          label: t("inventory.forms.newProductSupplierLine.fields.currencyId"),
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "delay",
          name: "delay",
          type: "number",
          label: t("inventory.forms.newProductSupplierLine.fields.delay"),
          width: "1/2",
          defaultValue: 0,
        },
        {
          id: "sequence",
          name: "sequence",
          type: "number",
          label: t("inventory.forms.newProductSupplierLine.fields.sequence"),
          width: "1/2",
          defaultValue: 10,
        },
      ],
    },
  ],
})

export const newProductPackagingForm = (t: TFunction): FormConfig => ({
  id: "new-product-packaging",
  title: t("inventory.forms.newProductPackaging.title"),
  description: t("inventory.forms.newProductPackaging.description"),
  sections: [
    {
      id: "packaging-main",
      title: t("inventory.forms.newProductPackaging.sections.main"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("inventory.forms.newProductPackaging.fields.name"),
          required: true,
          width: "full",
        },
        {
          id: "qty",
          name: "qty",
          type: "number",
          label: t("inventory.forms.newProductPackaging.fields.qty"),
          required: true,
          width: "1/2",
          defaultValue: 1,
        },
        {
          id: "uomId",
          name: "uomId",
          type: "select",
          label: t("inventory.forms.newProductPackaging.fields.uomId"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "barcode",
          name: "barcode",
          type: "text",
          label: t("inventory.forms.newProductPackaging.fields.barcode"),
          width: "full",
        },
        {
          id: "length",
          name: "length",
          type: "number",
          label: t("inventory.forms.newProductPackaging.fields.length"),
          width: "1/3",
          defaultValue: 0,
        },
        {
          id: "width",
          name: "width",
          type: "number",
          label: t("inventory.forms.newProductPackaging.fields.width"),
          width: "1/3",
          defaultValue: 0,
        },
        {
          id: "height",
          name: "height",
          type: "number",
          label: t("inventory.forms.newProductPackaging.fields.height"),
          width: "1/3",
          defaultValue: 0,
        },
        {
          id: "weight",
          name: "weight",
          type: "number",
          label: t("inventory.forms.newProductPackaging.fields.weight"),
          width: "1/2",
          defaultValue: 0,
        },
        {
          id: "maxWeight",
          name: "maxWeight",
          type: "number",
          label: t("inventory.forms.newProductPackaging.fields.maxWeight"),
          width: "1/2",
          defaultValue: 0,
        },
      ],
    },
  ],
})

export const newAdjustmentReasonForm = (t: TFunction): FormConfig => ({
  id: "new-adjustment-reason",
  title: t("inventory.forms.newAdjustmentReason.title"),
  description: t("inventory.forms.newAdjustmentReason.description"),
  submitLabel: t("inventory.forms.newAdjustmentReason.submitLabel"),
  sections: [
    {
      id: "adjustment-reason-main",
      title: t("inventory.forms.newAdjustmentReason.sections.main"),
      fields: [
        {
          id: "code",
          name: "code",
          type: "text",
          label: t("inventory.forms.newAdjustmentReason.fields.code"),
          placeholder: t("inventory.forms.newAdjustmentReason.fields.codePlaceholder"),
          required: true,
          width: "1/2",
        },
        {
          id: "description",
          name: "description",
          type: "text",
          label: t("inventory.forms.newAdjustmentReason.fields.description"),
          width: "full",
        },
        {
          id: "isActive",
          name: "isActive",
          type: "checkbox",
          label: t("inventory.forms.newAdjustmentReason.fields.isActive"),
          width: "1/2",
          defaultValue: true,
        },
        {
          id: "isSystem",
          name: "isSystem",
          type: "checkbox",
          label: t("inventory.forms.newAdjustmentReason.fields.isSystem"),
          width: "1/2",
          defaultValue: false,
        },
        {
          id: "metadata",
          name: "metadata",
          type: "textarea",
          label: t("inventory.forms.newAdjustmentReason.fields.metadata"),
          width: "full",
        },
      ],
    },
  ],
})

export const newTraceabilityRecordForm = (t: TFunction): FormConfig => ({
  id: "new-traceability-record",
  title: t("inventory.forms.newTraceabilityRecord.title"),
  description: t("inventory.forms.newTraceabilityRecord.description"),
  submitLabel: t("inventory.forms.newTraceabilityRecord.submitLabel"),
  sections: [
    {
      id: "trace-record-main",
      title: t("inventory.forms.newTraceabilityRecord.sections.main"),
      fields: [
        {
          id: "productId",
          name: "productId",
          type: "text",
          label: t("inventory.forms.newTraceabilityRecord.fields.productId"),
          required: true,
          width: "1/2",
        },
        {
          id: "documentType",
          name: "documentType",
          type: "text",
          label: t("inventory.forms.newTraceabilityRecord.fields.documentType"),
          placeholder: t("inventory.forms.newTraceabilityRecord.fields.documentTypePlaceholder"),
          required: true,
          width: "1/2",
        },
        {
          id: "documentId",
          name: "documentId",
          type: "text",
          label: t("inventory.forms.newTraceabilityRecord.fields.documentId"),
          required: true,
          width: "1/2",
        },
        {
          id: "quantity",
          name: "quantity",
          type: "number",
          label: t("inventory.forms.newTraceabilityRecord.fields.quantity"),
          required: true,
          width: "1/4",
        },
        {
          id: "uomId",
          name: "uomId",
          type: "select",
          label: t("inventory.forms.newTraceabilityRecord.fields.uomId"),
          placeholder: t("inventory.forms.newProduct.fields.uomIdPlaceholder"),
          required: true,
          width: "1/4",
          options: emptySelect,
        },
        {
          id: "date",
          name: "date",
          type: "datetime",
          label: t("inventory.forms.newTraceabilityRecord.fields.date"),
          width: "full",
        },
        {
          id: "serialId",
          name: "serialId",
          type: "text",
          label: t("inventory.forms.newTraceabilityRecord.fields.serialId"),
          width: "1/2",
        },
        {
          id: "lotId",
          name: "lotId",
          type: "text",
          label: t("inventory.forms.newTraceabilityRecord.fields.lotId"),
          width: "1/2",
        },
        {
          id: "documentLineId",
          name: "documentLineId",
          type: "text",
          label: t("inventory.forms.newTraceabilityRecord.fields.documentLineId"),
          width: "1/2",
        },
        {
          id: "moveId",
          name: "moveId",
          type: "text",
          label: t("inventory.forms.newTraceabilityRecord.fields.moveId"),
          width: "1/2",
        },
        {
          id: "partnerId",
          name: "partnerId",
          type: "text",
          label: t("inventory.forms.newTraceabilityRecord.fields.partnerId"),
          width: "1/2",
        },
        {
          id: "origin",
          name: "origin",
          type: "text",
          label: t("inventory.forms.newTraceabilityRecord.fields.origin"),
          width: "1/2",
        },
        {
          id: "notes",
          name: "notes",
          type: "textarea",
          label: t("inventory.forms.newTraceabilityRecord.fields.notes"),
          width: "full",
        },
        {
          id: "metadata",
          name: "metadata",
          type: "textarea",
          label: t("inventory.forms.newTraceabilityRecord.fields.metadata"),
          width: "full",
        },
      ],
    },
  ],
})

export const newTraceabilityReportForm = (t: TFunction): FormConfig => ({
  id: "new-traceability-report",
  title: t("inventory.forms.newTraceabilityReport.title"),
  description: t("inventory.forms.newTraceabilityReport.description"),
  submitLabel: t("inventory.forms.newTraceabilityReport.submitLabel"),
  sections: [
    {
      id: "trace-report-main",
      title: t("inventory.forms.newTraceabilityReport.sections.main"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("inventory.forms.newTraceabilityReport.fields.name"),
          required: true,
          width: "full",
        },
        {
          id: "dateFrom",
          name: "dateFrom",
          type: "datetime",
          label: t("inventory.forms.newTraceabilityReport.fields.dateFrom"),
          required: true,
          width: "1/2",
        },
        {
          id: "dateTo",
          name: "dateTo",
          type: "datetime",
          label: t("inventory.forms.newTraceabilityReport.fields.dateTo"),
          required: true,
          width: "1/2",
        },
        {
          id: "productIds",
          name: "productIds",
          type: "textarea",
          label: t("inventory.forms.newTraceabilityReport.fields.productIds"),
          width: "full",
        },
        {
          id: "lotIds",
          name: "lotIds",
          type: "textarea",
          label: t("inventory.forms.newTraceabilityReport.fields.lotIds"),
          width: "full",
        },
        {
          id: "serialIds",
          name: "serialIds",
          type: "textarea",
          label: t("inventory.forms.newTraceabilityReport.fields.serialIds"),
          width: "full",
        },
        {
          id: "locationIds",
          name: "locationIds",
          type: "textarea",
          label: t("inventory.forms.newTraceabilityReport.fields.locationIds"),
          width: "full",
        },
        {
          id: "warehouseIds",
          name: "warehouseIds",
          type: "textarea",
          label: t("inventory.forms.newTraceabilityReport.fields.warehouseIds"),
          width: "full",
        },
        {
          id: "partnerIds",
          name: "partnerIds",
          type: "textarea",
          label: t("inventory.forms.newTraceabilityReport.fields.partnerIds"),
          width: "full",
        },
        {
          id: "pickingTypeIds",
          name: "pickingTypeIds",
          type: "textarea",
          label: t("inventory.forms.newTraceabilityReport.fields.pickingTypeIds"),
          width: "full",
        },
        {
          id: "metadata",
          name: "metadata",
          type: "textarea",
          label: t("inventory.forms.newTraceabilityReport.fields.metadata"),
          width: "full",
        },
      ],
    },
  ],
})

export const inventoryFormConfigs = (t: TFunction): Record<string, FormConfig> => ({
  "new-product": newProductForm(t),
  "new-transfer": newTransferForm(t),
  "new-inventory-adjustment": newInventoryAdjustmentForm(t),
  "new-stock-location": newStockLocationForm(t),
  "new-warehouse": newWarehouseForm(t),
  "edit-warehouse": editWarehouseForm(t),
  "edit-product": editProductForm(t),
  "new-product-variant": newProductVariantForm(t),
  "assign-user-picking": assignUserToPickingForm(t),
  "new-quality-check": newQualityCheckForm(t),
  "new-quality-alert": newQualityAlertForm(t),
  "new-quality-point": newQualityPointForm(t),
  "new-quality-team": newQualityTeamForm(t),
  "new-barcode-rule": newBarcodeRuleForm(t),
  "new-replenishment-rule": newReplenishmentRuleForm(t),
  "new-picking-wave": newPickingWaveForm(t),
  "new-product-category": newProductCategoryForm(t),
  "new-stock-quant": newStockQuantForm(t),
  "new-warehouse-3d-zone": newWarehouse3dZoneForm(t),
  "new-product-supplier-line": newProductSupplierLineForm(t),
  "new-product-packaging": newProductPackagingForm(t),
  "new-adjustment-reason": newAdjustmentReasonForm(t),
  "new-traceability-record": newTraceabilityRecordForm(t),
  "new-traceability-report": newTraceabilityReportForm(t),
})
