import type { TFunction } from "i18next"
import type { FormConfig } from "./form-types"

const emptySelect: Array<{ value: string; label: string; disabled?: boolean }> = []

export const newProjectForm = (t: TFunction): FormConfig => ({
  id: "new-project",
  title: t("projects.forms.newProject.title"),
  description: t("projects.forms.newProject.description"),
  sections: [
    {
      id: "proj-info",
      title: t("projects.forms.newProject.sections.projectDetails"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("projects.forms.newProject.fields.name"),
          placeholder: t("projects.forms.newProject.fields.namePlaceholder"),
          required: true,
          width: "full",
        },
        {
          id: "pricelistId",
          name: "pricelistId",
          type: "select",
          label: t("projects.forms.newProject.fields.pricelistId"),
          placeholder: t("projects.forms.newProject.fields.pricelistPlaceholder"),
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "partnerId",
          name: "partnerId",
          type: "select",
          label: t("projects.forms.newProject.fields.partnerId"),
          placeholder: t("projects.forms.newProject.fields.partnerIdPlaceholder"),
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "billType",
          name: "billType",
          type: "select",
          label: t("projects.forms.newProject.fields.billType"),
          width: "1/2",
          required: true,
          defaultValue: "customer_task",
          options: [
            { value: "customer_task", label: t("projects.forms.newProject.fields.billTypes.customer_task") },
            { value: "customer_project", label: t("projects.forms.newProject.fields.billTypes.customer_project") },
            { value: "no", label: t("projects.forms.newProject.fields.billTypes.no") },
          ],
        },
        {
          id: "pricingType",
          name: "pricingType",
          type: "select",
          label: t("projects.forms.newProject.fields.pricingType"),
          width: "1/2",
          required: true,
          defaultValue: "task_rate",
          options: [
            { value: "task_rate", label: t("projects.forms.newProject.fields.pricingTypes.task_rate") },
            { value: "fixed_rate", label: t("projects.forms.newProject.fields.pricingTypes.fixed_rate") },
            { value: "employee_rate", label: t("projects.forms.newProject.fields.pricingTypes.employee_rate") },
          ],
        },
        {
          id: "allocatedHours",
          name: "allocatedHours",
          type: "number",
          label: t("projects.forms.newProject.fields.allocatedHours"),
          placeholder: t("projects.forms.newProject.fields.allocatedHoursPlaceholder"),
          width: "1/2",
        },
        {
          id: "dateStart",
          name: "dateStart",
          type: "date",
          label: t("projects.forms.newProject.fields.dateStart"),
          width: "1/2",
        },
        {
          id: "dateEnd",
          name: "dateEnd",
          type: "date",
          label: t("projects.forms.newProject.fields.dateEnd"),
          width: "1/2",
        },
        {
          id: "description",
          name: "description",
          type: "textarea",
          label: t("projects.forms.newProject.fields.description"),
          placeholder: t("projects.forms.newProject.fields.descriptionPlaceholder"),
          width: "full",
          rows: 3,
        },
      ],
    },
  ],
})

export const newTaskForm = (t: TFunction): FormConfig => ({
  id: "new-task",
  title: t("projects.forms.newTask.title"),
  description: t("projects.forms.newTask.description"),
  sections: [
    {
      id: "task-info",
      title: t("projects.forms.newTask.sections.taskDetails"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("projects.forms.newTask.fields.name"),
          placeholder: t("projects.forms.newTask.fields.namePlaceholder"),
          required: true,
          width: "full",
        },
        {
          id: "projectId",
          name: "projectId",
          type: "select",
          label: t("projects.forms.newTask.fields.projectId"),
          placeholder: t("projects.forms.newTask.fields.projectIdPlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "stageId",
          name: "stageId",
          type: "select",
          label: t("projects.forms.newTask.fields.stageId"),
          placeholder: t("projects.forms.newTask.fields.stagePlaceholder"),
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "priority",
          name: "priority",
          type: "select",
          label: t("projects.forms.newTask.fields.priority"),
          width: "1/2",
          options: [
            { value: "0", label: t("projects.forms.newTask.fields.options.0") },
            { value: "1", label: t("projects.forms.newTask.fields.options.1") },
            { value: "2", label: t("projects.forms.newTask.fields.options.2") },
            { value: "3", label: t("projects.forms.newTask.fields.options.3") },
          ],
        },
        {
          id: "plannedHours",
          name: "plannedHours",
          type: "number",
          label: t("projects.forms.newTask.fields.plannedHours"),
          placeholder: t("projects.forms.newTask.fields.plannedHoursPlaceholder"),
          width: "1/2",
        },
        {
          id: "wbsCode",
          name: "wbsCode",
          type: "text",
          label: "WBS code",
          width: "1/2",
        },
        {
          id: "milestoneId",
          name: "milestoneId",
          type: "select",
          label: "Milestone",
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "dateDeadline",
          name: "dateDeadline",
          type: "date",
          label: t("projects.forms.newTask.fields.dateDeadline"),
          width: "1/2",
        },
        {
          id: "description",
          name: "description",
          type: "textarea",
          label: t("projects.forms.newTask.fields.description"),
          placeholder: t("projects.forms.newTask.fields.descriptionPlaceholder"),
          width: "full",
          rows: 3,
        },
      ],
    },
  ],
})

export const editProjectForm = (t: TFunction): FormConfig => ({
  id: "edit-project",
  title: t("projects.forms.editProject.title"),
  description: t("projects.forms.editProject.description"),
  sections: [
    {
      id: "proj-info",
      title: t("projects.forms.editProject.sections.projectDetails"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("projects.forms.editProject.fields.name"),
          placeholder: t("projects.forms.editProject.fields.namePlaceholder"),
          required: true,
          width: "full",
        },
        {
          id: "pricelistId",
          name: "pricelistId",
          type: "select",
          label: t("projects.forms.editProject.fields.pricelistId"),
          placeholder: t("projects.forms.editProject.fields.pricelistPlaceholder"),
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "partnerId",
          name: "partnerId",
          type: "select",
          label: t("projects.forms.editProject.fields.partnerId"),
          placeholder: t("projects.forms.editProject.fields.partnerIdPlaceholder"),
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "billType",
          name: "billType",
          type: "select",
          label: t("projects.forms.editProject.fields.billType"),
          width: "1/2",
          required: true,
          defaultValue: "customer_task",
          options: [
            { value: "customer_task", label: t("projects.forms.editProject.fields.billTypes.customer_task") },
            { value: "customer_project", label: t("projects.forms.editProject.fields.billTypes.customer_project") },
            { value: "no", label: t("projects.forms.editProject.fields.billTypes.no") },
          ],
        },
        {
          id: "pricingType",
          name: "pricingType",
          type: "select",
          label: t("projects.forms.editProject.fields.pricingType"),
          width: "1/2",
          required: true,
          defaultValue: "task_rate",
          options: [
            { value: "task_rate", label: t("projects.forms.editProject.fields.pricingTypes.task_rate") },
            { value: "fixed_rate", label: t("projects.forms.editProject.fields.pricingTypes.fixed_rate") },
            { value: "employee_rate", label: t("projects.forms.editProject.fields.pricingTypes.employee_rate") },
          ],
        },
        {
          id: "allocatedHours",
          name: "allocatedHours",
          type: "number",
          label: t("projects.forms.editProject.fields.allocatedHours"),
          placeholder: t("projects.forms.editProject.fields.allocatedHoursPlaceholder"),
          width: "1/2",
        },
        {
          id: "dateStart",
          name: "dateStart",
          type: "date",
          label: t("projects.forms.editProject.fields.dateStart"),
          width: "1/2",
        },
        {
          id: "dateEnd",
          name: "dateEnd",
          type: "date",
          label: t("projects.forms.editProject.fields.dateEnd"),
          width: "1/2",
        },
        {
          id: "description",
          name: "description",
          type: "textarea",
          label: t("projects.forms.editProject.fields.description"),
          placeholder: t("projects.forms.editProject.fields.descriptionPlaceholder"),
          width: "full",
          rows: 3,
        },
        {
          id: "active",
          name: "active",
          type: "switch",
          label: t("projects.forms.editProject.fields.active"),
          width: "1/2",
        },
      ],
    },
  ],
})

export const editTaskForm = (t: TFunction): FormConfig => ({
  id: "edit-task",
  title: t("projects.forms.editTask.title"),
  description: t("projects.forms.editTask.description"),
  sections: [
    {
      id: "task-info",
      title: t("projects.forms.editTask.sections.taskDetails"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("projects.forms.editTask.fields.name"),
          placeholder: t("projects.forms.editTask.fields.namePlaceholder"),
          required: true,
          width: "full",
        },
        {
          id: "projectId",
          name: "projectId",
          type: "select",
          label: t("projects.forms.editTask.fields.projectId"),
          placeholder: t("projects.forms.editTask.fields.projectIdPlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "stageId",
          name: "stageId",
          type: "select",
          label: t("projects.forms.editTask.fields.stageId"),
          placeholder: t("projects.forms.editTask.fields.stagePlaceholder"),
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "priority",
          name: "priority",
          type: "select",
          label: t("projects.forms.editTask.fields.priority"),
          width: "1/2",
          options: [
            { value: "0", label: t("projects.forms.editTask.fields.options.0") },
            { value: "1", label: t("projects.forms.editTask.fields.options.1") },
            { value: "2", label: t("projects.forms.editTask.fields.options.2") },
            { value: "3", label: t("projects.forms.editTask.fields.options.3") },
          ],
        },
        {
          id: "plannedHours",
          name: "plannedHours",
          type: "number",
          label: t("projects.forms.editTask.fields.plannedHours"),
          placeholder: t("projects.forms.editTask.fields.plannedHoursPlaceholder"),
          width: "1/2",
        },
        {
          id: "wbsCode",
          name: "wbsCode",
          type: "text",
          label: "WBS code",
          width: "1/2",
        },
        {
          id: "milestoneId",
          name: "milestoneId",
          type: "select",
          label: "Milestone",
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "dateDeadline",
          name: "dateDeadline",
          type: "date",
          label: t("projects.forms.editTask.fields.dateDeadline"),
          width: "1/2",
        },
        {
          id: "description",
          name: "description",
          type: "textarea",
          label: t("projects.forms.editTask.fields.description"),
          placeholder: t("projects.forms.editTask.fields.descriptionPlaceholder"),
          width: "full",
          rows: 3,
        },
        {
          id: "kanbanState",
          name: "kanbanState",
          type: "select",
          label: t("projects.forms.editTask.fields.kanbanState"),
          width: "1/2",
          options: [
            { value: "normal", label: t("projects.forms.editTask.fields.states.normal") },
            { value: "done", label: t("projects.forms.editTask.fields.states.done") },
            { value: "blocked", label: t("projects.forms.editTask.fields.states.blocked") },
          ],
        },
      ],
    },
  ],
})

export const logTimesheetForm = (t: TFunction): FormConfig => ({
  id: "log-timesheet",
  title: t("projects.forms.logTimesheet.title"),
  description: t("projects.forms.logTimesheet.description"),
  sections: [
    {
      id: "timesheet-info",
      title: t("projects.forms.logTimesheet.sections.details"),
      fields: [
        {
          id: "projectId",
          name: "projectId",
          type: "select",
          label: t("projects.forms.logTimesheet.fields.projectId"),
          placeholder: t("projects.forms.logTimesheet.fields.projectIdPlaceholder"),
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "taskId",
          name: "taskId",
          type: "select",
          label: t("projects.forms.logTimesheet.fields.taskId"),
          placeholder: t("projects.forms.logTimesheet.fields.taskIdPlaceholder"),
          width: "full",
          options: emptySelect,
        },
        {
          id: "employeeId",
          name: "employeeId",
          type: "select",
          label: t("projects.forms.logTimesheet.fields.employeeId"),
          placeholder: t("projects.forms.logTimesheet.fields.employeeIdPlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "currencyId",
          name: "currencyId",
          type: "select",
          label: t("projects.forms.logTimesheet.fields.currencyId"),
          placeholder: t("projects.forms.logTimesheet.fields.currencyIdPlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "date",
          name: "date",
          type: "date",
          label: t("projects.forms.logTimesheet.fields.date"),
          width: "1/2",
        },
        {
          id: "unitAmount",
          name: "unitAmount",
          type: "number",
          label: t("projects.forms.logTimesheet.fields.hours"),
          placeholder: t("projects.forms.logTimesheet.fields.hoursPlaceholder"),
          width: "1/2",
          step: 0.25,
          min: 0,
        },
        {
          id: "employeeCost",
          name: "employeeCost",
          type: "number",
          label: t("projects.forms.logTimesheet.fields.employeeCost"),
          placeholder: t("projects.forms.logTimesheet.fields.employeeCostPlaceholder"),
          width: "1/2",
          step: 0.01,
          min: 0,
          defaultValue: 0,
        },
        {
          id: "encodingUomId",
          name: "encodingUomId",
          type: "select",
          label: t("projects.forms.logTimesheet.fields.encodingUomId"),
          placeholder: t("projects.forms.logTimesheet.fields.encodingUomIdPlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "timesheetInvoiceType",
          name: "timesheetInvoiceType",
          type: "select",
          label: t("projects.forms.logTimesheet.fields.timesheetInvoiceType"),
          width: "1/2",
          defaultValue: "billable",
          options: [
            { value: "billable", label: t("projects.forms.logTimesheet.fields.invoiceTypes.billable") },
            { value: "non_billable", label: t("projects.forms.logTimesheet.fields.invoiceTypes.non_billable") },
            { value: "timesheet_revenues", label: t("projects.forms.logTimesheet.fields.invoiceTypes.timesheet_revenues") },
          ],
        },
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("projects.forms.logTimesheet.fields.description"),
          placeholder: t("projects.forms.logTimesheet.fields.descriptionPlaceholder"),
          width: "full",
        },
      ],
    },
  ],
})

export const newProjectRateCardForm = (_t: TFunction): FormConfig => ({
  id: "new-project-rate-card",
  title: "New rate card",
  description: "Cost and sell rates for project timesheets",
  sections: [
    {
      id: "rate-card-info",
      title: "Rate card",
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: "Name",
          required: true,
          width: "full",
        },
        {
          id: "currencyId",
          name: "currencyId",
          type: "select",
          label: "Currency",
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "projectId",
          name: "projectId",
          type: "select",
          label: "Project (optional)",
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "active",
          name: "active",
          type: "switch",
          label: "Active",
          width: "1/2",
          defaultValue: true,
        },
      ],
    },
  ],
})

export const newProjectRateCardLineForm = (_t: TFunction): FormConfig => ({
  id: "new-project-rate-card-line",
  title: "New rate card line",
  description: "Scoped employee, task, or project rates",
  sections: [
    {
      id: "line-info",
      title: "Line",
      fields: [
        {
          id: "rateCardId",
          name: "rateCardId",
          type: "select",
          label: "Rate card",
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "scope",
          name: "scope",
          type: "select",
          label: "Scope",
          required: true,
          width: "1/2",
          defaultValue: "employee",
          options: [
            { value: "employee", label: "Employee" },
            { value: "task", label: "Task" },
            { value: "project", label: "Project" },
          ],
        },
        {
          id: "currencyId",
          name: "currencyId",
          type: "select",
          label: "Currency",
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "employeeId",
          name: "employeeId",
          type: "select",
          label: "Employee",
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "taskId",
          name: "taskId",
          type: "select",
          label: "Task",
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "costRate",
          name: "costRate",
          type: "number",
          label: "Cost rate",
          required: true,
          width: "1/2",
          step: 0.01,
          min: 0,
        },
        {
          id: "sellRate",
          name: "sellRate",
          type: "number",
          label: "Sell rate",
          required: true,
          width: "1/2",
          step: 0.01,
          min: 0,
        },
        {
          id: "active",
          name: "active",
          type: "switch",
          label: "Active",
          width: "1/2",
          defaultValue: true,
        },
      ],
    },
  ],
})

export const newResourceAllocationForm = (_t: TFunction): FormConfig => ({
  id: "new-resource-allocation",
  title: "Book resource allocation",
  description: "Reserve employee or HR resource capacity on a project/task",
  sections: [
    {
      id: "allocation",
      title: "Allocation",
      fields: [
        {
          id: "employeeId",
          name: "employeeId",
          type: "select",
          label: "Employee",
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "resourceId",
          name: "resourceId",
          type: "select",
          label: "HR resource",
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "projectId",
          name: "projectId",
          type: "select",
          label: "Project",
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "taskId",
          name: "taskId",
          type: "select",
          label: "Task (optional)",
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "dateFrom",
          name: "dateFrom",
          type: "date",
          label: "From",
          required: true,
          width: "1/2",
        },
        {
          id: "dateTo",
          name: "dateTo",
          type: "date",
          label: "To",
          required: true,
          width: "1/2",
        },
        {
          id: "allocatedHours",
          name: "allocatedHours",
          type: "number",
          label: "Hours",
          width: "1/2",
          step: 0.5,
          min: 0,
          defaultValue: 8,
        },
        {
          id: "allocationPercent",
          name: "allocationPercent",
          type: "number",
          label: "Percent (alt)",
          width: "1/2",
          step: 1,
          min: 0,
          max: 100,
          defaultValue: 0,
        },
        {
          id: "enforceCapacity",
          name: "enforceCapacity",
          type: "switch",
          label: "Reject if over-allocated",
          width: "1/2",
          defaultValue: true,
        },
        {
          id: "skillHint",
          name: "skillHint",
          type: "text",
          label: "Skill match hint (optional)",
          width: "full",
          placeholder: "Soft match against HR skills matrix",
        },
        {
          id: "notes",
          name: "notes",
          type: "textarea",
          label: "Notes",
          width: "full",
          rows: 2,
        },
      ],
    },
  ],
})

export const newProjectMilestoneForm = (_t: TFunction): FormConfig => ({
  id: "new-project-milestone",
  title: "New milestone",
  description: "Delivery milestone linked to project tasks",
  sections: [
    {
      id: "milestone",
      title: "Milestone",
      fields: [
        {
          id: "projectId",
          name: "projectId",
          type: "select",
          label: "Project",
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "name",
          name: "name",
          type: "text",
          label: "Name",
          required: true,
          width: "full",
        },
        {
          id: "deadline",
          name: "deadline",
          type: "date",
          label: "Deadline",
          width: "1/2",
        },
        {
          id: "sequence",
          name: "sequence",
          type: "number",
          label: "Sequence",
          width: "1/2",
          defaultValue: 10,
        },
        {
          id: "billAmount",
          name: "billAmount",
          type: "number",
          label: "Bill amount",
          width: "1/2",
          defaultValue: 0,
        },
        {
          id: "percentComplete",
          name: "percentComplete",
          type: "number",
          label: "% complete",
          width: "1/2",
          defaultValue: 0,
        },
        {
          id: "description",
          name: "description",
          type: "textarea",
          label: "Description",
          width: "full",
          rows: 2,
        },
      ],
    },
  ],
})

/** Expense project rebill launched from Projects (calls expenses reducer). */
export const projectExpenseRebillForm = (_t: TFunction): FormConfig => ({
  id: "project-expense-rebill",
  title: "Rebill project expense",
  description: "Create a client invoice from a posted expense sheet linked to a project",
  sections: [
    {
      id: "rebill",
      title: "Rebill",
      fields: [
        {
          id: "sheetId",
          name: "sheetId",
          type: "select",
          label: "Expense sheet",
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "invoiceDate",
          name: "invoiceDate",
          type: "date",
          label: "Invoice date",
          required: true,
          width: "full",
        },
        {
          id: "journalId",
          name: "journalId",
          type: "select",
          label: "Journal",
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "receivableAccountId",
          name: "receivableAccountId",
          type: "select",
          label: "Receivable account",
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "incomeAccountId",
          name: "incomeAccountId",
          type: "select",
          label: "Income account",
          required: true,
          width: "1/2",
          options: emptySelect,
        },
      ],
    },
  ],
})

/** Wave E — change order (scope / budget / rate deltas; dual baselines on apply). */
export const newProjectChangeOrderForm = (_t: TFunction): FormConfig => ({
  id: "new-project-change-order",
  title: "New change order",
  description: "Capture scope, budget, and rate deltas; apply to rebaseline",
  sections: [
    {
      id: "change-order",
      title: "Change order",
      fields: [
        {
          id: "projectId",
          name: "projectId",
          type: "select",
          label: "Project",
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "name",
          name: "name",
          type: "text",
          label: "Name",
          required: true,
          width: "full",
        },
        {
          id: "scopeDelta",
          name: "scopeDelta",
          type: "textarea",
          label: "Scope delta",
          required: false,
          width: "full",
        },
        {
          id: "budgetDelta",
          name: "budgetDelta",
          type: "number",
          label: "Budget delta",
          required: true,
          width: "1/2",
        },
        {
          id: "plannedHoursDelta",
          name: "plannedHoursDelta",
          type: "number",
          label: "Planned hours delta",
          required: true,
          width: "1/2",
        },
        {
          id: "rateDeltaPercent",
          name: "rateDeltaPercent",
          type: "number",
          label: "Rate delta %",
          required: true,
          width: "1/2",
        },
        {
          id: "description",
          name: "description",
          type: "textarea",
          label: "Description",
          required: false,
          width: "full",
        },
      ],
    },
  ],
})

/** Wave E — link vendor PO / bill cost to project (subcontractor). */
export const linkSubcontractorCostForm = (_t: TFunction): FormConfig => ({
  id: "link-subcontractor-cost",
  title: "Link subcontractor cost",
  description: "Attribute a vendor PO or bill amount to a project for margin",
  sections: [
    {
      id: "subcon",
      title: "Cost link",
      fields: [
        {
          id: "projectId",
          name: "projectId",
          type: "select",
          label: "Project",
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "purchaseOrderId",
          name: "purchaseOrderId",
          type: "text",
          label: "Purchase order ID",
          required: false,
          width: "1/2",
        },
        {
          id: "purchaseOrderLineId",
          name: "purchaseOrderLineId",
          type: "text",
          label: "PO line ID",
          required: false,
          width: "1/2",
        },
        {
          id: "amount",
          name: "amount",
          type: "number",
          label: "Amount",
          required: true,
          width: "1/2",
        },
        {
          id: "currencyId",
          name: "currencyId",
          type: "text",
          label: "Currency ID",
          required: true,
          width: "1/2",
        },
        {
          id: "name",
          name: "name",
          type: "text",
          label: "Label",
          required: false,
          width: "full",
        },
      ],
    },
  ],
})

/** Wave E — create project integration intent (payroll / calendar / e-invoice). */
export const newProjectIntegrationIntentForm = (_t: TFunction): FormConfig => ({
  id: "new-project-integration-intent",
  title: "New project integration intent",
  description: "Queue payroll export, calendar sync, or e-invoice for the worker",
  sections: [
    {
      id: "intent",
      title: "Intent",
      fields: [
        {
          id: "projectId",
          name: "projectId",
          type: "select",
          label: "Project (optional)",
          required: false,
          width: "full",
          options: emptySelect,
        },
        {
          id: "intentType",
          name: "intentType",
          type: "select",
          label: "Type",
          required: true,
          width: "full",
          options: [
            { value: "payroll_export", label: "Payroll export" },
            { value: "calendar_sync", label: "Calendar sync" },
            { value: "e_invoice", label: "E-invoice" },
          ],
        },
        {
          id: "idempotencyKey",
          name: "idempotencyKey",
          type: "text",
          label: "Idempotency key",
          required: true,
          width: "full",
        },
        {
          id: "payload",
          name: "payload",
          type: "textarea",
          label: "Payload (JSON)",
          required: true,
          width: "full",
        },
      ],
    },
  ],
})

export const projectsFormConfigs = (t: TFunction): Record<string, FormConfig> => ({
  "new-project": newProjectForm(t),
  "new-task": newTaskForm(t),
  "edit-project": editProjectForm(t),
  "edit-task": editTaskForm(t),
  "log-timesheet": logTimesheetForm(t),
  "new-project-rate-card": newProjectRateCardForm(t),
  "new-project-rate-card-line": newProjectRateCardLineForm(t),
  "new-resource-allocation": newResourceAllocationForm(t),
  "new-project-milestone": newProjectMilestoneForm(t),
  "project-expense-rebill": projectExpenseRebillForm(t),
  "new-project-change-order": newProjectChangeOrderForm(t),
  "link-subcontractor-cost": linkSubcontractorCostForm(t),
  "new-project-integration-intent": newProjectIntegrationIntentForm(t),
})
