import type { TFunction } from "i18next"
import type { FormConfig } from "./form-types"

const emptySelect: Array<{ value: string; label: string; disabled?: boolean }> = []

export const newProjectForm = (t: TFunction): FormConfig => ({
  id: "new-project",
  title: t("projects.forms.newProject.title"),
  description: t("projects.forms.newProject.description"),
  sections: [
    {
      id: "proj-info",
      title: t("projects.forms.newProject.sections.projectDetails"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("projects.forms.newProject.fields.name"),
          placeholder: t("projects.forms.newProject.fields.namePlaceholder"),
          required: true,
          width: "full",
        },
        {
          id: "pricelistId",
          name: "pricelistId",
          type: "select",
          label: t("projects.forms.newProject.fields.pricelistId"),
          placeholder: t("projects.forms.newProject.fields.pricelistPlaceholder"),
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "partnerId",
          name: "partnerId",
          type: "select",
          label: t("projects.forms.newProject.fields.partnerId"),
          placeholder: t("projects.forms.newProject.fields.partnerIdPlaceholder"),
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "allocatedHours",
          name: "allocatedHours",
          type: "number",
          label: t("projects.forms.newProject.fields.allocatedHours"),
          placeholder: t("projects.forms.newProject.fields.allocatedHoursPlaceholder"),
          width: "1/2",
        },
        {
          id: "dateStart",
          name: "dateStart",
          type: "date",
          label: t("projects.forms.newProject.fields.dateStart"),
          width: "1/2",
        },
        {
          id: "dateEnd",
          name: "dateEnd",
          type: "date",
          label: t("projects.forms.newProject.fields.dateEnd"),
          width: "1/2",
        },
        {
          id: "description",
          name: "description",
          type: "textarea",
          label: t("projects.forms.newProject.fields.description"),
          placeholder: t("projects.forms.newProject.fields.descriptionPlaceholder"),
          width: "full",
          rows: 3,
        },
      ],
    },
  ],
})

export const newTaskForm = (t: TFunction): FormConfig => ({
  id: "new-task",
  title: t("projects.forms.newTask.title"),
  description: t("projects.forms.newTask.description"),
  sections: [
    {
      id: "task-info",
      title: t("projects.forms.newTask.sections.taskDetails"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("projects.forms.newTask.fields.name"),
          placeholder: t("projects.forms.newTask.fields.namePlaceholder"),
          required: true,
          width: "full",
        },
        {
          id: "projectId",
          name: "projectId",
          type: "select",
          label: t("projects.forms.newTask.fields.projectId"),
          placeholder: t("projects.forms.newTask.fields.projectIdPlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "stageId",
          name: "stageId",
          type: "select",
          label: t("projects.forms.newTask.fields.stageId"),
          placeholder: t("projects.forms.newTask.fields.stagePlaceholder"),
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "priority",
          name: "priority",
          type: "select",
          label: t("projects.forms.newTask.fields.priority"),
          width: "1/2",
          options: [
            { value: "0", label: t("projects.forms.newTask.fields.options.0") },
            { value: "1", label: t("projects.forms.newTask.fields.options.1") },
            { value: "2", label: t("projects.forms.newTask.fields.options.2") },
            { value: "3", label: t("projects.forms.newTask.fields.options.3") },
          ],
        },
        {
          id: "plannedHours",
          name: "plannedHours",
          type: "number",
          label: t("projects.forms.newTask.fields.plannedHours"),
          placeholder: t("projects.forms.newTask.fields.plannedHoursPlaceholder"),
          width: "1/2",
        },
        {
          id: "dateDeadline",
          name: "dateDeadline",
          type: "date",
          label: t("projects.forms.newTask.fields.dateDeadline"),
          width: "1/2",
        },
        {
          id: "description",
          name: "description",
          type: "textarea",
          label: t("projects.forms.newTask.fields.description"),
          placeholder: t("projects.forms.newTask.fields.descriptionPlaceholder"),
          width: "full",
          rows: 3,
        },
      ],
    },
  ],
})

export const editProjectForm = (t: TFunction): FormConfig => ({
  id: "edit-project",
  title: t("projects.forms.editProject.title"),
  description: t("projects.forms.editProject.description"),
  sections: [
    {
      id: "proj-info",
      title: t("projects.forms.editProject.sections.projectDetails"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("projects.forms.editProject.fields.name"),
          placeholder: t("projects.forms.editProject.fields.namePlaceholder"),
          required: true,
          width: "full",
        },
        {
          id: "pricelistId",
          name: "pricelistId",
          type: "select",
          label: t("projects.forms.editProject.fields.pricelistId"),
          placeholder: t("projects.forms.editProject.fields.pricelistPlaceholder"),
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "partnerId",
          name: "partnerId",
          type: "select",
          label: t("projects.forms.editProject.fields.partnerId"),
          placeholder: t("projects.forms.editProject.fields.partnerIdPlaceholder"),
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "allocatedHours",
          name: "allocatedHours",
          type: "number",
          label: t("projects.forms.editProject.fields.allocatedHours"),
          placeholder: t("projects.forms.editProject.fields.allocatedHoursPlaceholder"),
          width: "1/2",
        },
        {
          id: "dateStart",
          name: "dateStart",
          type: "date",
          label: t("projects.forms.editProject.fields.dateStart"),
          width: "1/2",
        },
        {
          id: "dateEnd",
          name: "dateEnd",
          type: "date",
          label: t("projects.forms.editProject.fields.dateEnd"),
          width: "1/2",
        },
        {
          id: "description",
          name: "description",
          type: "textarea",
          label: t("projects.forms.editProject.fields.description"),
          placeholder: t("projects.forms.editProject.fields.descriptionPlaceholder"),
          width: "full",
          rows: 3,
        },
        {
          id: "active",
          name: "active",
          type: "switch",
          label: t("projects.forms.editProject.fields.active"),
          width: "1/2",
        },
      ],
    },
  ],
})

export const editTaskForm = (t: TFunction): FormConfig => ({
  id: "edit-task",
  title: t("projects.forms.editTask.title"),
  description: t("projects.forms.editTask.description"),
  sections: [
    {
      id: "task-info",
      title: t("projects.forms.editTask.sections.taskDetails"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("projects.forms.editTask.fields.name"),
          placeholder: t("projects.forms.editTask.fields.namePlaceholder"),
          required: true,
          width: "full",
        },
        {
          id: "projectId",
          name: "projectId",
          type: "select",
          label: t("projects.forms.editTask.fields.projectId"),
          placeholder: t("projects.forms.editTask.fields.projectIdPlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "stageId",
          name: "stageId",
          type: "select",
          label: t("projects.forms.editTask.fields.stageId"),
          placeholder: t("projects.forms.editTask.fields.stagePlaceholder"),
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "priority",
          name: "priority",
          type: "select",
          label: t("projects.forms.editTask.fields.priority"),
          width: "1/2",
          options: [
            { value: "0", label: t("projects.forms.editTask.fields.options.0") },
            { value: "1", label: t("projects.forms.editTask.fields.options.1") },
            { value: "2", label: t("projects.forms.editTask.fields.options.2") },
            { value: "3", label: t("projects.forms.editTask.fields.options.3") },
          ],
        },
        {
          id: "plannedHours",
          name: "plannedHours",
          type: "number",
          label: t("projects.forms.editTask.fields.plannedHours"),
          placeholder: t("projects.forms.editTask.fields.plannedHoursPlaceholder"),
          width: "1/2",
        },
        {
          id: "dateDeadline",
          name: "dateDeadline",
          type: "date",
          label: t("projects.forms.editTask.fields.dateDeadline"),
          width: "1/2",
        },
        {
          id: "description",
          name: "description",
          type: "textarea",
          label: t("projects.forms.editTask.fields.description"),
          placeholder: t("projects.forms.editTask.fields.descriptionPlaceholder"),
          width: "full",
          rows: 3,
        },
        {
          id: "kanbanState",
          name: "kanbanState",
          type: "select",
          label: t("projects.forms.editTask.fields.kanbanState"),
          width: "1/2",
          options: [
            { value: "normal", label: t("projects.forms.editTask.fields.states.normal") },
            { value: "done", label: t("projects.forms.editTask.fields.states.done") },
            { value: "blocked", label: t("projects.forms.editTask.fields.states.blocked") },
          ],
        },
      ],
    },
  ],
})

export const logTimesheetForm = (t: TFunction): FormConfig => ({
  id: "log-timesheet",
  title: t("projects.forms.logTimesheet.title"),
  description: t("projects.forms.logTimesheet.description"),
  sections: [
    {
      id: "timesheet-info",
      title: t("projects.forms.logTimesheet.sections.details"),
      fields: [
        {
          id: "projectId",
          name: "projectId",
          type: "select",
          label: t("projects.forms.logTimesheet.fields.projectId"),
          placeholder: t("projects.forms.logTimesheet.fields.projectIdPlaceholder"),
          required: true,
          width: "full",
          options: emptySelect,
        },
        {
          id: "taskId",
          name: "taskId",
          type: "select",
          label: t("projects.forms.logTimesheet.fields.taskId"),
          placeholder: t("projects.forms.logTimesheet.fields.taskIdPlaceholder"),
          width: "full",
          options: emptySelect,
        },
        {
          id: "date",
          name: "date",
          type: "date",
          label: t("projects.forms.logTimesheet.fields.date"),
          required: true,
          width: "1/2",
        },
        {
          id: "unitAmount",
          name: "unitAmount",
          type: "number",
          label: t("projects.forms.logTimesheet.fields.hours"),
          placeholder: t("projects.forms.logTimesheet.fields.hoursPlaceholder"),
          required: true,
          width: "1/2",
          step: 0.25,
          min: 0,
        },
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("projects.forms.logTimesheet.fields.description"),
          placeholder: t("projects.forms.logTimesheet.fields.descriptionPlaceholder"),
          width: "full",
        },
        {
          id: "billable",
          name: "billable",
          type: "switch",
          label: t("projects.forms.logTimesheet.fields.billable"),
          width: "1/2",
        },
      ],
    },
  ],
})

export const projectsFormConfigs = (t: TFunction): Record<string, FormConfig> => ({
  "new-project": newProjectForm(t),
  "new-task": newTaskForm(t),
  "edit-project": editProjectForm(t),
  "edit-task": editTaskForm(t),
  "log-timesheet": logTimesheetForm(t),
})
