import type { TFunction } from "i18next"
import type { FormConfig } from "./form-types"

const emptySelect: Array<{ value: string; label: string; disabled?: boolean }> = []

export const newSaleOrderForm = (t: TFunction): FormConfig => ({
  id: "new-sale-order",
  title: t("sales.forms.newSaleOrder.title"),
  description: t("sales.forms.newSaleOrder.description"),
  sections: [
    {
      id: "so-customer",
      title: t("sales.forms.newSaleOrder.sections.customer"),
      fields: [
        {
          id: "partnerId",
          name: "partnerId",
          type: "select",
          label: t("sales.forms.newSaleOrder.fields.partnerId"),
          placeholder: t("sales.forms.newSaleOrder.fields.partnerPlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "clientOrderRef",
          name: "clientOrderRef",
          type: "text",
          label: t("sales.forms.newSaleOrder.fields.clientOrderRef"),
          placeholder: t("sales.forms.newSaleOrder.fields.clientOrderRefPlaceholder"),
          width: "1/2",
        },
      ],
    },
    {
      id: "so-order",
      title: t("sales.forms.newSaleOrder.sections.orderDetails"),
      fields: [
        {
          id: "pricelistId",
          name: "pricelistId",
          type: "select",
          label: t("sales.forms.newSaleOrder.fields.pricelistId"),
          placeholder: t("sales.forms.newSaleOrder.fields.pricelistPlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "warehouseId",
          name: "warehouseId",
          type: "select",
          label: t("sales.forms.newSaleOrder.fields.warehouseId"),
          placeholder: t("sales.forms.newSaleOrder.fields.warehousePlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "paymentTermId",
          name: "paymentTermId",
          type: "number",
          label: t("sales.forms.newSaleOrder.fields.paymentTermId"),
          placeholder: t("sales.forms.newSaleOrder.fields.paymentTermPlaceholder"),
          width: "1/2",
        },
        {
          id: "validityDate",
          name: "validityDate",
          type: "date",
          label: t("sales.forms.newSaleOrder.fields.validityDate"),
          width: "1/2",
        },
        {
          id: "commitmentDate",
          name: "commitmentDate",
          type: "date",
          label: t("sales.forms.newSaleOrder.fields.commitmentDate"),
          width: "1/2",
        },
      ],
    },
    {
      id: "so-notes",
      title: t("sales.forms.newSaleOrder.sections.notes"),
      fields: [
        {
          id: "note",
          name: "note",
          type: "textarea",
          label: t("sales.forms.newSaleOrder.fields.note"),
          placeholder: t("sales.forms.newSaleOrder.fields.notePlaceholder"),
          width: "full",
          rows: 3,
        },
      ],
    },
  ],
})

export const newPricelistForm = (t: TFunction): FormConfig => ({
  id: "new-pricelist",
  title: t("sales.forms.newPricelist.title"),
  description: t("sales.forms.newPricelist.description"),
  sections: [
    {
      id: "pl-info",
      title: t("sales.forms.newPricelist.sections.pricelistDetails"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("sales.forms.newPricelist.fields.name"),
          placeholder: t("sales.forms.newPricelist.fields.namePlaceholder"),
          required: true,
          width: "1/2",
        },
        {
          id: "currencyId",
          name: "currencyId",
          type: "number",
          label: t("sales.forms.newPricelist.fields.currencyId"),
          placeholder: t("sales.forms.newPricelist.fields.currencyPlaceholder"),
          required: true,
          width: "1/2",
        },
        {
          id: "discountPolicy",
          name: "discountPolicy",
          type: "select",
          label: t("sales.forms.newPricelist.fields.discountPolicy"),
          width: "1/2",
          options: [
            { value: "WithoutDiscount", label: t("sales.forms.newPricelist.fields.options.WithoutDiscount") },
            { value: "WithDiscount", label: t("sales.forms.newPricelist.fields.options.WithDiscount") },
          ],
        },
      ],
    },
  ],
})

export const newPricelistItemForm = (t: TFunction): FormConfig => ({
  id: "new-pricelist-item",
  title: t("sales.forms.newPricelistItem.title"),
  description: t("sales.forms.newPricelistItem.description"),
  sections: [
    {
      id: "pli-scope",
      title: t("sales.forms.newPricelistItem.sections.scope"),
      fields: [
        {
          id: "pricelistId",
          name: "pricelistId",
          type: "select",
          label: t("sales.forms.newPricelistItem.fields.pricelistId"),
          required: true,
          width: "full",
          options: [],
        },
        {
          id: "appliedOn",
          name: "appliedOn",
          type: "select",
          label: t("sales.forms.newPricelistItem.fields.appliedOn"),
          required: true,
          width: "1/2",
          defaultValue: "AllProducts",
          options: [
            { value: "AllProducts", label: t("sales.forms.newPricelistItem.fields.appliedOnAll") },
            { value: "Category", label: t("sales.forms.newPricelistItem.fields.appliedOnCategory") },
            { value: "Product", label: t("sales.forms.newPricelistItem.fields.appliedOnProduct") },
          ],
        },
        {
          id: "computePrice",
          name: "computePrice",
          type: "select",
          label: t("sales.forms.newPricelistItem.fields.computePrice"),
          required: true,
          width: "1/2",
          defaultValue: "Fixed",
          options: [
            { value: "Fixed", label: t("sales.forms.newPricelistItem.fields.computeFixed") },
            { value: "Percentage", label: t("sales.forms.newPricelistItem.fields.computePercentage") },
            { value: "Formula", label: t("sales.forms.newPricelistItem.fields.computeFormula") },
          ],
        },
        {
          id: "productId",
          name: "productId",
          type: "number",
          label: t("sales.forms.newPricelistItem.fields.productId"),
          width: "1/3",
        },
        {
          id: "categId",
          name: "categId",
          type: "number",
          label: t("sales.forms.newPricelistItem.fields.categId"),
          width: "1/3",
        },
        {
          id: "minQuantity",
          name: "minQuantity",
          type: "number",
          label: t("sales.forms.newPricelistItem.fields.minQuantity"),
          width: "1/3",
          defaultValue: 1,
        },
      ],
    },
    {
      id: "pli-pricing",
      title: t("sales.forms.newPricelistItem.sections.pricing"),
      fields: [
        {
          id: "fixedPrice",
          name: "fixedPrice",
          type: "number",
          label: t("sales.forms.newPricelistItem.fields.fixedPrice"),
          width: "1/2",
          defaultValue: 0,
        },
        {
          id: "percentPrice",
          name: "percentPrice",
          type: "number",
          label: t("sales.forms.newPricelistItem.fields.percentPrice"),
          width: "1/2",
          defaultValue: 0,
        },
        {
          id: "priceDiscount",
          name: "priceDiscount",
          type: "number",
          label: t("sales.forms.newPricelistItem.fields.priceDiscount"),
          width: "1/3",
          defaultValue: 0,
        },
        {
          id: "sequence",
          name: "sequence",
          type: "number",
          label: t("sales.forms.newPricelistItem.fields.sequence"),
          width: "1/3",
          defaultValue: 10,
        },
      ],
    },
  ],
})

export const newPickingBatchForm = (t: TFunction): FormConfig => ({
  id: "new-picking-batch",
  title: t("sales.forms.newPickingBatch.title"),
  description: t("sales.forms.newPickingBatch.description"),
  sections: [
    {
      id: "batch-details",
      title: t("sales.forms.newPickingBatch.sections.details"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("sales.forms.newPickingBatch.fields.name"),
          placeholder: t("sales.forms.newPickingBatch.fields.namePlaceholder"),
          required: true,
          width: "full",
        },
        {
          id: "pickingIds",
          name: "pickingIds",
          type: "textarea",
          label: t("sales.forms.newPickingBatch.fields.pickingIds"),
          placeholder: t("sales.forms.newPickingBatch.fields.pickingIdsPlaceholder"),
          description: t("sales.forms.newPickingBatch.fields.pickingIdsHint"),
          width: "full",
          rows: 3,
        },
        {
          id: "isWave",
          name: "isWave",
          type: "checkbox",
          label: t("sales.forms.newPickingBatch.fields.isWave"),
          description: t("sales.forms.newPickingBatch.fields.isWaveHint"),
          width: "full",
        },
      ],
    },
  ],
})

export const newDeliveryPriceRuleForm = (t: TFunction): FormConfig => ({
  id: "new-delivery-price-rule",
  title: t("sales.forms.newDeliveryPriceRule.title"),
  description: t("sales.forms.newDeliveryPriceRule.description"),
  sections: [
    {
      id: "dpr-main",
      title: t("sales.forms.newDeliveryPriceRule.sections.main"),
      fields: [
        {
          id: "variable",
          name: "variable",
          type: "text",
          label: t("sales.forms.newDeliveryPriceRule.fields.variable"),
          placeholder: t("sales.forms.newDeliveryPriceRule.fields.variablePlaceholder"),
          required: true,
          width: "1/2",
        },
        {
          id: "operator",
          name: "operator",
          type: "select",
          label: t("sales.forms.newDeliveryPriceRule.fields.operator"),
          width: "1/2",
          options: [
            { value: "<=", label: "<=" },
            { value: "<", label: "<" },
            { value: ">=", label: ">=" },
            { value: ">", label: ">" },
            { value: "=", label: "=" },
          ],
        },
        {
          id: "maxValue",
          name: "maxValue",
          type: "number",
          label: t("sales.forms.newDeliveryPriceRule.fields.maxValue"),
          width: "1/2",
        },
        {
          id: "listBasePrice",
          name: "listBasePrice",
          type: "number",
          label: t("sales.forms.newDeliveryPriceRule.fields.listBasePrice"),
          width: "1/2",
        },
        {
          id: "listPrice",
          name: "listPrice",
          type: "number",
          label: t("sales.forms.newDeliveryPriceRule.fields.listPrice"),
          width: "1/2",
        },
        {
          id: "standardPrice",
          name: "standardPrice",
          type: "number",
          label: t("sales.forms.newDeliveryPriceRule.fields.standardPrice"),
          width: "1/2",
        },
      ],
    },
  ],
})

export const newDeliveryCarrierForm = (t: TFunction): FormConfig => ({
  id: "new-delivery-carrier",
  title: t("sales.forms.newDeliveryCarrier.title"),
  description: t("sales.forms.newDeliveryCarrier.description"),
  sections: [
    {
      id: "dc-main",
      title: t("sales.forms.newDeliveryCarrier.sections.main"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("sales.forms.newDeliveryCarrier.fields.name"),
          required: true,
          width: "1/2",
        },
        {
          id: "productId",
          name: "productId",
          type: "number",
          label: t("sales.forms.newDeliveryCarrier.fields.productId"),
          required: true,
          width: "1/2",
        },
        {
          id: "currencyId",
          name: "currencyId",
          type: "number",
          label: t("sales.forms.newDeliveryCarrier.fields.currencyId"),
          required: true,
          width: "1/2",
        },
        {
          id: "deliveryType",
          name: "deliveryType",
          type: "text",
          label: t("sales.forms.newDeliveryCarrier.fields.deliveryType"),
          width: "1/2",
        },
        {
          id: "integrationLevel",
          name: "integrationLevel",
          type: "text",
          label: t("sales.forms.newDeliveryCarrier.fields.integrationLevel"),
          width: "1/2",
        },
        {
          id: "invoicePolicy",
          name: "invoicePolicy",
          type: "text",
          label: t("sales.forms.newDeliveryCarrier.fields.invoicePolicy"),
          width: "1/2",
        },
        {
          id: "priceRuleIds",
          name: "priceRuleIds",
          type: "textarea",
          label: t("sales.forms.newDeliveryCarrier.fields.priceRuleIds"),
          description: t("sales.forms.newDeliveryCarrier.fields.priceRuleIdsHint"),
          width: "full",
          rows: 2,
        },
        {
          id: "margin",
          name: "margin",
          type: "number",
          label: t("sales.forms.newDeliveryCarrier.fields.margin"),
          width: "1/3",
        },
        {
          id: "amount",
          name: "amount",
          type: "number",
          label: t("sales.forms.newDeliveryCarrier.fields.amount"),
          width: "1/3",
        },
        {
          id: "fixedCharge",
          name: "fixedCharge",
          type: "number",
          label: t("sales.forms.newDeliveryCarrier.fields.fixedCharge"),
          width: "1/3",
        },
        {
          id: "fixedWeight",
          name: "fixedWeight",
          type: "number",
          label: t("sales.forms.newDeliveryCarrier.fields.fixedWeight"),
          width: "1/3",
        },
        {
          id: "shippingInsurance",
          name: "shippingInsurance",
          type: "number",
          label: t("sales.forms.newDeliveryCarrier.fields.shippingInsurance"),
          width: "1/3",
        },
        {
          id: "freeOver",
          name: "freeOver",
          type: "checkbox",
          label: t("sales.forms.newDeliveryCarrier.fields.freeOver"),
          width: "1/3",
        },
        {
          id: "shippingInsuranceIsPercentage",
          name: "shippingInsuranceIsPercentage",
          type: "checkbox",
          label: t("sales.forms.newDeliveryCarrier.fields.shippingInsuranceIsPercentage"),
          width: "1/3",
        },
        {
          id: "canGenerateReturn",
          name: "canGenerateReturn",
          type: "checkbox",
          label: t("sales.forms.newDeliveryCarrier.fields.canGenerateReturn"),
          width: "1/3",
        },
        {
          id: "returnLabelOnDelivery",
          name: "returnLabelOnDelivery",
          type: "checkbox",
          label: t("sales.forms.newDeliveryCarrier.fields.returnLabelOnDelivery"),
          width: "1/3",
        },
        {
          id: "getReturnLabelFromPortal",
          name: "getReturnLabelFromPortal",
          type: "checkbox",
          label: t("sales.forms.newDeliveryCarrier.fields.getReturnLabelFromPortal"),
          width: "1/3",
        },
        {
          id: "useDetailedDeliveryDescription",
          name: "useDetailedDeliveryDescription",
          type: "checkbox",
          label: t("sales.forms.newDeliveryCarrier.fields.useDetailedDeliveryDescription"),
          width: "full",
        },
        {
          id: "countryIds",
          name: "countryIds",
          type: "textarea",
          label: t("sales.forms.newDeliveryCarrier.fields.countryIds"),
          width: "full",
          rows: 2,
        },
        {
          id: "stateIds",
          name: "stateIds",
          type: "textarea",
          label: t("sales.forms.newDeliveryCarrier.fields.stateIds"),
          width: "full",
          rows: 2,
        },
        {
          id: "zipPrefixIds",
          name: "zipPrefixIds",
          type: "textarea",
          label: t("sales.forms.newDeliveryCarrier.fields.zipPrefixIds"),
          width: "full",
          rows: 2,
        },
      ],
    },
  ],
})

export const newShippingMethodForm = (t: TFunction): FormConfig => ({
  id: "new-shipping-method",
  title: t("sales.forms.newShippingMethod.title"),
  description: t("sales.forms.newShippingMethod.description"),
  sections: [
    {
      id: "sm-main",
      title: t("sales.forms.newShippingMethod.sections.main"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("sales.forms.newShippingMethod.fields.name"),
          required: true,
          width: "1/2",
        },
        {
          id: "provider",
          name: "provider",
          type: "text",
          label: t("sales.forms.newShippingMethod.fields.provider"),
          width: "1/2",
        },
        {
          id: "productId",
          name: "productId",
          type: "number",
          label: t("sales.forms.newShippingMethod.fields.productId"),
          required: true,
          width: "1/2",
        },
        {
          id: "deliveryType",
          name: "deliveryType",
          type: "text",
          label: t("sales.forms.newShippingMethod.fields.deliveryType"),
          width: "1/2",
        },
        {
          id: "integrationLevel",
          name: "integrationLevel",
          type: "text",
          label: t("sales.forms.newShippingMethod.fields.integrationLevel"),
          width: "1/2",
        },
        {
          id: "invoicePolicy",
          name: "invoicePolicy",
          type: "text",
          label: t("sales.forms.newShippingMethod.fields.invoicePolicy"),
          width: "1/2",
        },
        {
          id: "fixedPrice",
          name: "fixedPrice",
          type: "number",
          label: t("sales.forms.newShippingMethod.fields.fixedPrice"),
          width: "1/3",
        },
        {
          id: "margin",
          name: "margin",
          type: "number",
          label: t("sales.forms.newShippingMethod.fields.margin"),
          width: "1/3",
        },
        {
          id: "amount",
          name: "amount",
          type: "number",
          label: t("sales.forms.newShippingMethod.fields.amount"),
          width: "1/3",
        },
        {
          id: "freeOver",
          name: "freeOver",
          type: "checkbox",
          label: t("sales.forms.newShippingMethod.fields.freeOver"),
          width: "full",
        },
      ],
    },
  ],
})

export const newPosPaymentMethodForm = (t: TFunction): FormConfig => ({
  id: "new-pos-payment-method",
  title: t("sales.forms.newPosPaymentMethod.title"),
  description: t("sales.forms.newPosPaymentMethod.description"),
  sections: [
    {
      id: "pm-main",
      title: t("sales.forms.newPosPaymentMethod.sections.main"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("sales.forms.newPosPaymentMethod.fields.name"),
          required: true,
          width: "1/2",
        },
        {
          id: "paymentMethodType",
          name: "paymentMethodType",
          type: "select",
          label: t("sales.forms.newPosPaymentMethod.fields.paymentMethodType"),
          width: "1/2",
          options: [
            { value: "Cash", label: "Cash" },
            { value: "Bank", label: "Bank" },
            { value: "Card", label: "Card" },
            { value: "DigitalWallet", label: "Digital wallet" },
            { value: "LoyaltyPoints", label: "Loyalty points" },
          ],
        },
        {
          id: "sequence",
          name: "sequence",
          type: "number",
          label: t("sales.forms.newPosPaymentMethod.fields.sequence"),
          width: "1/2",
        },
        {
          id: "isCashCount",
          name: "isCashCount",
          type: "checkbox",
          label: t("sales.forms.newPosPaymentMethod.fields.isCashCount"),
          width: "1/3",
        },
        {
          id: "isCardPayment",
          name: "isCardPayment",
          type: "checkbox",
          label: t("sales.forms.newPosPaymentMethod.fields.isCardPayment"),
          width: "1/3",
        },
        {
          id: "splitTransactions",
          name: "splitTransactions",
          type: "checkbox",
          label: t("sales.forms.newPosPaymentMethod.fields.splitTransactions"),
          width: "1/3",
        },
        {
          id: "openCashbox",
          name: "openCashbox",
          type: "checkbox",
          label: t("sales.forms.newPosPaymentMethod.fields.openCashbox"),
          width: "1/3",
        },
        {
          id: "receivableAccountId",
          name: "receivableAccountId",
          type: "number",
          label: t("sales.forms.newPosPaymentMethod.fields.receivableAccountId"),
          width: "1/2",
        },
        {
          id: "outstandingAccountId",
          name: "outstandingAccountId",
          type: "number",
          label: t("sales.forms.newPosPaymentMethod.fields.outstandingAccountId"),
          width: "1/2",
        },
        {
          id: "journalId",
          name: "journalId",
          type: "number",
          label: t("sales.forms.newPosPaymentMethod.fields.journalId"),
          width: "1/2",
        },
        {
          id: "cashJournalId",
          name: "cashJournalId",
          type: "number",
          label: t("sales.forms.newPosPaymentMethod.fields.cashJournalId"),
          width: "1/2",
        },
        {
          id: "usePaymentTerminal",
          name: "usePaymentTerminal",
          type: "text",
          label: t("sales.forms.newPosPaymentMethod.fields.usePaymentTerminal"),
          width: "full",
        },
      ],
    },
  ],
})

export const newLoyaltyProgramForm = (t: TFunction): FormConfig => ({
  id: "new-loyalty-program",
  title: t("sales.forms.newLoyaltyProgram.title"),
  description: t("sales.forms.newLoyaltyProgram.description"),
  sections: [
    {
      id: "lp-main",
      title: t("sales.forms.newLoyaltyProgram.sections.main"),
      fields: [
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("sales.forms.newLoyaltyProgram.fields.name"),
          required: true,
          width: "1/2",
        },
        {
          id: "currencyId",
          name: "currencyId",
          type: "number",
          label: t("sales.forms.newLoyaltyProgram.fields.currencyId"),
          required: true,
          width: "1/2",
        },
        {
          id: "programType",
          name: "programType",
          type: "text",
          label: t("sales.forms.newLoyaltyProgram.fields.programType"),
          width: "1/2",
        },
        {
          id: "limitUsage",
          name: "limitUsage",
          type: "number",
          label: t("sales.forms.newLoyaltyProgram.fields.limitUsage"),
          width: "1/2",
        },
        {
          id: "validityDuration",
          name: "validityDuration",
          type: "number",
          label: t("sales.forms.newLoyaltyProgram.fields.validityDuration"),
          width: "1/2",
        },
        {
          id: "validityDurationType",
          name: "validityDurationType",
          type: "select",
          label: t("sales.forms.newLoyaltyProgram.fields.validityDurationType"),
          width: "1/2",
          options: [
            { value: "days", label: t("sales.forms.newLoyaltyProgram.fields.durationDays") },
            { value: "weeks", label: t("sales.forms.newLoyaltyProgram.fields.durationWeeks") },
            { value: "months", label: t("sales.forms.newLoyaltyProgram.fields.durationMonths") },
          ],
        },
        {
          id: "dateTo",
          name: "dateTo",
          type: "date",
          label: t("sales.forms.newLoyaltyProgram.fields.dateTo"),
          width: "1/2",
        },
        {
          id: "isNominative",
          name: "isNominative",
          type: "checkbox",
          label: t("sales.forms.newLoyaltyProgram.fields.isNominative"),
          width: "full",
        },
        {
          id: "triggerProductIds",
          name: "triggerProductIds",
          type: "textarea",
          label: t("sales.forms.newLoyaltyProgram.fields.triggerProductIds"),
          description: t("sales.forms.newLoyaltyProgram.fields.triggerProductIdsHint"),
          width: "full",
          rows: 2,
        },
      ],
    },
  ],
})

export const newLoyaltyCardForm = (t: TFunction): FormConfig => ({
  id: "new-loyalty-card",
  title: t("sales.forms.newLoyaltyCard.title"),
  description: t("sales.forms.newLoyaltyCard.description"),
  sections: [
    {
      id: "lc-main",
      title: t("sales.forms.newLoyaltyCard.sections.main"),
      fields: [
        {
          id: "programId",
          name: "programId",
          type: "select",
          label: t("sales.forms.newLoyaltyCard.fields.programId"),
          placeholder: t("sales.forms.newLoyaltyCard.fields.programPlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "code",
          name: "code",
          type: "text",
          label: t("sales.forms.newLoyaltyCard.fields.code"),
          required: true,
          width: "1/2",
        },
        {
          id: "points",
          name: "points",
          type: "number",
          label: t("sales.forms.newLoyaltyCard.fields.points"),
          required: true,
          width: "1/2",
        },
        {
          id: "partnerId",
          name: "partnerId",
          type: "number",
          label: t("sales.forms.newLoyaltyCard.fields.partnerId"),
          width: "1/2",
        },
      ],
    },
  ],
})

export const addSaleOrderLineForm = (t: TFunction): FormConfig => ({
  id: "add-sale-order-line",
  title: t("sales.forms.addSaleOrderLine.title"),
  description: t("sales.forms.addSaleOrderLine.description"),
  sections: [
    {
      id: "sol-order",
      title: t("sales.forms.addSaleOrderLine.sections.order"),
      fields: [
        {
          id: "orderId",
          name: "orderId",
          type: "select",
          label: t("sales.forms.addSaleOrderLine.fields.orderId"),
          placeholder: t("sales.forms.addSaleOrderLine.fields.orderPlaceholder"),
          required: true,
          width: "full",
          options: emptySelect,
        },
      ],
    },
    {
      id: "sol-product",
      title: t("sales.forms.addSaleOrderLine.sections.product"),
      fields: [
        {
          id: "productId",
          name: "productId",
          type: "select",
          label: t("sales.forms.addSaleOrderLine.fields.productId"),
          placeholder: t("sales.forms.addSaleOrderLine.fields.productPlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "uomId",
          name: "uomId",
          type: "select",
          label: t("sales.forms.addSaleOrderLine.fields.uomId"),
          placeholder: t("sales.forms.addSaleOrderLine.fields.uomPlaceholder"),
          required: true,
          width: "1/2",
          options: emptySelect,
        },
        {
          id: "quantity",
          name: "quantity",
          type: "number",
          label: t("sales.forms.addSaleOrderLine.fields.quantity"),
          required: true,
          width: "1/2",
        },
        {
          id: "priceUnit",
          name: "priceUnit",
          type: "number",
          label: t("sales.forms.addSaleOrderLine.fields.priceUnit"),
          required: true,
          width: "1/2",
        },
      ],
    },
    {
      id: "sol-details",
      title: t("sales.forms.addSaleOrderLine.sections.details"),
      fields: [
        {
          id: "discount",
          name: "discount",
          type: "number",
          label: t("sales.forms.addSaleOrderLine.fields.discount"),
          width: "1/3",
          defaultValue: 0,
        },
        {
          id: "sequence",
          name: "sequence",
          type: "number",
          label: t("sales.forms.addSaleOrderLine.fields.sequence"),
          width: "1/3",
          defaultValue: 10,
        },
        {
          id: "name",
          name: "name",
          type: "text",
          label: t("sales.forms.addSaleOrderLine.fields.name"),
          placeholder: t("sales.forms.addSaleOrderLine.fields.namePlaceholder"),
          width: "full",
        },
        {
          id: "taxIds",
          name: "taxIds",
          type: "textarea",
          label: t("sales.forms.addSaleOrderLine.fields.taxIds"),
          placeholder: t("sales.forms.addSaleOrderLine.fields.taxIdsPlaceholder"),
          description: t("sales.forms.addSaleOrderLine.fields.taxIdsHint"),
          width: "full",
          rows: 2,
        },
      ],
    },
  ],
})

export const createInvoiceFromSaleOrderForm = (t: TFunction): FormConfig => ({
  id: "create-invoice-from-sale-order",
  title: t("sales.forms.createInvoiceFromOrder.title"),
  description: t("sales.forms.createInvoiceFromOrder.description"),
  submitLabel: t("sales.forms.createInvoiceFromOrder.submitLabel"),
  cancelLabel: t("common.cancel"),
  sections: [
    {
      id: "accounting",
      title: t("sales.forms.createInvoiceFromOrder.sections.accounting"),
      fields: [
        {
          id: "journalId",
          name: "journalId",
          type: "select",
          label: t("sales.forms.createInvoiceFromOrder.fields.journalId"),
          required: true,
          width: "1/2",
          options: [],
        },
        {
          id: "defaultIncomeAccountId",
          name: "defaultIncomeAccountId",
          type: "select",
          label: t("sales.forms.createInvoiceFromOrder.fields.defaultIncomeAccountId"),
          required: true,
          width: "1/2",
          options: [],
        },
        {
          id: "receivableAccountId",
          name: "receivableAccountId",
          type: "select",
          label: t("sales.forms.createInvoiceFromOrder.fields.receivableAccountId"),
          required: true,
          width: "1/2",
          options: [],
        },
        {
          id: "receivableLineName",
          name: "receivableLineName",
          type: "text",
          label: t("sales.forms.createInvoiceFromOrder.fields.receivableLineName"),
          width: "full",
        },
        {
          id: "narration",
          name: "narration",
          type: "textarea",
          label: t("sales.forms.createInvoiceFromOrder.fields.narration"),
          placeholder: t("sales.forms.createInvoiceFromOrder.fields.narrationPlaceholder"),
          width: "full",
          rows: 3,
        },
        {
          id: "incomeExcludeFromInvoiceTab",
          name: "incomeExcludeFromInvoiceTab",
          type: "checkbox",
          label: t("sales.forms.createInvoiceFromOrder.fields.incomeExcludeFromInvoiceTab"),
          defaultValue: false,
        },
        {
          id: "incomeBlocked",
          name: "incomeBlocked",
          type: "checkbox",
          label: t("sales.forms.createInvoiceFromOrder.fields.incomeBlocked"),
          defaultValue: false,
        },
        {
          id: "receivableExcludeFromInvoiceTab",
          name: "receivableExcludeFromInvoiceTab",
          type: "checkbox",
          label: t("sales.forms.createInvoiceFromOrder.fields.receivableExcludeFromInvoiceTab"),
          defaultValue: true,
        },
        {
          id: "receivableBlocked",
          name: "receivableBlocked",
          type: "checkbox",
          label: t("sales.forms.createInvoiceFromOrder.fields.receivableBlocked"),
          defaultValue: false,
        },
      ],
    },
  ],
})

export const salesFormConfigs = (t: TFunction): Record<string, FormConfig> => ({
  "new-sale-order": newSaleOrderForm(t),
  "new-pricelist": newPricelistForm(t),
  "new-pricelist-item": newPricelistItemForm(t),
  "new-picking-batch": newPickingBatchForm(t),
  "add-sale-order-line": addSaleOrderLineForm(t),
  "create-invoice-from-sale-order": createInvoiceFromSaleOrderForm(t),
  "new-delivery-price-rule": newDeliveryPriceRuleForm(t),
  "new-delivery-carrier": newDeliveryCarrierForm(t),
  "new-shipping-method": newShippingMethodForm(t),
  "new-pos-payment-method": newPosPaymentMethodForm(t),
  "new-loyalty-program": newLoyaltyProgramForm(t),
  "new-loyalty-card": newLoyaltyCardForm(t),
})
