/// AI & Business Intelligence Module
///
/// # Tables
/// | Table | Description |
/// |-------|-------------|
/// | **AiAgent** | AI model configurations (provider, temperature, budget) |
/// | **AiTeamMember** | AI persona definitions with roles and personality |
/// | **AiInsight** | Business intelligence insights generated by AI |
/// | **AiDocumentProcessingJob** | Document OCR / extraction / classification jobs |
/// | **SearchEmbedding** | Vector embeddings for semantic search |
pub mod action_draft_lifecycle;
pub mod action_drafts;
pub mod agents;
pub mod calibration_profile;
pub mod capability_execution;
pub mod capability_grants;
pub mod chat;
pub mod decision_events;
pub mod decision_precedent;
pub mod decision_type_registry;
pub mod evidence_common;
pub mod evidence_dependency;
pub mod evidence_lineage;
pub mod evidence_source;
pub mod intelligence;
pub mod knowledge_entry;
pub mod knowledge_promotion;
pub mod model_configuration;
pub mod reducer_allowlist;
pub mod run_lifecycle;
pub mod run_review;
pub mod skill_registry;
pub mod skills;
pub mod spend;

pub use action_drafts::*;
pub use agents::*;
pub use calibration_profile::*;
pub use capability_execution::*;
pub use capability_grants::*;
pub use chat::*;
pub use decision_events::*;
pub use decision_precedent::*;
pub use decision_type_registry::*;
pub use evidence_dependency::*;
pub use evidence_lineage::*;
pub use evidence_source::*;
pub use intelligence::*;
pub use knowledge_entry::*;
pub use knowledge_promotion::*;
pub use model_configuration::*;
pub use reducer_allowlist::*;
pub use run_lifecycle::*;
pub use run_review::*;
pub use skill_registry::*;
pub use skills::*;
pub use spend::*;
