/// AI & Business Intelligence Module
///
/// # Tables
/// | Table | Description |
/// |-------|-------------|
/// | **AiAgent** | AI model configurations (provider, temperature, budget) |
/// | **AiTeamMember** | AI persona definitions with roles and personality |
/// | **AiInsight** | Business intelligence insights generated by AI |
/// | **AiDocumentProcessingJob** | Document OCR / extraction / classification jobs |
/// | **SearchEmbedding** | Vector embeddings for semantic search |
pub mod action_draft_lifecycle;
pub mod action_drafts;
pub mod agents;
pub mod answer_gate;
pub mod chat;
pub mod continuation;
pub mod diagnostics;
pub mod inspector;
pub mod intelligence;
pub mod lineage;
pub mod provenance;
pub mod questions;
pub mod reducer_allowlist;
pub mod session_controls;
pub mod skill_registry;
pub mod skills;
pub mod spend;

pub use action_drafts::*;
pub use agents::*;
pub use answer_gate::*;
pub use chat::*;
pub use continuation::*;
pub use diagnostics::*;
pub use inspector::*;
pub use intelligence::*;
pub use lineage::*;
pub use provenance::*;
pub use questions::*;
pub use reducer_allowlist::*;
pub use session_controls::*;
pub use skill_registry::*;
pub use skills::*;
pub use spend::*;
